### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by BeastOTL** [AgriCraft/AgriCraft#1001]
I added a few mods to Skyfactory 3 and got this crash on startup. Same thing happened when i added agricraft to the dw20 modpack for 1.10

[crash-2017-06-11_22.15.37-client.txt](https://github.com/AgriCraft/AgriCraft/files/1066706/crash-2017-06-11_22.15.37-client.txt)

**Comment by TokkenGmr** [comment]
This looks to be the same as #996 and #998

**Comment by RavensFlight92** [comment]
It Is you just need to replace the Json listed in [#998](https://github.com/AgriCraft/AgriCraft/issues/998)

**Comment by RlonRyan** [comment]
Duplicate of #985
