### ISSUE TITLE
Harvestcraft Json

### ISSUE THREAD

**Issue by RavensFlight92** [AgriCraft/AgriCraft#1002]
Iv gone through and made the edits for all the crops yet i cannot find
out where im going wrong on coffee and rice seeds

https://pastebin.com/gu9JdgMR Coffee seeds
https://pastebin.com/XLFGWf71 Rice Seeds 

Thank you for any help

**Comment by RavensFlight92** [comment]
Whoops also should have added everything else works

**Comment by TokkenGmr** [comment]
I can not see anything wrong with your JSON files. Have you checked the log to see what it is saying there may help a lil bit

**Comment by RavensFlight92** [comment]
nothing showing on the log just seems like agricraft dislikes the rice and coffee seeds

**Comment by RlonRyan** [comment]
Depends on the HarvestCraft version... The ftb wiki has the coffee seed id as `harvestcraft:coffeeseedItem` so it might be an issue with captialization...

**Comment by RlonRyan** [comment]
No updates in a week so I'll assume this question has been answered.
