### ISSUE TITLE
Botania Horn of the Wilds won't harvest plants.

### ISSUE THREAD

**Issue by Furious1964** [AgriCraft/AgriCraft#1005]
I used to be able to sound the horn in MC 1.7.10 and the Agricraft plants would be harvested. But now I can't. I tested the Horn on regular plants and it works on them but not plants in crop sticks.

**Comment by InfinityRaider** [comment]
Is this an issue for 1.7.10 or 1.10?

**Comment by Furious1964** [comment]
It's for 1.10.2, Sir.


Sent from my Samsung device over Bell's LTE network.

-------- Original message --------

**Comment by InfinityRaider** [comment]
Compatibility is not a priority in 1.10 yet, considering the build itself is not as stable as it should be.
Things like these are for later, see also #572
