### ISSUE TITLE
Agricraft 1.10.2 0.10.0-a18 Infinitylib 0.10 Null Pointer

### ISSUE THREAD

**Issue by ReportBot9009** [AgriCraft/AgriCraft#1010]
Hello,

Just tried adding the latest alpha with the new 0.10 infinity lib with a Null Pointer crash on startup.

[Null Pointer](https://paste.ee/p/Pp6Cd)

Hope this helps!

**Comment by Dilnu** [comment]
I'm experiencing the same crash:
https://pastebin.com/xYGrRh1v

**Comment by CodesCubesAndCrashes** [comment]
The #987 thread is about this issue, and has more information. It hopefully is fixed for the next release, but no eta on that. Cheers!

**Comment by InfinityRaider** [comment]
Closing this because its a duplicate
