### ISSUE TITLE
[1.10.2] Incompatible with Actually Additions

### ISSUE THREAD

**Issue by SHIuSH** [AgriCraft/AgriCraft#1014]
[Crash Report](https://paste.ee/p/WtgZW)

**Comment by TehNut** [comment]
#985

**Comment by TokkenGmr** [comment]
I was about to say the same thing, also check #998. May want to grab the changed JSON files till there is a fix. It fixed some of my issues not all

**Comment by RlonRyan** [comment]
This is a duplicate of #985. I should hopefully like to release a19 soon so that this issue stops getting duplicated...
