### ISSUE TITLE
Default Beet JSON files

### ISSUE THREAD

**Issue by KennyBurch** [AgriCraft/AgriCraft#1015]
Looks like the beet plant  "id":"beet_Plant" is used if you Pam's harvestcraft installed overwriting the vanilla version.

This prevents the vanilla mine craft beet seeds from being used properly.  I think i fixed it locally by renaming the "id":"beet_plant" to something else.

**Comment by TokkenGmr** [comment]
Should we just change the vanilla beet_Plant to beetroot_Plant or something similar? Seeing as its actual name is minecraft:beetroot. I know it would have to be replace in a few other places but it seems like the quickest fix

**Comment by bibo38** [comment]
I've just searched for all duplicates: See https://github.com/AgriCraft/AgriPlants/issues/27
As suggested in the issue, I would rather tend to a namespace feature to keep the id's mod specific.
