### ISSUE TITLE
1.10 a17: Agricultural journal doesn't record pre-analyzed seeds

### ISSUE THREAD

**Issue by Dilnu** [AgriCraft/AgriCraft#1019]
Steps to reproduce:
1: analyze a seed without the journal in the seed analyzer
2: remove the seed
3: insert journal
4: reinsert seed

Expected:
Journal updated

Actual:
Journal not updated

**Comment by InfinityRaider** [comment]
Has been like that for a while, but I suppose this could be fixed yes.

**Comment by CodesCubesAndCrashes** [comment]
This has been added, and it'll be in a20+.
