### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by 3DLudi** [AgriCraft/AgriCraft#1024]
Somewhat (distantly) related to:
https://github.com/AgriCraft/AgriCraft/issues/878

Please bring back the 1.7.10 option to disable resource crops.  Pretty please =)

    # set to true if you wish to enable resource crops [default: true]
    B:"Resource Crops"=false

And if this works into a future update, if selecting false could you remove the registration of your nuggets?  It is way too difficult to try and get UniDict working correctly with so many mods installed.

Thanks for your time and consideration...

**Comment by CodesCubesAndCrashes** [comment]
Quick question: have you tried just moving the resource crop JSON files out of your modpack's config? 

In the current versions of AgriCraft, the plants are under the control of the player. By removing them entirely, you would be making your client faster and leaner as well. But, once I can I'll remind myself what the 1.7.10 config achieved, and see what's different now.

**Comment by 3DLudi** [comment]
No, I can't say that I did.

 I did though look them all to see if I could spot anything resembling "nuggets" or "resource crops" but nothing jumped out at me.  Most of them seemed geared toward other mods seed/ plant compatibility as I remember it.  And due to the pain of trying to get rid of them (nuggets) via UniDict I simply opted to remove AgriCraft) :(.

UniDict is nice, and it tries hard, but duplicate ores really screw around with machine recipes.  Lets face it;  I have duplicate ingots/nuggets from Thermal Expansion, Immersive Engineering, Extreme Reactors, and Gaia.  A couple of other mods add ingots but they are unique so do not conflict with anything -- like demon ore (Extra Utilities).

Tomorrow I will download it again and test it out though.  I kinda have gotten used to having it around.

**Comment by 3DLudi** [comment]
Actually, now that I am thinking about it.  Couldn't you just use nuggets already existing in the OreDict or something?  After all.  What is the point of growing a copper nugget plant if copper ore is not added by another mod?

**Comment by 3DLudi** [comment]
OK I think I am finished testing.

Tried to delete all the folders but they all regenerated on the next startup (suppose that was expected).
Tried to delete all the files in the folders but they all regenerated on the next startup (again expected).

Went through all the JSON files and disabled them -- enabled: false.
Reloaded and all the nuggets are still there.
All non-vanilla variants did not have any function; no recipe or uses.
Vanilla ones did; dimond nugget*9 > dimond [[etc]] or vise versa.
All the nuggets were OreDicted so if I did add a mod which used that ore it would enable.

It was a good try.  Thanks for the suggestion.

**Comment by CodesCubesAndCrashes** [comment]
Sorry the suggestion was off. Yup, deleting those doesn't work. But doing "enabled: false" did work for me too. So it seems you found the resource crops in the end. 

The nuggets meanwhile are part of an older issue (#939), and still need improving.
