### ISSUE TITLE
Regenerating JSON files?

### ISSUE THREAD

**Issue by robertmaxton42** [AgriCraft/AgriCraft#1025]
Is it still possible to regenerate the default mutation files for all currently installed mods with default plugins? I would assume so but I can't seem to figure out how - there's nothing in the configs and no commands registered that I can see...

**Comment by bibo38** [comment]
Deleting the `*_mutation.json` files in `config/agricraft/json/defaults` should regenerate these.

Otherwise you can just download the config files from https://github.com/AgriCraft/AgriPlants and place them in `config/agricraft/json/defauls`.

**Comment by CodesCubesAndCrashes** [comment]
Sorta. If you're only interested the mods that are supported by default*, then you can do it like bibo38 said. I had tested that that still worked, but forgot to report back. If you're curious, the defaults get transferred over here: [Line 71 of CoreHandler.java](https://github.com/AgriCraft/AgriCraft/blob/master/src/main/java/com/infinityraider/agricraft/core/CoreHandler.java#L71). It uses the `copyResource` method from AgriCore's `util.ReourceHelper` class. 

That said, it doesn't generate anything auto-magically. So if you have mods installed other than those that are part of the default* JSONs, then it won't help you. If you're coming from a mod pack which had defaults, then those should be easy enough to download and replace? 

Good luck!

* defaults = Actually Additions, Botania, Harvestcraft, Immersive Engineering, Mystic Additions, Mystic Agriculture, Natura, Resource Crops, and Vanilla. [[Link](https://github.com/AgriCraft/AgriPlants/tree/master)]

**Comment by RlonRyan** [comment]
Yup regenerating basically amounts to deleting the JSON files. All the supported default files will be regenerated automatically on the next launch (by a basic copy operation from the internal copy of the default JSON files).
