### ISSUE TITLE
[Agricraft] - Question - Enable Resources Crops

### ISSUE THREAD

**Issue by Misteralex007** [AgriCraft/AgriCraft#1027]
I have some trouble to enable resource crops in the update of the modpack FTB Beyond v1.9.0 I changed the config: set true instead of false but it doesn't work for the server work fine for the client. I did the same changes but I'm blocked. I need some help to figure out.

Thanks for your help

If you need more information

**Comment by olback** [comment]
I'm having the same issue as @Misteralex007. I tried setting up a new Server (FTB Beyond 1.10), and i can't get recourse crops working there either. After some googleing arround people said that i have to change `B:Enable Resource = true` but there is no entry called that in any of the configs. Is it even possible to enable recourse crops in this version? 

agricraft-2.0.0-0.10.0-a17

**Comment by RlonRyan** [comment]
You have to go into `config/agricraft/json/default/resource/` and edit all the files in there setting the `enabled` field to true.
