### ISSUE TITLE
a19: Seeds degrade on single spreading.

### ISSUE THREAD

**Issue by Dilnu** [AgriCraft/AgriCraft#1028]
It looks like the mutation stat divisor change might be being applied to sam-crop mutations which is confusing.

**Comment by CodesCubesAndCrashes** [comment]
@Dilnu 
Hi! I've uploaded a preview of the a20 release, which contains the fix for this stat increase problem. If you get a chance to try it out, let me know. Any feedback will be great. :)

https://github.com/AgriCraft/AgriCraft/releases/tag/v2.0.0a20
