### ISSUE TITLE
JSON plant configuration files need updated documentation

### ISSUE THREAD

**Issue by 3DLudi** [AgriCraft/AgriCraft#1030]
Some feedback on the custom plants JSON files (and bugs)...
Just added in three new soils and a turnip from Biomes O Plenty =) looks awesome BTW !

My adventures --
1>
The existing file structure is: default/**mod_modid**/.
So I thought I should do the same and create my files in default/**mod_biomesoplenty**/
AgriCraft would not read the files.  I had already read the online wiki which stated it needed to be:
default/**biomesoplenty_mod**/
But I thought the wiki was just outdated.

Some consistency would be nice to avoid confusion...

2>
Could not (initially) figure out how to identify farmland to add a soil type.  After all middle clicking farmland yields soil, not farmland.  It also does not show up in creative items list for JEI.  So I thought to myself it must be regular soil with metadata.  I tried adding some obvious text to soil config:
"tags": "", (in variants)
But anything I tried crashed the client.
It is my fault for messing around without knowing how it worked but I do not think it should have crashed either.

3> 
Perhaps a feature request?
I now have four different farmland dirts: default Minecraft and BOPs silty, sandy, and loamy.  The configs were easy and I was able to add all the relevant plants to all my soils but sadly JEI does not cycle through them as I expected them to.

New thought.  Do I need to OreDict them together somehow?  I was not able to find an OreDict for farmland...

**Comment by renadi** [comment]
You can ore dictionary items, but not blocks in the world I don't think.

**Comment by RlonRyan** [comment]
If this is still an issue please submit a pr to the AgriDocs repository.
