### ISSUE TITLE
[a19] HarvestCraft seeds not working

### ISSUE THREAD

**Issue by chland** [AgriCraft/AgriCraft#1031]
One of the last Harvestcraft-versions renamed all items to lowercase. For example "harvestcraft:artichokeItem" became "harvestcraft:artichokeitem". Because of that, the config-files a19 generates won't work with the latest Harvestcraft-version. You can't analyze or plant any of the HC-seeds.

You'll get tons of errors like:

`00:00:00] [Client thread/INFO]: Invalid Product: Invalid Item: harvestcraft:riceItem!`

and of course all mutations fail:

`[00:00:00] [Client thread/INFO]: Invalid Mutation: Invalid Child: "celery_plant"!`

**Comment by bibo38** [comment]
Already reported as #988 .

**Comment by RlonRyan** [comment]
Duplicate of #988.
