### ISSUE TITLE
Re-add MFR support

### ISSUE THREAD

**Issue by InjuredWolf** [AgriCraft/AgriCraft#1032]
Not sure whether this requires work on your side, MFR's side, or both, but now that MineFactory Reloaded is updated to 1.10, could the support be re-implemented for it please? Cheers,

**Comment by CodesCubesAndCrashes** [comment]
I think I might be accomplishing this with a revised version of #1022 (not uploaded yet, but in discussion), in which case I'll test it with the new MFR and report back.

**Comment by CodesCubesAndCrashes** [comment]
I'll check after the next release, but in the a21 branch AgriCraft crop sticks have support for the IGrowable interface, so they should be compatible with the Fertilizer by using [this](https://github.com/skyboy/MineFactoryReloaded/blob/master/src/powercrystals/minefactoryreloaded/farmables/fertilizables/FertilizableIGrowable.java) in MFR. Not sure yet if there's an easy way to register the AgriCraft crop block though.

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
