### ISSUE TITLE
Make it possible to update the Docs with PRs

### ISSUE THREAD

**Issue by bibo38** [AgriCraft/AgriCraft#1033]
Like noted in #1030, the Docs are outdated for the 1.10 version.
But because Github doesn't allow Pull Requests for the Wiki, there should be some better way.

My thoughts:

- Use an external service like [Read the Docs](https://readthedocs.org/) and put the docs maybe in the master branch.
- Put the docs into the [AgriCraft/agricraft.github.io](https://github.com/AgriCraft/agricraft.github.io) repository.
- Use some sort of automation(maybe TravisCI) to publish a folder in the master branch or a seperate branch into the [Wiki-Repository](https://help.github.com/articles/adding-and-editing-wiki-pages-locally/)

🚀 I hope that I can help updating the docs in the future! 🤣

**Comment by CodesCubesAndCrashes** [comment]
I also would love to contribute to the docs, by whatever system is possible. :)

**Comment by RlonRyan** [comment]
It really is a shame that the wiki can't accept pull requests...

**Comment by RlonRyan** [comment]
Fixed! See: https://github.com/AgriCraft/AgriDocs

Now just to update all the links...
