### ISSUE TITLE
a19: Potatoes are unable to pass 5/5/5

### ISSUE THREAD

**Issue by DinDillian** [AgriCraft/AgriCraft#1036]
Spent the past day trying to pass 5/5/5, and have been unable to so far. The configs are set to 10/10/10.

**Comment by DinDillian** [comment]
Created a modpack with just JEI, Agricraft a19 and Mystical Agriculture and couldn't pass 3/3/3.

**Comment by CodesCubesAndCrashes** [comment]
@DinDillian  
Hi! I've uploaded a preview of the a20 release, which contains the fix for this stat increase problem. If you get a chance to try it out, let me know. Any feedback will be great. :)

https://github.com/AgriCraft/AgriCraft/releases/tag/v2.0.0a20

**Comment by DinDillian** [comment]
@CodesCubesAndCrashes Tried using it and I have successfully managed to get some 10/10/10 potatoes
