### ISSUE TITLE
Mod ignores "Set to false to disable automatic JSON writeback" config line

### ISSUE THREAD

**Issue by pexium** [AgriCraft/AgriCraft#1039]
What it says on the tin. When I tried to manually update the JSON files to the recently uploaded fixed version in the Agriplants repo, even when said config line was set to false, Agricraft would re-add the broken defaults anyways. Version is most recent (19a).

**Comment by RlonRyan** [comment]
Write-back is not the same as re-generation. Write back is when AgriCraft goes through and automatically formats all the files in the JSON config. In order to remove plants you have to set the "enabled" field to false.
