### ISSUE TITLE
Mutated/Spreaded plants not being able to grow

### ISSUE THREAD

**Issue by TurboniumAlt** [AgriCraft/AgriCraft#1040]
I'm really new to agricraft, and I'm not sure if this is a known bug or not, but when I use the crop sticks to breed crops, they breed, but the waila tells me they aren't able to grow. This occurs with every plant. At the moment, im only using the single crop sticks to spread instead of mutate, but I will try to see if this occurs with mutated plants.
Edit: I have been able to mutate crops and they grow normally.

**Comment by Meth962** [comment]
Yeah, I found this out after an update and thought it was only mushrooms. But then found out it's also cactus, and eventually, all naturally spread crops.

https://github.com/AgriCraft/AgriCraft/issues/1029

**Comment by CodesCubesAndCrashes** [comment]
@TurboniumAlt Hi! I'm going to close this as a duplicate, and continue the discussion over in number 1029. If you can stop by that thread, I your feedback on my research would be much appreciated. Thanks!
