### ISSUE TITLE
(1.10.2) Seed Storage not Craftable?

### ISSUE THREAD

**Issue by Massivefro** [AgriCraft/AgriCraft#1041]
There isn't an option to craft the Seed Storage. I found out it existed through a video on YT. Tried using other versions and I see the options to Enable/Disable it but even though the options are set for it to be utilized Its still not currently craftable nor can I see it in JEI. 

Currently usinga; agricraft-2.0.0-0.10.0-a19.jar

**Comment by CodesCubesAndCrashes** [comment]
Seed storage has not been ported to 1.10.2. The plan is to get the core features stable before adding on the secondary features. See #1026 and #970. Cheers!

**Comment by Massivefro** [comment]
Wow this is great information. I looked through the three pages here to try not to repeat any issues but I suppose I missed what you referred to. Thanks a lot because I spent the last couple of days scouring the internet for a "how to" lol. Thanks again!
