### ISSUE TITLE
a19: Agricraft Tin Nuggets

### ISSUE THREAD

**Issue by DinDillian** [AgriCraft/AgriCraft#1043]
In the modpack I'm currently playing converting Thermal Foundation tin ingots into nuggets via the crafting table creates Agricraft tin nuggets. These nuggets however cannot be used in any recipes. Searching JEI for "@agricraft tin nugget" also reveals nothing.

Update: After investigating further with this issue, I tried to repeat the above steps in a creative world as opposed to the survival server the issue was discovered on, and Thermal Foundation tin nuggets were crafted. More investigation is required on my part to reproduce the issue.

Update 2: I tried creating the Mekanism 'oredictionificator' on the server to convert the Agricraft tin nuggets to Thermal Foundation ones. The oredictionificator recognises the nugget when searching nuggetTin to create a filter, however won't convert the nuggets when placed into the machine. This suggests to me that maybe there's a problem with the way that the nuggets are registered server side?

**Comment by TokkenGmr** [comment]
This is going to be related to #939 I am  pretty sure

**Comment by DinDillian** [comment]
Yes @TokkenGmr. The issue described there seems to be exactly the same as what I experienced.
