### ISSUE TITLE
Harvest Craft not being recognised by Agricraft at all?

### ISSUE THREAD

**Issue by jwebba** [AgriCraft/AgriCraft#1044]
Pam's HarvestCraft 1.10.2j.jar

agricraft-2.0.0-0.10.0-a19

It manages to work for botania, Immersive Engineering and mystical Agriculture? 

I tried moving the files over manually from "defaults" to my "server_numbers_numbers" but it didn't work.

**Comment by renadi** [comment]
You need to update your configs, Harvestcraft changed all items from
capitalized to lower case, I think you can download the updated files at
https://github.com/AgriCraft/AgriPlants

**Comment by TokkenGmr** [comment]
@renadi You are correct current repo has the harvestcraft fix

**Comment by xAlicatt** [comment]
@renadi @TokkenGmr Could I not just delete the Agricraft folder in configs and let it regenerate itself?

**Comment by renadi** [comment]
Yes, make sure you remove server and client side.

**Comment by xAlicatt** [comment]
K I've deleted the Agri and HC configs on both server and client and I'm still not able to plant HC seeds in crop sticks or put them in the seedalyser
