### ISSUE TITLE
GIVE SPRINKER BACK

### ISSUE THREAD

**Issue by khris190** [AgriCraft/AgriCraft#1045]
like in title GIVE ME MY SPLINKER BACK AND I WILL BE HAPPY

**Comment by InfinityRaider** [comment]
Im not sure, what do you want exactly, a sprinker or a splinker?
Either way, youre going to have to elaborate because I have no clue what either of them is.

**Comment by TehNut** [comment]
I think he wants the thing that puts the waiter on the craps

**Comment by darthvader45** [comment]
In order to clearly process all this bad grammar, the sprinkler needs to be added back into Agricraft.
