### ISSUE TITLE
agri crash my game

### ISSUE THREAD

**Issue by Goten87** [AgriCraft/AgriCraft#1047]
if i install the mod in my game
and look up for `@ag` my game crashes
use `agricraft-2.0.0-0.10.0-a19.jar`

**Comment by CodesCubesAndCrashes** [comment]
Given the timing, I'm guessing this was due to #1034. Please check that, try removing and then updating JourneyMap, and upload some logs to gist. If you reply here, we'll see it. But for others, I'm going to close this issue. Cheers!
