### ISSUE TITLE
AgriCraft - JourneyMap crash

### ISSUE THREAD

**Issue by Ockman** [AgriCraft/AgriCraft#1050]
While working on a custom modpack for my server I started noticing Agricraft crashing when you view it's creative tab or view it in JEI/NEI. I assumed it was from a mod adding seeds to it's creative tab, but after toggling through 1 by 1 to find the source, I found it to be Journeymap instead. I even went and updated Java just to be safe.

I made a clean new profile in curseforge with only the problematic mods installed, to recreate the exact crash without any other mods getting in the way:

- forge-12.18.3.2422
- agricraft-2.0.0-0.10.0-a19
- infinitylib-0.11.0
- journeymap-1.10.2-5.4.9b1

https://pastebin.com/hbixPz0u

If this turns out to be a problem with Journeymap and not Agricraft, I will direct this information to them instead, Most of the crash report points to InfinityLib/Agricraft though, so I figure starting on this end makes more sense.

**Comment by TokkenGmr** [comment]
I know that it only seems to happen on journeymap-1.10.2-5.4.9b1.

**Comment by ACGaming** [comment]
https://github.com/AgriCraft/AgriCraft/issues/1034#issuecomment-315677104

For now, just downgrade to the latest stable version of JourneyMap.

**Comment by accessdenied0** [comment]
This is a really strange issue... I'd never know it was Journeymap, if I didn't find this issue...

In my case it crashed every time a Item from Agricraft showed up in JEI. I could load the game and the world. So as well open my Inventory but If I turned the pages to Agricraft stuff [it crashed immediately.](https://pastebin.com/t0Xf0CqZ)

Even the crash pointed to Agricraft/JEI.

Strange. With JourneyMap-1.10.2-5.4.6.jar it is working fine.
