### ISSUE TITLE
Biomesoplenty turnip seeds problem

### ISSUE THREAD

**Issue by winnetrie83** [AgriCraft/AgriCraft#1051]
There is a json file for the biomesoplenty turnip seeds, but in game i can't plant them on the sticks.
What can i do to fix this?

**Comment by winnetrie83** [comment]
I checked my log to see how many plants that were registered. It said 91 and it had to be 93. I have IE , BOP and harvestcraft installed. That should give me 93 plants that can be planted within agricraft. So i checked every registered plant and found out that the biomesoplenty turnip is not registering AND the vanilla beetroot. I was able to fix the vanilla beetroot problem as it had the same id as the harvestcraft beet. I thought this was the problem for biomesoplenty, but alas it wasn't. At least i think it isn't. So now it is registering 92 out of 93 plants. The only 1 not working is the biomesoplenty 1.
For the vanilla beetroot, just change this:
`  "id": "beet_plant",`

to:
`  "id": "beetroot_plant",`
Do know this is only the case if you have harvestcraft installed!

**Comment by TokkenGmr** [comment]
As far as the vanilla beet being overwritten check [here](https://github.com/AgriCraft/AgriPlants/issues/27). I think the long term plan is to do something other than just a "name change", might be wrong tho.
As for the turnip seeds from biomesoplenty, did you create a custom JSON for the plant? BoP is not currently supported by default, can you supply your JSON for the turnip seeds please?

**Comment by winnetrie83** [comment]
https://pastebin.com/XU3f0wcF

Oh i thought, if i add it myself it would work anyways. Guess not

**Comment by TokkenGmr** [comment]
It will work if you add them yourself. I was able to get [this](https://pastebin.com/PFmFJVMi) to work. The first few times I tried to place it in "mod_biomesoplenty" it did not register, and I am not sure why. I will check naming structure later. Hope that helps. Also if it is just named turnip_plant then it will get overwritten by harvestcraft most likely, If I get a chance I will look into BoP JSON's.

**Comment by winnetrie83** [comment]
Oh awsome that worked for me as well. What variable you read after mod_ ?
The mod id? mod name? Anyway putting it in the vanilla folder works fine for me. This makes me happy! :-)
Thank you very much!

**Comment by TokkenGmr** [comment]
Glad it helped, also realized that turnip seeds are the only seeds added by BoP. So once I figure out why I could not get it to load from it's own folder I will make a PR

**Comment by RlonRyan** [comment]
I think this is fixed with a17

**Comment by winnetrie83** [comment]
lol after 2 years…….
