### ISSUE TITLE
Harvestcraft, handling "seed" varieties

### ISSUE THREAD

**Issue by winnetrie83** [AgriCraft/AgriCraft#1052]
There is a flaw in the json plants.
Mustard and sesam plant drops seed and seeds. I know very confusing!
Example you have mustard seed wich can be planted only, but you have also mustard seeds wich can be planted AND eaten. json file only handle the mustard seed and not the mustard seeds. So if you disable vanilla planting(wich is in my opinion the whole point), you can still plants the mustard seeds on normal soil. Same thing for the sesam seeds.

**Comment by TokkenGmr** [comment]
I am unable to duplicate this. I have tried to plant both mustard seeds and sesame seeds on farmland and I am unable to get them to plant, I can eat them no problem. The seed for each of the plants is working as intended it plants and gives you seeds that you can eat but not plant. Not sure on this one, fresh instance and everything is fine.

**Comment by winnetrie83** [comment]
What MC version are you? I am on 1.10.2. I have fixed my problem with some tweakings here and there. Without that, the seeds you can eat can also be planted, the other seed works like intended.

**Comment by TokkenGmr** [comment]
MC 1.10.2
Forge 12.18.3.2422
Agricraft  a19
Harvestcraft 1.10.2j

I do apologize, I somehow included Hunger Overhaul in that instance which makes it so you can not plant the seeds that you can eat. When I remove it from the instance I am then able to plant the seeds as well I will add the JSON's for those seeds when I make my next push to agriplants repo. Nice catch.

**Comment by winnetrie83** [comment]
I have made json files to fix this for the moment. It is not a nice fix, but it works somehow. They can still be planted, but only on the cropsticks, like all other plants. I actually do not want them to be plantable but i do not know how to disable that. Instead i was able to set the growth chance to 0.0! So now both edible sesam and mustard seeds can only be planted (when vanilla planting is disabled) on cropsticks, but will not grow! Because i want to force "the player" to plant the non edible seed ofcourse!
If there is a way to disable the capability to plant a registered crop, i will be happy to hear!
If you like i can post the jsons

**Comment by winnetrie83** [comment]
I have fine tuned the json files and they now work properly! The edible seeds cannot be planted now with these json files.
Mustardseeds .json: https://pastebin.com/wRruXA2q
Sesamseeds .json: https://pastebin.com/RJqrS9wY

What i have done to prevent them to be planted is at the "required soil" adding "disabled" instead of farmland_soil. Unless there is a mod that have a soil called "disabled" , the json will work fine now.

**Comment by winnetrie83** [comment]
Since i saw MatrexsVigils answer on your post. I went trying to plant any crops while vanilla planting is disabled. It appears you can still plant the crops. I just never tried to plant the crops, because i thought there are seeds for a reason. Apparently not, not really. You still can analyze them to get better. So you will have to add something to your code or add .json files to prevent crops from being planted when vanilla farming is disabled. I can help you with that if you like. I already created it for sesam and mustard.

**Comment by CodesCubesAndCrashes** [comment]
I think the bug here with normal behavior has been fixed and released, but worth saying that the discussion could be useful for making a more hardcore set of configurations.
