### ISSUE TITLE
CustomStuff Blocks & Items Not Found By AgriCraft

### ISSUE THREAD

**Issue by MBelhardi** [AgriCraft/AgriCraft#1053]
Don't know if this is a problem with CustomStuff 3 (1.10.2-0.11.10) or AgriCraft (2.0.0-0.10.0-a19), so I will post it at both mods
I have tried to make a new Item/Block (with CustomStuff) and used it for the products-part of an AgriCraft Crop, but the recipe won't show.
Same when I tried to put a block, created with CustomStuff, as a dependent/conditional block, but like before, the recipe won't show.

**Comment by InfinityRaider** [comment]
CustomStuff probably registers its blocks and items too late

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
