### ISSUE TITLE
Problems with creating new custom recipes for Agricraft (2.0.0-0.10.0-a19) 

### ISSUE THREAD

**Issue by MBelhardi** [AgriCraft/AgriCraft#1054]
- artificial blocks (like air, water, lava, fire) won't be accepted as dependent/conditional blocks (I've tried to use the for the element-seeds for "Primoral Crops")
- if I put, as a condition, that the crop has  to look, in a 3x3 grid under the farmblock, for 9 blocks of, for example, gold-ore, to accept a seed, then all that is realy needed is 1 block in the 3x3 grid, and the seed will be accepted
- Some blocks, such as skulls, will be accepted as dependent/conditional blocks for the recipe, but, when placed under the farmblock, they are not recognized by the seed.

**Comment by CodesCubesAndCrashes** [comment]
I can offer something for that second point. I haven't checked out the other two yet.

So I found a typo in the plant and requirement loading code that was causing all the BlockConditions to be created with the amount set to 1. I fixed it two different ways, but I'm preferring [PR #3](https://github.com/AgriCraft/AgriCore/pull/3) on AgriCore.

To test that out I changed the JSON for a Diamahlia plant like this:
```
    "conditions": [
      {
        "amount": 3,
        "min_x": -1,
        "min_y": -2,
        "min_z": -1,
        "max_x": 1,
        "max_y": -1,
        "max_z": 1,
        "item": "minecraft:diamond_ore",
        "meta": 0,
        "tags": "",
        "ignoreMeta": true,
        "ignoreTags": [],
        "useOreDict": true
      }
    ]
```
And then I verified various combinations: [**pictures!**](http://imgur.com/a/EoUq8) 
![2017-08-28_08 52 46](https://user-images.githubusercontent.com/28678248/29775980-30dcec70-8bd5-11e7-8df3-9224ca788a2a.png)
