### ISSUE TITLE
how to translate (localisation) of plant-name and seed-name?

### ISSUE THREAD

**Issue by MBelhardi** [AgriCraft/AgriCraft#1059]
how can I translate the tags "plant_name" and "seed_name". I know how to translate the description, because it's part of the json-files, but I don't know, how I can implement the localisation (lang-files) because I don't know how the tags are defined in the localisation. Maybe you can give us an example.

**Comment by RlonRyan** [comment]
The plant_name and seed_name tags currently do not support translation. This is a feature to be possibly added in the future.

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
