### ISSUE TITLE
JEI and AgriCraft

### ISSUE THREAD

**Issue by Harlou** [AgriCraft/AgriCraft#1060]
I've been having a lot of issues with AgriCraft and JEI.
[crash-2017-08-08_14.27.37-client.txt](https://github.com/AgriCraft/AgriCraft/files/1209319/crash-2017-08-08_14.27.37-client.txt)

The crash occurs when I type something into the JEI bar and an agricraft item appears.

**Comment by TehNut** [comment]
#1034
