### ISSUE TITLE
seed analyzer not opening up gui

### ISSUE THREAD

**Issue by Figruingrabbit** [AgriCraft/AgriCraft#1068]
I am unable to open up the seed analyzer gui i have tried with just agricraft and its lib but it still doesn't work

**Comment by CodesCubesAndCrashes** [comment]
Hi! What versions of Minecraft, AgriCraft, and InfinityLib were you using? An if InfinityLib isn't up to date that can cause that problem.

Otherwise, was this in an existing world or did you try it in a new save? Could you upload the full log file from your test, showing the start up and the click attempts?

Also, you should check out and post your data to #1046, that is the thread for this bug. 

Thank you!

**Comment by Figruingrabbit** [comment]
minecraft version 1.10.2 agricraft version 2.0.0-0.10.0-a19 and infinity lib version 0.11.0

**Comment by CodesCubesAndCrashes** [comment]
Hm, interesting. If you have answers to the following questions, can you post them in #1046 please?

Does the problem happen in single player, multiplayer, both? How about in a brand new save? (Using creative mode should be fine.) Can you upload the logs?

Thank you!

**Comment by Figruingrabbit** [comment]
My problem happens in both single player and multiplayer

**Comment by superdude808** [comment]
i can confirm the same problem and same everything

**Comment by Boolyman** [comment]
I am currently looking for a resolution to this problem for the players using my modpack.  I have recieved multiple tickets regarding this.

**Comment by xAlicatt** [comment]
Downgrade InfLib to 0.10.0 fixes this.

**Comment by Fastjur** [comment]
I also have this issue on the latest ftb beyond pack:

* MC 1.10.2
* Agricraft 2.0.0-0.10.0-a19
* infinitylib-0.11.0

**Comment by CodesCubesAndCrashes** [comment]
@Fastjur Using InfinityLib 0.10 will solve the problem, or you can use the unofficial a20 or a21 builds of AgriCraft. I'm hoping to do a stable release soon. 

In the meantime, this is still a duplicate thread. So I'm closing it. :)

**Comment by Fastjur** [comment]
Great. Thanks for picking it up!
