### ISSUE TITLE
Can't plan any seed on crop sticks.

### ISSUE THREAD

**Issue by Aneexul** [AgriCraft/AgriCraft#1076]
I'm playing on Agricraft 2.0.0.-0.11.0-a20 and using infinitylib-0.11.0. When I loaded up a world, and tried to plant seeds, it won't let me plant any type of seeds in crop sticks. I was initially trying it with Mystical Agriculture Tier 2 Inferium Seed but it did not even work for the vanilla ones, like potato or wheat. I tried to analyze them first, they all get 1-1-1 trait and even then it doesn't want to plant.

In rare occasions, if I make a new world and try to plant it will plant, but it takes forever to grow. Then once harvested, I can't plant anymore stuff in any crop sticks / farm land.

---------------------
Edit:
Well I think the problem is most of the seeds require a high light level like 10 or more...

How can I change them to a lower value? Most of my farmland is like 8-10 light only.. only few are 11-13

I used the json files from [Mystical Agriculture](https://minecraft.curseforge.com/projects/mystical-agricraft), and the mystical agriculture crops are growing / spreading / mutating correctly (at-least on the seeds i have tested) but the spreading / mutation takes for ever.. even with higher trait seeds like 9-8-9 takes 2+ mins to make a new improved seed in the middle..

Any way to change those times?

**Comment by CodesCubesAndCrashes** [comment]
Both the light level requirements and the per-mutation success chance are controlled by the JSON files. You can edit your copies and adjust them. They're found inside of `\minecraft\config\agricraft\json\`, where each server has its own subfolder. (defaults = local.) 

Also, a plant won't spread or create a mutant offspring anywhere that its growth requirements aren't satisfied, and that includes light level. That can slow things down too. 

You can also play with the settings in the Mod Options sub menu for AgriCraft. The 'Cross Over Chance' is the first probability check that a cross crop does when it gets an update. So a higher value will speed things up. And there's also 'Mutation Chance', which controls if a cross crop is more likely to create a mutant offspring of two neighbors (when the setting is high), or instead create a stronger version of a spreading neighbor (when the setting is low). 

In any case, make sure that after you change anything, you restart Minecraft. And if you play on a dedicated server, make sure your modified JSON files are the same on the server.
