### ISSUE TITLE
Irrigation sprinklers dont work

### ISSUE THREAD

**Issue by nak0604** [AgriCraft/AgriCraft#1078]
Running a modpack with agricraft 2.0.0-0.10.0-a19 and minecraft 1.10.2 and irrigation sprinklers wont irrigate the tilled dirt blocks.

**Comment by darthvader45** [comment]
They currently irrigate at the origin 0,0,0 and above the sprinkler.  Try going to the Agricraft Discord server and download a21.

**Comment by CodesCubesAndCrashes** [comment]
Duplicate of #862. But the fix is in testing!
