### ISSUE TITLE
Fire Forge events for crops

### ISSUE THREAD

**Issue by CodesCubesAndCrashes** [AgriCraft/AgriCraft#1080]
## To do
- [ ] Look up event spawning references and practices.
- [ ] Find which events are relevant. 
- [ ] ...

## Potential Events
* `BlockEvent.CropGrowEvent`
* `BlockEvent.HarvestCropsEvent`
* `CropPlantedEvent` (AgriCraft's own)
* `EntityEvent.LivingEvent.PlayerEvent.BonemealEvent` (Not our responsibility, I suspect.) 
* `HarvestCheck` in `PlayerEvent`?

## Links 
* https://github.com/AgriCraft/AgriCraft/blob/master/src/main/java/com/infinityraider/agricraft/tiles/TileEntityCrop.java#L105-L109
* https://github.com/TheAtomicOption/harvestcraft/blob/5fcd69fdea95b2b9336166cb6ed3cdcd6b4fcd2d/src/main/java/com/pam/harvestcraft/blocks/growables/BlockPamCrop.java#L152-L154

**Comment by InfinityRaider** [comment]
I suggest extending the CropGrowEvent and HarvestCropsEvent with two new events in the API, to also pass the ICrop object, and fire these instead.

**Comment by Buuz135** [comment]
It would be neat if the 1.12.2 had those events

**Comment by InfinityRaider** [comment]
Such events will be in 1.16 rewrite.
