### ISSUE TITLE
Support the ActuallyAdditions Farmer

### ISSUE THREAD

**Issue by bibo38** [AgriCraft/AgriCraft#1086]
## Quick description
Currently there are few ways to automate harvesting AgriCraft Crops in 1.10.2. This Issue focuses on Auto-Farming with the Actually Additions Farmer

## Related issues and searches
Actually Additions, Farmer, Auto-Harvest

## Mods and versions used
Just tested with FTB Beyond Version 1.11.

## Steps to replicate the issue
- Make a little Farm
- Plant some AgriCraft crops  with seeds
- Add a Actually Additions Farmer facing the farm.
- Give the Farmer a Power source
- No Profit!

## Expectations and explanations
- The farmer should harvest fully grown wheat crops in crop sticks.
- It should also plant seeds in empty cropsticks

## Your environment
* How are you playing?
  * Operating System: Windows
  * Launcher: FTB Launcher
  * Modpack: FTB Beyond 1.11
* What kind of server:
  * [x] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [ ] Survival
  * [x] Creative
* Save File:
  * [x] Brand new save
  * [ ] Only an existing save

## Possible Solution
Implement the `IFarmerBehaviour` from Actually Additions. Examples can be found at https://github.com/Ellpeck/ActuallyAdditions/tree/master/src/main/java/de/ellpeck/actuallyadditions/mod/misc/apiimpl/farmer

**Comment by RlonRyan** [comment]
Fixed in 1.12 branch.
