### ISSUE TITLE
Machine Request

### ISSUE THREAD

**Issue by Colton-Slayden** [AgriCraft/AgriCraft#1087]
## Quick description

Was wondering if you can add a machine to auto sort out the best seeds/stats given in a filter. For example if you want only seeds with 5 or higher stat in one chest have it run through and send the ones that meet the requirement outputted to one face while the ones that don't get shoved out another face

## Related issues and searches

* https://github.com/AgriCraft/AgriCraft/issues?q=is%3Aissue%20EXAMPLE

## Mods and versions used

* Minecraft:
* AgriCraft:
* InfinityLib:
* [List the other required mods here]

## Steps to replicate the issue

1. Loaded up `...`
2. Placed a `...`
3. Right-clicked with `...` on `...`
4.

## Your environment

* How are you playing?
  * Operating System:
  * Launcher:
  * Modpack:
* What kind of server:
  * [ ] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [ ] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc

* https://gist.github.com/
* https://paste.ee/
* https://duckduckgo.com/?q=pastebin+alternatives
* Upload them somewhere, and then replace these links.

**Comment by darthvader45** [comment]
Would be cool for auto-sorting systems.

**Comment by InfinityRaider** [comment]
Related to #43

**Comment by darthvader45** [comment]
I believe a silo, as I said before, would be better than a warehouse.

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
