### ISSUE TITLE
Agricraft crops will not grow/spread when offline, even if chunkloaded

### ISSUE THREAD

**Issue by TheLargeCactus** [AgriCraft/AgriCraft#1088]
## Quick description

I am running agricraft-2.0.0-0.11.0-a21 for minecraft 1.10.2 on forge-12.18.3.2511 and infinitylib-0.11.0 and for some reason, even when chunks are loaded via FTBU, crops do not grow/spread while my character is offline. Offline chunk loading is enabled in FTBU, and through testing the chunks appear to stay loaded when I am offline. Other machines in said chunks still function, but crops do not grow/spread.

## Steps to replicate the issue

1. Load game with mentioned mods
2. place crops down with spread possible
3. load chunks via FTBU, making sure config allows for offline chunk loading
4. notice how plants never grow/spread while offline.

## Expectations and explanations

If the chunk is loaded, the game should function as normal in those chunks, meaning crops should grow/spread.

## Your environment

* How are you playing?
  * Operating System: Windows 10 Education
  * Launcher: Twitch
  * Modpack: Modified Direwolf20 1.10.2
* What kind of server:
  * [ ] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [X] Only an existing save

**Comment by InfinityRaider** [comment]
This means the crops are not receiving random ticks anymore.
Do vanilla crops grow or not?

**Comment by TheLargeCactus** [comment]
Apologies, turns out that the problem was with FTBU not loading chunks.
