### ISSUE TITLE
Crafting irrigation gates always creates spruce variants

### ISSUE THREAD

**Issue by JCLaHoot** [AgriCraft/AgriCraft#1093]
## Quick description
When crafting irrigation channel valves or the bigger square irrigation channels, no matter what type of wood I use it gets crafted as Spruce

## Mods and versions used
* Minecraft: 1.10.2
* AgriCraft: a21
* InfinityLib: 0.11.0

## Steps to replicate the issue
- Make a simple irrigation channel using any wood.
- use that irrigation channel to try to craft a valve, or one of the square irrigation channels (btw what are the square ones for exactly?)
- Notice that the new valve or channel is spruce... somehow.

(I tried using actual spruce to make my irrigation stuff, and that didn't work either.  It's ridiculous, but the valve is now made of "Spruce Planks" but my channels and tanks are made of "Spruce Wood Planks")

## Expectations and explanations
The wood type shouldn't change for no reason.
There shouldn't be multiple types of spruce -.-

## Your environment

* How are you playing?
  * Operating System:  Mac OS 10.13.3
  * Launcher: Forge 12.18.3
  * Modpack: FTB Beyond
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [X] Only an existing save

## Screenshots (or videos)
<img width="731" alt="asdf" src="https://user-images.githubusercontent.com/12401777/36362033-fc32e2b4-14fe-11e8-9995-0a49daa3b7cb.png">
<img width="698" alt="asdfasd" src="https://user-images.githubusercontent.com/12401777/36362034-fc3f6854-14fe-11e8-9765-416319eb91fc.png">

**Comment by RlonRyan** [comment]
Fixed in the 1.12 branch.
