### ISSUE TITLE
Unable to plant silicon seeds in crop sticks - No json file

### ISSUE THREAD

**Issue by imazing** [AgriCraft/AgriCraft#1094]
* Minecraft: 1.10.2
* AgriCraft: 2.0
* InfinityLib: 0.11

Placing mystical agriculture plants hadn't been an issue until I attempted to plant the silicon seed. I can't place the seed on the crop sticks, but I can place it on normal farmland. Is there something I can do personally to fix this?

*edit* I took a look through the configs for mystical agriculture and there's no json file for the silicon seed

**Comment by RlonRyan** [comment]
You can fix this yourself by creating your own JSON file for the silicon plant. If you wind up creating one, submitting it to the AgriPlants repo would be greatly appreciated.

**Comment by darthvader45** [comment]
Check AgriPlants, submitted pull request for the addition of silicon plant.
