### ISSUE TITLE
Server crash due to client side calls

### ISSUE THREAD

**Issue by tyra314** [AgriCraft/AgriCraft#1095]
## Quick description
Crash on server because of ClientSide shit called

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a0
* InfinityLib: 1.12.2-1.12.0  

## Steps to replicate the issue
Try running it on server

## Your environment
* What kind of server:
  * [ ] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
https://gist.github.com/tyra314/dbec811e73b64929956812e640e3f0e7

**Comment by Matryoshika** [comment]
It's a dumb Forge thing. 
Forge manages to post the event-handler to both sides, even though it [should only exist on one](https://github.com/AgriCraft/AgriCraft/blob/master/src/main/java/com/infinityraider/agricraft/handler/TextureStitchHandler.java#L12).

@RlonRyan SideOnly needs to be annotated on methods, not the class itself, in an annotation-based, eventbus subscription class.

**Comment by TehNut** [comment]
No, the even subscriber annotation needs to have the side changed from both (default) to client. The modid should also be added.

**Comment by AcidGames** [comment]
Same issue https://pastebin.com/we7KVcty

**Comment by RlonRyan** [comment]
Fixed in 1.12.0a1
