### ISSUE TITLE
[1.12.2] Irrigation Channels Don't Fill Up

### ISSUE THREAD

**Issue by EmosewaPixel** [AgriCraft/AgriCraft#1096]
## Quick description
 Simply Irrigation Channels don't accepy Water from adjacent filled Wooden Water Tanks.

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a1
* InfinityLib: 1.12.0

## Steps to replicate the issue
1. Fill up a Wooden Water Tank
2. Place an Irrigation Channel next to it

## Expectations and explanations
 I expected the Irrigation Channel to fill up and then have a working Sprinkler connected to it.

## Your environment
* How are you playing?
  * Operating System: Windows 10
  * Launcher: Twitch
  * Modpack: Modern Skyblock 3 
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [ ] Brand new save
  * [X] Only an existing save

## Screenshots (or videos)
![image](https://user-images.githubusercontent.com/25333164/36974654-ae8bd000-2077-11e8-9f60-d91bd0a514a3.png)

**Comment by RlonRyan** [comment]
Already on it. I decided to completely scrap the irrigation system for the next alpha, because why not? So the next version could have a more broken irrigation system or a less broken one...

**Comment by darthvader45** [comment]
That's good, always good to polish it up before it makes it in fully, so that nothing's majorly wrong.  Instead of scrapping the code entirely, just comment it out until you have a solid fix.  That way you can come back to it later.  Unless you meant to completely rewrite it, which is fine too.

**Comment by TheAdventAgain** [comment]
Is there any kind of work around for this issue that anyone has found in the meantime by chance?

**Comment by gff1979** [comment]
Well, it would be nice if you could either roll back to a time where it worked. You bust be really busy. I'll try installing older versions until I find a version that might work off curse. Hopefully you get it fixed soon.
