### ISSUE TITLE
Seed stats do not improve after mutation.

### ISSUE THREAD

**Issue by 41k0n** [AgriCraft/AgriCraft#1097]
## Quick description
Mutations seem to not work.

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 1.12.0-a2
* InfinityLib: 1.12.0

## Steps to replicate the issue
Place 2 seeds, put a crosscrop between them, wait. Mutated seed is always 1/1/1. 

## Expectations and explanations
I expected the mutated seed to have improved values.

## Your environment

* How are you playing?
  * Operating System: Win10
  * Launcher: MultiMC
  * Modpack: none
* What kind of server:
  * [X] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Screenshots (or videos)

https://imgur.com/a/R67Nf

**Comment by InfinityRaider** [comment]
Try surrounding it with 4 (one on each side), and see what that gives

**Comment by 41k0n** [comment]
I tried that. I did seven mutations and none had improved values.
