### ISSUE TITLE
[1.12.2] Crops With AgriCraft Seeds Drop Ones Without NBT

### ISSUE THREAD

**Issue by EmosewaPixel** [AgriCraft/AgriCraft#1100]
## Quick description
 When breaking Crop Sticks with a crop that has AgriCraft Seeds, a Seed without any NBT is dropped.

## Mods and versions used
Minecraft: 1.12.2
AgriCraft: 2.12.0-1.12.0-a1
InfinityLib: 1.12.0

## Steps to replicate the issue
1. Place Crops Sticks
2. Put a crop that uses AgriCraft Seeds in them
2. Break the Crop Sticks

## Expectations and explanations
 I expected the correct Seeds to drop.

## Your environment
* How are you playing?
  * Operating System: Windows 10
  * Launcher: Twitch
  * Modpack: Crimson Skies
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [ ] Brand new save
  * [X] Only an existing save

**Comment by fguillod** [comment]
I have the same issue. Breaking a crop drops crystalline seeds, and when I use the scanner, it turns them into potato seeds.
