### ISSUE TITLE
[1.12.2]Breaking crops with potato/carrot plant drops Crystalline seeds

### ISSUE THREAD

**Issue by SlyJacobTheBeast** [AgriCraft/AgriCraft#1101]
## Quick description

When you place down crop sticks, place a potato or carrot on them and then break it all, it will drop Crystalline seeds and the crop sticks.
## Mods and versions used

* Minecraft: 1.12.2
* AgriCraft: agricraft-2.12.0-1.12.0-a1
* InfinityLib: infinitylib-1.12.0
* [List the other required mods here]

## Steps to replicate the issue

1. Place down crop sticks
2. Place carrot or potato on them
3. Break the crop sticks
4. Profit?? (Crystalline seeds)

## Expectations and explanations

Was expecting the source seed.
## Your environment

* How are you playing?
  * Operating System: Win10
  * Launcher: Twitchapp
  * Modpack: Private modpack
* What kind of server:
  * [x] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [x] Survival
  * [ ] Creative
* Save File:
  * [x] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc

* https://gist.github.com/
* https://paste.ee/
* https://duckduckgo.com/?q=pastebin+alternatives
* Upload them somewhere, and then replace these links.

**Comment by RlonRyan** [comment]
Is this still an issue with the latest releases?
