### ISSUE TITLE
[1.12.2] No Tooltips In The Seed Analyzer

### ISSUE THREAD

**Issue by EmosewaPixel** [AgriCraft/AgriCraft#1108]
## Quick description
 Item tooltips/names don't display when hovering over them in the Seed Analyzer.

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a1
* InfinityLib: 1.12.0

## Steps to replicate the issue
1. Open the Seed Analyzer's GUI
2. However over an item

## Expectations and explanations
 I expected the tooltips to be displayed.

## Your environment
* How are you playing?
  * Operating System: Windows 10
  * Launcher: Twitch
  * Modpack: Modern Skyblock 3 
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [ ] Brand new save
  * [X] Only an existing save

## Screenshots (or videos)
![image](https://user-images.githubusercontent.com/25333164/37876589-d201d2f0-304e-11e8-9376-cf52ae6e9e27.png)

**Comment by TehNut** [comment]
@RlonRyan Minecraft changed how GuiContainer draws things. You need to manually make some calls that used to be there by default:

 ```java
    @Override
    public void drawScreen(int mouseX, int mouseY, float partialTicks) {
        this.drawDefaultBackground();
        super.drawScreen(mouseX, mouseY, partialTicks);
        this.renderHoveredToolTip(mouseX, mouseY);
    }
```

**Comment by RlonRyan** [comment]
Thanks for the assist @TehNut!
