### ISSUE TITLE
[Suggestion] Config To Disable Weeds

### ISSUE THREAD

**Issue by EmosewaPixel** [AgriCraft/AgriCraft#1109]
I haven't found any way to disable Weeds in the 1.12.2 version of the mob. Could you please add that or at least make the chances of ones spawning configurable?

**Comment by ThePoet444** [comment]
It's JSON controlled now. Go into config > agricraft > json > defaults >vanilla > plants  Then edit the weeds.json

**Comment by EmosewaPixel** [comment]
Yeah, I found it right after...
