### ISSUE TITLE
Weed Seed Config option not working

### ISSUE THREAD

**Issue by Treehawk-Watts** [AgriCraft/AgriCraft#1110]
## Quick description
Changing the config setting "Raking weeds drops seeds" under "Farming Settings" does nothing. Both "false" and "true" options have weeds drop weed seeds when raked.

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a3
* InfinityLib: 1.12.0

## Steps to replicate the issue
1. Go to mod options, change AgriCraft config Farming Setting "Raking weeds drops seeds" to false
2. Let weeds grow on a crop stick.
3. Right click the crop with a rake. Weed seeds drop.

## Expectations and explanations
Expectation: No weed seeds should drop when raked.

## Your environment
* How are you playing?
  * Operating System: Windows 10
  * Launcher: Twitch
  * Modpack: custom modpack containing only agricraft & dependancies
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Screenshots (or videos)
![2018-03-30_20 34 38](https://user-images.githubusercontent.com/37279532/38158481-a1186270-345a-11e8-8a46-64e56acf0d3a.png)
![2018-03-30_20 30 33](https://user-images.githubusercontent.com/37279532/38158482-a12c7468-345a-11e8-9bec-46b111d85c15.png)
![2018-03-30_20 34 23](https://user-images.githubusercontent.com/37279532/38158483-a14006ae-345a-11e8-9eee-b5fa8e79b3e8.png)

**Comment by Liinche** [comment]
Confirmed

**Comment by SAFCxHarter** [comment]
Confirmed too... It hasn't worked in the past version "a1" either
