### ISSUE TITLE
Crash caused by placement and removal of irrigation channels on water tank

### ISSUE THREAD

**Issue by Globberbob** [AgriCraft/AgriCraft#1112]
## Quick description

(Crashed) Placed a wooden irrigation channel attached to a water tank above a previously placed channel, issue also occurred on breaking any channel attached to the water tank. (Hoping this is maybe on my end so I can fix it asap, otherwise I hope this is informative)
## Related issues and searches

* https://github.com/AgriCraft/AgriCraft/issues?q=is%3Aissue%20EXAMPLE

## Mods and versions used

* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a3
* InfinityLib: 1.12.0
* [List the other required mods here]

## Steps to replicate the issue

1. Build water tank.
2. Place an irrigation channel on the side.
3. Place an irrigation channel above the previous

or
1. Have an irrigation channel above another channel.
2. Break the top irrigation channel.

## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: Twitch (FTB)
  * Modpack: FTB Revelation for MC 1.12.2
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc

https://pastebin.com/SmrBDkuL

**Comment by RlonRyan** [comment]
Is this still an issue with the latest releases?
