### ISSUE TITLE
[1.12.2] Sprinklers Don't Work

### ISSUE THREAD

**Issue by EmosewaPixel** [AgriCraft/AgriCraft#1113]
## Quick description
 Sprinklers don't fill up with Water from Irrigation Channels.

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a3
* InfinityLib: 1.12.0

## Steps to replicate the issue
1. Set up an Irrigation system
2. Get the Channels to fill up

## Expectations and explanations
 I expected the Sprinkler to fill up with Water and work.

## Your environment
  * Operating System: Windows 10
  * Launcher: Twitch
  * Modpack: Modern Skyblock 3
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Screenshots (or videos)
![image](https://user-images.githubusercontent.com/25333164/38246616-a4eda06e-3742-11e8-94e9-fc3bc84652e5.png)

**Comment by shufunk** [comment]
Actually it does work but in a weird way! You setup the system but have to break the system to make it work.... Just watch my video to see how weird this is! Either way it's really bugged!

https://youtu.be/Hd7Aa8oxSz4
