### ISSUE TITLE
[1.12.2] TOP Tooltips are broken on servers

### ISSUE THREAD

**Issue by EmosewaPixel** [AgriCraft/AgriCraft#1114]
## Quick description
 On servers, and only on servers, the tooltips in TOP for AgriCraft are broken.

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a3
* InfinityLib: 1.12.0

## Steps to replicate the issue
1. Load up an instance with AgriCrat and TOP on a server
2. Place Crop Sticks and Seeds on them
3. Look at them

## Expectations and explanations
 I expected the tooltips to display properly, as they do in SP.

## Your environment
  * Operating System: Windows 10
  * Launcher: Twitch
  * Modpack: Modern Skyblock 3
* What kind of server:
  * [ ] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Screenshots (or videos)
![image](https://user-images.githubusercontent.com/25333164/38306061-8ffc8ce2-380f-11e8-96b4-1c531a15015d.png)

**Comment by RlonRyan** [comment]
It's because TOP seems to be handling tooltips on the server-side, but the server side cannot translate, so what is TOP doing on the server side?

**Comment by RlonRyan** [comment]
I see. TOP gets all information from server side as to ensure it is not out-of-date, so you have to wrap all translation keys in "{**}" and top will translate them once they get to the client side.
