### ISSUE TITLE
Water tanks are not filling up

### ISSUE THREAD

**Issue by mrjoejoe** [AgriCraft/AgriCraft#1119]
## Quick description
Hey I recently created my own 1.12.2 Modpack and Agricraft is one of the mods. I already used it in 1.7.10 and had tons of fun using it. Today I tried building some Water tanks to make my crops grow faster but the tanks just would not fill up when it was raining. Putting buckets of water in there would do nothing either. I then created another world, went into creative and build some Water tanks from all kinds of materials but rain would still not fill them up but when I put buckets of water in there the first 5 times the water would just go away after a second after that it would fill up but quite slow.

## Related issues and searches
No related Issues found

## Mods and versions used

* Minecraft: 1.12.2
* AgriCraft: agricraft-2.12.0-1.12.0-a3
* InfinityLib: infinitylib-1.12.0
I tried running the forge 12.2 version without all those mods listed below and it would not work either so it can´t be a problem with those mods I guess.

About 60 mods that would take hours to list all versions used here. I use forestry with addons, journey map, JEI, Real World, Plants, Astral Sorcery, Ambient Sounds, Ender Storage, Twilight Forest, Erebus, Tinkers Construct, Storage Drawers, Harvestcraft, mystical agriculture, Optifine, Garden Stuff, Hopperducts, Redstonepaste, Ezstorage, Torchmaster, Simply Enchanting, Exotic Birds, Animania, Botania, Chococraft, Chisel, Biomes O plenty, Better Foliage, Torohealth, Inventory Tweaks, Soul Shards
  

## Steps to replicate the issue

1. Loaded up `minecraft with all the mods and just with agricraft`
2. Placed a `bunch of water tanks`
3. Used toggledownfall to see if tanks fill up also used buckets of water

## Expectations and explanations
 Rain should have filled up the tanks
 It worked in 1.7.10 so I guess it´s a bug since I couldnt find anywhere that it´s some kind of new mechanic

## Your environment

* How are you playing?
  * Operating System: Windows 10 64 Bit
  * Launcher: Forge Profile: 1.12.2 - 14.23.2.2651
  * Modpack: My Own/Also tried Agricraft only
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Screenshots

![minecraft 1 12 2 05 04 2018 12_06_21](https://user-images.githubusercontent.com/38100638/38362642-e08f52e4-38d1-11e8-9861-223347d1615f.png)

**Comment by TheAdventAgain** [comment]
I am experiencing the same issues running the a3 build with Revelations. Also, in my case, no matter how large I make my tanks they always have a capacity of 16000. Dunno if that is related.
