### ISSUE TITLE
Vanilla fences connect to crop sticks

### ISSUE THREAD

**Issue by MatthiasMann** [AgriCraft/AgriCraft#1123]
## Quick description
Vanilla fences (haven't tested any other) connect to crop sticks (both normal and double).
This doesn't look nice.

## Mods and versions used
agricraft-2.12.0-1.12.0-a3
infinitylib-1.12.0
forge-1.12.2-14.23.2.2654

## Your environment
OS: Linux Mint 18.3
Launcher: minecraft.jar
Mod pack: https://minecraft.curseforge.com/projects/modern-skyblock-3-departed/files/2549897

Singleplayer
Survival
Existing world from Modern Skyblock 3.2

**Comment by RlonRyan** [comment]
That's a new one...
