### ISSUE TITLE
mushroom does not grow at dark ineffable glass (EU2)

### ISSUE THREAD

**Issue by xILikepuddingx** [AgriCraft/AgriCraft#1124]
## Quick description
mushroom does not grow at dark ineffable glass (EU2)

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: agricraft-2.12.0-1.12.0-a3
* InfinityLib: infinitylib-1.12.0
* too much mods in the modpack

## Steps to replicate the issue
see video below

## Expectations and explanations
Since this glass brings the light level to 0, the mushrooms should actually grow. But do not do it.

## Your environment

* How are you playing?
  * Operating System: Windows 10 64 bit
  * Launcher: MyFTB Launcher
  * Modpack: Modern Skyblock 3
* What kind of server:
  * [x] Singleplayer
  * [x] Multiplayer
* Game Modes:
  * [x] Survival
  * [x] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Screenshots (or videos)
https://files.ilikepudding.tk/o6xb7ob1rz.mp4

**Comment by RlonRyan** [comment]
See #1079
