### ISSUE TITLE
[1.12.2] [Suggestion] Add support for the Farming Station

### ISSUE THREAD

**Issue by TheLimePixel** [AgriCraft/AgriCraft#1125]
Could you add support for EIO's Farming Station? Unless I'm wrong, it was supported in 1.10, so it should be supported once again.

**Comment by RlonRyan** [comment]
EnderIO finally made it to 1.12. Nice.

**Comment by RlonRyan** [comment]
Now just to wait for them to fix their maven...

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
