### ISSUE TITLE
"Valid Parents" config setting has no effect following previous refactoring

### ISSUE THREAD

**Issue by svj0hn** [AgriCraft/AgriCraft#1126]
## Quick description
The "validParents" config setting is supposed to allow usage of mutation parents (or all plants) as valid parents for stat increasing, depending on its value. This does not seem to be the case, rather they are currently considered invalid parents (tested with validParents = 2, further conclusions drawn from reading the code itself). As far as I can tell by searching this repo, the setting is never even looked at (StatCalculatorBase.java).

## Related issues and searches
Searching found similar issues in the past (such as #428), where it was fixed, but the feature was seemingly forgotten during refactoring (commit dd40bd9) and never reintroduced.

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a3
* InfinityLib: 1.12.0
* (Modern Skyblock 3.3.1)

## Steps to replicate the issue
1. Set "Valid Parents" = 1 or 2 in config (make sure hardcore is off)
2. Plant a mutation child with low stats next to it's mutation parents with high stats (I used Raspberry 5/5/5 next to three Soybean 10/10/10) and crossbreed until the child spreads.

## Expectations and explanations
New seed would be expected to have a minimum of 8's, based on stat algorithm (using average of all valid parents + random stat gain), but has even lower stats than the original plant (in my test, it had 1/1/1, suggesting all my Soybeans were considered invalid parents).

## Your environment
* How are you playing?
  * Operating System: Windows 10
  * Launcher: Twitch
  * Modpack: Modern Skyblock 3 (3.3.1)
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * Existing MSB3 save file

**Comment by RlonRyan** [comment]
I'll assign you, @InfinityRaider, to this one as i'm not quite sure as to how you want this to work.

**Comment by niklas2233** [comment]
still no progress on this?

**Comment by InfinityRaider** [comment]
No, apologies.

Closing since we are moving to 1.16.
