### ISSUE TITLE
[Compatibility Request] Serene Seasons

### ISSUE THREAD

**Issue by ddelaparte** [AgriCraft/AgriCraft#1127]
Requesting some compatibility with the Serene Seasons mod. IE certain crops grow better / not at all during specific seasons. Maybe even mutations allowing crops specific to one seasons to grow well in others. Like summer squash in winter.

**Comment by theCorvid** [comment]
Seconded!

Mod link for posterity: https://minecraft.curseforge.com/projects/serene-seasons

**Comment by Guinaro** [comment]
Thirded.
I would love to be able to configure stuff like accelerated growth in season/subseason
Halted growth in season/subseason
Conversion to weed/withered crop in this season/subseason
Accelerated/Slowed/Halted growth during rain fall/ storm / snow (unless under greenhouse glass).
Higher yield during season/subseason.

**Comment by renadi** [comment]
I third this.
Even just changing growth rate would be nice, but it would be interesting
if there were more interesting ideas too.

**Comment by InfinityRaider** [comment]
For info: this could be tackled from both sides, even making the seasons affect mutations/spreading is possible by registering a new [mutation engine](https://github.com/AgriCraft/AgriCraft/blob/92ee00d338b57c87799a6cd3938d1ed3d1361a98/src/main/java/com/infinityraider/agricraft/impl/v1/AgriMutationEngine.java)

**Comment by WolfieWaffle** [comment]
If I can get Agricraft working in eclipse with TAN loaded as well I will try to see if I can do anything. This mod looks a bit out of my level of competence but I wanted to try and see if I could implement this before I even saw this issue.

If I do anything I'll try to follow the general style of the code etc., and only add what I can understand. Probably will need other people to do more of the complex stuff.

**Comment by LunariusH** [comment]
Any update on this? Has this ever happened? I came here specifically to see if Serene Season compatibility occurred. :)

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.

**Comment by perdakovich** [comment]
https://www.curseforge.com/minecraft/mc-mods/agriseasons
