### ISSUE TITLE
Game and server crash water tank is full and rain

### ISSUE THREAD

**Issue by orblazer** [AgriCraft/AgriCraft#1130]
## Quick description
Game and server crash when water tank is full and is rain

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a3
* InfinityLib: 1.12.0

## Steps to replicate the issue
1. Setup irigation channel
2. Turn on rain
3. Wait water tank is full
4. And now probably crash if rain

## Your environment
* How are you playing?
  * Operating System: Windows 10
  * Launcher: Twitch
  * Modpack: Crop Block
* What kind of server:
  * [ ] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
* https://pastebin.com/kGBQ4PB0

**Comment by RlonRyan** [comment]
Same as #1128
