### ISSUE TITLE
How do i disable weeds in 1.7.10

### ISSUE THREAD

**Issue by Biggest12345** [AgriCraft/AgriCraft#1131]
Hello, i have decided to play agrarian skies 2 (yes old mod pack) because It seemed fun. The only problem is weeds. They are really annoying and I honestly cant bother to deal with them. I tried disabling them in the config but they still appear on my crops. Please help

I dont see the "json" file in the agricraft folder. I don't know much about modding so please simplify your answer as if you were talking to a 10 year old.

**Comment by InfinityRaider** [comment]
In the config file, 1.7.10 does not pull from jsons.
