### ISSUE TITLE
Mystical Agriculture: Can't plant inferium seeds in cropsticks

### ISSUE THREAD

**Issue by xGnoSiSx** [AgriCraft/AgriCraft#1132]
Hi,

I've tweeked configs to get this working but it seems that is not possible at all. Just trying to recreate the modpack feeling of regrowth in 1.12.2

Reported in Mystical Agriculture: [issue](https://github.com/BlakeBr0/MysticalAgriculture/issues/158#issuecomment-383746303)
I'm also reporting this here. If anyone has found a way to make inferium seeds work with cropsticks please advise.

Pack: Modified DireWolf 1.12 curse launcher
agricraft-2.12.0-1.12.0-a4
mysticalagriculture-1.12-1.6.9
mysticalagradditions-1.12-1.2.8 (with/without - doesn't make much difference)

Not sure the reason it happens: wrong seed identifier? Mystical agriculture bug? Agricraft bug? Not supported?

There are videos of 1.10 where that used to work, and of course did so in 1.7.10

**Comment by Cazadorsniper** [comment]
I made them work by creating a new world.

**Comment by flamingram** [comment]
so how did you fx i then because now i need to use clippers as well

**Comment by Cazadorsniper** [comment]
all i did was make a new world and that is it. I was able to plant the mystical agriculture seeds with the cropsticks, haven't messed with the clippers yet though.

**Comment by Shadowmaster09** [comment]
The Problem is the Final Product dropping cause it was named **mysticalagriculture:inferium_essence** but now it is called **mysticalagriculture:crafting** change name and it is working =)

**Comment by SlyJacobTheBeast** [comment]
@Shadowmaster09 thanks man! That worked. Don't forget to change it in all 5 tiers of the seed!

**Comment by xGnoSiSx** [comment]
Will try it after work tonight...

**Comment by PirateToshio** [comment]
@Shadowmaster09 

> The Problem is the Final Product dropping cause it was named mysticalagriculture:inferium_essence but now it is called mysticalagriculture:crafting change name and it is working =)

Can confirm this fixes it, thanks so much :)

**Comment by KingDrider** [comment]
Hiya, Is there anyway to fix this in version 1.6.12 of Mystical Agriculture? We have launched an "All the mods 3" v5.9.8d server and I am unable to plant any tier of crafting seed... Maybe I am missing something but looking through all the server files I could not find the exact code line mentioned above to change it?

**Comment by KingDrider** [comment]
Sorry guys you will have to excuse me I have been stupid I was not making the seeds into the actual plantable inferium seeds

**Comment by darthvader45** [comment]
It's fine, happens to all of us.

**Comment by xGnoSiSx** [comment]
As per replies, and tests this is resolved.

>The Problem is the Final Product dropping cause it was named mysticalagriculture:inferium_essence but >now it is called mysticalagriculture:crafting change name and it is working =)

**Comment by ladamtla** [comment]
Hi,
Anyone having the same problem right now (1.18.2)?
The above method doesn't work only with each one Should I change the json for all the platnts?
