### ISSUE TITLE
"Raking weeds drops seeds" blocks other seeds

### ISSUE THREAD

**Issue by ss1h2a3tw** [AgriCraft/AgriCraft#1133]
## Quick description

`B:"Raking weeds drops seeds"=false` will stop not only weed but any seed from dropping.
Setting `B:"Raking weeds drops seeds"=true` will turn all of the dropping on.

## Mods and versions used

* Minecraft: 1.12.2
* AgriCraft: agricraft-2.12.0-1.12.0-a4
* InfinityLib: infinitylib-1.12.0

## Steps to replicate the issue

1. Using a rake to pickup seeds.

**Comment by darthvader45** [comment]
Rather odd, perhaps separating weed seed config from the other seeds in the code is needed?

**Comment by RlonRyan** [comment]
The two settings are as follows:
1. `Raking weeds drops items`
2. `Raking weeds drops seeds`
