### ISSUE TITLE
[Configuration Request] for Weeds

### ISSUE THREAD

**Issue by Cazadorsniper** [AgriCraft/AgriCraft#1134]
## Quick description
For the next version of Agricraft, can we have a config to disable weeds entirely. 
If there is already a config for that then I don't see it.
Would be much appreciated.

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a4
* InfinityLib: 1.12.0

## Your environment
* How are you playing?
  * Operating System: Win10
  * Launcher: TwitchApp
  * Modpack: Project Ozone 3 
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [ ] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

**Comment by TehNut** [comment]
#1129

**Comment by Cazadorsniper** [comment]
oh, well thanks.
