### ISSUE TITLE
[a4] Seed duping with Inventory Tweaks

### ISSUE THREAD

**Issue by CurePindal** [AgriCraft/AgriCraft#1137]
When using a4 with Inventory Tweaks it happily dupes seeds when placeing them.
1.  take a fancy (identified) seed and plant it
2. planted identified seed is replaced with the same duped one in the tool belt by Inventory Tweaks which pulls them from default/unidentified seeds.
3. voila - endless high-tier seeds

just tested in SP, forge 2681, latest invtweaks

**Comment by darthvader45** [comment]
Might be an Inventory Tweaks problem, have you reported it on their end?  I
say this because if it stops happening when ITweaks is removed, then it is
likely a problem on their end.

Golden rule in Minecraft: Never dig straight down.

**Comment by RlonRyan** [comment]
Is this still an issue?
