### ISSUE TITLE
Disabling vanilla planting (harvestcraft)

### ISSUE THREAD

**Issue by winnetrie83** [AgriCraft/AgriCraft#1138]
Disabling vanilla planting does not disable it for harvestcraft plants.
MC 1.12.2, + latest version of forge, harvestcraft and agricraft.

**Comment by RlonRyan** [comment]
The setting only disables planting of seeds that have been registered as plants in the AgriCraft JSONs it is more than likely that they are simply missing JSON definitions and thus cannot be planted in AgriCraft crops and therefore are not blocked from normal planting as not to make certain plant products un-obtainable.
