### ISSUE TITLE
Server is crashing, what can i do?

### ISSUE THREAD

**Issue by ToastyFishHeads** [AgriCraft/AgriCraft#1139]
I'm hosting a server, and it seems that agricraft is causing it to crash suddenly. Before it crashed, it had no issues with it. 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b150.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.22.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 5/12/18 6:54 AM
Description: Ticking block entity

java.lang.AssertionError: With 16029mb of total fluid, somehow consumed -13mb, which should be impossible!
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.acceptFluid(TileEntityChannel.java:228)
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.pushToComponent(TileEntityChannel.java:338)
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.func_73660_a(TileEntityChannel.java:272)
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityTank.func_73660_a(TileEntityTank.java:57)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.acceptFluid(TileEntityChannel.java:228)
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.pushToComponent(TileEntityChannel.java:338)
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.func_73660_a(TileEntityChannel.java:272)
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityTank.func_73660_a(TileEntityTank.java:57)

-- Block entity being ticked --
Details:
	Name: agricraft:tile.water_tank // com.infinityraider.agricraft.tiles.irrigation.TileEntityTank
	Block type: ID #1132 (tile.agricraft:water_tank // com.infinityraider.agricraft.blocks.irrigation.BlockWaterTank)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (126,69,202), Chunk: (at 14,4,10 in 7,12; contains blocks 112,0,192 to 127,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #1132 (tile.agricraft:water_tank // com.infinityraider.agricraft.blocks.irrigation.BlockWaterTank)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 290 Drop: 0
	Level seed: -2824225730543587630
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (228,64,252), Chunk: (at 4,4,12 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1899168 game time, 334539 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 4986 (now: true), thunder time: 74253 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6543641368 bytes (6240 MB) / 8151629824 bytes (7774 MB) up to 8151629824 bytes (7774 MB)
	JVM Flags: 2 total; -Xms4096M -Xmx8192M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.3.2678 58 mods loaded, 58 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                         | Version                  | Source                                          | Signature                                |
	|:--------- |:-------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                  | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                        | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                        | 8.0.99.99                | forge-1.12.2-14.23.3.2678-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                      | 14.23.3.2678             | forge-1.12.2-14.23.3.2678-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | opencomputers|core         | 1.7.2.67                 | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | actuallyadditions          | 1.12.2-r135              | ActuallyAdditions-1.12.2-r135.jar               | None                                     |
	| UCHIJAAAA | infinitylib                | 1.12.2-1.12.0            | infinitylib-1.12.0.jar                          | None                                     |
	| UCHIJAAAA | agricraft                  | 2.12.0-1.12.0-a4         | agricraft-2.12.0-1.12.0-a4.jar                  | None                                     |
	| UCHIJAAAA | aroma1997core              | 2.0.0.0.b150             | Aroma1997Core-1.12.2-2.0.0.0.b150.jar           | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAA | aromabackup                | 2.1.1.3.b98              | AromaBackup-1.12.2-2.1.1.3.b98.jar              | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAA | aromabackuprecovery        | 2.1.1.3.b98              | AromaBackup-1.12.2-2.1.1.3.b98.jar              | None                                     |
	| UCHIJAAAA | quark                      | r1.4-123                 | Quark-r1.4-123.jar                              | None                                     |
	| UCHIJAAAA | autoreglib                 | 1.3-17                   | AutoRegLib-1.3-17.jar                           | None                                     |
	| UCHIJAAAA | biomesoplenty              | 7.0.1.2384               | BiomesOPlenty-1.12.2-7.0.1.2384-universal.jar   | None                                     |
	| UCHIJAAAA | chisel                     | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                    | None                                     |
	| UCHIJAAAA | chiselsandbits             | 14.16                    | chiselsandbits-14.16.jar                        | None                                     |
	| UCHIJAAAA | codechickenlib             | 3.1.8.341                | CodeChickenLib-1.12.2-3.1.8.341-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux               | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | cofhcore                   | 4.4.1                    | CoFHCore-1.12.2-4.4.1.12-universal.jar          | None                                     |
	| UCHIJAAAA | cofhworld                  | 1.1.1                    | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UCHIJAAAA | endercore                  | 1.12.2-0.5.22            | EnderCore-1.12.2-0.5.22.jar                     | None                                     |
	| UCHIJAAAA | jei                        | 4.9.1.168                | jei_1.12.2-4.9.1.168.jar                        | None                                     |
	| UCHIJAAAA | thermalfoundation          | 2.4.1                    | ThermalFoundation-1.12.2-2.4.1.15-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalexpansion           | 5.4.2                    | ThermalExpansion-1.12.2-5.4.2.27-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | enderio                    | 5.0.24                   | EnderIO-1.12.2-5.0.24.jar                       | None                                     |
	| UCHIJAAAA | enderiointegrationtic      | 5.0.24                   | EnderIO-1.12.2-5.0.24.jar                       | None                                     |
	| UCHIJAAAA | enderiobase                | 5.0.24                   | EnderIO-1.12.2-5.0.24.jar                       | None                                     |
	| UCHIJAAAA | enderioconduits            | 5.0.24                   | EnderIO-1.12.2-5.0.24.jar                       | None                                     |
	| UCHIJAAAA | enderiointegrationforestry | 5.0.24                   | EnderIO-1.12.2-5.0.24.jar                       | None                                     |
	| UCHIJAAAA | enderiointegrationticlate  | 5.0.24                   | EnderIO-1.12.2-5.0.24.jar                       | None                                     |
	| UCHIJAAAA | enderiomachines            | 5.0.24                   | EnderIO-1.12.2-5.0.24.jar                       | None                                     |
	| UCHIJAAAA | enderiopowertools          | 5.0.24                   | EnderIO-1.12.2-5.0.24.jar                       | None                                     |
	| UCHIJAAAA | enderstorage               | 2.4.2.126                | EnderStorage-1.12.2-2.4.2.126-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | extrautils2                | 1.0                      | extrautils2-1.12-1.7.6.jar                      | None                                     |
	| UCHIJAAAA | forgemultipartcbe          | 2.4.1.57                 | ForgeMultipart-1.12.2-2.4.1.57-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | microblockcbe              | 2.4.1.57                 | ForgeMultipart-1.12.2-2.4.1.57-universal.jar    | None                                     |
	| UCHIJAAAA | minecraftmultipartcbe      | 2.4.1.57                 | ForgeMultipart-1.12.2-2.4.1.57-universal.jar    | None                                     |
	| UCHIJAAAA | ichunutil                  | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UCHIJAAAA | gravitygun                 | 7.0.0                    | GravityGun-1.12.2-7.0.1.jar                     | None                                     |
	| UCHIJAAAA | hats                       | 7.0.0                    | Hats-1.12.2-7.0.2.jar                           | None                                     |
	| UCHIJAAAA | harvestcraft               | 1.12.2t                  | Pam's HarvestCraft 1.12.2t.jar                  | None                                     |
	| UCHIJAAAA | theoneprobe                | 1.4.22                   | theoneprobe-1.12-1.4.22.jar                     | None                                     |
	| UCHIJAAAA | immersiveengineering       | 0.12-82                  | ImmersiveEngineering-0.12-82.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | immersivehempcraft         | 1.12-0.0.6.2             | Immersive HempCraft-1.12-0.0.6.2.jar            | None                                     |
	| UCHIJAAAA | inventorytweaks            | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironbackpacks              | 1.12.2-3.0.7-10          | IronBackpacks-1.12.2-3.0.7-10.jar               | None                                     |
	| UCHIJAAAA | ironchest                  | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                 | None                                     |
	| UCHIJAAAA | mcjtylib_ng                | 2.6.7                    | mcjtylib-1.12-2.6.7.jar                         | None                                     |
	| UCHIJAAAA | mekanism                   | 1.12.2-9.4.10.345        | Mekanism-1.12.2-9.4.10.345.jar                  | None                                     |
	| UCHIJAAAA | mekanismgenerators         | 9.4.10                   | MekanismGenerators-1.12.2-9.4.10.345.jar        | None                                     |
	| UCHIJAAAA | mekanismtools              | 9.4.10                   | MekanismTools-1.12.2-9.4.10.345.jar             | None                                     |
	| UCHIJAAAA | opencomputers              | 1.7.2.67                 | OpenComputers-MC1.12.2-1.7.2.67.jar             | None                                     |
	| UCHIJAAAA | portalgun                  | 7.0.2                    | PortalGun-1.12.2-7.0.2.jar                      | None                                     |
	| UCHIJAAAA | rftools                    | 7.33                     | rftools-1.12-7.33.jar                           | None                                     |
	| UCHIJAAAA | simplyjetpacks             | 2.2.4.34                 | SimplyJetpacks2-1.12.2-2.2.4.34.jar             | None                                     |
	| UCHIJAAAA | thermaldynamics            | 2.4.1                    | ThermalDynamics-1.12.2-2.4.1.10-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | twilightforest             | 3.6.345                  | twilightforest-1.12.2-3.6.345-universal.jar     | None                                     |
	| UCHIJAAAA | wrcbe                      | 2.3.0                    | WR-CBE-1.12.2-2.3.0.27-universal.jar            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b150.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (Quark-r1.4-123.jar)
  vazkii.quark.base.asm.ClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.22.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	Ender IO: No known problems detected.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Profiler Position: N/A (disabled)
	Player Count: 0 / 15; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by darthvader45** [comment]
That's alpha 4, way out-of-date.  Current is around alpha 21 or so.

Golden rule in Minecraft: Never dig straight down.

**Comment by ToastyFishHeads** [comment]
@darthvader45 forgot to mention I'm using 1.12.2, and alpha 4 is the most recent version for it

**Comment by darthvader45** [comment]
Oh, In that case that's a pretty major bug @InfinityRaider This might need
to be looked at, channels should never draw negative water.

Golden rule in Minecraft: Never dig straight down.

**Comment by SilentAssassin01** [comment]
Is it raining in your world? Looks similar if not the same to #1128

**Comment by kotoroshinoto** [comment]
I was having this error as well. had to pull the mod

**Comment by Syndaryl** [comment]
I am having the same crash in 1.12.2, agricraft-2.12.0-1.12.0-a4, infinitylib-1.12.0 with Forge 14.23.3.2655

**I have a set of 10 tanks double-stacked on top of each other** and a sprinkler system that was *shut off* and therefore not drawing from them. The bottom tanks were nearing capacity when it started raining. There was a brief delay (I suspect as it filled the bottom rank of tanks), and then it crashed. Now when I log in, I have a few seconds and then it crashes again with the following stacktrace:

`[18:04:49] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.AssertionError: With 16031mb of total fluid, somehow consumed -15mb, which should be impossible!
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.acceptFluid(TileEntityChannel.java:228) ~[TileEntityChannel.class:?]
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.pushToComponent(TileEntityChannel.java:338) ~[TileEntityChannel.class:?]
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.func_73660_a(TileEntityChannel.java:272) ~[TileEntityChannel.class:?]
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityTank.func_73660_a(TileEntityTank.java:57) ~[TileEntityTank.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1832) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
	... 4 more`


I have attached my crash log and my game log

[crash-2018-06-19_18.04.49-server.txt](https://github.com/AgriCraft/AgriCraft/files/2119136/crash-2018-06-19_18.04.49-server.txt)

[latest.log](https://github.com/AgriCraft/AgriCraft/files/2119137/latest.log)

**Comment by RlonRyan** [comment]
Same as #1128
