### ISSUE TITLE
Peripheral-related server crash

### ISSUE THREAD

**Issue by evhub** [AgriCraft/AgriCraft#1141]
## Quick description
Server crashes right after startup. Seems related to agricraft's computercraft peripherals.

## Links to crash logs, stack traces, etc
https://gist.github.com/evhub/0010a7e5efd31e1552f9ed912572842f

**Comment by RlonRyan** [comment]
Missing Method:

searge | name | side | desc
-- | -- | -- | --
func_175624_G | getWorldType | 2

If I am not mistaken, the mcp mapping above says that the method is on both the client and server side. Thus I wonder what is going on here, as this shouldn't be a @SideOnly thing...

**Comment by RlonRyan** [comment]
Oh, nevermind. I managed to finally get the sources jar attached in netbeans and now I see that it is `@SideOnly(Side.CLIENT)`...
