### ISSUE TITLE
Question For Making Json Files

### ISSUE THREAD

**Issue by Cazadorsniper** [AgriCraft/AgriCraft#1142]
Is it possible to use 1 seed in many Jsons that have different products? Trying to make Jsons for Karat Garden but it seems 1 seed can't be used in multiple Jsons.

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a4
* InfinityLib: 1.12.0
* Karat Garden: 0.1.4-[1.12.2]

**Comment by RlonRyan** [comment]
You just have to add multiple products to the plant definition, as one plant can drop any number of products.
