### ISSUE TITLE
Overtake setting not respected

### ISSUE THREAD

**Issue by mpevner** [AgriCraft/AgriCraft#1143]
I've noticed in the 1.7.10 version that setting B:"Weeds can overtake plants" to false has no effect. If my understanding of the code and testing is correct, the fix for this is to change if(this.hasCrop()) to if(crop.hasCrop()). If my understanding is correct, this also currently means the Strength value of a crop is not used for determining weed overtake chances.

https://github.com/AgriCraft/AgriCraft/blob/d1f5d1f7bf1424b4f8b302118cc46bf79755ebd6/src/main/java/com/InfinityRaider/AgriCraft/tileentity/TileEntityCrop.java#L248

**Comment by RlonRyan** [comment]
The setting needs to be changed to a general overtake setting or removed completely now that all plants are capable of overtaking other plants.

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
