### ISSUE TITLE
[1.12.2] [Compatability] Add support for Botania's Horn of the Wild

### ISSUE THREAD

**Issue by kriNon** [AgriCraft/AgriCraft#1145]
Was hoping that you'd look into supporting Botania's Horn of the Wild like you had in 1.7.10.

As far as I am aware it's a matter of implementing IHornHarvestable from Botania's API.

**Comment by MasterEnderman** [comment]
This feature was added in the last update of [botania tweaks](https://minecraft.curseforge.com/projects/botania-tweaks)

**Comment by kriNon** [comment]
yeah, was going to close this issue, but since this functionality should realistically be done by agricraft I decided to leave up the issue. Quat1024 says in his comments that he'll remove the patch to agricraft once it's implemented within agricraft.

**Comment by RlonRyan** [comment]
Fixed in fa9293f
