### ISSUE TITLE
Crash when loading save. 

### ISSUE THREAD

**Issue by Tiviacz1337** [AgriCraft/AgriCraft#1147]
When my world is coming to load up, Minecraft crashes

---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.8.10.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.177.jar)
  CTMCorePlugin (CTM-MC1.12-0.3.0.15.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.30.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 6/17/18 11:14 AM
Description: Ticking block entity

java.lang.AssertionError: With 16026mb of total fluid, somehow consumed -10mb, which should be impossible!
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.acceptFluid(TileEntityChannel.java:228)
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.pushToComponent(TileEntityChannel.java:338)
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.func_73660_a(TileEntityChannel.java:272)
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityTank.func_73660_a(TileEntityTank.java:57)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.acceptFluid(TileEntityChannel.java:228)
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.pushToComponent(TileEntityChannel.java:338)
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.func_73660_a(TileEntityChannel.java:272)
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityTank.func_73660_a(TileEntityTank.java:57)

-- Block entity being ticked --
Details:
	Name: agricraft:tile.water_tank // com.infinityraider.agricraft.tiles.irrigation.TileEntityTank
	Block type: ID #2837 (tile.agricraft:water_tank // com.infinityraider.agricraft.blocks.irrigation.BlockWaterTank)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-154,69,-192), Chunk: (at 6,4,0 in -10,-12; contains blocks -160,0,-192 to -145,255,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #2837 (tile.agricraft:water_tank // com.infinityraider.agricraft.blocks.irrigation.BlockWaterTank)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: TvPack
	All players: 1 total; [GCEntityPlayerMP['InTivi'/11540, l='TvPack', x=-169.69, y=70.00, z=-243.47]]
	Chunk stats: ServerChunkCache: 921 Drop: 0
	Level seed: 6157760312185058528
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (244,64,224), Chunk: (at 4,4,0 in 15,14; contains blocks 240,0,224 to 255,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1788499 game time, 603527 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 21694 (now: true), thunder time: 39609 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1335608032 bytes (1273 MB) / 4563402752 bytes (4352 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -XX:ParallelGCThreads=4 -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=500 -XX:G1HeapRegionSize=16M -XX:+OptimizeStringConcat
	IntCache: cache: 0, tcache: 0, allocated: 5, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 Optifine OptiFine_1.12.2_HD_U_D3 103 mods loaded, 103 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                | Version                  | Source                                           | Signature                                |
	|:--------- |:--------------------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft                         | 1.12.2                   | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | mcp                               | 9.42                     | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | FML                               | 8.0.99.99                | forge-1.12.2-14.23.4.2705.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                             | 14.23.4.2705             | forge-1.12.2-14.23.4.2705.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | ivtoolkit                         | 1.3.3-1.12               | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | micdoodlecore                     |                          | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | foamfixcore                       | 7.7.4                    | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | jei                               | 4.9.2.196                | jei_1.12.2-4.9.2.196.jar                         | None                                     |
	| UCHIJAAAA | abyssalcraft                      | 1.9.4.9                  | AbyssalCraft-1.12.2-1.9.4.9.jar                  | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCHIJAAAA | actuallyadditions                 | 1.12.2-r135              | ActuallyAdditions-1.12.2-r135.jar                | None                                     |
	| UCHIJAAAA | infinitylib                       | 1.12.2-1.12.0            | infinitylib-1.12.0.jar                           | None                                     |
	| UCHIJAAAA | agricraft                         | 2.12.0-1.12.0-a4         | agricraft-2.12.0-1.12.0-a4.jar                   | None                                     |
	| UCHIJAAAA | applecore                         | 3.1.1                    | AppleCore-mc1.12.2-3.1.1.jar                     | None                                     |
	| UCHIJAAAA | appleskin                         | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                       | None                                     |
	| UCHIJAAAA | appliedenergistics2               | rv5-stable-11            | appliedenergistics2-rv5-stable-11.jar            | None                                     |
	| UCHIJAAAA | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                           | None                                     |
	| UCHIJAAAA | astralsorcery                     | 1.8.10                   | astralsorcery-1.12.2-1.8.10.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCHIJAAAA | betterfoliage                     | 2.1.10                   | BetterFoliage-MC1.12-2.1.10.jar                  | None                                     |
	| UCHIJAAAA | bibliocraft                       | 2.4.4                    | BiblioCraft[v2.4.4][MC1.12.2].jar                | None                                     |
	| UCHIJAAAA | biomesoplenty                     | 7.0.1.2391               | BiomesOPlenty-1.12.2-7.0.1.2391-universal.jar    | None                                     |
	| UCHIJAAAA | bookshelf                         | 2.3.549                  | Bookshelf-1.12.2-2.3.549.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | thaumcraft                        | 6.1.BETA16               | Thaumcraft-1.12.2-6.1.BETA16.jar                 | None                                     |
	| UCHIJAAAA | botania                           | r1.10-354                | Botania+r1.10-354.jar                            | None                                     |
	| UCHIJAAAA | codechickenlib                    | 3.1.9.344                | CodeChickenLib-1.12.2-3.1.9.344-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux                      | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | brandonscore                      | 2.4.2                    | BrandonsCore-1.12-2.4.2.157-universal.jar        | None                                     |
	| UCHIJAAAA | buildcraftlib                     | 7.99.17                  | buildcraft-7.99.17.jar                           | None                                     |
	| UCHIJAAAA | buildcraftcore                    | 7.99.17                  | buildcraft-7.99.17.jar                           | None                                     |
	| UCHIJAAAA | buildcraftbuilders                | 7.99.17                  | buildcraft-7.99.17.jar                           | None                                     |
	| UCHIJAAAA | buildcraftenergy                  | 7.99.17                  | buildcraft-7.99.17.jar                           | None                                     |
	| UCHIJAAAA | buildcraftfactory                 | 7.99.17                  | buildcraft-7.99.17.jar                           | None                                     |
	| UCHIJAAAA | buildcraftrobotics                | 7.99.17                  | buildcraft-7.99.17.jar                           | None                                     |
	| UCHIJAAAA | buildcrafttransport               | 7.99.17                  | buildcraft-7.99.17.jar                           | None                                     |
	| UCHIJAAAA | buildcraftsilicon                 | 7.99.17                  | buildcraft-7.99.17.jar                           | None                                     |
	| UCHIJAAAA | ctm                               | MC1.12-0.3.0.15          | CTM-MC1.12-0.3.0.15.jar                          | None                                     |
	| UCHIJAAAA | chisel                            | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                     | None                                     |
	| UCHIJAAAA | cb                                | 1.0                      | CloudBoots-1.12.2-1.3.0.jar                      | None                                     |
	| UCHIJAAAA | cofhcore                          | 4.5.2                    | CoFHCore-1.12.2-4.5.2.19-universal.jar           | None                                     |
	| UCHIJAAAA | cofhworld                         | 1.2.0                    | CoFHWorld-1.12.2-1.2.0.5-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | craftingtweaks                    | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                  | None                                     |
	| UCHIJAAAA | cucumber                          | 1.1.0                    | cucumber-1.12-1.1.0.jar                          | None                                     |
	| UCHIJAAAA | customspawner                     | 3.11.4                   | CustomMobSpawner-3.11.4.jar                      | None                                     |
	| UCHIJAAAA | cxlibrary                         | 1.6.1                    | cxlibrary-1.12.1-1.6.1.jar                       | None                                     |
	| UCHIJAAAA | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| UCHIJAAAA | darkutils                         | 1.8.210                  | DarkUtils-1.12.2-1.8.210.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | thermalfoundation                 | 2.5.0                    | ThermalFoundation-1.12.2-2.5.0.19-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | draconicevolution                 | 2.3.11                   | Draconic-Evolution-1.12-2.3.11.290-universal.jar | None                                     |
	| UCHIJAAAA | mocreatures                       | 12.0.4                   | DrZharks MoCreatures Mod-12.0.4.jar              | None                                     |
	| UCHIJAAAA | endercore                         | 1.12.2-0.5.30            | EnderCore-1.12.2-0.5.30.jar                      | None                                     |
	| UCHIJAAAA | thermalexpansion                  | 5.5.0                    | ThermalExpansion-1.12.2-5.5.0.29-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | enderio                           | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                        | None                                     |
	| UCHIJAAAA | enderiointegrationtic             | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                        | None                                     |
	| UCHIJAAAA | enderiobase                       | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                        | None                                     |
	| UCHIJAAAA | enderioconduits                   | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                        | None                                     |
	| UCHIJAAAA | enderioconduitsappliedenergistics | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                        | None                                     |
	| UCHIJAAAA | enderioconduitsopencomputers      | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                        | None                                     |
	| UCHIJAAAA | enderioconduitsrefinedstorage     | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                        | None                                     |
	| UCHIJAAAA | ic2                               | 2.8.83-ex112             | industrialcraft-2-2.8.83-ex112.jar               | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | mantle                            | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                         | None                                     |
	| UCHIJAAAA | natura                            | 1.12.2-4.3.2.49          | natura-1.12.2-4.3.2.49.jar                       | None                                     |
	| UCHIJAAAA | forestry                          | 5.8.0.295                | forestry_1.12.2-5.8.0.295.jar                    | None                                     |
	| UCHIJAAAA | enderiointegrationforestry        | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                        | None                                     |
	| UCHIJAAAA | tconstruct                        | 1.12.2-2.10.1.84         | TConstruct-1.12.2-2.10.1.84.jar                  | None                                     |
	| UCHIJAAAA | enderiointegrationticlate         | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                        | None                                     |
	| UCHIJAAAA | enderiomachines                   | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                        | None                                     |
	| UCHIJAAAA | enderiopowertools                 | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                        | None                                     |
	| UCHIJAAAA | extrautils2                       | 1.0                      | extrautils2-1.12-1.7.6.jar                       | None                                     |
	| UCHIJAAAA | foamfix                           | 0.9.9.1-1.12.2           | foamfix-0.9.9.1-1.12.2-anarchy.jar               | None                                     |
	| UCHIJAAAA | cfm                               | 4.2.0                    | furniture-4.2.0-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | galacticraftcore                  | 4.0.1.177                | GalacticraftCore-1.12.2-4.0.1.177.jar            | None                                     |
	| UCHIJAAAA | galacticraftplanets               | 4.0.1.177                | Galacticraft-Planets-1.12.2-4.0.1.177.jar        | None                                     |
	| UCHIJAAAA | gravestone                        | 1.10.1                   | gravestone-1.10.1.jar                            | None                                     |
	| UCHIJAAAA | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironbackpacks                     | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                | None                                     |
	| UCHIJAAAA | ironchest                         | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                  | None                                     |
	| UCHIJAAAA | jeibees                           | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                     | None                                     |
	| UCHIJAAAA | journeymap                        | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                      | None                                     |
	| UCHIJAAAA | jeresources                       | 0.8.7.41                 | JustEnoughResources-1.12.2-0.8.7.41.jar          | None                                     |
	| UCHIJAAAA | lootbags                          | 2.5.6                    | LootBags-1.12.2-2.5.6.jar                        | None                                     |
	| UCHIJAAAA | magicbees                         | 1.0                      | MagicBees-1.12.2-3.1.10.jar                      | None                                     |
	| UCHIJAAAA | multipagechest                    | 1.9.1                    | MultiPageChest-1.12-1.9.1.jar                    | None                                     |
	| UCHIJAAAA | mysticalagriculture               | 1.6.10                   | mysticalagriculture-1.12-1.6.10.jar              | None                                     |
	| UCHIJAAAA | mysticalagradditions              | 1.2.8                    | mysticalagradditions-1.12-1.2.8.jar              | None                                     |
	| UCHIJAAAA | naturescompass                    | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                  | None                                     |
	| UCHIJAAAA | nex                               | 2.1.14.15                | NetherEx-1.12-2.1.14.15.jar                      | None                                     |
	| UCHIJAAAA | neid                              | 1.5.4.2                  | NotEnoughIDs-1.5.4.2.jar                         | None                                     |
	| UCHIJAAAA | harvestcraft                      | 1.12.2u                  | Pam's+HarvestCraft+1.12.2u.jar                   | None                                     |
	| UCHIJAAAA | twilightforest                    | 3.7.424                  | twilightforest-1.12.2-3.7.424-universal.jar      | None                                     |
	| UCHIJAAAA | plustic                           | 6.5.0.0                  | PlusTiC-Mod-1.12.2.jar                           | None                                     |
	| UCHIJAAAA | reccomplex                        | 1.4.7                    | RecurrentComplex-1.4.7.jar                       | None                                     |
	| UCHIJAAAA | roots                             | 0.104                    | roots-2-0.104.jar                                | None                                     |
	| UCHIJAAAA | rustic                            | 1.0.5                    | rustic-1.0.5.jar                                 | None                                     |
	| UCHIJAAAA | simplyenchanting                  | 1.0.3                    | SimplyEnchanting-1.12-1.0.3.jar                  | None                                     |
	| UCHIJAAAA | thermaldynamics                   | 2.5.1                    | ThermalDynamics-1.12.2-2.5.1.14-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | simplyjetpacks                    | 2.2.7.45                 | SimplyJetpacks2-1.12.2-2.2.7.45.jar              | None                                     |
	| UCHIJAAAA | thebetweenlands                   | 3.3.8                    | TheBetweenlands-3.3.8-universal.jar              | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCHIJAAAA | thermalcultivation                | 0.3.0                    | ThermalCultivation-1.12.2-0.3.0.7-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | torohealthmod                     | 1.12.2-11                | torohealth-1.12.2-11.jar                         | None                                     |
	| UCHIJAAAA | wanionlib                         | 1.12.2-1.5               | WanionLib-1.12.2-1.5.jar                         | None                                     |
	| UCHIJAAAA | waystones                         | 4.0.43                   | Waystones_1.12.2-4.0.43.jar                      | None                                     |
	| UCHIJAAAA | xpholder                          | 1.0.1                    | XP-Holder-Mod-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | immersiveengineering              | 0.12-82                  | ImmersiveEngineering-0.12-82.jar                 | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | unidict                           | 1.12.2-2.5c              | UniDict-1.12.2-2.5c.jar                          | None                                     |

	Loaded coremods (and transformers): 
AstralCore (astralsorcery-1.12.2-1.8.10.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.177.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
CTMCorePlugin (CTM-MC1.12-0.3.0.15.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
Plugin (NotEnoughIDs-1.5.4.2.jar)
  ru.fewizz.neid.asm.Transformer
EnderCorePlugin (EnderCore-1.12.2-0.5.30.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['InTivi'/11540, l='TvPack', x=-169.69, y=70.00, z=-243.47]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_D3
	OptiFine Build: 20180515-125031
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 398.11
	OpenGlRenderer: GeForce GTX 750/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by darthvader45** [comment]
Please use [](pastebin.com) for crash reports.  Also, this issue seems surprisingly similar to #1128, mainly if it was raining before the crash.

**Comment by RlonRyan** [comment]
Same as #1128
