### ISSUE TITLE
Ticking block entity crash

### ISSUE THREAD

**Issue by pyure** [AgriCraft/AgriCraft#1149]
## Quick description
Game crashes to desktop with ticking block entity error.

I'm currently just testing the mod.  The I have several water tanks joined together with water flowing over.  They're being extracted from by a single Inductive Logistics extraction pipe.

I also have a Thermal Dynamics fluiduct with "Steam" in it connected to a seperate water tank (I was simply curious about various possibly-weird mechanics)

## Mods and versions used
Mod pack with 100 mods.

## Steps to replicate the issue
Uncertain.  Probably related to water tanks in flowing-water-fills-tanks mode = true.

## Your environment
Forge: 2705

## Links to crash logs, stack traces, etc
https://pastebin.com/ktBuRu5b

Thanks kindly gentlemen.

**Comment by pyure** [comment]
Probably a duplicate of https://github.com/AgriCraft/AgriCraft/issues/1128

**Comment by RlonRyan** [comment]
Same as #1128
