### ISSUE TITLE
[1.12.2] Crash when ActuallyAditions farmer harvests a crop

### ISSUE THREAD

**Issue by karelmikie3** [AgriCraft/AgriCraft#1150]
## Quick description
Minecraft crashes when a farmer from Actuallyaditions tries to harvest an Agricraft crop.

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a4
* InfinityLib: 1.12.0
* ActuallyAdditions: 1.12.2-r136-hotfix5
* Forge: 14.23.4.2705

## Steps to replicate the issue
1. set up a farmer & power it
2. plant some crops using agricraft crop sticks and let them grow fully
3. minecraft crashes as the farmer tries to harvest the block.

## Expectations and explanations
Expectations: No crash.  :P
Explanation: The crash is most likely due to the fact that ActuallyAdditions updated their API from r135->r136 making the old API incompatible. Fixing this would require AgriCraft to update their implementation of the API.

## Your environment
* How are you playing?
  * Operating System: Windows 10
  * Launcher: multimc
  * Modpack: own custom
* What kind of server:
  * [X] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
[crash report](https://paste.ee/p/XcybW)

**Comment by RlonRyan** [comment]
Probably fixed by #1155.
