### ISSUE TITLE
[1.12.2] Cross-crops are unusable

### ISSUE THREAD

**Issue by Austin5003** [AgriCraft/AgriCraft#1151]
Right clicking with any seed or item on a cross-crop will make it revert to a regular crop, making stat progression impossible

**Comment by darthvader45** [comment]
You can't, you plant the seeds on crops adjacent to a cross crop, and they
spread to the cross-crop.  Therefore, this is not a bug and works as
intended.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Golden rule in Minecraft: Never dig straight down.

**Comment by Austin5003** [comment]
Nevermind, I was just being a dumbass and mishearing information

**Comment by darthvader45** [comment]
It's all right, everyone has that moment (except a certain unnamed someone
in the WH).

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Golden rule in Minecraft: Never dig straight down.
