### ISSUE TITLE
(Minor) Fences visually connect to crops

### ISSUE THREAD

**Issue by Crowfooted** [AgriCraft/AgriCraft#1153]
Simple and minor - vanilla fences (and other fences) connect visually to neighbouring Agricraft crops.

**Comment by darthvader45** [comment]
Seems like a simple code change to prevent this from happening.  Thanks for
the report.

Golden rule in Minecraft: Never dig straight down.

**Comment by darthvader45** [comment]
I'm sure they'll fix this quickly.

Golden rule in Minecraft: Never dig straight down.

**Comment by opl-** [comment]
Duplicate of #1123
