### ISSUE TITLE
Water tank causing client and server crashes

### ISSUE THREAD

**Issue by theCorvid** [AgriCraft/AgriCraft#1156]
Serverside crash report: https://pastebin.com/d5VtSVqN
Clientside crash report: https://pastebin.com/6eT0WP8v

Odd behaviour on these crashes, in case it's helpful: my client crashed first, but the error did not initially crash the server and other players on the server (who were playing close nearby) did not crash either. A few minutes later, a player got the same crash and the server also crashed.

The water tanks on my base were the only ones on the server and they had been there for a long time doing nothing before this happened. My base is in a desert biome, so they did not fill with rain and I had intended to fill them using Aqueous Accumulators later but had not yet. I'm not sure how fluid could have got into them.

**Comment by theCorvid** [comment]
#1128

**Comment by RlonRyan** [comment]
Same as #1128
