### ISSUE TITLE
Only a short compile Question out of the Box ;)

### ISSUE THREAD

**Issue by cyberpunkbln** [AgriCraft/AgriCraft#1157]
Hello,

i have compiled the newest dev-build here with the Tank fix and i have a shorg question that google cannot answer;).

How can i say Git on windows that it resolve the symbolic links in Agricraft/Lib/* automaticly at the cloning from the root Project Agricraft and then automatic clone the tree branch?

git clone https://github.com/AgriCraft/AgriCraft.git

and then put automaticly the other repos in the ../lib with the correct tree-branch

https://github.com/AgriCraft/AgriCore/tree/3321cc14a5c734eeb36e45be18eaef60351b18c6
https://github.com/AgriCraft/AgriPlants/tree/db0767daf14514c30b4df345e028d7c9982ece4c
https://github.com/InfinityRaider/InfinityLib/tree/9d7f97ab7693e7b6a004530b9a5a53f7c4cd806d

when i use the tree as an branch with " -b " it don't functioned

Now i have download the tree-branch as a zip and manually copy in the Agricraft/Lib and all problems in the compile-process was solved.

Thx for the out of the box question, agricraft is the first minecraft-mod-source that i compile with that tree-symbolic-links.

**Comment by cyberpunkbln** [comment]
I have found a one line solution;)

`git clone https://github.com/AgriCraft/AgriCraft.git --recursive`

Now i can compile with the right submodules and specific trees;).

**Comment by darthvader45** [comment]
Good to see you found a solution.  If something else happens, feel free to reopen this for more help.

**Comment by cyberpunkbln** [comment]
Hello,

thx, that will i do;). At the moment i have a compiled AgriCraft where i can found at the moment no bugs (im so happy that the Tanl bug is fixed:). I found this state of code can be updated on curseforge, that other peoples that don't have the possibility to compile itself became a fresher binary distribution.

**Comment by darthvader45** [comment]
Sounds good.  Once this mod is fully functional, I'll have a medieval agricultural system set up.

**Comment by cyberpunkbln** [comment]
Sounds really nice. I have made my own modpack with finite water and hunger overhaul and really need Agricraft for collecting water and gain more food;). A medieval agri system was cool to use staging or questing mods with timeages;).
