### ISSUE TITLE
Crash with overfilled wooden tanks

### ISSUE THREAD

**Issue by Ludeb** [AgriCraft/AgriCraft#1158]
## Quick description
I had a crash using the wooden tanks and filling them with flowing water above

## Related issues and searches
crash
minecraft 1.12

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0
* InfinityLib: 1.12.0
*Modpack Direwolf20 (version 1.10.0)

## Steps to replicate the issue

1. Put a wooden tank
2. Put an irrigation channel on a side of the tank
3. Put a sprinkler under the irrigation channel
4. Filled the tank using flowing water over the tank
5. The tank overfilled itself (16100mb/16000mb) and the game/the server crashed

## Expectations and explanations
I think that the tank shouldn't have overfilled itself.
The phrase "With 16025mb of total fluid, somehow consumed -9mb, which should be impossible!" in the crash report make me think that the overflow is not detected so doesn't make crash the game but the sprinkler is lowering the water level in the overfilled tank and at that moment the exception is catched

## Your environment

* How are you playing?
  * Operating System: Windows
  * Launcher: Twitch application
  * Modpack: Direwolf20 (version 1.11.0)
* What kind of server:
  * [X] Singleplayer
  * [X] Multiplayer
       *Crashed on server and when tested in solo crashed too
* Game Modes:
  * [X] Survival
  * [X] Creative
        *Crashed in survival on server and crashed when tried to make the same steps in creative on 
          singleplayer
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
Link to the server crash report: https://pastebin.com/T32LLHSm
Link to the solo crash report: https://pastebin.com/jcncBVxB

## Screenshots (or videos)
Couldn't do any, sorry

**Comment by TehNut** [comment]
#1128

**Comment by RlonRyan** [comment]
Same as #1128
