### ISSUE TITLE
Maker says It is fixed but cant find the new version anywhere

### ISSUE THREAD

**Issue by EdTheDog** [AgriCraft/AgriCraft#1160]
Ok... One of the makers (or helpers) of this mod just said a bug I posted was fixed in #1152 but I am using the newest version of it on curseforge and can't find a newer version anywhere else. If I need to download it from git hub THEN WHERE AND HOW.

**Comment by TehNut** [comment]
You literally waited an hour. This is an issue tracker, not a messaging service. You cannot expect instant replies to your questions.

**Comment by TehNut** [comment]
To answer your question, the fix is not available yet.

**Comment by EdTheDog** [comment]
Um ok then. Just he was just on seconds after asking what to do and it seemed like he had an answer so I expected him to reply. Sorry.

**Comment by EdTheDog** [comment]
And Thank you for the info
