### ISSUE TITLE
Agricraft not being harvested by machines

### ISSUE THREAD

**Issue by tyggna** [AgriCraft/AgriCraft#1163]
This is a fresh save, server runs forge-1.12.2-14.23.4.2705 and minecraft 1.12.2
Agricraft is version: 2-12.0-1.12.0-a4

Specific machine I'm testing on is the Plant Gatherer from Industrial Foregoing (remake of Minefactory Reloaded) version 1.12.2-1.10.2-178

Expected behavior is that the gatherer automatically harvests within about 10 ticks when plant is mature.

**Comment by darthvader45** [comment]
a5 is out, should that fix it?

**Comment by tyggna** [comment]
Check out the mod named IntegrationForegoing, it provides this functionality.
