### ISSUE TITLE
Crop Sticks and Seeds not working

### ISSUE THREAD

**Issue by Rako100** [AgriCraft/AgriCraft#1164]
SUMMARY:
I am making a modpack and added agricraft and when trying to place crop sticks they can't be placed. I've tried plaicing them on farm land and sand but is not working. I created a new profile with only agricraft but I got the same result.
And same for the seeds I analyze the seeds and I cannot plant them. Game does not crash or anything else.

VERSION:
Agricraft 2.12.0-1.12.0-a4

How are you playing?
Operating System: Windows 10 64 bit
Launcher: Twitch Launcher
Modpack: Own Modpack

What kind of server:
[ X] Singleplayer
  Multiplayer
Game Modes:
[X ] Survival
  Creative
Save File:
[X]Brand new save
[ ] Only an existing save

**Comment by darthvader45** [comment]
I think there's a pull request made that fixes your issue.  The only thing
is, the new version isn't publicly available on CurseForge yet.

Golden rule in Minecraft: Never dig straight down.

**Comment by Rako100** [comment]
Any idea when that version is gonna be out?

**Comment by RlonRyan** [comment]
Is this still an issue?

**Comment by Rako100** [comment]
OK after testing with the newest version it all works thank you.
