### ISSUE TITLE
Modded Agricraft Resource seeds not appearing

### ISSUE THREAD

**Issue by Jedddie** [AgriCraft/AgriCraft#1168]
## Quick description
Modded resource seeds (jaslumine, petinia, cuprosia, etc) not being added

## Related issues and searches
1 similar issue with Agricraft not registering mystical agricultre

## Mods and versions used
* Minecraft: 1.12.2 forge 14.23.4.2707
* AgriCraft: 2.12.0 a5
* InfinityLib: 1.12.0
* COFH core: 4.5.2.19
* Geolosys: 1.9.4
* Thermal Foundation: 2.5.0.19
(More mods, but these are the relevant ones, and issue still occurs with just these)

## Expectations and explanations
Expected cuprosia seeds etc, none found in JEI or the morphs book

## Your environment

* How are you playing?
  * Operating System: Windows 10 Home 1803
  * Launcher: Vanilla Launcher
  * Modpack: personal pack
* What kind of server:
  * [ ] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Screenshots (or videos)
![2018-07-14_18 39 09](https://user-images.githubusercontent.com/34596339/42721802-51880be6-8795-11e8-9ab5-44309da80d61.png)

**Comment by RlonRyan** [comment]
I see the emerylis, redstondendron, and lapis seeds...

**Comment by RlonRyan** [comment]
Oh that's why. The cuprosa plant simply doesn't exist atm.
