### ISSUE TITLE
Client crash - ALREADY CONSTRUCTING VERTICES item.item.agricraft:agri_seed

### ISSUE THREAD

**Issue by ProsperCraft** [AgriCraft/AgriCraft#1170]
Client crashing when playing on a multiplayer server, then again in single player, reinstalling the pack fixed it.

## Mods and versions used

* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a5 
* InfinityLib:1.12.2-1.12.0     
* https://minecraft.curseforge.com/projects/ancient-towncraft

## Your environment

* How are you playing?
  * Operating System:
  * Launcher:
  * Modpack: https://minecraft.curseforge.com/projects/ancient-towncraft

* What kind of server:
  * [ ] Singleplayer
  * [X ] Multiplayer
* Game Modes:
  * [ X] Survival
  * [ ] Creative

## Links to crash logs, stack traces, etc
https://gist.github.com/ProsperCraft/a37f323fce0ce0dfcfe921d4bba4aaeb

**Comment by RlonRyan** [comment]
After much thinking, I almost wonder if this is perhaps a threading issue... Which would explain why it doesn't show up often... I'll have to go through and thread the rendering code in infinitylib, and see if that helps.

**Comment by InfinityRaider** [comment]
That's what I thought at the time as well, so I made it so every thread has its own [Tessellator instance](https://github.com/InfinityRaider/InfinityLib/blob/master/src/main/java/com/infinityraider/infinitylib/render/tessellation/TessellatorBakedQuad.java#L38)...

**Comment by RlonRyan** [comment]
hmmm...

**Comment by ParadoxBomb** [comment]
Similar issue but different description at the header of the crashlog:

•Minecraft: 1.12.2
•AgriCraft: 2.12.0-1.12.0-a6 
•InfinityLib:1.12.2-1.12.0

OS: Windows 10 64-bit
Launcher: Technic
Modpack: Custom, see crashlog for loaded .jars

Server: Survival Multiplayer

Crashlog:
VanillaFix was used to capture the crash
https://paste.dimdev.org/ikoyivodux.mccrash

**Comment by RlonRyan** [comment]
Wait... @ParadoxBomb... that's a beta version of jei...

**Comment by ParadoxBomb** [comment]
Is that a bad thing?

**Comment by RlonRyan** [comment]
What I don't get is why the method calls in the stack trace seem to be duplicated...

```
at com.infinityraider.infinitylib.render.tessellation.TessellatorBakedQuad.startDrawing(TessellatorBakedQuad.java:104)
at com.infinityraider.infinitylib.render.tessellation.TessellatorBakedQuad.onStartDrawingQuadsCall(TessellatorBakedQuad.java:92)
at com.infinityraider.infinitylib.render.tessellation.TessellatorAbstractBase.startDrawingQuads(TessellatorAbstractBase.java:90)
at com.infinityraider.infinitylib.render.item.BakedInfItemSubModel.getQuads(BakedInfItemSubModel.java:77)
at com.infinityraider.infinitylib.render.item.BakedInfItemSubModel.getQuads(BakedInfItemSubModel.java:30)
at net.minecraft.client.renderer.RenderItem.renderModel(RenderItem.java:122)
at net.minecraft.client.renderer.RenderItem.renderModel(RenderItem.java:106)
at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:62)
```

**Comment by RlonRyan** [comment]
And the line numbers in the stack trace seem incorrect too, as `BakedInfItemSubModel.java:30` would reference [this line](https://github.com/InfinityRaider/InfinityLib/blob/9d7f97ab7693e7b6a004530b9a5a53f7c4cd806d/src/main/java/com/infinityraider/infinitylib/render/item/BakedInfItemSubModel.java#L30), but that line isn't even in the method `com.infinityraider.infinitylib.render.item.BakedInfItemSubModel.getQuads`

**Comment by katubug** [comment]
Additional reports of this issue:

https://github.com/AgriCraft/AgriCraft/issues/1242
https://github.com/AgriCraft/AgriCraft/issues/1258
https://github.com/AgriCraft/AgriCraft/issues/1259

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
