### ISSUE TITLE
Inconsistant sprinklers. Works but only for a few seconds

### ISSUE THREAD

**Issue by Kupperu** [AgriCraft/AgriCraft#1172]
## Quick description
The sprinklers aren't constant. They irrigate my farmalnd for a few seconds then it goes dry again. Then it get's irrigated again.

## Mods and versions used

* Minecraft: 1.12.2
* AgriCraft: 2.12.0-a5
* InfinityLib: 1.12.0
ATM3 V5.9.8d modpack
## Steps to replicate the issue
1. Make an irrigatino system with sprinkler
2. Watch the farmland

## Expectations and explanations
I expected the farmland to remain irrigated constantly
## Your environment

* How are you playing?
  * Operating System: Windows 10 64 bit
  * Launcher: MutliMC 0.6.2-develop-1245
  * Modpack: ATM3 V5.9.8d
* What kind of server:
  * [x] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [x] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [x] On an existing save

## Screenshots (or videos)
A video of the problem
https://youtu.be/XtElmLTy9NQ

**Comment by TLomon** [comment]
I observed the same behavior so started to test with bare bones.
Minecraft: 1.12.2
AgriCraft: 2.12.0-a6
InfinityLib: 1.12.0
Exact same behavior observed. Some blocks stay unhydrated enough to turn to normal dirt.

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
