### ISSUE TITLE
Question about getting the mod working in Eclipse

### ISSUE THREAD

**Issue by WolfieWaffle** [AgriCraft/AgriCraft#1174]
I want to see if I can get this mod working with Serene Season support and make a PR, so I forked it and cloned it, then ran `git submodule update --init --recursive`. I used "Import existing projects into workspace" to get it into eclipse. However now it says the source folders for AgriCore and InfinityLib are missing.
![capture](https://user-images.githubusercontent.com/8770485/44496091-15d93e80-a630-11e8-9526-9d7731fbbbb5.PNG)

I tried the minecraft mod dev discord and stack exchange, but all the problems usually result in the setup of a specific library rather than missing source folders. How do I add AgriCore and InfinityLib properly so that these errors go away?

**Comment by RlonRyan** [comment]
```
git clone --recurse-submodules git@github.com:AgriCraft/AgriCraft.git
gradle setupDecompWorkspace eclipse
```

Is the best I can tell you.

You are probably better off moving to the community edition of intellij, as it has the best support nowadays.

**Comment by WolfieWaffle** [comment]
I've figured out that if I import it as a project it works, however now Agricraft master branch has a bunch of syntax errors. I'll list a few in case this is stuff fixed in a version I don't have for whatever reason:

```
The import com.infinityraider.agricraft.utility.OreDictUtil cannot be resolved

The method initConfiguration(FMLPreInitializationEvent) of type IProxy must override or implement a supertype method

The type AgriCraft must implement the inherited abstract method InfinityMod.getConfiguration()

Cannot infer type argument(s) for <U> flatMap(Function<? super T,Optional<U>>)
```
etc.

I didn't remove any code, and these package names of the missing things appear to be in AgriCraft. Am I using a too recent unstable version?

**Comment by WolfieWaffle** [comment]
That's odd, I refreshed that specific package and it appeared :/ perhaps you are right about changing IDE, or at least updating it. I thought this was AgriCraft related since I'd never seen these issues before, but maybe it's using stuff that this IDE isn't prepared for yet or something.

**Comment by WolfieWaffle** [comment]
Now I have a new problem though, which is that even on this GitHub on master branch, `ItemDebugger` refrences `com.infinityraider.infinitylib.handler.ConfigurationHandler` which does not exist on the master branch of InfinityLib.
