### ISSUE TITLE
Cant place cross sticks for mutating seeds in Departed

### ISSUE THREAD

**Issue by luckyjiant** [AgriCraft/AgriCraft#1175]
## Related issues and searches

* https://github.com/AgriCraft/AgriCraft/issues?q=is%3Aissue%20EXAMPLE

## Mods and versions used

* Minecraft:
* AgriCraft:
* InfinityLib:
* [List the other required mods here]

## Steps to replicate the issue

1. Started server
2. Placed a cropstick on another
3. It pops off

## Your environment

* How are you playing?
  * Operating System: Windows 10-64bit
  * Launcher:Twitch
  * Modpack: Sky Block 3 Departed
* What kind of server:
  *Multiplayer
* Game Modes:
  * [ ] Survival
* Save File:
  * [ ] Brand new save

## Links to crash logs, stack traces, etc
No Crash
## Screenshots (or videos)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/42719593/44630984-bcc12180-a933-11e8-8fdd-2492e96dc95b.gif)

**Comment by RlonRyan** [comment]
What version of AgriCraft?

**Comment by Timeslice42** [comment]
Version 3.4.2 of MS3 is using this version: https://i.imgur.com/7OwSEIK.png

**Comment by Poisonsting** [comment]
Can confirm my server is experiencing the same issue on Agricraft 2.12.0-1.12.0-a5

**Comment by Timeslice42** [comment]
Sounds like a MP permissions issue then. I remember this being an issue with a much older version of AgriCraft. @Poisonsting Test and see if an OP can place the crop sticks.

**Comment by Poisonsting** [comment]
2 OPs and 1 regular player are experiencing the same problem.

**Comment by Timeslice42** [comment]
Thanks for testing. To be clear, when it worked for me that was in a single-player world. I also tried starting SSP, and then enabling LAN connection. Cross-crops still worked. I have *not* tried SMP.

**Comment by mrtomwolf** [comment]
I have the same issue. Also can't place water with buckets if I've gotten the water from the Wooden Water Tank. I can place water I got from other sources just fine. Probably related.

**Comment by xILikepuddingx** [comment]
U can place it with shift + right click

**Comment by luckyjiant** [comment]
No you can’t have tried that does as in the video

**Comment by xILikepuddingx** [comment]
https://files.ilikepudding.de/annj721dgf.mp4

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
