### ISSUE TITLE
[Question] com.infinityraider.infinitylib.handler.ConfigurationHandler does not exist on master branch of InfinityLib

### ISSUE THREAD

**Issue by WolfieWaffle** [AgriCraft/AgriCraft#1177]
I am attempting to get AgriCraft working in my dev environment and so far have found workarounds for my IDE problems. I have a new problem though, which is that on this GitHub on master branch, `ItemDebugger` refrences `com.infinityraider.infinitylib.handler.ConfigurationHandler` which does not exist on the master branch of InfinityLib at https://github.com/InfinityRaider/InfinityLib/tree/master/src/main/java/com/infinityraider/infinitylib.

I'm unfamiliar with how this repository is organized, so I am assuming this is the wrong branch or something. My intent is to work on the 1.12 alpha version. Is there currently a branch which is free of syntax errors that I should be using?

**Comment by RlonRyan** [comment]
I blame @InfinityRaider

**Comment by InfinityRaider** [comment]
Ye, me too!

...
Wait...
