### ISSUE TITLE
[Suggestion] Moving or removing the "Clipping did not take..." text

### ISSUE THREAD

**Issue by ProxyPlayerHD** [AgriCraft/AgriCraft#1178]
everytime a clipping did not work on cropsticks it posts that one message into the chat, which quickly spam the entire chat full. which gets very annoying in MP and SP.

so i got 3 ideas to fix that,
1. make it only write a single message in text (look at the drums from ExU2 for example, they do it perfectly)
2. use the space above the Hotbar to write text (like Beds, Minecarts, Boats, etc. do)
3. just remove it completely (i don't see the reason behind having that message there in the first place)

**Comment by darthvader45** [comment]
Option 2 sounds good.

**Comment by InfinityRaider** [comment]
Keeping this for consideration in the 1.16 rewrite

**Comment by InfinityRaider** [comment]
Is no longer relevant since the clippers functionality has changed completely in 1.16.
