### ISSUE TITLE
[suggestion] hide wooden stuff from JEI

### ISSUE THREAD

**Issue by TimGoll** [AgriCraft/AgriCraft#1180]
Add an option similar to the one in Tinkers Construct which allows you to disable 20 times the same item in JEI. With Biomes O Plenty installed AgriCraft has page after page of the same block:

![image](https://user-images.githubusercontent.com/13639408/44848693-07a2a800-ac58-11e8-81c0-0ff1110359b2.png)

**Comment by SynexWolf** [comment]
You could already do it in jei itself...

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
