### ISSUE TITLE
Missing World Config

### ISSUE THREAD

**Issue by dragonriderworld** [AgriCraft/AgriCraft#1181]
## Quick description
Installed Agricraft
Loocked into config
No World Config -> Can't edit Greenhouse spawn rate

## Mods and versions used

* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1-12-0-a6
* InfinityLib: 1.12.0 (1.12.2-1.12.0)

## Expectations and explanations
Wanted a World Config

## Your environment

* How are you playing?
  * Operating System: Windows?
  * Launcher: Curse
  * Modpack: MY own (Not Public)
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Screenshots (or videos)
![2018-09-03_20 21 06](https://user-images.githubusercontent.com/40246719/44998581-11f5d680-afb7-11e8-920d-65659f6f19c4.png)

**Comment by RlonRyan** [comment]
Greenhouses were removed from AgriCraft for the time being, starting with the 1.10 releases. As such there should be no greenhouse configuration options, as there are no greenhouses.

**Comment by Macleykun** [comment]
Sorry to revive this issue, but are there plans to re-add the greenhouse for 1.12.2?
I really love the greenhouse especially that it spawns in villages, it really motivates me/players to start with other foods other then vanilla thanks to this!

**Comment by InfinityRaider** [comment]
No, sorry, no more 1.12 work.
