### ISSUE TITLE
[Suggestion] Crops rotting compatibility / Different products on different stages

### ISSUE THREAD

**Issue by Alessandro404** [AgriCraft/AgriCraft#1182]
As per title, I'm trying to make a modpack using agricraft + food funk + spice of life.

Food funk makes vanilla crops rot if not harvested in time, a thing that helps with spice of life: keeping a low amount of food readily harvestable to counter food spoiling over time. 

Harvestcraft right now once the crop has matured is an indefinite storage for crops.

The best solution, if possible, would be to make both Agricraft and food funk compatible, spoiling the possibile output of a crop after the same time inside food funk configs.

Another solution could be a way to choose a different product when the crop is at a certain stage, much like potatoes > poisoned potatoes in Ic2. That would help modpacks makers and  I could manually add as a "last stage" the rotten version of the crop :D 

Thank you for your time

**Comment by InfinityRaider** [comment]
I like this suggestion.

**Comment by InfinityRaider** [comment]
Keeping this open for consideration in the 1.16 rewrite

**Comment by InfinityRaider** [comment]
In 1.16 AgriCraft's API is implemented such that plants can be easily overridden by plugins.
Also, plant harvestability is now no longer tied to being the final growth stage, so a plugin could be made, wrapping each plant into a new instance, replacing the growth logic with an additional growth stage for being fully grown.

Crops rotting is not something I want to have in Vanilla AgriCraft, therefore it will be up to you, or someone else to make a plugin that does this.
