### ISSUE TITLE
Agricraft Tank + Thermal Foundation Fluiduct crash

### ISSUE THREAD

**Issue by Black0305** [AgriCraft/AgriCraft#1184]
## Quick description
Game crashes when you break a filled Fluiduct from Thermal Foundation, which is attached to a AgriCraft tank

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 1.12.0-a6
* InfinityLib: 1.12.0
* Thermal Foundation / Dynamics both latest version

## Steps to replicate the issue
1. Place Agricraft Tank, fill it with water and attach two Fluiducts with a servo to extract water (Fluiduct must be filled)
2. Break the second Fluiduct
3. Crash 

## Expectations and explanations
Shouldnt crash

## Your environment
* What kind of server:
  * [x] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [x] Survival
  * [x] Creative
* Save File:
  * [x] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
* https://pastebin.com/19uEKcCB

## Screenshots (or videos)
![agricrash](https://user-images.githubusercontent.com/42079463/45066527-19080c00-b0bf-11e8-8493-f96f991df744.JPG)

**Comment by RlonRyan** [comment]
Looks like the IFluidHandler interface doesn't work the way I would have expected it to, in that it seems to allow draining negative amounts, which makes no sense. I'll have to remove the precondition check so it doesn't crash the game when the interface is abused.
