### ISSUE TITLE
Stats Breeding Seems really challenging with default settings and weeds.

### ISSUE THREAD

**Issue by KaneHart** [AgriCraft/AgriCraft#1186]
**Version:** AgriCraft-2.12.0-1.12.0-a6.jar
**Other Mods:** With or Without it seems to be about the same.
Description of the Issue: No matter what I do it seems like breeding stats seems to be very challenging and hard but mutation breeding seems simple. I tried to increase stats the same way as I mutate but I seem to get 99% weeds.

**Examples of methods I tried:**
https://cdn.discordapp.com/attachments/486001186202189825/488436440573935627/unknown.png
method I prefer in IC2:
https://cdn.discordapp.com/attachments/486001186202189825/488434160952803349/unknown.png

Like I said no matter what I spend 99% of the time getting weeds where when I do the same with mutations 2 diff plants it takes maybe 2-3 tries and boom the new plant. 

I'm hoping I'm doing it wrong to save you time fixing it. Thanks.

**Comment by Algester** [comment]
you can kind of disable the weeds to a more manageable outcome by doing a 95% chance of mutation on the config yes its a bit cheaty but that was the fix I got

**Comment by LucyDemooon** [comment]
what for an config for disabling this weed shit?

**Comment by RlonRyan** [comment]
To disable weeds go to `config\agricraft\json\defaults\vanilla\plants\weed_plant.json` and set `enabled` to `false` instead of `true`.
