### ISSUE TITLE
Garden Trowel deletion glitch.

### ISSUE THREAD

**Issue by BadsyEdgecat** [AgriCraft/AgriCraft#1191]
## Quick description
Placing a Garden Trowel containing a plant in the Seed Analyzer destroys the trowel.

## Related issues and searches
I cannot find any other similar bug reports here.

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0
* InfinityLib: 1.12.0?

## Steps to replicate the issue
1. I used a garden trowel to pick up a Pumpkin plant, although it works with any crop.
2. I took the trowel with the plant in it and put it into the GUI of the Seed Analyzer.
3. The trowel was replaced with a scanned seed, which destroys the trowel completely.

## Expectations and explanations
What should've happened is that the trowel should've continued to exist, with the seedling's Strength, Growth, and Gain stats being visible on the item.

**Comment by Skipper-is** [comment]
Seconded, Got the same issue in latest release

**Comment by taiyoko** [comment]
I am also getting this issue.
Minecraft 1.12.2
Agricraft 2.12.0 a6
InfinityLib 1.12.0

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
