### ISSUE TITLE
Crossbreading not working

### ISSUE THREAD

**Issue by 11hunter22** [AgriCraft/AgriCraft#1193]
## Quick description
 I added agricraft to a modpack and wanted to do some crossbreading.
Started like this:
... O
ONO
...O

O being the vanilla wheat seeds in a crop
N being a empty double crop

Everything is lightened up and irrigated

For some reason no crossbreaded seed is appearing. I tried to crossbread some other seeds, but it wont work.
Any ideas why this is happening?

## Related issues and searches

* https://github.com/AgriCraft/AgriCraft/issues?q=is%3Aissue%20EXAMPLE

## Mods and versions used

* Minecraft: 1.12.2
* AgriCraft: 1.12.2
* InfinityLib: 1.12.2
* [List the other required mods here]

## Steps to replicate the issue

1. Loaded up `...`
2. Placed a `...`
3. Right-clicked with `...` on `...`
4.

## Expectations and explanations
 I basically want a new seed to appear in the middle of this crosslike pattern of seads.

## Your environment

* How are you playing?
  * Operating System: Win 10 64 bit
  * Launcher: 
  * Modpack: FTB revelation V. 2.5.0
* What kind of server: -
  * [x] Singleplayer +
  * [ ] Multiplayer -
* Game Modes:
  * [x] Survival +
  * [ ] Creative -
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc

* https://gist.github.com/
* https://paste.ee/
* https://duckduckgo.com/?q=pastebin+alternatives
* Upload them somewhere, and then replace these links.

**Comment by Algester** [comment]
try tinkering with the configs with the weeds permanently on place it will take some time to get your seeds like really a long time try it with torcherino and see if your new seeds spawn sometimes with torcherino at 400% it takes about 1-2 minutes before a plant appears

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
