### ISSUE TITLE
[Compat Issue] Cannot automate placing crop sticks.

### ISSUE THREAD

**Issue by Deathlymad** [AgriCraft/AgriCraft#1195]
So I wanted to build an Auto-Breeder with OpenComputers, And the program should later automatically create farms frfom the 10/10/10 seeds. That fell flat when i discovered that robots cannot place crop sticks. After that i tried to use other placer Blocks all failed, so i assume that the issue lies with Agricraft.

## Related issues and searches
I did not really find issues relating this. All i found were several references to crop sticks generally not being placable. However in this case I can place them was a player.However I remember that it was possible to auto place them in older versions.

## Mods and versions used
https://pastebin.com/kByWmStR
Minecraft Version 1.12.2

## Steps to replicate the issue
Use a third party placer and attempt to place crop sticks with them.
I tested with:
Industrial Forgoing Block Placer
OpenComputers Robot
Actually Additions Block Placer
Striped Pipe Buildcraft

## Expectations and explanations
I would assume that at least some placers should be able to place crop sticks. 

## Your environment

* How are you playing?
  * Operating System: Win10x64
  * Launcher: Twitch Launcher
  * Modpack: Modern Skyblock 3: Departed 3.4.2
* What kind of server:
  * [X ] Multiplayer
* Game Modes:
  * [X ] Survival
* Save File:
  * [X ] Only an existing save

## Links to crash logs, stack traces, etc
I checked the logs extensively there were no errorsin that time frame or any log generally. If required i can try to replicate it again with the debug mode on.

**Comment by Deathlymad** [comment]
Edit 1: I had a look at the OnItemUse Function in ItemCrop. First thing i tried from that was auto placing in a single player world. With the same results. Working theory is that the auto-placers try to *use* the item instead of placing it (even with robot.place in oc robots). So the onItemUse would get the Block the item is used on and not the block on top of it *maybe*. That would lead to a failure without it being intended and no log following that.

**Comment by Algester** [comment]
you need to be sneaking to place a Cross Crop maybe Thermal Expansion's block place is more useful for this automation?

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
