### ISSUE TITLE
EnderIO's Grains of Infinity and Thermal Expansion's Fluxed Electrum seeds from Mystical Agriculture arent considered "cropable"

### ISSUE THREAD

**Issue by Algester** [AgriCraft/AgriCraft#1196]
## Quick description
Fluxed Electrum Seeds and Grains of Infinity Seeds arent considered valid crops.

## Mods and versions used
EnderIO
Thermal Expansion
Mystical Agriculture
edited "Stone Block modpack"

## Steps to replicate the issue
the Crops block just doesnt want to accept the Seeds to be planted

## Expectations and explanations
seeds become part of Agricraft interaction

## Your environment

* How are you playing?
  * Operating System: Windows 10 Pro
  * Launcher: Twitch
  * Modpack: Stoneblock
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Screenshots (or videos)
![2018-10-20_02 08 33](https://user-images.githubusercontent.com/6236070/47235931-18c49580-d40d-11e8-94dd-05672888174d.png)

**Comment by Algester** [comment]
nevermind I found out that Flux Electrum dont have json files inside the config folder from Mystical Agriculture

**Comment by Zerocool211** [comment]
Had this issue and managed to create a json file for grains of infinity, so they work in the crops, here is a link to the file:
[grains_of_infinity_plant.zip](https://github.com/AgriCraft/AgriCraft/files/3297681/grains_of_infinity_plant.zip)

put this file in:
*your_pack*\config\agricraft\json\defaults\mod_mysticalagriculture\plants

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
