### ISSUE TITLE
Snow forming on wooden irrigation channels

### ISSUE THREAD

**Issue by SlimF** [AgriCraft/AgriCraft#1198]
### Mods and versions used:

Minecraft - 1.12.2
AgriCraft - 2.12.0-1.12.0-a6
Forge - 14.23.5.2772

### Steps to replicate the issue:
Place a couple of irrigation channels in a snowy biome, turn rain on and wait until snow starts accumulating on the channels.

![2018-11-06_13 36 15](https://user-images.githubusercontent.com/6482572/48065469-7dd10700-e1d3-11e8-8e54-5177b89c786b.png)

**Comment by InfinityRaider** [comment]
Funky.

Closing since we are moving to 1.16.
