### ISSUE TITLE
Client crash while rendering item

### ISSUE THREAD

**Issue by LineOfRage** [AgriCraft/AgriCraft#1199]
Client crashing when playing in multiplayer server. It can crash in my friend's client, he is playing on server too. And it can crash at any point in time, when searching in the JEI, when breaking a block and drop an item from AgriCraft, when I look in the chest where the items from AgriCraft. It can be a seed, a seed analyzer, a nugget, etc.

## Mods and versions used
* Minecraft: 1.12.2 forge 14.23.4.2707
* AgriCraft: AgriCraft-2.12.0-1.12.0-a6
* InfinityLib: infinitylib-1.12.0
* other from sevtech

## Your environment
* How are you playing?
  * Operating System:
  * Launcher:
  * Modpack: https://minecraft.curseforge.com/projects/sevtech-ages
* What kind of server:
  * [ ] Singleplayer
  * [X ] Multiplayer
* Game Modes:
  * [X ] Survival
  * [X ] Creative

## Links to crash logs, stack traces, etc
https://gist.github.com/LineOfRage/a0ac2c5ab28d2cc9572e0b34bc65e4d3#file-crash-2018-11-24_23-48-42-client-txt

**Comment by tyler489** [comment]
I also had this crash with Water tanks https://paste.dimdev.org/viloconoge.mccrash

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
had This Problem too...

**Comment by RlonRyan** [comment]
Duplicate #1170
