### ISSUE TITLE
[Suggestion] Plant Agricraft Seeds Off Cropsticks

### ISSUE THREAD

**Issue by inkdear** [AgriCraft/AgriCraft#1200]
The ability to plant agricraft crops off of cropsticks for "reasonable realism" and/or aesthetic/building reasons (since IRL you don't have to plant a wheat field on support sticks.) Crops planted off sticks wouldn't be able to affect mutations, spread, etc, but would retain whatever stats they'd been bred with. Might also shotgun-style increase automation compatibility with other mods...?

**Comment by InfinityRaider** [comment]
Keeping this open to consider in the 1.16 rewrite (no guarantees).

**Comment by InfinityRaider** [comment]
Has been implemented
