### ISSUE TITLE
JourneyMap Mob Icon Integration

### ISSUE THREAD

**Issue by MeinKraft** [AgriCraft/AgriCraft#1201]
## Quick description

Add JourneyMap Mob Icon integration

## Mods and versions used

* Minecraft: 1.12.2
* AgriCraft:2.12.0-1.12.0-a6
* InfinityLib:

**## Expectations and explanations

**

If you rename your 'textures\entities' folder to 'textures\entity' to allow JourneyMap and resource packs to show custom icons for your mobs on JourneyMaps Mini/Fullscreen maps

https://journeymap.info/Custom_Mob_Icon_Sets

thank you..

## Your environment

* How are you playing?
  * Operating System:Win10
  * Launcher:Twitch
  * Modpack:
* What kind of server:
  * [X ] Singleplayer
  * [X ] Multiplayer
* Game Modes:
  * [ X] Survival
  * [ X] Creative
* Save File:
  * [ X] Brand new save
  * [X ] Only an existing save

**Comment by starryknight64** [comment]
Pardon my ignorance, but what mobs does Agricraft add?

**Comment by MeinKraft** [comment]
dragon, butterfly and villager are listed in the mods .jar file

**Comment by Syndaryl** [comment]
I'm not sure if the custom villager is live. Or the other two. But it's there for when they go live anyways 😊

**Comment by InfinityRaider** [comment]
villager is disabled and dragons nor butterflies where ever a thing...
