### ISSUE TITLE
Implement (or reimplement) HWYLA Integration

### ISSUE THREAD

**Issue by khift363** [AgriCraft/AgriCraft#1202]
I don't actually know whether this is a bug or a suggestion. I can find many older posts (2+ years) about AgriCraft's WAILA integration, and even a small handful of posts (~1 year ago) about it working with HWYLA. However, in game right now, AgriCraft does not work with HWYLA, and I can find no config options or other method to make it work, and I can find many recent posts of people publicly recognizing that AgriCraft does not have HWYLA integration. 

I don't know if the current lack of HWYLA integration is a bug, oversight, or intentional choice on the part of AgriCraft's team, but I must ask that you please consider implementing or reimplementing it. The One Probe is a great addon, but it doesn't support all of the other mods in my modpack, and so I'm left with a choice where I have to decide which mod doesn't get tooltip support, and sadly AgriCraft loses that battle. We're trying to make do with Magnifying Glasses, but it's not an ideal solution.

**Comment by MJRamon** [comment]
I double on that question.

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
