### ISSUE TITLE
Quartz Shard and Quartzantheum Seed showing -1 for ID (not showing in NEI list)

### ISSUE THREAD

**Issue by ResqDiver1317** [AgriCraft/AgriCraft#1203]
## Quick description
I know this is issue is for an old version so if you do not want to answer, I understand, but hopefully someone can throw some advice out. We are running a newer server on 1.7.10 and have a few players trying to get a jump on Avaritia. One of the Avaritia recipes calls for Quartz Shards. I looked these up and they don't show in our NEI. If I click the Shard in the Avaritia Recipe, it shows you can make them from the Quartzantheum seeds, but these seeds also do not show in our NEI. When hovering over either of these in the recipes, they are both showing an Item ID of -1. I can see the seed in the mutations file, but the NEI is not showing how to make the seed like it does other agricraft seeds.

## Mods and versions used
* Minecraft: 1.7.10
* AgriCraft: AgriCraft-1.7.10-1.5.0
* InfinityLib: Not Applicable for 1.7.10 I believe?
* [List the other required mods here]

## Steps to replicate the issue

Look up Avaritia Ultimate Stew Recipe. Mouse over the Quartz Shard and see it's ID as -1. Click the shard in the recipe and see how it can be crafted from quartz and grown using the seeds (mouse over the seed to see it also has an ID of -1. 

Looking up either the shard or seed in the NEI brings no results. Clicking the seed shown in the recipe for the shard (when the shard is clicked from the ultimate stew recipe) shows no method for making the seed. 

Attempting to craft the shard by placing a piece of quartz causes the 9 shards to appear very briefly in the output slot, but it immediately vanishes. 

My first thought was to just add a crafting recipe for the shards but being as they are showing -1 for the itemID, I cannot even /give the shard to myself to use it for this. 

## Your environment

* How are you playing?
  * Operating System: Windows 7
  * Launcher: Technic
  * Modpack: AC Special Sauce 1.7.10 (custom modpack I built for our community.
* What kind of server:
  * [ ] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative (I did look in the creative menu and neither the seed nor shard show here either)
* Save File:
  * [ ] Brand new save
  * [x] Only an existing save

## Links to crash logs, stack traces, etc

* https://gist.github.com/
* https://paste.ee/
* https://duckduckgo.com/?q=pastebin+alternatives
* Upload them somewhere, and then replace these links.

## Screenshots (or videos)
![2018-12-26_23 08 29](https://user-images.githubusercontent.com/18246580/50466441-2fceb900-0963-11e9-93d1-13b60d78ecf7.png)
![2018-12-26_23 08 35](https://user-images.githubusercontent.com/18246580/50466443-32311300-0963-11e9-8862-67cd2b876a34.png)

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
