### ISSUE TITLE
Crops Invisible w/ VanillaFix

### ISSUE THREAD

**Issue by nephatrine** [AgriCraft/AgriCraft#1204]
Visual issue where planted AgriCraft crops are invisible when using AgriCraft and VanillaFix together. Makes my greenhouses look barren.

Using AgriCraft-2.12.0-1.12.0-a6 (w/ infinitylib-1.12.0) and VanillaFix-1.1.1-132. Forge is 1.12.2-14.23.5.2772.

Opened issue on VanillaFix tracker as well: https://github.com/DimensionalDevelopment/VanillaFix/issues/153

**Comment by RlonRyan** [comment]
This is caused by another mod messing with our unique rendering pipeline, which shouldn't be done.
