### ISSUE TITLE
Crash with Avatar 2: Out of the Iceberg installed

### ISSUE THREAD

**Issue by Rileyyyy** [AgriCraft/AgriCraft#1205]
I use both Agricraft and Avatar 2: Out of the Iceberg on a server and when a player bends using the avatar mod it removes an import that it shouldn't and causes the players game to crash. I
 have a few crash logs of the issue. Thanks!

[crash-2019-01-14_17.46.26-client.txt](https://github.com/AgriCraft/AgriCraft/files/2758250/crash-2019-01-14_17.46.26-client.txt)

[crash-2019-01-14_18.38.27-client.txt](https://github.com/AgriCraft/AgriCraft/files/2758251/crash-2019-01-14_18.38.27-client.txt)

[crash-2019-01-14_19.23.26-client.txt](https://github.com/AgriCraft/AgriCraft/files/2758252/crash-2019-01-14_19.23.26-client.txt)

**Comment by FavouriteDragon** [comment]
Hey, I'm one of the devs of avatar mod :P
For some reason, using Agricraft with Avatar causes some rendering to crash. Does Agricraft change the player's rendering in any way? Because it seems that with Agricraft installed, the player doesn't have access to any Matrix4D functions with OpenGl.

**Comment by InfinityRaider** [comment]
In 1.7 it used to, but not anymore.
Anyway, it seems to me that the joml library is just not present.
