### ISSUE TITLE
Farming Problem

### ISSUE THREAD

**Issue by LokyLive** [AgriCraft/AgriCraft#1206]
Hello Everyone !

I'm currently working on a modpack in 1.12.2 and i encounter some problem with Agricraft :

1 - Vanilla farming enable - I do crossbreeding and i obtain 3-2-3 seed and when i plant the seed on farmland without crop bar , she could grow without under soil requirement ( i use vanilla ore as requirement under farmland )

-2 When i fully grow my 3-2-3 seed (without cropbar) and i break it to take back the seed , i drop an unidentified seed  and as result when i identify her i get a 1-1-1 seed 

PS: Are you still working on a release version ? 

## Mods and versions used
minecraft - Minecraft - 1.12.2
mcp - Minecraft Coder Pack - 9.42
FML - Forge Mod Loader - 8.0.99.99
forge - Minecraft Forge - 14.23.5.2807
smoothfontcore - Smooth Font Core - mc1.12.2-1.16
foamfixcore - FoamFixCore - 7.7.4
smoothfont - Smooth Font - mc1.12.2-1.16.2
rpghud - RPG-Hud - 3.6.6.2
actuallyadditions - Actually Additions - 1.12.2-r144
baubles - Baubles - 1.5.2
actuallybaubles - Actually Baubles - 1.1
infinitylib - InfinityLib - 1.12.2-1.12.0
agricraft - AgriCraft - 2.12.0-1.12.0-a6
crafttweaker - CraftTweaker2 - 4.1.13
mtlib - MTLib - 3.0.5
modtweaker - Mod Tweaker - 4.0.15
jei - Just Enough Items - 4.14.4.257
appleskin - AppleSkin - 1.0.9
armoreablemobs - ArmoreableMobs - 1.1.2
astikoor - Astikoor - 1.1.1
base - B.A.S.E - 3.11.0
bdlib - BD Lib - 1.14.3.12
betteranimals - Better Animals Mod - 3.1
betteranimalsplus - Better Animals+ - 4.1.0
betterbuilderswands - Better Builder's Wands - 0.12.1
biometweaker - BiomeTweaker - 3.2.354
blockcraftery - Blockcraftery - 1.12.2-1.1.0
blockdropstweaker - Block Drops Tweaker - 2.4
bloodmoon - Bloodmoon - 1.5.3
bookshelf - Bookshelf - 2.3.571
forestry - Forestry - 5.8.2.380
careerbees - careerbees - 1.0
gamestages - Game Stages - 2.0.114
carryon - Carry On - 1.12.1
ctm - CTM - MC1.12.2-0.3.3.22
chisel - Chisel - MC1.12.2-0.2.1.35
endercore - EnderCore - 1.12.2-0.5.44
enderio - Ender IO - 5.0.39
enderiointegrationtic - Ender IO Integration with Tinkers' Construct - 5.0.39
mantle - Mantle - 1.12-1.3.3.39
tconstruct - Tinkers' Construct - 1.12.2-2.12.0.113
ceramics - Ceramics - 1.12-1.3.6
chameleon - Chameleon - 1.12-4.1.3
chattweaks - Chat Tweaks - 5.1.20
chococraft - Chococraft 3 - 0.9.7.0
shadowmc - ShadowMC - 3.8.0
clipboard - Clipboard - @VERSION@
codechickenlib - CodeChicken Lib - 3.2.2.353
cofhworld - CoFH World - 1.3.0
compfac - Compressed Factory - 1.3.1
contenttweaker - ContentTweaker - 1.12.2-4.9.1
conarm - Construct's Armory - 1.2.2
controlling - Controlling - 3.0.6
ctgui - CT-GUI - 1.0.0
crafttweakerjei - CraftTweaker JEI Support - 2.0.2
creeperconfetti - Creeper Confetti - 1.4.2
cucumber - Cucumber Library - 1.1.3
culinaryconstruct - Culinary Construct - 1.3.1
dimstages - Dimension Stages - 2.0.23
dumpsterdiving - Dumpster Diving - 1.0 - 1.12.2
dynamictrees - Dynamic Trees - 1.12.2-0.9.4
endercrop - Ender Crop - 1.12.2-1.6.0
enderiobase - Ender IO Base - 5.0.39
enderioconduits - Ender IO Conduits - 5.0.39
enderioconduitsappliedenergistics - Ender IO Applied Energistics Conduits - 5.0.39
enderioconduitsopencomputers - Ender IO Open Computers Conduits - 5.0.39
refinedstorage - Refined Storage - 1.6.12
enderioconduitsrefinedstorage - Ender IO Refined Storage Conduits - 5.0.39
enderiointegrationforestry - Ender IO Integration with Forestry - 5.0.39
enderiointegrationticlate - Ender IO Integration with Tinkers' Construct - 5.0.39
ftblib - FTB Library - 5.4.1.77
enderiomachines - Ender IO Machines - 5.0.39
enderiopowertools - Ender IO Powertools - 5.0.39
enderioendergy - Ender IO endergy - 5.0.39
enderstorage - EnderStorage - 2.4.5.135
enderutilities - Ender Utilities - 0.7.12
railcraft - Railcraft - 12.0.0-beta-4
immersiveengineering - Immersive Engineering - 0.12-88
engineersdoors - Engineer's Doors - 0.8.0
epicsiegemod - Epic Siege Mod - 13.163
exchangers - Exchangers - 1.12.2-2.8
fbp - Fancy Block Particles - 2.4.1
fastleafdecay - Fast Leaf Decay - v14
fencejumper - Fence Jumper - 1.0.5
foamfix - FoamFix - 0.10.3-1.12.2
forgelin - Shadowfacts' Forgelin - 1.8.2
forgemultipartcbe - Forge Multipart CBE - 2.6.0.79
microblockcbe - Forge Microblocks - 2.6.0.79
minecraftmultipartcbe - Minecraft Multipart Plugin - 2.6.0.79
ftbutilities - FTB Utilities - 5.3.0.73
itemfilters - Item Filters - 1.0.1.5
ftbquests - FTB Quests - 1.4.1.115
fw - Fullscreen Windowed - 1.6.0
gamestagebooks - Gamestage Books - 1.12.2-1.0.0
gendustry - GenDustry - 1.6.5.8
gobblecore - Gobble Core - 1.12-0.1.6.35
waila - Waila - 1.8.26
horsepower - Horse Power - 2.6.1
iguanatweaks - IguanaTweaks Reborn - 1.4.5
mcjtylib_ng - McJtyLib - 3.1.1
immcraft - Immersive Craft - 1.5.1
immersivecables - Immersive Cables - 1.3.2
immersivetech - Immersive Tech - 1.3.10
incontrol - InControl - 3.8.3
teslacorelib - Tesla Core Lib - 1.0.15
industrialforegoing - Industrial Foregoing - 1.12.2-1.12.2
mysticalagriculture - Mystical Agriculture - 1.7.1
integrationforegoing - Integration Foregoing - 1.12.2-1.8.2
inventorysorter - Simple Inventory sorting - 1.13.3+57
itemstages - Item Stages - 2.0.46
jeibees - JEI Bees - 0.9.0.5
journeymap - JourneyMap - 1.12.2-5.5.3
jaff - Just a Few Fish - 1.7_for_1.12
logisticspipes - Logistics Pipes - 0.10.1.110
loottweaker - LootTweaker - 0.0.8
malisiscore - MalisisCore - 1.12.2-6.4.0
malisisdoors - MalisisDoors - 1.12.2-7.3.0
metalchests - MetalChests - v3.9.0.g9b0c79e
mikedongles - Mike Dongles - 0.6.0
mobstages - Mob Stages - 2.0.13
morelibs - More Libs - 1.0.8
moreoverlays - MoreOverlays - 1.14
mousetweaks - Mouse Tweaks - 2.9
multifarmcrops - Multifarm Crops - 1.2.0
naturescompass - Nature's Compass - 1.5.1
neat - Neat - 1.4-17
norecipebook - No Recipe Book - 1.2.1
neid - NotEnoughIDs - 1.5.4.3
noworldgen5you - No World Gen 5 You - 1.0.8
nutrition - Nutrition - 4.0.0
omlib - OMLib - 3.1.0-195
ompd - Open Modular Passive Defense - 3.0.0-36
openmodularturrets - Open Modular Turrets - 3.1.0-292
orestages - Ore Stages - 2.0.38
outfox - Outfox - 0.1.3
patchouli - Patchouli - 1.0-16
placebo - Placebo - 1.5.0
pe2 - Powered Elements 2 - 1.69
playerskins - Player Skin Mobs - 1.0.4
pneumaticcraft - PneumaticCraft: Repressurized - 1.12.2-0.9.0-310
primal - PrimalCore - 0.6.104
prodigytech - Prodigy Tech - 1.0.0
realdrops - Realistic Item Drops - 1.2.14
reborncore - Reborn Core - 3.13.1.402
rebornstorage - RebornStorage - 1.0.0
recipestages - RecipeStages - 1.1.1
refinedstorageaddons - Refined Storage Addons - 0.4.3
resourceloader - Resource Loader - 1.5.3
ruins - Ruins Mod - 17.1
scavenge - Scavenge - 1.8
storagenetwork - Simple Storage Network - 1.5.6
storagedrawers - Storage Drawers - 1.12-5.3.5
surge - Surge - 2.0.76
tinkeredhegemony - Tinkered Hegemony - @VERSION@
tinkersjei - Tinker's JEI - 1.0
tinkertoolleveling - Tinkers Tool Leveling - 1.12.2-1.1.0.DEV.b23e769
toastcontrol - Toast Control - 1.7.1
tombstone - Corail Tombstone - 3.3.0
translocators - Translocators - 2.5.1.77
twitchintegration - Twitch Integration - 4.1.10
vanillafix - VanillaFix - 1.0.10-SNAPSHOT
vanillafoodpantry - Vanilla Food Pantry - 4.3.0
wailaharvestability - Waila Harvestability - 1.1.12
watercontrolextreme - Water Control Extreme - 1.0.0
waterstrainer - Water Strainer - 3.2.0
waterworks - Waterworks - 1.12.2-1.0.12
wawla - What Are We Looking At - 2.5.265
weirdinggadget - The Weirding Gadget - 1.0
wopper - Wopper - 1.12-r5
yoyos - Yoyos - 1.12.2-1.2.2.20
mysticallib - MysticalLib - 1.12.2-1.0.0
primal_tech - primal_tech - 0.3.3
teslacorelib_registries - Tesla Core Lib Registries - 1.0.15
wrapup - WrapUp - 1.12-1.1.3

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
