### ISSUE TITLE
[1.12.2] Start up crash

### ISSUE THREAD

**Issue by TheSnowyChickens** [AgriCraft/AgriCraft#1207]
## Quick description
I can't start MC.

## Related issues and searches
Point 1. I searched with "crash", but I could not find a "start up" crash.

## Mods and versions used

* Minecraft: 1.12.2
* AgriCraft: AgriCraft-2.12.0-1.12.0-a6.jar
* InfinityLib:  infinitylib-1.12.0.jar
* Other mods can be found in the crash log (with versions)

## Steps to replicate the issue
1. Im Dev. from the Curse Modpack "Deep Night" and I want to release an update
2. So I updated all mods (17/18.01.2019)
3. Start the Game
4. RIP

## Expectations and explanations
Point 1: A clean MC start.
Point 2: Mod compatibilities ?

## Your environment

* How are you playing?
  * Operating System: Win10, 64bit
  * Launcher: Default MC
  * Modpack: Deep Night (Curse/Twitch)
* What kind of server: [irrelevant]
* Game Modes: [irrelevant]
* Save File:
  * [ ] Brand new save
  * [X] Only an existing save

## Links to crash logs, stack traces, etc
https://hastebin.com/aticiwudom.rb

## Screenshots (or videos)
I had a Picture, but now I can't reproduce it, because it crashes earlier.
(it was a VanillaFix error screen with "Agricraft" and "InfinityLib" as crash reason)

## Other stuff
The one big problem is, the default MC launcher is broken after this crash, I need to restart my PC OR wait a long time.

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
