### ISSUE TITLE
Config folder has depth

### ISSUE THREAD

**Issue by Divineaspect** [AgriCraft/AgriCraft#1208]
## Quick description
Agricraft folder in configs forms additional config folders within it, which it in turn copies it's agricraft config folder into, ad infinitum. It seems to add a layer every time the server resets.

## Related issues and searches
I searched for Config issues and found nothing similar open or closed. 

## Mods and versions used
* AgriCraft:2.12.0-1.12.0-a6
Infinity Lib: 1.12.0

**Comment by troneleck** [comment]
I have the same problem.

There are many copys from the config folder inside the folder's.
 

![agricraft](https://user-images.githubusercontent.com/17239456/60060669-07e1c780-96f2-11e9-86ae-d88ed78f29e4.png)

**Comment by RlonRyan** [comment]
Can you run the `tree` command in your agricraft config folder, and link the paste here please?

Unless if the folders are recursively nesting in the configuration folder, this is the default behavior, as agricraft maintains separate config directories for each server that it connects to, and has the `default` config as the local config.
