### ISSUE TITLE
Computer Controller Seed Analyser not working with OpenComputers

### ISSUE THREAD

**Issue by TheKrowi** [AgriCraft/AgriCraft#1209]
## Quick description
I've been trying to get the Computer Controller Seed Analyser (CCSA) to work with OpenComputers but no succes. Placing the CCSA next to the Computer Case or next to an Adapter, it does not show up when calling "component.list()". I've done my tests with a note block to see if it's actually working and the note block is recognized by the Adapter.

## Related issues and searches
I found the following topic related to AgriCraft and OpenComputers which might explain why the CCSA is not working.

## Mods and versions used

* Minecraft:
* AgriCraft:
* InfinityLib:
* [List the other required mods here]

## Steps to replicate the issue
1. Set up an OpenComputers Computer
2. Connect an Adapter to it
3. Connected the CCSA to the Adapter
4. Run "lua" command on the OpenComputer and run "component.list()" command
5. The CCSA does not show

Same if you directly connect the CCSA to the computer

## Expectations and explanations
I would expect the OpenComputer to find the CCSA and show it as a component that can be used.

## Your environment
* How are you playing?
  * Operating System: Windows 10
  * Launcher: Twitch
  * Modpack: Project Ozone 3
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
No crashes

## Screenshots (or videos)
![2019-02-01_13 18 51](https://user-images.githubusercontent.com/22818581/52122676-0a009800-2624-11e9-8f21-3d6cdd6fd38f.png)
![2019-02-01_13 19 06](https://user-images.githubusercontent.com/22818581/52122677-0a009800-2624-11e9-8679-e98be0fd6b17.png)

**Comment by fuiru** [comment]
For the devs, is the modid in the @optional method case sensitive? TileEntityPeripheral.java has it as "opencomputers"; wondering if it ought to be "OpenComputers".

**Comment by TehNut** [comment]
All modids are lowercase.

**Comment by fuiru** [comment]
Ah, both [OC](https://github.com/MightyPirates/OpenComputers/tree/master-MC1.7.10/src/main/java/li/cil/oc/api) and [this blog](https://cazzar.net/tutorials/fml/optional-annotations-the-usages/) show upper case for both, which is why I had thought it might be so.

**Comment by TehNut** [comment]
You are looking at a branch targetting 1.7.10 which did not have that enforcement.

**Comment by fuiru** [comment]
Ah, gotcha. Thanks

**Comment by Giraaffes** [comment]
I'm having the same issue

**Comment by mrrykler** [comment]
Having the exact same problem.

**Comment by RlonRyan** [comment]
Combined into #572
