### ISSUE TITLE
Missing Harvestcraft seeds (Due to Pam's Update)

### ISSUE THREAD

**Issue by bookerthegeek** [AgriCraft/AgriCraft#1210]
# Heyo!
Pam updated HarvestCraft, adding some more plants. Yippy. :) 
Here is a list of seeds that do not currently have JSON's populated.

## Seeds ##
```
Agave
Amaranth
Arrowroot
Cassava
Chickpea
Elderberry
Flax
Gigapickle
Greengrape
Huckleberry
Jicama
Jute
Kale
Kenaf
Kohlrabi
Lentil
Millet
Mulberry
Quinoa
Sisal
Taro
```

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a6
* InfinityLib: 1.12.0
* HarvestCraft: 1.12.2zb

**Comment by DrakusorU** [comment]
I have the same issue.. I could easily add them myself but I have no clue about how the mutations should be done for these plants or even if there should any mutations for them at all...

**Comment by DrakusorU** [comment]
here are the plant json files for the new crops, not including the mutation part as I have no idea of what plants to mix to get these.. I didn't get to test all of them, but only a couple in-game and they worked fine.. no broken textures.. 

the files go to "config\agricraft\json\defaults\mod_harvestcraft\plants" in case you don't know.

[agricraft_harvestcraft_new_seeds.zip](https://github.com/AgriCraft/AgriCraft/files/2873537/agricraft_harvestcraft_new_seeds.zip)

**Comment by bookerthegeek** [comment]
Perfect.

**Comment by RlonRyan** [comment]
Added thanks.

**Comment by darkaxel1989** [comment]
I don't know why this was closed at all, this config file wasn't included into the latest cuseforge version (which is more or less 1 year old) Did you make a new version and didn't upload it into curse?
Seeing you're still answering questions and such, I'm sure the project wasn't abandoned, so, any reasons for not adding it in a new build?
