### ISSUE TITLE
CCSA Not Working with CC: Tweaked Computers/Turtles

### ISSUE THREAD

**Issue by thehappybub** [AgriCraft/AgriCraft#1211]
## Quick description
CC: Tweaked computers/turtles do not recognize the Computer Controlled Seed Analyzer as a peripheral.

## Related issues and searches
I listed the issue under the CC: Tweaked GitHub issues page as well. The problem lies in one of the two mods, the question is which one :)

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a6
* InfinityLib: 1.12.0

## Steps to replicate the issue

1. Place down Computer Controlled Seed Analyzer (CCSA)
2. Place a CC: Tweaked Advanced Computer or Turtle on top of the CCSA
3. Open the Computer/Turtle gui (CraftOS 1.8) by right clicking the block
4. Type: "edit startup" click ENTER
5. Type "peripherals.getNames()"
6. Press CTRL and ENTER to save the program.
7. Press and hold CTRL+R for 3 seconds.
8. Screen returns red text saying "attempt to index global 'peripherals' (a nil value)"

This means that the Computer/Turtle does not recognize any peripherals it can wrap to on any of its sides, even though the CCSA is supposed to interface with the Computers/Turtles.

## Your environment

* How are you playing?
  * Operating System: Win 10 Pro 64 bit
  * Launcher: Curse/Twitch
  * Modpack: ATM3-Remix

* Game Modes:
Survival

## Screenshots (or videos)
![2019-02-11_00 59 10](https://user-images.githubusercontent.com/47515626/52549386-76a03300-2d98-11e9-91a2-a135f468a45d.png)

![2019-02-11_00 59 12](https://user-images.githubusercontent.com/47515626/52549387-7869f680-2d98-11e9-8201-6b3fc58ffd9f.png)

![2019-02-11_00 59 16](https://user-images.githubusercontent.com/47515626/52549389-7a33ba00-2d98-11e9-989e-145dd32784cb.png)

![2019-02-11_00 59 30](https://user-images.githubusercontent.com/47515626/52549391-7dc74100-2d98-11e9-85a2-fab195ebd147.png)

**Comment by TDY2012** [comment]
Same problem here in both Survival and Creative mode.

**Comment by ridjack** [comment]
I know this is old, but I'm replying here for anyone coming via Google:

It's **peripheral**, not peripheral**s**. Singular, not plural.

**Comment by RlonRyan** [comment]
Duplicate #572
