### ISSUE TITLE
org.reflections.Reflections

### ISSUE THREAD

**Issue by bookerthegeek** [AgriCraft/AgriCraft#1214]
# Heyo!
Love the mod. Got some pollution in my Server Log. Does not seem to effect game play.

## Related issues
 - #876 
 - #903 
 - I understand that this is technically a duplicate but those are old and closed and this issue submission looks better anywise.

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a6
* InfinityLib: 1.12.0
* [Full Mod List](https://gist.github.com/bookerthegeek/a0f0b398fe9563af2a6e6ffc3cb87444)

## Steps to replicate the issue
1. Start Game
2. Look at log

## Expectations and explanations
For reflection to work

## Your environment
  * Operating System: Windows 10
  * Launcher: MultiMC
  * Modpack: Private
* What kind of server:
  * [X] Singleplayer
  * [x] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
 * [HERE](https://gist.github.com/bookerthegeek/ee51aa80324aaea34129fc5a7fb49e17)

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
