### ISSUE TITLE
Seed Analyzer crashes client when placed on server

### ISSUE THREAD

**Issue by d1kong2** [AgriCraft/AgriCraft#1218]
## Quick description
Seed Analyzer crashes client when placed on server

## Mods and versions used
60 mods

## Your environment
minecraft launcher, remote hosted server
custom pack

## Links to crash logs, stack traces, etc

[crash-2019-03-11_11.46.41-client.txt](https://github.com/AgriCraft/AgriCraft/files/2953384/crash-2019-03-11_11.46.41-client.txt)

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
