### ISSUE TITLE
FTB Revelations: Cross-Breed recipe Missing for Therm.F.

### ISSUE THREAD

**Issue by CraftierUD** [AgriCraft/AgriCraft#1220]
Just simply **missing the crop-breed recipes** for the resource/ore seeds involving **Thermal Foundation** as I notice that the content for them is missing in the mod file. This is for the FTB modpack Revalations (2?) knowing that its not built for it but most mods simply perform better with FTB configurations.

Hopefully theres a simple work around.

**Comment by Ravin890** [comment]
Adding the crossbreeding stuff yourself?
*the crossbreeding isn't hardcoded, its all config files

**Comment by CraftierUD** [comment]
Thing is, Their there but not functioning. I tried matching the scripting to the vanilla ones as of "Mod:Platiolus_plant" to "Platiolus_plant" with no luck.

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
