### ISSUE TITLE
Weeds Overtaking Crops When Not Crossbreeding 

### ISSUE THREAD

**Issue by Spooky-8-Pack** [AgriCraft/AgriCraft#1221]
I was creating a farm, (16 * 18) and had my sprinkler system set up and went to plant. I also had Pams Harvestcraft, so I planted a few vanilla crops (wheat, potatoes, carrots) and Pams crops. I was not crossbreeding, just growing in cropsticks. I leave it alone, come back and almost my entire farm was overtaken with weeds. All the sticks had crops in them, and none were crossbreeding sticks. I should say that this is my first time irrigating with sprinklers, I have never had this problem before but all those farms were irrigated the old fashioned way with water blocks. I also planted Witchery Crops

I used the technic launcher for my mods, on Minecraft 1.7.10, Agricraft version 1.5.0, and Pams Harvestcraft version 1.7.10, Witchery version 1.7.10-0.24.1
I did have quite a few other mods but I don't think they effect the issue here 

I made quite a few searches on how to prevent weeds, or why the weeds were growing but they all referred to when crossbreeding plants and I was not crossbreeding. 

## Your environment

* How are you playing?
  * Operating System: Windows
  * Launcher: Technic 
  * Modpack: WC Tech & Magic Reborn 
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

**Comment by darthvader45** [comment]
1.7.10 is most likely no longer supported.  I'd suggest trying 1.12.2's builds.

**Comment by InfinityRaider** [comment]
Yes, 1.7.10 has no longer been supported since a loooong time now.
