### ISSUE TITLE
Compatibility with Rustic's Fertile Soil and RandomThings Fertilized Dirt

### ISSUE THREAD

**Issue by katubug** [AgriCraft/AgriCraft#1223]
I hit enter too early! Sorry!

## Quick description
Rustic and Random Things both add modded dirts that don't require hydration, cannot be trampled, and the latter grants a growth speed boost. It would be nice if Crop Sticks could be planted on these soils.

**Comment by darthvader45** [comment]
It's all right.  To be perfectly honest, I would like to see these modded dirt types supported.

**Comment by katubug** [comment]
Hey so, I was digging around in the config files and I've found a way to make these modded soils compatible! I have no idea if the RandomThings soil will grant the growth boost to crops on crop sticks, but at least people won't have to replace their entire garden just to add Crop Sticks,

Here are the files that I made:
[soils.zip](https://github.com/AgriCraft/AgriCraft/files/3167323/soils.zip)

**Comment by katubug** [comment]
Just discovered today that you also need to add all those soils to each crop as a valid soil type. I'm not going to upload all my config folders, but it's just a matter of pasting in

>      "farmland_soil",
> 	  "fertilized_dirt_soil",
> 	  "fertile_soil"

**Comment by RlonRyan** [comment]
Closed as related to #1228
