### ISSUE TITLE
"Weeds growth rate" has no effect

### ISSUE THREAD

**Issue by LemADEC** [AgriCraft/AgriCraft#1225]
## Quick description
The "Weed Growth Rate" configuration is ambiguous and has no effect.
The name suggest that increasing the value will make the weed grow *faster*.
The description "The average number of growth ticks for the weed to grow.", suggests that increasing the value will make the weed grow *slower*.
The actual property for this configuration is defaultGrowthChance which is never used.

## Related issues and searches
Code review findings

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a6
* InfinityLib: 1.12.0

## Steps to replicate the issue
n/a

## Expectations and explanations
Remove the dead code/configuration

## Your environment
* How are you playing?
  * Operating System: n/a
  * Launcher: n/a
  * Modpack: n/a
* What kind of server:
  * [x] Singleplayer
  * [x] Multiplayer
* Game Modes:
  * [x] Survival
  * [x] Creative
* Save File:
  * [x] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
n/a

## Screenshots (or videos)
n/a

**Comment by RlonRyan** [comment]
Looks like I moved that setting into the JSON plant files, where now each weed type has it's own rate of growth, so I might as well delete that setting.
