### ISSUE TITLE
Mystical Agricure inferium seeds give same amout of essence

### ISSUE THREAD

**Issue by niklas2233** [AgriCraft/AgriCraft#1226]
## Quick description
all the different tiers of inferium seed give the same amount of essence.

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: AgriCraft-2.12.0-1.12.0-a6.jar
* InfinityLib: infinitylib-1.12.0.jar

## Steps to replicate the issue
1. Loaded up `Minecraft`
2. Placed a `any tier of inferium seeds on cropsticks`
3. Right-clicked with `hand and still get the same amount with every seed` 
4.

## Expectations and explanations
the higher tier the seed is the more essence you are supposed to get

## Your environment
* How are you playing?
  * Operating System: windows 10
  * Launcher: twitch
  * Modpack: Enigmatica 2 expert
* What kind of server:
  * [x] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [x] Survival
  * [ ] Creative
* Save File:
  * [x] Brand new save
  * [ ] Only an existing save

**Comment by darthvader45** [comment]
You mean only 1 essence from any tier?  Probably because the Agricraft crop stick functionality overrides the MysAg seed tier.  Try crossbreeding them if possible, and you should eventually see an increase in essence gains.  Gain 10 is the best, you'll get 10 essence from 1 plant, 2x better than the tier 5 seed.

**Comment by niklas2233** [comment]
Yeah but it removes the whole point of having different tiers of seeds

**Comment by darthvader45** [comment]
Then just plant them on normal farmland.

**Comment by niklas2233** [comment]
No cause then I can't make a 10 10 10 tier 5 seed and get 50 essences per full growth

**Comment by darthvader45** [comment]
Well, why would you want that when it defeats the purpose of different tiers?  I suppose compatibility can be looked into, but idk.

**Comment by niklas2233** [comment]
No it doesn't see Tier 1 fully upgraded seed give 10 essences. Tier 2 seed fully upgraded seed give 20 essences and so on. That just make the gap between tiers bigger

**Comment by RlonRyan** [comment]
For the sake of limited time, I'm going to leave the seeds as-is for the moment, but you are welcome to create new plant JSON files for the different seed tiers and submit them to the [AgriPlants Repo](https://github.com/AgriCraft/AgriPlants) and we can add in the behavior you described that way.
