### ISSUE TITLE
I added a bunch of mod support to my JSONs and thought I'd share.

### ISSUE THREAD

**Issue by katubug** [AgriCraft/AgriCraft#1228]
## Quick description
I used the json config system to add mod support for Biomes O'Plenty, Rustic, and RandomThings. BTW, thank you for making the configs so modular. I absolutely love how customizable it is!

## Related issues and searches
I used some of the fixes from this thread: https://github.com/AgriCraft/AgriCraft/issues/1210 and this thread: https://github.com/AgriCraft/AgriCraft/issues/1222

Credit has been given to the people who came up with the solutions.

## Mods and versions used

* Minecraft: 1.12.2
* AgriCraft: AgriCraft-2.12.0-1.12.0-a6
* InfinityLib: infinitylib-1.12.0
* Rustic: rustic-1.1.0
* Random Things: RandomThings-MC1.12.2-4.2.7.1
* Biomes O Plenty: BiomesOPlenty-1.12.2-7.0.1.2439-universal

However, this should work with slightly different versions, as long as the IDs and texture paths haven't changed.

Here is the file:
[defaults.zip](https://github.com/AgriCraft/AgriCraft/files/3257279/defaults.zip)

I have posted this as an issue instead of making a Pull Request just because I didn't add support for the soils into Mystical Agriculture/Aggraditions, Ars Magica, or Natura. But I can add those and submit a PR if requested.

**Comment by RlonRyan** [comment]
I'd love to add your additional plant files to AgriCraft, however, your provided zip file is invalid.

If you could please upload them as a PR to the [AgriPlants Repo](https://github.com/AgriCraft/AgriPlants) we could merge them in there.
