### ISSUE TITLE
MysticalAgriculture Crops Not Moving To Double Crop Stick

### ISSUE THREAD

**Issue by m5g555** [AgriCraft/AgriCraft#1232]
## Quick description

When I plant a crop in crop sticks, the crop is able to spread to other single crop sticks, but it will not spread to double crop sticks. I have even tried going into the config and changing the spread chance in general to .95 and in the specific config of the seed, I have tried increasing the spread chance of an individual seed. However, it still does not spread to double crop sticks. I have also changed my config to match the one from Project Ozone  3, which I know works.

## Related issues and searches

* https://github.com/AgriCraft/AgriCraft/issues?q=is%3Aissue%20EXAMPLE

## Mods and versions used

* Minecraft: All The Mods 3 for Minecraft 1.12.2
* AgriCraft: 2.12.0-1.12.0- a6 (added after installing the modpack)
* InfinityLib: 1.12.0
* MysticalAgriculture

## Steps to replicate the issue

1. Loaded up Minecraft
2. Placed a single crop stick and a double crop stick next to each other.
3. Right-clicked with Inferium Seed Tier 1 or Iron Seed on single crop stick
4. Waited

## Expectations and explanations
It should have moved over to the double crop stick, but it didnt, even after 15 minutes of waiting.

## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: MultiMC 5
  * Modpack: All The Mods 3 with Agricraft added manually
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [X] Only an existing save

## Links to crash logs, stack traces, etc

Config for both agricraft and tier 1 inferium seeds
https://paste.ee/p/c7xEw

**Comment by flipolipo** [comment]
Same problem

**Comment by TechFish3000** [comment]
Same here, playing on PO3

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
