### ISSUE TITLE
Seed Analyzer might have caused crash

### ISSUE THREAD

**Issue by ZacEllis** [AgriCraft/AgriCraft#1233]
## Quick description
Have come across this crash once before but didn't catch the log, seems to be related to the seed analyzer, extrautils2 was mentioned the first time around too. 

## Related issues and searches
Seed analyzer, Extra Utilities 2 

## Mods and versions used
<details><summary>Mod List (Sorry it's long, I've not creatd a new profile to test this</summary>
<p>

/dank/null	TheRealp455w0rd	DankNull-1.12.2-1.5.71.jar	
AbyssalCraft	Shinoow	AbyssalCraft-1.12.2-1.9.8.jar	
AbyssalCraft Integration	Shinoow	AbyssalCraft Integration-1.12.2-1.8.1.jar	
Actually Additions	Ellpeck	ActuallyAdditions-1.12.2-r148.jar	
Additional Resources	Portablejim	additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar	
AE2 Stuff	bdew	ae2stuff-0.7.0.4-mc1.12.2.jar	
AE2 Wireless Terminal Library	TheRealp455w0rd	AE2WTLib-1.12.2-1.0.30.jar	
AgriCraft	InfinityRaider	AgriCraft-2.12.0-1.12.0-a6.jar	
AI Improvements	DarkGuardsman	AIImprovements-1.12-0.0.1b3.jar	
Akashic Tome	Vazkii_	AkashicTome-1.2-12.jar	
Apotheosis	Shadows_of_Fire	Apotheosis-1.12.2-1.10.2.jar	
AppleCore	squeek502	AppleCore-mc1.12.2-3.2.0.jar	
AppleSkin	squeek502	AppleSkin-mc1.12-1.0.9.jar	
Applied Energistics 2	AlgorithmX2	appliedenergistics2-rv6-stable-6.jar	
ArmorPlus	sokratis12GR	armorplus-1.12.2-11.24.0.60.jar	
Aroma1997Core	Aroma1997	Aroma1997Core-1.12.2-2.0.0.2.b165.jar	
Aroma1997s Dimensional World	Aroma1997	Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b89.jar	
Astral Sorcery	HellFirePvP	astralsorcery-1.12.2-1.10.19.jar	
AttributeFix	DarkhaxDev	AttributeFix-1.12.2-1.0.4.jar	
AutoRegLib	Vazkii_	AutoRegLib-1.3-31.jar	
Avaritia 1.1x	brandon3055	Avaritia-1.12.2-3.3.0.33-universal.jar	
Avaritia Tweaks	Jacky1356400	AvaritiaTweaks-1.12.2-1.1.jar	
B.A.S.E	lanse505	base-1.12.2-3.13.0.jar	
Baubles	Azanor13	Baubles-1.12-1.5.2.jar	
Baubley Heart Canisters	Radient_Sora	baubley-heart-canisters-1.12.2-2.0.3.jar	
BdLib	bdew	bdlib-1.14.3.12-mc1.12.2.jar	
Better Advancements	way2muchnoise	BetterAdvancements-1.12.2-0.1.0.77.jar	
Better Builder's Wands	Portablejim	BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar	
Better Questing	Funwayguy	BetterQuesting-3.5.300.jar	
Better Questing - Standard Expansion	Funwayguy	StandardExpansion-3.4.159.jar	
Better Questing Triggerer	MrAmericanMike	BetterQuestingTriggerer-1.0.jar	
BetterFps	Guichaguri	BetterFps-1.4.8.jar	
BiblioCraft	JDSinclair	BiblioCraft[v2.4.5][MC1.12.2].jar	
BiomeTweaker	superckl	BiomeTweaker-1.12.2-3.2.354.jar	
BiomeTweakerCore	superckl	BiomeTweakerCore-1.12.2-1.0.39.jar	
Blockcraftery	EpicSquid319	blockcraftery-1.12.2-1.3.1.jar	
Blood Magic	WayofTime	BloodMagic-1.12.2-2.4.1-103.jar	
Bonsai Trees	Davenonymous	bonsaitrees-1.1.3-b156.jar	
Bookshelf	DarkhaxDev	Bookshelf-1.12.2-2.3.585.jar	
Botania	Vazkii_	Botania r1.10-361.jar	
Botania: Garden of Glass	Vazkii_	GardenOfGlass.jar	
Brandon's Core	brandon3055	BrandonsCore-1.12.2-2.4.12.205-universal.jar	
Broken Wings	quat1024	brokenwings-2.0.0.jar	
Building Gadgets	direwolf20	BuildingGadgets-2.6.8.jar	
Ceramics	KnightMiner	Ceramics-1.12-1.3.7.jar	
Chameleon	jaquadro	Chameleon-1.12-4.1.3.jar	
Chance Cubes	turkey2349	ChanceCubes-1.12.2-4.0.0.271.jar	
Chicken Chunks 1.8.+	covers1624	ChickenChunks-1.12.2-2.4.1.73-universal.jar	
Chisel	tterrag1098	Chisel-MC1.12.2-0.2.1.35.jar	
Chisels & Bits	AlgorithmX2	chiselsandbits-14.33.jar	
Client Tweaks	BlayTheNinth	ClientTweaks_1.12.2-3.1.11.jar	
Clumps	Jaredlll08	Clumps-3.1.2.jar	
CodeChicken Lib 1.8.+	covers1624	CodeChickenLib-1.12.2-3.2.2.353-universal.jar	
CoFH Core	TeamCoFH	CoFHCore-1.12.2-4.6.3.27-universal.jar	
CoFH World	TeamCoFH	CoFHWorld-1.12.2-1.3.1.7-universal.jar	
Compacter	bdew	compacter-1.3.0.3-mc1.12.2.jar	
ConnectedTexturesMod	tterrag1098	CTM-MC1.12.2-0.3.3.22.jar	
ContentTweaker	Jaredlll08	ContentTweaker-1.12.2-4.9.1.jar	
Controlling	Jaredlll08	Controlling-3.0.7.jar	
Cooking for Blockheads	BlayTheNinth	CookingForBlockheads_1.12.2-6.4.71.jar	
Corail Tombstone	Corail_31	tombstone-3.5.5-1.12.jar	
Crafting Tweaks	BlayTheNinth	CraftingTweaks_1.12.2-8.1.9.jar	
CraftTweaker	Jaredlll08	CraftTweaker2-1.12-4.1.19.jar	
CreativeCore	CreativeMD	CreativeCore_v1.9.45_mc1.12.2.jar	
Cucumber Library	BlakeBr0	Cucumber-1.12.2-1.1.3.jar	
Cyclops Core	kroeser	CyclopsCore-1.12.2-1.4.0.jar	
Dark Utilities	DarkhaxDev	DarkUtils-1.12.2-1.8.226.jar	
Diet Hoppers	RWTema	diethopper-1.1.jar	
Dimensional Edibles	Jacky1356400	DimensionalEdibles-1.12.2-1.3.1.jar	
DiscordSuite	HRZNStudio	DiscordSuite-2.2.4.jar	
Draconic Evolution	brandon3055	Draconic-Evolution-1.12.2-2.3.22.343-universal.jar	
ElecCore	Elec332	ElecCore-1.12.2-1.9.452.jar	
Embers Rekindled	BordListian	EmbersRekindled-1.13-hotfix2.jar	
Ender IO	CrazyPants_MC	EnderIO-1.12.2-5.0.46.jar	
Ender IO Endergy	tterrag1098	EnderIO-endergy-1.12.2-5.0.46.jar	
Ender Storage 1.8.+	covers1624	EnderStorage-1.12.2-2.4.5.135-universal.jar	
Ender Tweaker	Shadows_of_Fire	EnderTweaker-1.12.2-1.1.7.jar	
EnderCore	tterrag1098	EnderCore-1.12.2-0.5.59.jar	
Enderman Evolution	TheRealp455w0rd	EndermanEvolution-1.12.2-1.0.29.jar	
Epic Siege Mod	Funwayguy	EpicSiegeMod-13.164.jar	
Equivalent Integrations	pkmnfrk	EquivalentIntegrations-0.4.6.jar	
Ex Nihilo: Creatio	BloodWorkXGaming	exnihilocreatio-1.12.2-0.4.5.jar	
Expanded Equivalence	Zeitheron	ExpandedEquivalence-1.12.2-12r.jar	
Extended Crafting	BlakeBr0	ExtendedCrafting-1.12.2-1.5.4.jar	
Extra Utilities	RWTema	extrautils2-1.12-1.9.9.jar	
ExtraCells2	Destroyer7128	ExtraCells-1.12.2-2.6.2a.jar	
ExtraPlanets	MJRLegends	ExtraPlanets-1.12.2-0.5.3.jar	
Farming for Blockheads	BlayTheNinth	FarmingForBlockheads_1.12.2-3.1.28.jar	
FastWorkbench	Shadows_of_Fire	FastWorkbench-1.12.2-1.7.2.jar	
FoamFix for Minecraft	asiekierka	foamfix-0.10.5-1.12.2.jar	
Forge MultiPart CBE	covers1624	ForgeMultipart-1.12.2-2.6.1.81-universal.jar	
FTB Library	FTB	FTBLib-5.4.3.125.jar	
FTB Utilities	FTB	FTBUtilities-5.4.0.100.jar	
FTB Utilities: Backups	LatvianModder	FTBUtilitiesBackups-1.0.0.4.jar	
Furnace Overhaul	TheCazadorSniper	FurnaceOverhaul-1.12.2-2.2.0.jar	
Galacticraft Tweaker	MJRLegends	GalacticraftTweaker-1.12.2-1.0.3.jar	
Hammer (Lib) Core	Zeitheron	HammerCore-1.12.2-2.0.4.7.jar	
Hunting Dimension	DarkhaxDev	HuntingDimension-1.12.2-1.0.39.jar	
Hwyla	TehNut	Hwyla-1.8.26-B41_1.12.2.jar	
Immersive Engineering	BluSunrize	ImmersiveEngineering-0.12-89.jar	
Immersive Petroleum	theFlaxbeard	immersivepetroleum-1.12.2-1.1.9.jar	
Industrial Foregoing	Buuz135	industrialforegoing-1.12.2-1.12.12-236.jar	
InfinityLib	InfinityRaider	infinitylib-1.12.0.jar	
InstantUnify	KidsDontPlay	instantunify-1.12.2-1.1.2.jar	
Integration Foregoing	Jacky1356400	IntegrationForegoing-1.12.2-1.9.jar	
Inventory Tweaks	Kobata	InventoryTweaks-1.63.jar	
Iron Chests	progwml6	ironchest-1.12.2-7.0.69.845.jar	
JourneyMap	techbrew	journeymap-1.12.2-5.5.4.jar	
Just Enough Energistics (JEE)	TheRealp455w0rd	JustEnoughEnergistics-1.12.2-1.0.7.jar	
Just Enough Items (JEI)	mezz	jei_1.12.2-4.15.0.285.jar	
Just Enough Petroleum	BordListian	JustEnoughPetroleum-0.1.jar	
Karat Garden	MrAmericanMike	KaratGarden-0.1.4-[1.12.2].jar	
KleeSlabs	BlayTheNinth	KleeSlabs_1.12.2-5.4.12.jar	
Knob Control	Kashdeya	knobcontrol-1.12-4.0.20.jar	
Land Craft	landmaster_phuong0429	landcraft-2.3.0.2.jar	
LandCore	landmaster_phuong0429	landcore-1.5.0.1.jar	
LibraryEx	LogicTechCorp	LibEx-1.12.2-1.0.8.jar	
LootBags	Malorolam	LootBags-1.12.2-2.5.8.5.jar	
LootTableTweaker	DarkhaxDev	LootTableTweaker-1.12.2-1.1.14.jar	
Lord Craft	Cobbs_3	Lord Craft 2.9.16.jar	
LunatriusCore	Lunatrius	LunatriusCore-1.12.2-1.2.0.42-universal.jar	
Magneticraft	cout970	Magneticraft_1.12-2.6.5-dev.jar	
ManaVisualizer	ExtraMeteorP	ManaVisualizer-r1.0-1.jar	
Mantle	mDiyo	Mantle-1.12-1.3.3.55.jar	
Mapmaker's Gadgets	Tmtravlr	Mapmaker's Gadgets-1.2_for_1.12.x.jar	
McJtyLib	McJty	mcjtylib-1.12-3.5.3.jar	
MCMultiPart	amadornes	MCMultiPart-2.5.3.jar	
Mekanism	aidancbrady	Mekanism-1.12.2-9.7.8.379.jar	
Mekanism Generators	aidancbrady	MekanismGenerators-1.12.2-9.7.8.379.jar	
Mekanism Tools	aidancbrady	MekanismTools-1.12.2-9.7.8.379.jar	
Mike's Mods Library	pkmnfrk	MikesModsLib-1.0.2.jar	
MJRLegends Lib	MJRLegends	MJRLegendsLib-1.12.2-1.1.8.jar	
Mob Grinding Utils	vadis365	MobGrindingUtils-0.3.13.jar	
Mod Name Tooltip	mezz	modnametooltip_1.12.2-1.10.0.jar	
ModelLoader	cout970	modelloader-1.1.6.jar	
ModTweaker	Jaredlll08	modtweaker-4.0.17.jar	
Modular Diversity	BordListian	Modular Diversity-1.6-hotfix.jar	
Modular Machinery	HellFirePvP	modularmachinery-1.12.2-1.10.0.jar	
Moo Fluids	TheRoBrit	MooFluids-1.12.2-1.8.12.02a.jar	
More Overlays	feldim2425	moreoverlays-1.14-mc1.12.2.jar	
Morph-o-Tool	Vazkii_	Morph-o-Tool-1.2-21.jar	
Mouse Tweaks	YaLTeR97	MouseTweaks-2.10-mc1.12.2.jar	
MPUtils	GenDeathrow	MPUtils-1.12.2-1.5.7.jar	
MPUtils Basic Tools	GenDeathrow	mpbasic-1.12.2-1.4.11.jar	
MrTJPCore	Mr_TJP	MrTJPCore-1.12.2-2.1.3.35-universal.jar	
MTLib	Jaredlll08	MTLib-3.0.6.jar	
Mystical Agradditions	BlakeBr0	MysticalAgradditions-1.12.2-1.3.2.jar	
Mystical Agriculture	BlakeBr0	MysticalAgriculture-1.12.2-1.7.5.jar	
Mystical Agriculture Tiered Crystals	Electrolyte	matc-1.0.1-hotfix.jar	
MysticalLib	EpicSquid319	mysticallib-1.12.2-1.3.0.jar	
Natura	mDiyo	natura-1.12.2-4.3.2.69.jar	
Neat	Vazkii_	Neat 1.4-17.jar	
Netherending Ores	ic_trab	Netherending-Ores-1.12.2-1.3.jar	
NotEnoughIDs	fewizz	NotEnoughIDs-1.5.4.4.jar	
NuclearCraft	tomdodd4598	NuclearCraft-2.17a-1.12.2.jar	
OMLib	Keridos15	omlib-1.12.2-3.1.3-246.jar	
Open Modular Passive Defense	Keridos15	ompd-1.12.2-3.1.0-61.jar	
OpenBlocks	OpenMods	OpenBlocks-1.12.2-1.8.1.jar	
Overloaded	cjm721	Overloaded-1.12.2-0.0.58.jar	
Overloaded Armor Bar	tfarecnim	overloadedarmorbar-1.0.4g.jar	
p455w0rd's Library	TheRealp455w0rd	p455w0rdslib-1.12.2-2.2.151.jar	
PackMode	Sky_Som	packmode-1.12.2-1.2.0.jar	
Pam's HarvestCraft	MatrexsVigil	Pam's HarvestCraft 1.12.2zd Surprise for Yogcast.jar	
Phosphor	jellysquid_	phosphor-1.12.2-0.2.4+build46-universal.jar	
Placebo	Shadows_of_Fire	Placebo-1.12.2-1.6.0.jar	
PlusTiC	landmaster_phuong0429	plustic-7.0.7.0.jar	
PneumaticCraft: Repressurized	desht	pneumaticcraft-repressurized-1.12.2-0.11.3-366.jar	
Portality	Buuz135	portality-1.12.2-1.2.3-15.jar	
Project EX	LatvianModder	ProjectEX-1.2.0.36.jar	
Project Intelligence	brandon3055	ProjectIntelligence-1.12.2-1.0.5.21-universal.jar	
Project Red - Base	Mr_TJP	ProjectRed-1.12.2-4.9.1.92-Base.jar	
Project Red - Mechanical	Mr_TJP	ProjectRed-1.12.2-4.9.1.92-mechanical.jar	
Project Red - World	Mr_TJP	ProjectRed-1.12.2-4.9.1.92-world.jar	
ProjectE	sinkillerj	ProjectE-1.12.2-PE1.4.1.jar	
QuantumFlux	FantasyTeddy	quantumflux-1.12.2-2.0.18.jar	
QuantumStorage	Gigabit1011	QuantumStorage-1.12-4.6.8.jar	
Quark	Vazkii_	Quark-r1.5-167.jar	
Random Things	lumien231	RandomThings-MC1.12.2-4.2.7.2.jar	
RandomPatches	TheRandomLabs	randompatches-1.12.2-1.17.1.0.jar	
ReAuth	TechnicianLP	reauth-3.6.0.jar	
Reborn Core	modmuss50	RebornCore-1.12.2-3.13.12.447-universal.jar	
Redstone Arsenal	TeamCoFH	RedstoneArsenal-1.12.2-2.6.3.18-universal.jar	
Redstone Flux	TeamCoFH	RedstoneFlux-1.12-2.1.0.6-universal.jar	
Reliquary v1.3	P3pp3rF1y	Reliquary-1.12.2-1.3.4.786.jar	
Resource Loader	lumien231	ResourceLoader-MC1.12.1-1.5.3.jar	
RFTools	McJty	rftools-1.12-7.71.jar	
RFTools Control	McJty	rftoolsctrl-1.12-2.0.2.jar	
RFTools Dimensions	McJty	rftoolsdim-1.12-5.71.jar	
RiteClicker Mod	OCDiary	riteclicker-1.12.2_2.jar	
Rock Candy	Radient_Sora	rockcandy-1.12.2-3.0.0.jar	
Shadowfacts' Forgelin	shadowfactsmc	Forgelin-1.8.3.jar	
Simple Sponge	Jacky1356400	SimpleSponge-1.12.2-3.6.2.jar	
Simple Void World	modmuss50	Simple-Void-World-1.12-1.2.0.9-universal.jar	
Simply Jetpacks 2	Tomson124	SimplyJetpacks2-1.12.2-2.2.12.65.jar	
SkyLandsForge	Asd1995sse	SkyLandsForge-1.12.2_0.2.jar	
Solar Flux Reborn	Zeitheron	SolarFluxReborn_1.12.2-4.32r.jar	
Soot	BordListian	Soot-1.6.jar	
Stackie	Lunatrius	Stackie-1.12.2-1.6.0.48-universal.jar	
Stacksize	wwrpg	stacksize-1.12.2-1.0.jar	
Storage Drawers	jaquadro	StorageDrawers-1.12.2-5.3.8.jar	
TamModized	Tamaized	TamModized-1.12.1-0.15.5.jar	
TESLA	DarkhaxDev	Tesla-1.12.2-1.0.63.jar	
Tesla Core Lib	Face_of_Cat	tesla-core-lib-1.12.2-1.0.15.jar	
Teslafied	TheRealp455w0rd	teslafied-1.12-1.1.1.jar	
The Twilight Forest	Benimatic	twilightforest-1.12.2-3.8.689-universal.jar.bak	
TheDragonLib	sokratis12GR	thedragonlib-1.12.2-5.3.0.jar	
Tinkers Construct	mDiyo	TConstruct-1.12.2-2.12.0.157.jar	
Tinkers' Complement	KnightMiner	TinkersComplement-1.12.2-0.4.2.jar	
Tinkers' Tool Leveling	bonusboni	TinkerToolLeveling-1.12.2-1.1.0.jar	
Tiny Progressions	Kashdeya	tinyprogressions-1.12.2-3.3.34-Release.jar	
Toast Control	Shadows_of_Fire	Toast Control-1.12.2-1.8.1.jar	
Translocators 1.8.+	covers1624	Translocators-1.12.2-2.5.1.77-universal.jar	
Tweakers Construct	RCXcrafter	tweakersconstruct-1.12.2-1.5.1.jar	
Twerk Sim 2K16	Funwayguy	TS2K16-1.2.10.jar	
Unforgiving Void	The_Fireplace	UnforgivingVoid-1.12.2-1.0.2.jar	
UniDict	WanionCane	UniDict-1.12.2-2.9.2.jar	
Unloader	Unnoen	unloader-1.2.0.jar	
VanillaFix	Runemoro	VanillaFix-1.0.10-99.jar	
VoidCraft	Tamaized	VoidCraft-1.12-0.26.10.jar	
Waila Harvestability	squeek502	WailaHarvestability-mc1.12-1.1.12.jar	
WaitingTime	Jaredlll08	WaitingTime-1.0.1.jar.disabled	
WanionLib	WanionCane	WanionLib-1.12.2-2.2.jar	
Wasaila	Mrbysco	Wasaila-1.0.jar	
Wawla - What Are We Looking At	DarkhaxDev	Wawla-1.12.2-2.5.273.jar	
Waystones	BlayTheNinth	Waystones_1.12.2-4.0.72.jar	
Wireless Crafting Terminal	TheRealp455w0rd	WirelessCraftingTerminal-1.12.2-3.12.93.jar	
Woot	Ipsis	woot-1.12.2-1.4.11.jar	
XCPatch	Shadows_of_Fire	XCPatch-1.12.2-1.0.1.jar	
XNet	McJty	xnet-1.12-1.8.1.jar	
YABBA	LatvianModder	YABBA-1.1.2.53.jar	
YNot	asiekierka	YNot-0.2.4.jar	
ZeroCore	ZeroNoRyouki	zerocore-1.12.2-0.1.2.8.jar

</p>
</details>

## Steps to replicate the issue
I have not been able to deliberately replicate, has only happened twice and I didn't catch the log the first time.

## Your environment
* How are you playing?
  * Operating System: Win10
  * Launcher: Twitch
  * Modpack: Project Ozone 3 v3.0.41
* What kind of server:
  * Singleplayer
* Game Modes:
  * Survival
  * Creative
* Save File:
  * Only an existing save

## Links to crash logs, stack traces, etc
https://paste.dimdev.org/ewusazaxog.mccrash

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
