### ISSUE TITLE
Config-related suggestions regarding Water Tanks and Computer-Controlled Seed Analyzer

### ISSUE THREAD

**Issue by katubug** [AgriCraft/AgriCraft#1239]
##  Quick description
I would love a config option to disable the Computer-Controlled Seed Analyzer, as well as Wooden Water Tanks. Also, there are some config options that do not seem to affect anything in game as of now?

## Related issues and searches
None that I was able to find with a quick search for "analyzer" or "config."

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: AgriCraft-2.12.0-1.12.0-a6
* InfinityLib: infinitylib-1.12.0

## Expectations and explanations
I currently have
```
    # Set to true if you want to enable irrigation systems. [default: true]
    B:"Enable Irrigation"=false
```
In my config. It does not disable Water Tanks, but there is no additional config to disable them. I would have assumed they'd be disabled with the rest of the irrigation, but if not, a separate option would be nice. Also a minor note, but I would love the ability to show only one Tank/Channel/etc in JEI, similar to the way Tinker's Construct does it with their Tool Forge and Part options. Otherwise searching "planks" in JEI is swamped with procedurally generated irrigation-related items.

Additionally, the Computer-Controlled Seed Analyzer does not have an option to be disabled.

Finally, I see two config options for "seed storage systems/warehouses," which I thought might have been related to the Analyzer, since I don't see any seed storage blocks in JEI at all. However, setting them to false did not remove the Analyzer, so I guess I was mistaken. It's very likely you already know about this issue, but I thought I would mention, just in case.

**Comment by InfinityRaider** [comment]
That config option was indeed broken.

Closing since we are moving to 1.16.
