### ISSUE TITLE
broken compatibility with Forestry farms

### ISSUE THREAD

**Issue by BorisMulder** [AgriCraft/AgriCraft#1240]
also see https://github.com/ForestryMC/ForestryMC/issues/2189

In short, Forestry multifarms no longer harvest Agricraft crops in 1.12 versions. I don't know if this issue is on your side or on theirs. Is there any code that was changed in such a way that it could break compatibility?

I tested it with AgriCraft 2.12.0 and Forestry 5.8.2.387 on the Infitech3 modpack.

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
