### ISSUE TITLE
[SUGGESTION] JEI Cleanup

### ISSUE THREAD

**Issue by Omegapsychosis** [AgriCraft/AgriCraft#1245]
When utilizing AgriCraft along with mods that add many wood types (Forestry, Biomes O'Plenty, etc) JEI can become cluttered very quickly. 

I tried using JEI hide mode to hide things like the irrigation channels, watertanks, etc., however doing so results in every one of a type being hidden. I would like at least 1 default one, such as oak, to be available for the recipe viewing.

I had a similar issue with Tinker's Construct and the tables, but using JEI hide from the menu allows you to hide -all- of the items by wildcard, and then un-hide 1 so the recipe can still be viewed, just without clutter. 

I am not sure of how this can be achieved, but I do know it has been done. I just know I and many others dislike having JEI overwhelmed with 5000 recipes for 1 block, just with different wood types.

**Comment by katubug** [comment]
@Omegapsychosis This is something I've been wanting as well. You say you know it's been done - with AgriCraft or with another mod? If you've seen someone hide the AgriCraft irrigation stuff from JEI I could probably reverse engineer it and get you a solution.

**Comment by Omegapsychosis** [comment]
I've seen it done but not with AgriCraft.

Tinker's Construct adds tables for all kinds of wood types, you can hide them all but then enable only 1 variation in JEI, say Oak. All others are still craftable, just the clutter is gone.

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
