### ISSUE TITLE
Current/best 1.12.2 version?

### ISSUE THREAD

**Issue by Carnaxus** [AgriCraft/AgriCraft#1246]
Just wondering which if any of the "releases" is the current or best 1.12.2 version of the mod, since Curseforge only has a single file, and it's for 1.7.10.

**Comment by TehNut** [comment]
https://www.curseforge.com/minecraft/mc-mods/agricraft/files/2609648

**Comment by Skipper-is** [comment]
Except that release doesn't seem to have a functioning seed storage, and the trowel deletes itself if you put it in the analyser, and resets growth when you pot on a plant....

**Comment by katubug** [comment]
In fairness, it does warn you that the mod is in alpha. Bugs are to be expected.

**Comment by InfinityRaider** [comment]
"Best version" is highly subjective based on what you want to do with the mod and in which pack you use it.
As Katabug mentioned, the 1.12 branch has never reached a release which we considered as being stable enough to be labelled as release.
