### ISSUE TITLE
Suggestion: Allow growth boost/harvest boost per soil

### ISSUE THREAD

**Issue by katubug** [AgriCraft/AgriCraft#1248]
Hi, I know you're on an indefinite hiatus at the moment, but in case you ever come back to this, I wanted to make a suggestion. If there was a way to define in the soil jsons how quickly the crops should grow, and if there should be any boost to the amounts harvested, that would be rad.

A lot of mods add soils with beneficial effects - those being the two most common. As of now, I can make those soils *compatible* with Crop Sticks, but to my knowledge they don't apply their affect to the plants put on them. So we have to choose between using crop sticks and soils with boosts - which, ultimately, isn't a *huge* deal. It'd just be a nice option to have.

Thank you for your time!

**Comment by InfinityRaider** [comment]
Might be relevant to consider for the 1.16 rewrite.
Thanks for the suggestion

**Comment by InfinityRaider** [comment]
Soil growth modifiers have been implemented, I do not like the soil influencing the number of fruits though, so I have not implemented that.

Thanks again for the suggestion.

**Comment by darthvader45** [comment]
Agreed, best to leave it to the crop's Gain stat.
