### ISSUE TITLE
Some modded resource crops requirements to grow, breed and mutate can be bypassed

### ISSUE THREAD

**Issue by darkaxel1989** [AgriCraft/AgriCraft#1249]
## Quick description
Modded ores to crossbreed and grow "ore crops" can be used instead of one another. For example, use copper ores for growing Niccisius (nickel crop) or jalousmine (aluminum crop, sorry if I'm writing them wrong). Vanilla ores work as intended. Iron only grows Ferranum, and Ferranum doesn't grow on any other modded or vanilla ore. Gold ore and crop also working properly.

## Mods and versions used
Agricraft 2.12.0 1.12.0-a6
Thermal Foundation and its child mods.
Version of this or other mods doesn't change anything, behaviour stays the same.
InfinityLib 1.12.0

## Steps to replicate the issue
1) Place any modded ore (from thermal foundation) on the ground
2) Place gravel on the ground
3) Place crop sticks on the ground
4) Place a crop that yields modded metals that doesn't match the ore placed on step 1.
5)  Crop will grow like it would with the proper ore.

## Expectations and explanations
I would expect crops with the wrong ores NOT to grow at all. And not to mutate on the wrong ore.

## Your environment

* How are you playing?
  * Operating System: Windows
  * Launcher: Twitch
  * Modpack: Custom
* What kind of server:
  * Singleplayer
  * Multiplayer not tested, but probably will work.
* Game Modes:
  * Survival
  * Creative

Additional info:
I didn't try every possible combination with every possible crop, ore and mod, but until now that's what I've discovered:

1) This appears to be only related to **metal ores** from **Thermal Foundation**. No shale oil ores or energized netherrack or destabilized redstone ores will allow to grow crops.

2) Only crops that grow **Thermal foundation metals** are affected, things like Osmium seeds don't grow on wrong ores.

3) For some reason, **Petinia seeds work as intended**. **Tin ore** however does not, and it will let grow other seeds.

That's all as far as I can tell. I tried other mods, like Immersive engineering, advanced rocketry and forestry ores and it seems they all worked as intended. I could have missed something anyway, so don't take my word for it.

**Comment by RlonRyan** [comment]
This might be an oredict isssue, but more likely an incomplete JSON definition.

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
