### ISSUE TITLE
EX2 Item Searching stops working when Seed Analyzer is in range

### ISSUE THREAD

**Issue by Rafii2198** [AgriCraft/AgriCraft#1250]
## Quick Summary:
As in title: When there is ***Seed analyzer*** in range of ***Item searching*** from Extra Utilities 2 it stops working.
## Mods Used:
I am playing on Project Ozone 3 which is big modpack but this issue is just about Agricraft(ver. 2,12,0-1,12,0-a6) and Extra Utilities 2(ver. 1.9.9) anyways.
## Server Console:
When anyone is hitting T nearby Analyzer this shows in *server console*:
- https://hastebin.com/equqaqijes.pl
It is not crashing the server or anything it just gives error message.

Full log is too big but there is nothing more relating this issue from what I saw.

**Comment by murmanox** [comment]
I noticed this too on Project Ozone 3.

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
