### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ddteam90** [AgriCraft/AgriCraft#1251]
https://paste.dimdev.org/mixagevizi.mccrash

**Comment by darthvader45** [comment]
What version are you using here?  If not the latest, you should download the latest version.  Discord might have a newer version on the Agricraft server.

**Comment by ddteam90** [comment]
Link?

**Comment by darthvader45** [comment]
https://discordapp.com/invite/9qfhaWc

**Comment by ddteam90** [comment]
48 / 10000
АНГЛИЙСКИЙ
Перевести вGoogleBing
Okay, I'm in discord, but where can I find the mod itself?

**Comment by ddteam90** [comment]
Okay, I'm in discord, but where can I find the mod itself?

**Comment by darthvader45** [comment]
There's the mod-support chennel.  It's for any of InfinityRaider's mods, which includes Agricraft.
