### ISSUE TITLE
[Suggestion] Alter location server configs are stored

### ISSUE THREAD

**Issue by Darkosto** [AgriCraft/AgriCraft#1252]
Hello,

Is it possible to reevaluate where server configs are stored and what information is given? Currently in 1.12.2 Agricraft, the server IP is displayed as the folder name for every server you have connected to? Can this information be stored outside of the config folder? Or, if that is not possible, can the IP not be visible? 

This honestly makes it difficult for me to work with the mod, as I do not want server IP's to be seen for privacy reasons. 

Thanks for your consideration. Have a great day!
Darkosto

**Comment by RlonRyan** [comment]
Without the server IPs there is no good way of tracking what jsons came from where, or when differential downloads need to take place.

**Comment by InfinityRaider** [comment]
@Darkosto, why is this problematic to you exactly? These config directories are only generated when a client connects to this server, therefore the user is already aware of what the IP address of the server is...
