### ISSUE TITLE
Seeds Duping

### ISSUE THREAD

**Issue by Digimasterhir0** [AgriCraft/AgriCraft#1253]
Hi! I found a nasty bug!

Steps:
1. Grow any crop on crop sticks
2. Use clipper on the crop to get a clippling
3. Analyse the clippling in the Seed Analyzer
4. The result is a seed, plant it. 100% success planting of clipplings achieved!

* Minecraft - 1.12.2
* AgriCraft - 2.12.0-1.12.0-a6
* InfinityLib - infinitylib-1.12.0

**Comment by sproga2** [comment]
Successfully replicated in Forge 1.12.2-14.23.5.2847, AgriCraft 2.12.0-1.12.0-a6, InfinityLib 1.12.0. Looks like this isn't a one-off.

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
