### ISSUE TITLE
Computer Controlled Seed Analyser not working with Open Computers

### ISSUE THREAD

**Issue by littleoz2** [AgriCraft/AgriCraft#1254]
## Quick description
I have tried using the Computer Controlled Seed Analyser with Open Computers and it doesn't seem to be working, I have tried connecting the Computer up via an Adapter as well as having a robot sitting ontop of the block, but when I run "component.list()" in lua on the Computer, the CCSA doesn't show up.

## Mods and versions used
AgriCraft
OpenComputers

## Steps to replicate the issue
1. Setup OpenComputers computer or Robot
2. Place adapter next to CCSA or robot on top
3. Run lua -> component.list()

## Expectations and explanations
Trying to automate the breeding of seeds using the Computer Controlled Seed Analyser

## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: Twitch Launcher
  * Modpack: Project Ozone 3
* What kind of server:
  * [X] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [X] Only an existing save

## Links to crash logs, stack traces, etc
No Crash logs

**Comment by fraenkelc** [comment]
This might be as simple as a wrong modid.
OpenComputers lists it mod id as "opencomputers"
https://github.com/MightyPirates/OpenComputers/blob/a7eb1db087be0093e216b58f977af23810f63f41/src/main/scala/li/cil/oc/OpenComputers.scala#L16-L20

The reference in this mod is "open_computers" though
https://github.com/AgriCraft/AgriCraft/blob/bc6a73efec879a637e97db0df937bb55848bb44c/src/main/java/com/infinityraider/agricraft/tiles/TileEntityPeripheral.java#L21-L22

**Comment by cenodis** [comment]
I tried building it with the changes @fraenkelc proposed but OC still does not recognize the analyzer as a component. Neither cable nor adapter work. It might be part of the issue but theres another problem somewhere else. Unfortuantely the game log does not give me any indication of whats wrong.

**Comment by fraenkelc** [comment]
Turns out I was not the first to look at this, see #1260 for a working fix (as it lists, it also needs a fix in infinitylib)

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
