### ISSUE TITLE
missing potato seeds?

### ISSUE THREAD

**Issue by gallifreyhanyou** [AgriCraft/AgriCraft#1255]
## Quick description
Despite spending many minutes and multiple in-game days I am unable to find any potato seeds. Only wheat seeds drop from grass. No carrot seeds drop either but it seems that you can now crossbreed them in 1.12.2.

## Mods and versions used
I have pulled and run agricraft by itself and there are no potato seeds. confirmed. there is no interplay between other mods in my pack.
* Minecraft: 1.12.2 Forge version 14.23.5.2847
* AgriCraft: 2.12.0-1.12.0-a6
* InfinityLib: 1.12.0
* Agriseasons: 1.0.2
* Micdoodle8 core
* Applecore: 3.2.0
* JEI: 4.15.0.289
* Appleskin: 1.0.9
* Bibliocraft: 2.4.5
* Mantle: 1.3.3.55
* Tinker's Construct: 1.12.2-2.12.0.157
* CompatSkills: 1.17.0
* Lieutenant: 1.3
* Pam's Harvestcraft: 1.12a
* Tough As Nails: 3.1.0
* Extra TAN: 4.0.83
* Galacticraft (core and planets) : 4.0.2.237
* WASAILA: 1.0
* WAILA: 1.8.26
* LunatriusCore: 1.2.0.42
* Ingame Info XML: 2.8.2.94
* InGame Info XML addon for SS: 1.0.0.1
* Serene Seasons: 1.2.17
* Just Enough Harvestcraft: 1.6.4
* Ordinary Coins: 1.5
* Realistic Torches: 1.12.2-2.1.1
* Rikmuld's Core: 1.3.3
* The Spice of Life: 1.3.12
* The Camping Mod 2: 2.4.3
* TombManyGraves: 1.12-4.2.0
* TombManyGraves2API: 1.12-1.0.0
* TombManyPlugins Galacticraft: 1.0.0
* Waystones: 4.0.72
* Xaero's Minimap: 1.18.1
* Xaero's World Map: 1.4.10.1
apologies for the ridiculous list, I'm putting together a modpack for a future server!

## Steps to replicate the issue
punch grass for a total of over 30 minutes, both with and without JSON file override of grass drops. only vanilla wheat seeds will drop.

## Expectations and explanations
I have only recently upgraded from 1.7.10 modded to 1.12.2, and I know some things have changed. I am used to seeing carrot, wheat and potato seeds drop from grass when it is cleared. however, carrot and potato seeds no longer drop. while carrot seeds can now be produced by mutation, potato seeds can't, and they can't be obtained by any crafting recipe I can find either. this makes potatoes completely impossible to farm if vanilla farming is disabled, which I intend it to be in my modpack. 

## Your environment
* How are you playing?
  * Operating System: Windows 10
  * Launcher: Java?
  * Modpack: a mess of my own making to be named "HubCraft"
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [X] Brand new save
  * [X] Only an existing save (first noticed on existing, started new world to verify)

**Comment by darthvader45** [comment]
Huh, well I can suggest a workaround for now:  Locate a village, harvest some potatoes/carrots, then craft a few into seeds.

**Comment by gallifreyhanyou** [comment]
> and they can't be obtained by any crafting recipe I can find either.

I'm guessing you skimmed the report and didn't notice that part? if there was a workaround like that (which I did already try with both carrots and potatoes upon noticing the missing seeds) I wouldn't have even reported this bug most likely. there is simply no way outside of creative mode to obtain seeds for these two crops. I assume this was the intention, to make potato seeds craftable or in some way mutatable, but it simply was forgotten. I don't have the coding knowledge to use crafttweaker or some similar mod to fix it myself and frankly I'm happy to just wait for a fix before rolling it out on multiplayer. I'm glad I was able to catch it myself this soon. I work full time anyway, so it's hardly urgent! :) and besides, if I'm having this issue, odds are a lot of other people might be too, and they're either just vanilla farming as a workaround (which I'll also do for now, I suppose, although this obviously also locks out mutation progression without the seeds) or using creative or the give command to cheat in the seeds.

**Comment by darthvader45** [comment]
Luckily for you, the /ctgui craftingtable command is made for you.  Just type it in, and you can use a gui to code in your recipes.

**Comment by RlonRyan** [comment]
You can plant potatoes in crops without needing the seed. Same goes for carrots. Both are defined as seed items in the agricraft jsons, unless if a custom modpack has changed the JSON files. Once the items have been planted in the crops they should automatically convert to a seed.
