### ISSUE TITLE
Agricraft/Wawla

### ISSUE THREAD

**Issue by InahoKaizuka76** [AgriCraft/AgriCraft#1261]
Hi, help me please.

I add Wawla and Hwyla mods, and I can't see full information in crop stics
![2020-01-13_00 43 54](https://user-images.githubusercontent.com/59807155/72226079-e2d57900-359d-11ea-8839-52e3732851d8.png)

**Comment by PurpleHel** [comment]
There's a mod for that. https://www.curseforge.com/minecraft/mc-mods/wasaila

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.

**Comment by PurpleHel** [comment]
ooooo, you're moving to 1.16?! yaya! please be at least 1.16.4 compatible! I know 1.16.5 is the newest, but none of the big mods (quark, BOP, etc) are on it yet.
