### ISSUE TITLE
Journal Suggestion?

### ISSUE THREAD

**Issue by Rithenar** [AgriCraft/AgriCraft#1263]
## Quick description
I am using 2 separate stations to analyze seeds and didn't think in advance to put 2 journals. Is there already a way, or if not could it possibly be implemented, to save all advancements to a book regardless on which analyzer it is used? Similar to other mods that use books to save progress, the research and discoveries could be saved in a file and update the Journal with that instead of the analyzer

## Related issues and searches

I have not been able to find much on the issue. Only one post that mentioned it also stated that the Journal is redundant with JEI

## Mods and versions used

* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a6
* InfinityLib: 1.12.0
* [List the other required mods here]

## Steps to replicate the issue

1. Put a seed in one analyzer
2. Put a different seed in a different analyzer
3. The analyzer with the Journal records the seed, but the seed analyzed in a different analyzer is not recorded
4. Same if you forget to put the Journal in the analyzer and discover a seed

## Expectations and explanations

My expectation is that the progress is saved for the player and not on a per-journal basis with a way to update the Journal with all the player discoveries on mutations regardless on which seed analyzer they were processed

## Your environment

* How are you playing?
  * Operating System: Win10
  * Launcher: Twitch
  * Modpack: Journey Across the Void
* What kind of server:
  * [x ] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [ x] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [x ] Only an existing save

## Links to crash logs, stack traces, etc

* https://gist.github.com/
* https://paste.ee/
* https://duckduckgo.com/?q=pastebin+alternatives
* Upload them somewhere, and then replace these links.

**Comment by RlonRyan** [comment]
Possible improvements here are either to allow for transcribing or to have the journal be tied to the player. I'd rather not have the journal entries be tied to the player though, as then you can't trade the journals. A transcription station might not be bad, as you don't want to lose a journal you've filled completely.

I think the behavior that each analyzer requires a book in it to log anything won't change though.
