### ISSUE TITLE
AgriSeed.class bug

### ISSUE THREAD

**Issue by Alex-D-G** [AgriCraft/AgriCraft#1264]
Hi everyone,

I've been playing a new modpack that uses this mod, the only problem is that when you place an upgraded seed and then break and pick it up again it turns back to a 1/1/1. I had a look online and found out it was a problem with the AgriSeed.class file where there was a problem in the code. Luckily the forum that i found also provided the awnser: replace the wrong code with some other code. I have tried wrapping my head around java coding but havent managed to figure it out. So my questionn is if anyone who knows their way around java is willing to change the code for me and then uploud the compiled version.

The code that is the problem:
return ret; (in function ItemStack in AgriSeed.Class)

Should be replaced with this:
ItemStack toReturn = new ItemStack(stack.getItem(), size, stack.getMetadata());
toReturn.setTagCompound(tag);
return toReturn;

source:
https://github.com/AgriCraft/AgriCraft/issues/1102

Thanks for any help!

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
