### ISSUE TITLE
Rendering glitches, no config option to remove or hide Water Tanks

### ISSUE THREAD

**Issue by MechanosG** [AgriCraft/AgriCraft#1265]
## Quick description
I'm having issues with (I assume) the water tanks messing up the rendering for 3D inventory objects.  Probably some weird interaction with one of the optimization mods I'm using (I'm not using optifine btw).  Before adding Agricraft, my modpack had no rendering issues, and it seems like I had a similar problem with the water tanks in past MC versions, so it's my primary suspect.  I'm trying to find a way to disable water tanks, or at least hide them from JEI.  I tried disabling irrigation hoping it would remove the water tanks, but it only removed the sprinklers and stuff unfortunately.

## Related issues and searches
There are multiple issues mentioning rendering problems, but they also said their game crashed, so may be unrelated.  I haven't had any crashes.

## Mods and versions used

* Minecraft: 1.12.2
* AgriCraft: AgriCraft-2.12.0-1.12.0-a6.jar
* InfinityLib: infinitylib-1.12.0.jar
* jei_1.12.2-4.15.0.291.jar

## Steps to replicate the issue

1. Search something in JEI that loads the water tanks, such as "water"
2. Watch as rendering glitches out, making the front face on 3D objects (including the player model in the inventory viewer and water tanks themselves) turn semi-transparant.
3. ???
4. Profit

## Expectations and explanations

I would expect 3D rendering to not glitch out.

## Your environment

* How are you playing?
  * Operating System: Win 7 - OpenJ9 VM, version 1.8.0_212
  * Launcher: Twitch
  * Modpack: SciTECH (currently indev and isn't public yet)
* What kind of server:
  * [x] Singleplayer
  * [?] Multiplayer (haven't tested this, but I assume it'll happen in a multiplayer environment too)
* Game Modes:
  * [x] Survival
  * [x] Creative
* Save File:
  * [x] Brand new save
  * [x] Only an existing save

## Links to crash logs, stack traces, etc

I haven't experienced any crashes, and I couldn't find anything in the logs related to rendering.  But if there's something I can look out for and get to you, please let me know.

## Screenshots (or videos)

![2020-02-21_14 58 33](https://user-images.githubusercontent.com/4360512/75078804-84b08580-54bb-11ea-90bd-285f93391870.png)
(In case it isn't noticeable at first glance, look at the player model's face in the inventory, and look at the front face of the water tanks.  They've become transparent, allowing the inside of the models to show through.)

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.

**Comment by MechanosG** [comment]
Heya.  I know you just closed this.  But at some point I figured out what was causing the rendering problem, and I forgot to update this.  There was a chunk pre-generator mod that rendered a HUD window while it was generating chunks (you can kind of see it underneath the water tanks in the screenshot).  Anytime that window was visible and chunks were being pre-generated, the front faces on 3D objects in the inventory turned transparent when AgriCraft's water tanks were being rendered.  No idea why they conflicted.  It would go back to normal when the chunk pregen mod finished generating and closed that HUD window.
