### ISSUE TITLE
Crop Sticks not working on TFC Farmland or Dirt

### ISSUE THREAD

**Issue by drago87** [AgriCraft/AgriCraft#1266]
## Quick description
Crop Sticks can be placed on [TFC 1.12.2](https://www.curseforge.com/minecraft/mc-mods/tfcraft) Farmland or dirt

## Mods and versions used

* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a6
* InfinityLib: 1.12.20

## Steps to replicate the issue
1. Loaded up `...`
2. Placed a `TFC dirt or Farmland of eny type`
3. Right-clicked with `Crop Sticks` on `placed dirt or Farmland` and Nothing happens
4. Right-clicked with `Crop Sticks` on `TFC Grass/gravel/raw stone` and Crop Sticks is placed

## Expectations and explanations
Crop Sticks being placed

## Your environment

* How are you playing?
  * Operating System:
  * Launcher:
  * Modpack:
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
No crashes

## Screenshots (or videos)
![2020-02-29_20 53 45](https://user-images.githubusercontent.com/6805712/75614093-7276bd00-5b35-11ea-87a2-be8c5d7b9778.png)

**Comment by wapachoo** [comment]
TFC isn't a default soil for agricraft, has to be added as a viable one. this is more of an issue for TFC devs to have a compat patch.

**Comment by drago87** [comment]
Is there a way for a user to add the soil?

**Comment by Omni-MC** [comment]
I've gotten it to work here change .txt to .json and put it under ~/config/agricraft/json/defaults/mod_tfc/soils/
also added the soils for TFCRocks+
Currently sorting out why I cant plant on them.
[tfc_soil.txt](https://github.com/AgriCraft/AgriCraft/files/5324555/tfc_soil.txt)

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
