### ISSUE TITLE
Phantom Breaker destroys seed in Agricraft Crop Sticks 

### ISSUE THREAD

**Issue by Flabadab** [AgriCraft/AgriCraft#1268]
## Quick description
When linking a Phantom Breaker to Agricraft Crop Sticks with any seed growing in the crops, when the Crop Sticks are broken, only the sticks appear inside the Phantom Breaker inventory - the seed is completely gone.

## Mods and versions used
Actually Additions (1.12.2-rc151)
Agricraft (2.12.0-1.12.0-a6)

## Steps to replicate the issue
1. Hoe some dirt
2. Place a Crop Stick on the dirt
3. Place any seed into the Crop Stick
4. Place an Actually Additions Phantom Breaker nearby
5. Use a Phantom Connector to connect the Phantom Breaker to the growing Crop Stick. The breaker will break the Crop Stick, and delete the seed.

## Expectations and explanations
When the Crop Sticks are broken with a Phantom Breaker, the seed growing in it is dropped as an item in the world. (Similar to when breaking a Furnace with Fuel inside it and the Fuel drops)

## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: Twitch
  * Modpack: MC Eternal (1.3.4)
* What kind of server:
  * [X] Singleplayer 
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
