### ISSUE TITLE
Water Tank in JEI crashes client

### ISSUE THREAD

**Issue by DandereDylan** [AgriCraft/AgriCraft#1271]
I'm somewhat new to Minecraft modded so I am not sure exactly what happened, but here is a link to my crash report nonetheless: https://pastebin.com/2cPB2tGp

**Comment by DandereDylan** [comment]
The same thing is happening again, and now it's saying it crashes with the Water Channel Valve: https://pastebin.com/8nbsnzqw

**Comment by DandereDylan** [comment]
It seems like this crashing only occurs when searching in the JEI, and the blocks that cause it are specifically the ones that have many wooden variants.

**Comment by KajDarkwind** [comment]
The same thing happens to me constantly and makes it so I can't even use the mod, or play any modpack that contains it. I would love to see a fix for this as it prevents me from playing a lot of packs that look really cool.

**Comment by ubergarm** [comment]
Similar deal here. I'm doing some pack dev and am pretty excited to have Pam's HarvestCraft plants in crop sticks, but the water tank is crashing clients when playing multiplayer (server stays up fine).

```
PM
Description: Rendering ingredient

java.lang.RuntimeException: ALREADY CONSTRUCTING VERTICES

...

JEI render details --
Details:
	Unique Id (for Blacklist): agricraft:water_tank:0
	Ingredient Type: class net.minecraft.item.ItemStack
	Error Info: 1xtile.agricraft:water_tank@0 agricraft:water_tank nbt:{agri_material_meta:8,agri_material:"chisel:planks-spruce"}
	Filter Text: wa
	Edit Mode Enabled: false
	Debug Mode Enabled: false
```
Hopefully I can use CraftTweaker or similar to hide/remove the offending water tank (and possibly water channel valve?) etc and keep this mod in the pack. It might also be I had a fancy `chisel` texture one in the world that was causing a similar bug e.g. `ALREADY BUILDING`...

https://pastebin.com/h6izz0AL

Thanks much and keep up the good work!

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
