### ISSUE TITLE
1.12.2 MC Argicraft + Mystical Agricuture Bug, Wrong plants are spreading!

### ISSUE THREAD

**Issue by Raenerys** [AgriCraft/AgriCraft#1272]
Hello!
I wrote a Modpack for me including Argicraft and Mystical Agriculture. I had to change one Line in the Data of mod_mysticalagriculture so I can use the Cropsticks with the  Inferium Seeds. Now on my field the Inferum should spread out an grow, but I get random on the field Wheat-Plants all by themselves, not inferum! What can I do to fix that? There is no Wheat around that could grow over there

![Argi Bug](https://user-images.githubusercontent.com/49061968/81294836-bd4e0d00-906f-11ea-87d3-6e0fb7e43d69.jpg)

**Comment by darthvader45** [comment]
Weird, I see 4 inferium plants, and a lot of weeds.  Might want to use the hand rake to clear em out and let the inferium spread/plant some more.
