### ISSUE TITLE
Trouble adding custom crop

### ISSUE THREAD

**Issue by ParkerRS** [AgriCraft/AgriCraft#1273]
Hello, I don't believe this is a bug but I'm having issues adding crops to crop sticks using the .json files. I used other .json files that are already included as a basis, but must've made an error somewhere. I was wondering if anybody could spot it, as I cannot.

https://pastebin.com/YvnZGF5X

**Comment by RlonRyan** [comment]
I don't see any glaring errors. The easiest way to solve this is to start with another plant file you know that works and then make one change at a time until you find the issue.

It should report any issues loading the JSON in the agricraft logs, so you'd have to check there to see what's really wrong.
