### ISSUE TITLE
Rustic Rope prevents water from sprinklers reaching crop ground underneath. 

### ISSUE THREAD

**Issue by Gaiyamato** [AgriCraft/AgriCraft#1274]
The Rope used for grapes in Rustic acts as a barrier to the water from the sprinklers. 

This actually makes total sense in a minecraft way, however  it would be nicer if a piece of rope didn't prevent irrigation. **^_^**

**Comment by RlonRyan** [comment]
I'm going to say that we won't fix this for now, since as far as I know there is no way of telling if a block is solid in a direction or what that even means. Sprinklers water down, and can only water through air blocks.
