### ISSUE TITLE
Missing Silverweed

### ISSUE THREAD

**Issue by VulpiniFox** [AgriCraft/AgriCraft#1275]
##  Quick description

My modpack is missing the silverweed plant and seeds, despite all other seeds from the packs being present and functional

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a6
* InfinityLib: 1.12.0
* Thermal Foundation: 2.6.7.1
* Thermal Expansion: 5.5.7.1

## Steps to replicate the issue

1. Loaded up custom world
2. Search for Silverweed seed or plant

## Expectations and explanations
No plant or seed found in search

## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: Twitch app
  * Modpack: Custom Modpack, with all other mods disabled.
* What kind of server:
  * [x] Singleplayer
  * [x] Multiplayer
* Game Modes:
  * [x] Survival
  * [x] Creative
* Save File:
  * [x] Brand new save
  * [ ] Only an existing save

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
