### ISSUE TITLE
Mutations aka Seed "Recipes" and Spreading not working

### ISSUE THREAD

**Issue by SimonEGgi** [AgriCraft/AgriCraft#1276]
hey there, 

I switched from the newest Forge 1.12.2 version to Forge 1.12.2 (14.23.5.2847) because my server host required it and now the mod does not work anymore, not singleplayer nor multiplayer.

What could be the reason? The forge change?

**Comment by SimonEGgi** [comment]
Apparently the recipes do show up if I go on the server with the newest forge edition. 
The crops just dont spread. So it probably must be the server's forge edition.
However i cant change that one. Any solutions?

**Comment by darthvader45** [comment]
I'd ask the server owner if they can update Forge.
