### ISSUE TITLE
seed_analyzer render causes crashes

### ISSUE THREAD

**Issue by Kazuto** [AgriCraft/AgriCraft#1277]
## Quick description
When I open the inventory (JEI) and look for anything related to AgriCraft like "seed" or "@agricraft" the client crashes. Even happens after reinstalling the pack.

## Related issues and searches
* https://github.com/AgriCraft/AgriCraft/issues/1233
* https://github.com/AgriCraft/AgriCraft/issues/1262
* https://github.com/AgriCraft/AgriCraft/issues/1259
* https://github.com/AgriCraft/AgriCraft/issues/1170

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0
* InfinityLib: 1.12.0
* JEI: 4.15.0.291

## Steps to replicate the issue
1. Opened Inventory
2. Searched for anything related like "seed" or "@agricraft"
3. Game crashes

## Your environment
* How are you playing?
  * Operating System: MacOS
  * Launcher: Curse Launcher
  * Modpack: ATGM (All The Good Mods)
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [x] Creative
* Save File:
  * [x] Brand new save
  * [X] Only an existing save

## Links to crash logs, stack traces, etc
* https://pastebin.com/6TpxqtPp

**Comment by Kazuto** [comment]
Found the culprit. Apparently there is a conflict with JEI 4.15.0.291. Using 4.15.0.293 seems to work fine.

**Comment by Kazuto** [comment]
I guess I've found the bug. If you change or add json configurations for missing seeds the world gets somewhat corrupted if there is a seed analyzer placed and it results in this bug.

- Deleted config/agricraft
- Re-create config/agricraft on forge initialization at launch
- Removed the seed analyzer from world/inventory
- Added the changed/missing configurations back
- Loaded the existing save and it works

Maybe someone can check if this was indeed the bug and not just for me.

**Comment by Kazuto** [comment]
After a lot of trial and error, searching und reading I found following issue https://github.com/AgriCraft/AgriCraft/issues/1034 that points to JourneyMap as the cause.

Xaero's Minimap/Worldmap is in this modpack installed instead of JourneyMap but could it be the same problem causing the bug? I've temporarily removed these two mods and it works for now, but it could just be a coincident.

**Comment by ubergarm** [comment]
Thanks for the tip on Xaero's Minimap @Kazuto , I couldn't even open my inventory as my JEI was viewing `agricraft:water_tank` page and would immediately crash the client w/ a rendering issue.

I disabled Xaero's Minimap long enough to get in and add it to my JEI itemBlacklist.cfg e.g.:
```
advanced {
    S:itemBlacklist <
        agricraft:water_tank
     >
}
```

So hopefully after disabling watering tanks in JEI blacklist and disabling all irrigation stuff via config I can use this mod... Going to try the seed analyzer next, if it crashes then i have to decide between a minimap and mutating crops in this pack i guess.. :/

Thanks!
