### ISSUE TITLE
No recipes for irrigation channel or tanks

### ISSUE THREAD

**Issue by Kazuto** [AgriCraft/AgriCraft#1278]
## Quick description
I've installed AgriCraft but I can't craft irrigation channels or water tanks because the recipe doesn't show up.
I've also checked the config.cfg and it's enabled but the only thing that shows up is the sprinkler itself.

```
irrigation {
    # The amount of water in mB that an irrigation channel can hold. [range: 100 ~ 2000, default: 500]
    I:"Channel Capacity"=500

    # Set to true if you want to enable irrigation systems. [default: true]
    B:"Enable Irrigation"=true

    # Set to true to let tanks fill up when water flows above them. [default: false]
    B:"Fill tank from flowing water"=false

    # Set to true to let tanks fill up when water falls from the sky. [default: true]
    B:"Fill tank from rainfall"=true

    # Every loop, each unobscured plant in sprinkler range has this chance to get a growth tick from the sprinkler. [range: 0 ~ 100, default: 20]
    I:"Sprinkler growth chance"=10

    # The minimum number of ticks between successive starts of irrigation. No effect if it's less than the number required to actually finish. [range: 1 ~ 1200, default: 100]
    I:"Sprinkler growth interval"=100

    # Defined in terms of mB per second. The irrigation loop progress will pause when there is insufficient water. [range: 0 ~ 10000, default: 10]
    I:"Sprinkler water usage"=30
}
```

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a6
* InfinityLib: 1.12.0

## Your environment
* How are you playing?
  * Operating System: MacOS
  * Launcher: Curse
  * Modpack: ATGM
* What kind of server:
  * [X] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Screenshots (or videos)
![2020-07-04_13 42 19](https://user-images.githubusercontent.com/25435034/86511830-fea73280-bdfc-11ea-8019-e3470d36c21e.png)

**Comment by ubergarm** [comment]
Total guess, but might be due to rendering issues around those items. (see other issues) I added some while in creative mode and crashing clients repeatably by looking at the water tank in world or looking it up in the JEI. I'm actually trying to remove them from my modpack right now, lol.
