### ISSUE TITLE
Red Seeds will not grow on Lit Redstone Ore

### ISSUE THREAD

**Issue by NimonoSolenze** [AgriCraft/AgriCraft#1279]
## Quick description
Red Seeds work as intended- they only grow on Redstone Ore placed below their soil. _However_, for some reason this only checks for EXACTLY minecraft:redstone_ore, and thus ignores minecraft:lit_redstone_ore. If you try to plant red seeds on the soil in this state, you receive a message saying the plant won't grow- and this especially happens if you place the ore, then right-click the ore itself to place gravel, which causes the ore to light up. If you place the gravel by clicking a nearby block instead, this issue does not occur, allowing the red seed to grow.

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a6
* InfinityLib: 1.12.0

## Steps to replicate the issue

1. Launch game
2. Place Redstone Ore
3. Place Gravel by right-clicking the Ore itself
4. Place Crop Sticks and plant a Red Seed in it
5. Receive message that additional requirements are unmet

## Expectations and explanations

I would expect that since minecraft:lit_redstone_ore drops Redstone/Redstone Ore when broken, that the mod would count it as a valid "nutrient" for the plant to grow, given they are, in essence, the same block.

## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: MultiMC
  * Modpack: Custom
* What kind of server:
  * [ ] Singleplayer
  * [x] Multiplayer
* Game Modes:
  * [x] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Screenshots (or videos)

![2020-09-04_09 54 12](https://user-images.githubusercontent.com/27874923/92253010-a5a75980-ee94-11ea-87ef-41ae325e10ae.png)
![2020-09-04_09 54 14](https://user-images.githubusercontent.com/27874923/92253017-a809b380-ee94-11ea-8526-c1e4ed4caf3b.png)
![2020-09-04_09 54 19](https://user-images.githubusercontent.com/27874923/92253019-a93ae080-ee94-11ea-950c-b19687ebbed4.png)

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
