### ISSUE TITLE
Modpack long start time with registering nuggetUnknown

### ISSUE THREAD

**Issue by Liiw** [AgriCraft/AgriCraft#1280]
Hello! 

I am creating a quite sizable modpack which is inspired by Sevtech: Ages. 

I have noticed that when I start up the pack, the log shows that after:

`
[19:48:26] [Client thread/INFO] [agricraft]: Registering in Ore Dictionary: nuggetUnknown
`

it takes approximately 3 minutes after which it continues.  Is it possible to determine anything with this information or is additional info needed?

**Comment by RlonRyan** [comment]
It's hard to tell anything from that. It could be another mod loading during that time, or Forge preparing the registry. There is not really anything that can be done about the load time for 1.12, all of the agricraft loading is on-demand so it shouldn't slow down startup.
