### ISSUE TITLE
Version 1.12.2 MultiBlock Glitch

### ISSUE THREAD

**Issue by SnowNT** [AgriCraft/AgriCraft#1281]
In Minecraft version 1.12.2, under the modpack Infinity Evolved: Reloaded, the water tanks and irrigation channels are most of the time failing to connect to eachother. Using the same wood when attempting to multi-block the structures, they fail to connect. It is a multiplayer server. Over 180 mods in the modpack. Sometimes they connect, most of the time they do not.

![mcwatertanks](https://user-images.githubusercontent.com/74238473/98655477-85b96980-230d-11eb-9df7-ce8cba2bb9ca.jpg)

![mcchannels](https://user-images.githubusercontent.com/74238473/98655521-923dc200-230d-11eb-87cc-4e7e05acf5bc.jpg)

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
