### ISSUE TITLE
Crash on trying to use clippers

### ISSUE THREAD

**Issue by melbellrocks** [AgriCraft/AgriCraft#1283]
## Quick description
Instant crash upon trying to use clippers on an Agricraft crop.  Now the world instantly crashes when I try to load it.

## Mods and versions used

* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a6
* InfinityLib: 1.12.0

## Steps to replicate the issue

1. Attempted to use the clippers on a growing wheat plant (on crop sticks)

## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: FTB
  * Modpack: FTB University
* What kind of server:
  * [ X ] Singleplayer

* Game Modes:
  * [ X ] Survival

* Save File:
  * [ X ] Only an existing save

## Links to crash logs, stack traces, etc

* https://pastebin.com/Dac6xDki

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
