### ISSUE TITLE
[1.12] Final Release on CurseForge

### ISSUE THREAD

**Issue by InfinityRaider** [AgriCraft/AgriCraft#1287]
Reminder for myself for when I find the time and motiviation to bother doing this.

Confirm the 1.12 branch still works after all the merged PRs, and release new build of InfinityLib and AgriCraft on CurseForge.

**Comment by Just8Will** [comment]
If I can help with testing this please let me know. It'd be great to have the version used in packs have the fixed ccsa for opencomputers.

**Comment by InfinityRaider** [comment]
I am experiencing severe issues with the build script, which was unexpected, and can't be bothered to investigate and fix it.
Therefore, no more releases for 1.12.

**Comment by InfinityRaider** [comment]
Final release is up on CurseForge.
