### ISSUE TITLE
Agricraft JEI crash ALREADY CONSTRUCTING VERTICES

### ISSUE THREAD

**Issue by yosomith** [AgriCraft/AgriCraft#1289]
Playing a modified version of Stoneblock 2 with Agricraft installed, I searched something on JEI I think it was fe but I am not sure but it resulted in a crash, trying to reload the world works fine but every time I open my inventory and can see JEI I get a crash. Looking at the log seems to be some kind of render issue with the Wooden Grate.

Minecraft Version: 1.12.2
Modpack: Stoneblock 2 modified
AgriCraft: 2.12.0-1.12.0-a6
InfinityLib: 1.12.0

https://www.dropbox.com/s/n51ragxauon4ood/crash-2021-01-29_12.22.29-client.txt?dl=0

**Comment by InfinityRaider** [comment]
This is a duplicate, and 1.12 is no longer being worked on.
