### ISSUE TITLE
[Suggestion] Seasonal Fertility traits when mods like Serene Seasons or Better Weather are installed.

### ISSUE THREAD

**Issue by Corvus20** [AgriCraft/AgriCraft#1291]
Seasons mods like "Serene Seasons" or "Better Weather -Seasons, Blizzards, and more!" make it so plants are only fertile in certain seasons. I was wondering if there could be a mutation for crops that make them more resistant to heat or cold. This could at least reduce the growth speed penalty the season mod puts on the crop, if not outright nullify it. Could be a fun idea.

I am glad to hear that a 1.16 update is planned, and am looking forward to what the future will bring! Wishing you the best!

**Comment by InfinityRaider** [comment]
Thank you for this suggestion, I will look into it, indeed, I have been preparing support for whatever exotic growth requirement there could be, among which [seasons](https://github.com/AgriCraft/AgriCraft/blob/master/src/main/java/com/infinityraider/agricraft/api/v1/requirement/RequirementType.java#L75).
Also, there will be new stats, and strength will have a brand new function, [being the probability to overcome certain growth requirements](https://github.com/AgriCraft/AgriCraft/blob/master/src/main/java/com/infinityraider/agricraft/api/v1/stat/IAgriStatRegistry.java#L26-L29).

I have found the GithHub repositories for the [Serene Seasons mod](https://github.com/Glitchfiend/SereneSeasons) and the [Better Weather mod](https://github.com/CorgiTaco/Better-Weather), and they both do have an API, however I am not certain if it is hosted on a maven somewhere, I will try to get in touch with the respective mod devs.

**Comment by InfinityRaider** [comment]
I have added seasonal compatibility for both  mods.
Ambient temperature, humidity and current weather requirements are not implemented by default, but all support for them is implemented.
Implementing those should be trivial, but I am not currently going to bother with it, as it is too specific for something which is not vanilla, and perhaps better suited for a plugin.
