### ISSUE TITLE
Strength is nothing when you can analyse

### ISSUE THREAD

**Issue by Hyper-Miiko** [AgriCraft/AgriCraft#1293]
## Quick description
We can use every clip like it has 10 strength

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: sorry, forgot
* InfinityLib: sorry, forgot

## Steps to replicate the issue
1. Get clip from clipper on crops
2. Place the clip(s) in seed analyzer
3. Get the seed of the clip

## Expectations and explanations
Tried to analyse an undefined clip
But got the seed

## Your environment
* How are you playing?
  * Operating System: Win 8
  * Launcher: Minecraft.exe
  * Modpack: My own
* What kind of server:
  * [X] Singleplayer (and LAN)
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Screenshots (or videos)
Sorry I can't but I except I'm sufficiently clear

**Comment by InfinityRaider** [comment]
Please do not open new  1.12 issues, I am currently porting to 1.16.
