### ISSUE TITLE
JSON files corrupt and Say NUL over and over again

### ISSUE THREAD

**Issue by BocKerDoesGames** [AgriCraft/AgriCraft#1295]
Hey Everyone I just wanted to ask a question, I was making edits to JSON files for one of the modpacks I play right? the issue is that JSON files corrupt and Say NUL over and over again. and here is an example

(https://user-images.githubusercontent.com/79927492/109679649-630fc280-7b41-11eb-9bbf-28133756b7d6.png)

**Comment by InfinityRaider** [comment]
Not sure what is up with that.
Try a fresh download of the jar
