### ISSUE TITLE
1.16 bugs

### ISSUE THREAD

**Issue by nbrichau** [AgriCraft/AgriCraft#1302]
### Crops
- [x] can't place crop stick on clay underwater (water source & flowing water)
- [x] can't place a crop stick on a plant after placing the plant
- [x] can't place a water bucket on crop sticks and plants by right-clicking it
- [x] bonemealing a fully grown crop doesn't produce anything and use bonemeal indefinitely
- [x] 1 pixel between two soil requirements have the two tooltip text overlapping
- [x] plant without crop sticks is called "Unknown" on The One Probe and have a question mark texture, even when looking with the magnifying glass
- [x] water in a crop sticks doesn't flow from the side after breaking the block on this side
- [x] can't place a crop stick in cross on another by right-clicking the farmland the other was
- [x] the crop in the trowel disappears if used on cross crop sticks
- [x] plant without crop stick have not breaking particle texture
- [x] there is no hand animation when creating a cross crop stick

### Seed analyzer
- [x] right-clicking the seed analyzer with a block in main hand open the gui and place the block
- [x] while using the seed analyzer, the pov of the player is not really blocked : the player orientation change but not what it's looking at
  - [x] same for the agricultural journal
- [x] during the animation of the opening of the seed analyzer, we can see the inside of our head for a small duration
  - [x] same for the agricultural journal
- [x] ~~If the player is on top of the analyzer and open it, it's impossible to see the genes, the only thing possible to see is the inside of the player model~~
- [x] while using the seed analyzer we can still left-click, right-click, sneak and open the inventory
- [x] there is a way to x-ray by using the seed analyzer when there are blocks all around
- [x] using escape key after opening the seed analyzer closes the analyzer and open the pause menu.
- [x] rick click with a block in hand when the view is obstructed try to place the block and cause a desync ([video example](https://streamable.com/w3pzyz))

### Agricultural journal
- [x] using escape key after opening the agricultural journal closes the book and open the pause menu.
- [x] turning the page A of the journal, there is a small amount of time when we can see the text of the page B on the page A
- [x] the journal use the wrong wiew orientation. The orientation used is the orientation the player had the last time he opened the seed analyzer.
- [x] the tooltip have the text "Sneak + Right click to place on a Seed Analyzer" written twice

### Other
- [x] the search item creative tab have only agricraft items

**Comment by InfinityRaider** [comment]
When you have time, could you check if the Seed Analyzer desync has been resolved?

**Comment by nbrichau** [comment]
Yes it have been resolved, now the block is placed when the view is blocked.
But now the block is also placed when the view is not blocked.

**Comment by InfinityRaider** [comment]
Damn, that wasn't the intention.
