### ISSUE TITLE
Crash with Create mod

### ISSUE THREAD

**Issue by lperlaki** [AgriCraft/AgriCraft#1312]
## Quick description
The Game crashes on world load if the Create mod and AgriCraft are installed

## Related issues and searches

* https://github.com/Creators-of-Create/Create/issues/1612

## Mods and versions used

* Minecraft: forge-1.16.5-36.1.0
* AgriCraft: 1.16.5-3.0.0 
* InfinityLib: 1.16.5-2.0.2 
* Create: mc1.16.5_v0.3.1c+151

## Steps to replicate the issue

1. Load a World

## Your environment

* How are you playing?
  * Operating System: MacOS and Windows
  * Launcher: Minecraft Launcher
  * Modpack: -
* What kind of server:
  * [x] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [x] Survival
  * [x] Creative
* Save File:
  * [x] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
[Crash Report](https://gist.github.com/lperlaki/dab13c66b51e0ac2af697380aea8aaa5)

**Comment by InfinityRaider** [comment]
This error is not on my end.

**Comment by InfinityRaider** [comment]
To nuance: I might be doing something weird that messes up the things they have set up.
In any case, the stacktrace points entirely to Create's codebase, to which I am not familiar, therefore the Create devs are in a better position to debug this than me.
If and when they find the cause for this, and if (a part of) the fix would be on my end, I will cooperate with them.

But for now there is little I can do here.

**Comment by reidbhuntley** [comment]
After some digging, I believe this crash is being caused by `DynamicCamera.reset()` in InfinityLib setting `Minecraft.renderViewEntity` to null. Changing `this.originalCamera` to `this.getOriginalRenderViewEntity()` on line 320 of DynamicCamera.java may fix the issue.

**Comment by InfinityRaider** [comment]
Interesting, because the following:
1) i have managed to reproduce this reliably, and it is happening even when the dynamic camera is not, or has not been used.
2) vanilla code allows the renderViewEntity to be null, this is something I verified thoroughly before resetting to null instead of the previous one to avoid issues in case someone takes control of the renderViewEntity while I was using it.
3) the NPE is thrown by create fetching their custom renderer from their custom world object.

**Comment by InfinityRaider** [comment]
I will change it to reset back to the client player instance to see if it fixes things.
Changing back to the previous entity lay cause a deadlock in case someone else was controlling the camera before.

**Comment by reidbhuntley** [comment]
Maybe a better solution would be to add a null check on the Create side, since as you said the field is nullable in vanilla code. I'll try it out, and hopefully if it works then your end won't have to change anything

**Comment by lperlaki** [comment]
> Maybe a better solution would be to add a null check on the Create side, since as you said the field is nullable in vanilla code. I'll try it out, and hopefully if it works then your end won't have to change anything

I already tried that but then the AgriCraft crops won't render.

**Comment by InfinityRaider** [comment]
Ah I think I know what is happening.
I am lazy baking crop models, meaning the quads are not available until they have been rendered at least once.
Create probably doesn't amount for this, and probably wraps up the quads somehow to suit their rendering.
Resulting in agricraft crops not rendering.

**Comment by lperlaki** [comment]
This is now fixed on Creates side. I tested it and the AgriCraft crops also get renderd.
