### ISSUE TITLE
Dedicated Server does not start

### ISSUE THREAD

**Issue by lperlaki** [AgriCraft/AgriCraft#1315]
## Quick description
The Server does not boot with AgriCraft installed

## Mods and versions used

* Minecraft: forge-1.16.5-36.1.0
* AgriCraft: 1.16.5-3.0.0
* InfinityLib: 1.16.5-2.0.2
* [List the other required mods here]

## Your environment

* How are you playing?
  * Operating System: Linux
  * Launcher: -
  * Modpack: Custom
* What kind of server:
  * [ ] Singleplayer
  * [x] Multiplayer
* Game Modes:
  * [ ] Survival
  * [ ] Creative
* Save File:
  * [x] Brand new save
  * [x] Only an existing save

## Links to crash logs, stack traces, etc
[Crash Report](https://gist.github.com/lperlaki/dcee85748bcc09138c3c20ef1d29dff8)

**Comment by InfinityRaider** [comment]
I am officially retarded, obviously the ServerProxy is for Client side....

Anyway, there might be more of these bugs hidden in there.

**Comment by lperlaki** [comment]
Oh thanks for the Quick response. I tried that fix already and it did not fully fix the problem if I recall correctly, I will post the new crash soon

**Comment by lperlaki** [comment]
Here is the Crash Report with the fix [Crash Report](https://gist.github.com/lperlaki/3aa7098722ba68bf2664f40a7ff9c1be)

**Comment by InfinityRaider** [comment]
Well, where will it crash next?

**Comment by lperlaki** [comment]
Now it starts but when i try to join the server I get an error.

`User lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Modders must implement Ingredient.getSerializer in their custom Ingredients: com.infinityraider.infinitylib.crafting.dynamictexture.DynamicTextureIngredient@2de6b6b7`

this is with my modpack will test it without other mods soon

**Comment by InfinityRaider** [comment]
No, this is definitely InfinityLib, which is weird, as this should also crash a client...

**Comment by lperlaki** [comment]
In singleplayer it doesnot crash

**Comment by InfinityRaider** [comment]
It might do if you switch to LAN, anyway, I have pushed the fix, but you will need to rebuild InfinityLib as well.

**Comment by InfinityRaider** [comment]
Any more issues?
Can I close this?

**Comment by lperlaki** [comment]
no everything works for now, thank you

**Comment by InfinityRaider** [comment]
Cool, you might find some more crashes at runtime, but you know where to go with those.
