### ISSUE TITLE
Crop stick requirement (1.16.5)

### ISSUE THREAD

**Issue by Warbringer12** [AgriCraft/AgriCraft#1323]
would like the ability to add requirement for what tier crop stick the seeds will grow in. (inside the jsons)
also would like it if you added in diamond, gold, netherite, stone, netherrack, and end stone crop sticks if possible
lava logging would be also a nice feature to add in.

**Comment by InfinityRaider** [comment]
Lava logging is already a thing.
Not sure about the other materials as it feels a bit bloaty.

**Comment by InfinityRaider** [comment]
I've decided against this.
If an addon mod wants to do this, it is quite trivial to apply this via the API, but it is not something I want in Vanilla AgriCraft.
