### ISSUE TITLE
Load Crash with Create Mod

### ISSUE THREAD

**Issue by lperlaki** [AgriCraft/AgriCraft#1324]
## Quick description
The Game crashes on load when I try to load the Create mod dev setup with AgriCraft installed.

## Related issues and searches
I am trying to debug #1312 

## Mods and versions used

* Minecraft: 1.16.5  
* Forge: 36.1.0
* AgriCraft: 1.16.5-3.0.0
* InfinityLib: 1.16.5-2.0.3
* Create: 0.3.1b
* JEI: 7.6.1.71 

## Steps to replicate the issue

1. Pull [Create](http://github.com/Creators-of-Create/Create)
2. add AgriCraft and InfinityLib to `run/mods` folder
3. run with `cradle runClient` 

## Your environment

* How are you playing?
  * Operating System: MacOS
  * Launcher: -
  * Modpack: -
* What kind of server:
  * [ ] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [ ] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
[Crash Report](https://gist.github.com/lperlaki/defd956a3b75c13a6b16e4688d812223)

**Comment by lperlaki** [comment]
I just tested it with only the InfityLib mod. There also is a Crash but it looks different. [Crash Report](https://gist.github.com/lperlaki/3365095f37b50951fd47896be416cf43)

**Comment by InfinityRaider** [comment]
Do you have an obfuscated version in your dev env?

**Comment by InfinityRaider** [comment]
I'm pretty sure your method of adding mods to a dev environment is at fault here.
Unfortunately, adding mods to a dev environment is not as trivial as simply dropping them in the run/mods.
Try it with any other mod, it will not work.

I recommend you use CurseMaven: https://www.cursemaven.com/

You can find examples of usage in the Agricraft build.gradle.

**Comment by lperlaki** [comment]
Ok, thank you!
