### ISSUE TITLE
[1.16.5] Botania compact issue

### ISSUE THREAD

**Issue by Ryen1024** [AgriCraft/AgriCraft#1325]
## Quick description:
Game crash on loading with Botania installed.

## Mods and versions used:
* Minecraft: 1.16.5
* Forge: 36.1.0
* AgriCraft: 3.0.0
* InfinityLib: 2.0.3
* Curios: 4.0.4.0
* Botania: 1.16.5-415

## Steps to replicate the issue:
Install AgriCraft and Botania (and all required dependency) at the same time.

## Expectations and explanations:
Crash report says: 
Failure message: AgriCraft (agricraft) encountered an error during the common_setup event phase
		java.lang.NoSuchMethodError: 'void vazkii.botania.api.BotaniaAPI.registerHornHarvestableBlock(net.minecraft.util.ResourceLocation, vazkii.botania.api.item.IHornHarvestable)'
Looks like some of the botania's api that you're using has changed/deleted.

## Environment:
* How are you playing?
  * Operating System: Windows 10
  * Launcher: MultiMC 5 0.6.12-1530
  * Modpack: Custom
* What kind of server:
  * [x] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [x] Survival
  * [ ] Creative
* Save File:
  * [x] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc:
https://1drv.ms/t/s!AufDEIgnT82D8Uiw7kjgyKm_VAfw?e=cZwA5P

**Comment by InfinityRaider** [comment]
Botania needs an update.
Disable compat in the config, and go bug the botania devs to push an update to CurseForge.

**Comment by Ryen1024** [comment]
> Disable compat in the config, and go bug the botania devs to push an update to CurseForge.

Sorry to trouble you, but I've look into the config files, there is no option to disable botania compact in config\agricraft-client.toml, all entry under the [compact] label is: Create, JEI, TOP, Straw Golem Reborn, season logic, Immersive Engineering, Blood Magic, Cyclic, Industrial Foregoing and Botany Pots, **But no botania**.
Also I see no config file has been generated in saves\[world name]\serverconfig, don't know if that's normal.
