### ISSUE TITLE
Botania Compat Issue

### ISSUE THREAD

**Issue by AngelOfStars** [AgriCraft/AgriCraft#1326]
## Quick description

I have the same issue with Botania not being updated causing the game not to load, but there is no config option to turn Botania compatibility off. 
## Related issues and searches

https://github.com/AgriCraft/AgriCraft/issues/1325

## Mods and versions used

* Minecraft: 1.16.5
* AgriCraft
* InfinityLib
* Botania

## Steps to replicate the issue

Load up Botania + Its dependences and Agricraft + its dependences together. 

## Expectations and explanations

A config to turn off compatibility with Botania
## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher:
  * Modpack: Custom
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [X] Only an existing save

## Links to crash logs, stack traces, etc

Did not provide because the same issue was reported less than an hour ago - I know the problem

## Screenshots (or videos)

![agricraft sc](https://user-images.githubusercontent.com/76855321/120897850-25b24980-c5f6-11eb-83be-3ccc8525faec.png)

**Comment by InfinityRaider** [comment]
It's one of the Botany Pots ones, the one that says Botania in its description:
https://github.com/AgriCraft/AgriCraft/blob/master/src/main/java/com/infinityraider/agricraft/config/Config.java#L238

**Comment by InfinityRaider** [comment]
I'll need to fix that though.
