### ISSUE TITLE
Crash on mod loading, related to Botania - Crash report included

### ISSUE THREAD

**Issue by jmsilva90** [AgriCraft/AgriCraft#1327]
## Quick description

Hello. This is the first crash report for me, if there's anything wrong with it, do let me know ! There might be more to the problem than just what I interpreted, but the report specifically mentioned your mod and an error invoking a method related to Botania. Hope this helps.

## Related issues and searches

* https://github.com/AgriCraft/AgriCraft/issues?q=is%3Aissue%20EXAMPLE

## Mods and versions used

* Minecraft: 1.16.5
* AgriCraft: 3.0.0
* InfinityLib: 2.0.3
* Botania: 1.16.5-416

## Steps to replicate the issue

1. Loaded up pack, crashes at the end stage

## Your environment

* How are you playing?
  * Operating System: Windows
  * Launcher: Minecraft
  * Modpack: Custom
* What kind of server:
  * [x] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [ ] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc

* https://gist.github.com/jmsilva90/a3a648a2a3b0ae5b6bf20203c8ca4381

**Comment by InfinityRaider** [comment]
See #1325
