### ISSUE TITLE
[1.16.5] Any FOV effects breaks when installing AgriCraft.

### ISSUE THREAD

**Issue by Gbergz** [AgriCraft/AgriCraft#1328]
## Quick description
FOV effects breaks when installing AgriCraft.

## Mods and versions used
* Minecraft: 1.16.5
* AgriCraft: 3.0.1
* InfinityLib: 2.0.3

## Steps to replicate the issue
1. Load up AgriCraft
2. Try sprinting. Or apply speed potion, anything that changes fov.
3. FOV isn't changing.

## Expectations
FOV doesn't break when having agricraft installed.

## Your environment

* How are you playing?
  * Operating System: Windows
  * Launcher: CurseForge, it uses Vanilla MC launcher. (MMC aswell)
  * Modpack: No modpack
* What kind of server:
  * [X] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [X] An existing save

## Links to crash logs, stack traces, etc
No logs neeed.

## Screenshots (or videos)
**Empty instance without AgriCraft** (FOV Effects operational.)
https://user-images.githubusercontent.com/26634554/116894757-b5995800-ac32-11eb-9a2a-527c3aec5026.mp4

**Empty instance with only AgriCraft** (FOV Effects non-operational.)
https://user-images.githubusercontent.com/26634554/116894728-ae724a00-ac32-11eb-93d7-2f7b457f354b.mp4

(Messed up the order on these links on first report, edited correctly.)

**-** Gbergz

**Comment by InfinityRaider** [comment]
Ye I think I know what's going on.
Oversight on my part.
