### ISSUE TITLE
Incomparibility with botania

### ISSUE THREAD

**Issue by aburone** [AgriCraft/AgriCraft#1329]
## Quick description
Crash on startup, error referencian botania API

## Related issues and searches
https://github.com/Vazkii/Botania/issues/3741

## Mods and versions used
* Minecraft: 1.16.5
* AgriCraft:agricraft-3.0.1.jar
* InfinityLib:Infinitylib-2.0.3.jar
Botania Botania-1.16.5-416.jar

## Steps to replicate the issue
install Agricraft and botania
Try to start the game

## Your environment

* How are you playing?
  * Operating System: win10
  * Launcher:Tlauncher 2.75
  * Modpack:custom
* What kind of server:
  * [x] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [ ] Survival
  * [ ] Creative
  * [ x] N/A
* Save File:
* [X] N/A
  * [ ] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
https://hastebin.com/raw/pixafohofu

	Mod File: agricraft-3.0.1.jar
	Failure message: AgriCraft (agricraft) encountered an error during the common_setup event phase
		java.lang.NoSuchMethodError: 'void vazkii.botania.api.BotaniaAPI.registerHornHarvestableBlock(net.minecraft.util.ResourceLocation, vazkii.botania.api.item.IHornHarvestable)'
	Mod Version: 1.16.5-3.0.1
	Mod Issue URL: https://github.com/AgriCraft/AgriCraft/issues/
	Exception message: java.lang.NoSuchMethodError: 'void vazkii.botania.api.BotaniaAPI.registerHornHarvestableBlock(net.minecraft.util.ResourceLocation, vazkii.botania.api.item.IHornHarvestable)'
Stacktrace:

**Comment by InfinityRaider** [comment]
Check closed issues before reporting new ones
See #1325
