### ISSUE TITLE
[Request] Better configurability for Greenhouses

### ISSUE THREAD

**Issue by Filostorm** [AgriCraft/AgriCraft#1331]
Hello! Would it be possible to maybe be able to blacklist mods for the crops that grow in the greenhouse, and/or ideally be able to set a limit on the seed tier for mystical agricultural seeds?

Thank you!

**Comment by InfinityRaider** [comment]
What's version is this request for?

**Comment by InfinityRaider** [comment]
Look at the readme, 1.12 is closed, no more work will be done.

**Comment by InfinityRaider** [comment]
Actually I'm reopening this as it will be valid for 1.16.

**Comment by InfinityRaider** [comment]
Implemented for 1.18
