### ISSUE TITLE
Gain attribute question

### ISSUE THREAD

**Issue by edotenseilove** [AgriCraft/AgriCraft#1333]
Thanks for the update for 1.16 version I installed the most recent version of agricraft i tried getting more drops with 10 on all the stats And i could not get more drops from wheet then the max value stated in JSON file As if gain attribute did not work at all. Is it intendid or is it just a bug?

**Comment by InfinityRaider** [comment]
What is in the json file?

And yes, could be a bug.

**Comment by edotenseilove** [comment]
It looks almost exacly as in the 1. 12. Version min 1 max 3 but if i remember correctly those values could get amplified by the gain attribute resulting in a chance of getting more then 3 which i did not get a single time i tried right click left click but i always got 1 2 or 3 .

**Comment by InfinityRaider** [comment]
Right, I'll have a look at it.

**Comment by edotenseilove** [comment]
Thanks a lot

**Comment by edotenseilove** [comment]
I tested it with potatoes as well and problem is the same so it could be related to all crops

**Comment by InfinityRaider** [comment]
Having had a look at the code, there does indeed seem to be a bug, I'll fix it when I get some time.
