### ISSUE TITLE
[Bug] Crashing when combined with Botania

### ISSUE THREAD

**Issue by Elle199** [AgriCraft/AgriCraft#1334]
## Quick description
AgriCraft crashes during "common_setup" if both AgriCraft and Botania is installed at the same time. If Botania is disabled then it boots up just fine.

## Related issues and searches
Could not find

## Mods and versions used
* Minecraft: 1.16.5
* AgriCraft: 3.0.1
* InfinityLib: 2.0.3
* Botania: 416
* Curios API: 4.0.5.2
* Patchouli: 51
* Forge: 36.1.31
Everything is the latest release of each mod as of posting.

## Steps to replicate the issue
1. Install AgriCraft
2. Install Botania
3. Launch the game

## Your environment
* How are you playing?
  * Operating System: Windows 10
  * Launcher: CurseForge - Vanilla Launcher
  * Modpack: None
* What kind of server: **Irrelevant** 
  * [ ] Singleplayer
  * [ ] Multiplayer
* Game Modes: **Irrelevant** 
  * [ ] Survival
  * [ ] Creative
* Save File: **Irrelevant**  
  * [ ] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
https://pastebin.com/3zrbSGv9

## Screenshots (or videos)
https://i.imgur.com/kLMTFsK.png

**Comment by InfinityRaider** [comment]
Look at closed issues before reporting.
#1325 
#1329
