### ISSUE TITLE
Direwolf20 crash with Cylic

### ISSUE THREAD

**Issue by CoolFreeze23** [AgriCraft/AgriCraft#1335]
Hey, I tried adding the new version to the newest version of the Direwolf20 pack and it crashed and wouldn't start. This is what it said:
![image](https://user-images.githubusercontent.com/34906576/121465140-432f3c80-c983-11eb-98fa-d453f5e67976.png)

**Comment by InfinityRaider** [comment]
Update Cyclic

**Comment by CoolFreeze23** [comment]
nvm, just update cyclic, immersive engineering, and immersive posts

**Comment by CoolFreeze23** [comment]
oh damn thanks lol
