### ISSUE TITLE
One probe and tooltips show different stats than magnifiing glass

### ISSUE THREAD

**Issue by edotenseilove** [AgriCraft/AgriCraft#1336]
![image](https://user-images.githubusercontent.com/19620604/121489178-1d7e5380-c9d4-11eb-8d54-f7e74a34a447.png)
when I was upgrading my seeds i noticed that I have two sets of unstackeble maxed seeds which both was showing that they are maxed out acording to tooltip and one probe but when i used magnifiing glass one one of them it shows that they have something at 9 not at 10  all stats at 10 as one probe and tooltips says the other set was fine. I was playing the most recent version for 1.16.

**Comment by InfinityRaider** [comment]
This is the gene pairs, the higher number is the dominant allele and will result in the apparent trait, i.e. the stat.

10-1, 10-2, 10-3, ..., 10-9, and 10-10 will all have a stat of 10.
