### ISSUE TITLE
Game crashes when the mod Create is present

### ISSUE THREAD

**Issue by Her02N0one** [AgriCraft/AgriCraft#1337]
## Quick description

The Game immediately crashes after loading a world with the mods Agricraft and Create.

## Mods and versions used

* Minecraft:
* AgriCraft:
* InfinityLib:
* Create:

## Steps to replicate the issue

1. Put Create and Agricraft in your mods folder
2. Try to load into or create a new world

## Expectations and explanations

The world should load as usual.

## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: Forge
  * Modpack: Custom curseforge test pack with only agricraft and create
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [ ] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [X] Only an existing save

## Links to crash logs, stack traces, etc
* Crash report: https://ghostbin.co/paste/xgvtbps
* Log: https://ghostbin.co/paste/t2wxd8s

**Comment by Syndaryl** [comment]
I've experienced the same issue, I'll have logs to upload tomorrow, along with full configuration details.

**Comment by InfinityRaider** [comment]
Does noone here ever check recently closed issues?
#1312
