### ISSUE TITLE
Agricraft journal is a bit hard to read

### ISSUE THREAD

**Issue by Her02N0one** [AgriCraft/AgriCraft#1338]
The journal moves around a bit while your looking at it, making it a bit hard to focus on the words and imagery while reading.
It would be preferable to replace this with a more standard book GUI, instead of zooming into the hand.

**Comment by InfinityRaider** [comment]
Nah, no GUIs.

**Comment by Her02N0one** [comment]
A more standard gui doesn't necessarily have to be put in place. all that I wish is that your hand doesn't move the book around while you're trying to read it. because it causes some strange tearing on the text and images, and reading moving text is just a bit hard.

**Comment by InfinityRaider** [comment]
Yes I will make either the hand stationary, or the camera track the hand.
If I wasn't going to do anything, I would've closed this ;)
