### ISSUE TITLE
Crashes with Create

### ISSUE THREAD

**Issue by CoolFreeze23** [AgriCraft/AgriCraft#1339]
Whenever I try to run Agricraft with Create the game crashes. No other mods are present.

Steps to replicate the issue:
1. Add Create, Agricraft, and InfinityLib
2. Try creating a new World
3. Game Crashes
* How are you playing?
  * Operating System: Windows
  * Launcher: MultiMC
  * Modpack: Forge 36.1.4
* What kind of server:
  * [X ] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

Crash Report:
https://paste.ee/p/lvA88

**Comment by InfinityRaider** [comment]
Jesus Christ I swear....

#1312 
#1337

**Comment by CoolFreeze23** [comment]
My bad. Always forget about the closed issues tab.

**Comment by InfinityRaider** [comment]
You are foregiven.
Though y'all testing my sanity.

**Comment by CoolFreeze23** [comment]
Yeah sorry, I know it gets annoying 😅. I've seen hella people keep asking about the Botania crash too. I'll make sure to check next time if I have an issue.
