### ISSUE TITLE
encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by GalaxyGamerYT** [AgriCraft/AgriCraft#1342]
## Quick description
I ran my modded server with agriCraft and it pops up with an error saying: "encountered an error during the common_setup event phase"

## Related issues and searches

* https://github.com/AgriCraft/AgriCraft/issues?q=is%3Aissue%20EXAMPLE

## Mods and versions used

* Minecraft:
* AgriCraft:
* InfinityLib:
* There is too many to list here but the crash report mentions **_botania_**

## Steps to replicate the issue

1.Load minecraft with AgriCraft mod and this error pops up.

## Your environment

* How are you playing?
  * Operating System:
  * Launcher: Forge
  * Modpack: https://drive.google.com/drive/folders/1NwDX5-MefGmvCE3D3Ur_xgpACUyu-vN1?usp=sharing
* What kind of server:
  * [ ] Singleplayer
  * [x ] Multiplayer
* Game Modes:
  * [x ] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc

https://gist.github.com/GalaxyGamerYT/f1b5b3622e2f996584af85d2e521f88e

**Comment by InfinityRaider** [comment]
Sigh
#1334
#1329
#1325

Check closed issues before reporting
