### ISSUE TITLE
Betterweather plugin appears to be using a function in the BETA BW release

### ISSUE THREAD

**Issue by waidesoper** [AgriCraft/AgriCraft#1343]
## Quick description

Crash on world load when Agricraft 3.0.1 is installed with Better Weather 1.2.9. The error is No Class Defined corgitaco/betterweather/api/Climate. I've checked the source for that release of Better Weather (which is the only non-beta release on curseforge) and it is indeed missing. The function is available in the Beta release 2.0.

## Related issues and searches

* Better Weather
* Climate

## Mods and versions used

* Minecraft:
* AgriCraft:
* InfinityLib:
* Better Weather 1.2.9

## Steps to replicate the issue

1. Load minecraft with the above mods
2. Witness the fabulous crash

## Expectations and explanations

I don't think it is meant to crash, especially when it is listed as one of the compatible mods on the Curseforge page. If it is going to continue to rely on beta software, perhaps listing the version required could point people in the right direction.

## Your environment

* I was just cruising around reddit when I saw [This]{https://www.reddit.com/r/ModdedMC/comments/ny37zy/help_with_agricraft_and_betterweather_can_someone/} post. I took a look at the crash log, checked the source code of both mods and found the issue.
* I'm happy to let you know that I am running a 10 year old Acer laptop, running Ubuntu 21.04, with 12GB RAM and a discrete nVidia card on board. Although in this instance that probably won't help. 

## Links to crash logs, stack traces, etc

* https://pastebin.com/1YxBvaVb

**Comment by InfinityRaider** [comment]
I'm confused, is the version I'm depending on not available on CF, or do you want me to define a minimum version for the dependency?

**Comment by waidesoper** [comment]
The release version on curseforge, and the main version on GitHub both lack the climate class that you are importing. I think the simplest fix is to just define the minimum version

**Comment by InfinityRaider** [comment]
Yes I need those classes for compat, it was me who requested them ages ago.
I wasn't aware it was still in beta.
I'll define a minimum version.
