### ISSUE TITLE
Mod does not work with Thermal Expansion

### ISSUE THREAD

**Issue by Goronez** [AgriCraft/AgriCraft#1346]
## Quick description
World doen't load with AgriCarfts and Thermal Expansion

## Mods and versions used
* Minecraft 1.16.5:
* AgriCraft 3.0.1:
* InfinityLib 2.0.3:
* CoFH Core 1.2.1
* Thermal Expansion 1.2.0

## Steps to replicate the issue
1. Create a New World
2. Restart the game
3. Load the world
4. See it doesn't load

## Your environment
* How are you playing?
  * Operating System: Windows 10
  * Launcher: MultiMC 5
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
* https://paste.ee/p/SKWfk

## Screenshots (or videos)
![error](https://user-images.githubusercontent.com/85501764/121818424-c60c0c00-cc8f-11eb-83e9-ee4693a3407a.png)

**Comment by InfinityRaider** [comment]
This is Thermal trying to access burn times before tags are initialized.

**Comment by CoolFreeze23** [comment]
I literally know nothing about coding so don't take what I'm saying as fact. But I heard from the COFH team that this is a forge error that you can fix on your side. That's what the twilight author did.

**Comment by InfinityRaider** [comment]
Nope, Twilight was using a Forge event for something they didn't need a Forge event.
I am not using anything Forge.
Burn times should not be accessed before tags are initialized, which is what Thermal is doing .
Their code will also break when someone does need to use the Forge event btw.
