### ISSUE TITLE
Loading into ATM6 results in a crash

### ISSUE THREAD

**Issue by luckymomohd** [AgriCraft/AgriCraft#1350]
## Quick description
Loading into ATM6 with the latest commit of AgriCraft (fd76f98) and InfinityLib (7bac1c5) 
with the latest version of Industrial Foregoing on CurseForge results in a crash.

## Related issues and searches
-

## Mods and versions used
* Minecraft:
* AgriCraft: 1.16.5 / 3.0.1 (fd76f98)
* InfinityLib:  1.16.5 / 2.0.4 (7bac1c5)
* Mods of ATM6 (with fixed Botania, Immersive Engineering, Immersive Petroleum & Create)

## Steps to replicate the issue
1. Load into ATM6 1.6.7 (with fixed Botania, Immersive Engineering, Immersive Petroleum & Create)
2. ???
3. Crash

## Expectations and explanations
I'd like to load into a world.

## Your environment

* How are you playing?
  * Operating System: Windows 10 Pro
  * Launcher: MultiMC
  * Modpack: ATM6

## Links to crash logs, stack traces, etc
https://paste.ee/p/2Ei1b

**Comment by InfinityRaider** [comment]
Industrial Foregoing version?

**Comment by Syndaryl** [comment]
Crash log indicates infinitylib-2.0.4.jar
