### ISSUE TITLE
biome growth contol doesn't work on agricraft crops

### ISSUE THREAD

**Issue by Nathan22211** [AgriCraft/AgriCraft#1351]
## Quick description
agricraft crops don't check if biome growth controls let that crop grow in that biome

## Related issues and searches
tried 'biome' and 'control' into the search for this repo but nothing about the mod in question comes up

## Mods and versions used
* Minecraft:1.12.2
* AgriCraft:2.12.0-1.12.2-b2
* InfinityLib:1.12.1
* biome growth control:1.2.0

## Steps to replicate the issue
1. load up the game with bgc and agricraft's default configs
2. Place wheat in cropsticks on farmland in a river biome (or any crop in a biome it doesn't belong in)
3. after a bit the wheat should still grow

## Expectations and explanations
wheat should only be growing in the biomes specified in bgc's config

## Your environment

* How are you playing?
  * Operating System: windows 10
  * Launcher: overwolf's curse app
  * Modpack: custom made (UHP is the title)
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
no crash here, just a mod compact issue

## Screenshots (or videos)
![2021-06-18_03 53 32](https://user-images.githubusercontent.com/35241068/122535146-e407a280-cfe8-11eb-9861-180e59946f50.png)

**Comment by InfinityRaider** [comment]
It's not something that I have implemented.
I could have a look at implementing compat for that mod.

**Comment by InfinityRaider** [comment]
Wait, this is 1.12...
