### ISSUE TITLE
Better indication of light level in JEI Growth requirements tab

### ISSUE THREAD

**Issue by edotenseilove** [AgriCraft/AgriCraft#1352]
Hello, is it possible to add a numeric representation for light level requirements in JEI Growth requirements tab for example min light max light for a plant which would be updated by the selected strength stat? I think it would be great addition for the future because counting those small boxes is a little hard.

**Comment by InfinityRaider** [comment]
I will not add a numeric value to the JEI page, but I could add it in a tooltip.
