### ISSUE TITLE
Dedicated server crash on startup. (after/during world load)

### ISSUE THREAD

**Issue by CharlieUniformNovemberTango** [AgriCraft/AgriCraft#1356]
Crash on dedicated server with Integrated mods and agricraft

## Mods and versions used
* Minecraft: 1.16.5
* AgriCraft: 3.0.2
* InfinityLib: 2.0.4
* Forge: 36.1.30
* CommonCapabilities-1.16.5-2.7.0
* CyclopsCore-1.16.5-1.11.7
* IntegratedCrafting-1.16.5-1.0.15
* IntegratedDynamics-1.16.5-1.8.4
* IntegratedTerminals-1.16.5-1.2.4
* IntegratedTunnels-1.16.5-1.8.1
* Pretty large modpack 146 mods total

## Steps to replicate the issue
Only happens with the old server updated and with agricraft added.
Fresh install withouot prior world or other mods doesn't trigger crash.

## Your environment

* How are you playing?
  * Operating System:
  * Launcher:
  * Modpack:
* What kind of server:
  * [ ] Singleplayer
  * [x] Dedicated server

[debug-1.log](https://github.com/AgriCraft/AgriCraft/files/6682029/debug-1.log)

**Comment by InfinityRaider** [comment]
Report to CyclopsCore

**Comment by CharlieUniformNovemberTango** [comment]
Done

**Comment by InfinityRaider** [comment]
Thanks, we'll need to wait for a response from them to know what's going on.

**Comment by Hiranus** [comment]
Please release update with this.

**Comment by InfinityRaider** [comment]
Apparently fixed in https://github.com/InfinityRaider/InfinityLib/commit/32c0ce06eaaeb9419cd343dadd0ed4215479ad26
