### ISSUE TITLE
IInventory and IItemHandler share a method with the same signature

### ISSUE THREAD

**Issue by Her02N0one** [AgriCraft/AgriCraft#1358]
## Quick description
when you try to look at a seed analyzer with a seed in it, with the Jade mod installed, it crashes the game.
I posted this earlier but I forgot to format it. I wrote it on my phone, so the template didn't come up.

## Mods and versions used

* Minecraft: 1.16.5
* AgriCraft: 3.0.2
* InfinityLib: 2.0.4
* Jade 🔍: 2.7.1

## Steps to replicate the issue

1. Loaded up a new world
2. Placed a seed analyzer
3. Right-clicked with Agricraft seed on the seed analyzer
4. Game freezes for a few seconds and then crashes.

## Expectations and explanations
The game shouldn't crash. And perhaps the mod could even support Jade, which is a fork of HWYLA, to display block info.

## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: Curseforge
  * Modpack: Custom testing modpack, just Jade Agricraft and Infinitylib
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [X] An existing save

## Links to crash logs, stack traces, etc

* Crash: https://ghostbin.co/paste/733u
* Log:    https://ghostbin.co/paste/rrq4

**Comment by InfinityRaider** [comment]
Don't think this has anything to do with Jade.
I've discovered MCP mapped IInventory and Forge IItemHandler both have a method getStackInSlot(int), however the former will get obfuscated while the latter doesn't, so at compile time, this method's implementation is missing.
This will be a bother to fix, and it's a critical issue too.

**Comment by InfinityRaider** [comment]
Fixed with https://github.com/InfinityRaider/InfinityLib/commit/18c6f217fb62eac1fa576b39be4e0ef15dc31fc9
