### ISSUE TITLE
Can't breed chickens with seeds

### ISSUE THREAD

**Issue by ElementW** [AgriCraft/AgriCraft#1359]
## Quick description
AgriCraft seeds can't be used to breed chickens like regular MC seeds do.

## Related issues and searches
Croptopia [recently added chicken breeding support for its seeds through the use of mixins](https://github.com/ExcessiveAmountsOfZombies/Croptopia/commit/28078eb62a57f9b989e9e18ce4dd956f2166cefb#diff-2e69369ccc9229fcabccb81ada9fe01d8a911539149a6d13922636d5e3285aabR10).
Not using Mixins may require the use of Forge's [Access Transformers](https://mcforge.readthedocs.io/en/latest/advanced/accesstransformers/).
AgriCraft doesn't seem to mention any animal's `BREEDING_INGREDIENT`, and since chickens' is by default a static list of `Items.WHEAT_SEEDS, Items.MELON_SEEDS, Items.PUMPKIN_SEEDS, Items.BEETROOT_SEEDS` (Mojang should've made and used a `minecraft:seeds` tag), AgriCraft seeds do not work.

## Mods and versions used
* Minecraft: 1.16.5
* AgriCraft: 3.0.2
* InfinityLib: 2.0.4

## Steps to replicate the issue
1. Get vanilla & AC seeds
2. Try and breed chickens

## Expectations and explanations
Expected chickens to be able to breed with AC seeds since they essentially replace vanilla seeds.

**Comment by InfinityRaider** [comment]
Very valid issue, I will correct this for the next release.
And I won't be using mixins nor ATs, but instead some good old fashioned reflection.
