### ISSUE TITLE
Crops invisisble on dedi server, debugger server ctd 

### ISSUE THREAD

**Issue by Khitiara** [AgriCraft/AgriCraft#1360]
## Quick description
Crops are invisible when playing on a dedicated server, debugger in feedback mode causes server crash with https://pastebin.com/MnepHRWw

logs: https://gist.github.com/Khitiara/40d0782d5426d9f07cab97c8e41a95b2

## Related issues and searches
None found

## Mods and versions used

* Minecraft: 1.16.5-forge36.1.0
* AgriCraft: 3.0.2 (metadata erroneously reports as 3.0.1 in multimc)
* InfinityLib: 2.0.4

## Steps to replicate the issue

1. Loaded up a dedi server and connected
2. Tilled and placed crop sticks
3. Planted any seed. No plant renders
4. Used debugger in feedback mode, server crashes to desktop (client still up)

## Your environment

* How are you playing?
  * Operating System: Windows
  * Launcher: MultiMC
* What kind of server:
  * [ ] Singleplayer
  * [x] Multiplayer
* Game Modes:
  * [x] Survival
  * [x] Creative
* Save File:
  * [x] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc

* https://gist.github.com/Khitiara/40d0782d5426d9f07cab97c8e41a95b2

## Screenshots (or videos)
* https://cdn.discordapp.com/attachments/230709955324280832/857345569235533844/MMTD9bJjex.mp4

**Comment by DAmNRelentless** [comment]
This is still a thing in the newest version.

**Comment by InfinityRaider** [comment]
I can not replicate this in dev.
Please create a specific issue for this with explicit mention of:
 - AgriCraft & InfinityLib versions
 - Forge version
 - Method of playing (SP, Ded. Server, LAN, etc)
 - Other mods present
 - Does it still happen in an isolated instance (only AgriCraft + InfinityLib)

Basically, use the template.
