### ISSUE TITLE
Dedicated server crash on place analyzer block

### ISSUE THREAD

**Issue by Khitiara** [AgriCraft/AgriCraft#1361]
## Quick description
WTTS

## Related issues and searches
None found

## Mods and versions used

* Minecraft: 1.16.5
* AgriCraft: 3.0.2
* InfinityLib: 2.0.4

## Steps to replicate the issue

1. Loaded up dedicated server
2. Placed seed analyzer block
3. No crash on reloading server, unknown why

## Your environment

* How are you playing?
  * Operating System:
  * Launcher:
  * Modpack: Custom
* What kind of server:
  * [ ] Singleplayer
  * [x] Multiplayer
* Game Modes:
  * [x] Survival
  * [ ] Creative
* Save File:
  * [x] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc

* https://gist.github.com/Khitiara/0c0487cf07c73d54a42a72d47c7a0547

**Comment by InfinityRaider** [comment]
Fixed by #1358
