### ISSUE TITLE
'Transfer pipe' and 'Transfer node' won't pop up in the JEI interface

### ISSUE THREAD

**Issue by autismusprime69** [AgriCraft/AgriCraft#1362]
I was making a mob farm that involves the use of drawers and a vacuum chest. In order for it to work properly, I have to use transfer pipes and nodes for items (I tried to use item conduits from Ender IO but they didn't work properly). But when I go to JEI to look for the items they don't pop up, I looked in the recipe for the retrieval nodes and saw that they require the use of transfer nodes. You can guess what I did next and how it turned out.
Please fix this issue, it's really annoying and game-breaking!

**Comment by InfinityRaider** [comment]
Explain exactly how this is agricraft's fault.
Also there is a template for issues.
