### ISSUE TITLE
Crops are unknown?

### ISSUE THREAD

**Issue by agentwolf88** [AgriCraft/AgriCraft#1364]
I use the mod "Jade" to know what i looking at. But all crops of Pams Harvestcraft are unknow. Is this a bug?

![2021-06-30_13 14 35](https://user-images.githubusercontent.com/9948479/123952220-fb11a180-d9a5-11eb-9f51-dfc0d1fa4216.png)

**Comment by InfinityRaider** [comment]
Nope, there just isn't compat between agricraft and jade

**Comment by GeorgeOrwell1** [comment]
Use [Wasaila](https://www.curseforge.com/minecraft/mc-mods/wasaila) instead.
