### ISSUE TITLE
Will not load with Better Weather

### ISSUE THREAD

**Issue by Sixdd6** [AgriCraft/AgriCraft#1367]
## Quick description
Game complains about needing version 2.0 of Better Weather when loading. I attempted every version of BW 2.0 that exists and none worked.

## Mods and versions used
Minecraft: 1.16.5
Forge: 36.1.32
AgriCraft: 3.0.3
InfinityLib: 2.0.5
Better Weather: 2.0

## Steps to replicate the issue
Install versions listed above and upon load, game complains about Better Weather version.

## Expectations and explanations
Expected it to load.

## Your environment
* How are you playing?
  * Operating System: Windows 11 Dev Build
  * Launcher: GD Launcher

## Links to crash logs, stack traces, etc
[latest.log](https://github.com/AgriCraft/AgriCraft/files/6756742/latest.log)

**Comment by agentwolf88** [comment]
Same.

**Comment by InfinityRaider** [comment]
Which version are you using exactly?

**Comment by InfinityRaider** [comment]
Ok, I see, BW2's version string is weird.
You'll need to go ask corgitaco to properly version their mod i.e. <major>.<minor>.<patch> instead of having a whole"BETA_Vx" suffix, so FML's dependency checker can actually recognize the version.

**Comment by CorgiTaco** [comment]
This is problem bc of my uhhh registry hacks probably: https://github.com/CorgiTaco/Better-Weather/blob/Forge-1.16.X/src/main/java/corgitaco/betterweather/mixin/server/world/MixinServerWorld.java#L78-L92

@agentwolf88 @Sixdd6 make sure you're using beta 4, the log specifies beta 3.

**Comment by InfinityRaider** [comment]
I think it's the version string in the mods.toml, I think that due to the beta suffix, Forge's version check fails to parse the versioning.

**Comment by CorgiTaco** [comment]
Fixed here: https://www.curseforge.com/minecraft/mc-mods/better-weather/files/3391170

**Comment by InfinityRaider** [comment]
Thanks!
