### ISSUE TITLE
Crash report/ mod compatibility issue with botanypots

### ISSUE THREAD

**Issue by Shotguun29** [AgriCraft/AgriCraft#1369]
https://gist.github.com/Shotguun29/77fe6487cc5526be3dee377b22a30623

**Comment by Shotguun29** [comment]
crashed with BotanyPots-1.16.5-7.0.17.jar
Release
1.16.5
but it works with BotanyPots-1.16.5-7.1.23.jar
Beta
1.16.5
idk what you wanna do with said info

**Comment by InfinityRaider** [comment]
You need the beta version.
