### ISSUE TITLE
Client crop rendering issue in multiplayer environment

### ISSUE THREAD

**Issue by DAmNRelentless** [AgriCraft/AgriCraft#1370]
## Quick description
In a multiplayer environment, the plants inside crop sticks are not rendered for some clients.

## Related issues and searches
* https://github.com/AgriCraft/AgriCraft/issues/1360

## Mods and versions used
* Minecraft: 1.16.5
* Forge: 36.1.32
* AgriCraft: 3.0.3
* InfinityLib: 2.0.5
* JEI, TheOneProbe, Mystical Agriculture

## Steps to replicate the issue
1. Loaded up a new world in Singeplayer and opened the world to LAN
2. Another player joins
3. Tilled some dirt to get farmland with water in the block next to it
4. Placed cropsticks
5. Placed Wheat seeds inside the crop sticks

## Expectations and explanations
The placed seeds/the plant is only visible for the host (me in that case). The other player can't see it.
Even after breaking it and using a different block space, the same thing happens.
We also tried it when the other player placed the seed. Only the host is able to see the plant even if they didn't place it.

## Your environment

* How are you playing?
  * Operating System: Windows 10 Pro
  * Launcher: GDLauncher
  * Modpack: own small collection of mods
* What kind of server:
  * [ ] Singleplayer
  * [X] Multiplayer (LAN)
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
no log messages after joining the world

## Extra information
I am coming from the original AgriCraft mod in 1.7.10. I also played the beta version in 1.12 which was missing some features. I am glad you returned to the mod and a lot has changed in 1.16. I am still trying to get used to it.
What also confuses us is that right-clicking the middle of the crop sticks doesn't work anymore if you want to place the seeds. You have to click one of the sticks directly. I guess that's because the hitbox only contains the sticks now and not the whole block space anymore. I hope this will be changed again in the future.

**Comment by InfinityRaider** [comment]
Does this only happen for players joining from LAN, or is the host affected as well?

You should definitely be able to plant a seed on crop sticks by clicking the soil underneath.

**Comment by DAmNRelentless** [comment]
The plant is always visible for the host no matter who planted it and it's invisible for any player who joined the session.

Alright, I will retry it then.

**Comment by DAmNRelentless** [comment]
We were able to reproduce the issue with the planting.
If you use the vanilla Wheat seeds, you are not able to click directly on the soil to plant them. However, it works when you click one of the crop sticks.
But if you are using the AgriCraft Wheat seeds, you can directly click on the soil and it will plant correctly.

So either this is an issue with the vanilla seeds because they are not analyzed yet or the seeds are not automatically converted to AgriCraft seeds when clicking on the soil. And if it's not even intended that is plantable without analyzing, it's probably a bug that you are able to plant them by clicking on the crop sticks with it.
This happens for all vanilla seeds, not just Wheat.

**Comment by InfinityRaider** [comment]
Thanks for informing of these issues, however, next time, please open a separate issue for each one. 
(I have already fixed the conversion issues when clicking soil below crop sticks and when inserting in an analyzer, so no need to open a new issue this time).

I will need to experiment a bit to fix the LAN issue though...
