### ISSUE TITLE
Animation config options

### ISSUE THREAD

**Issue by DAmNRelentless** [AgriCraft/AgriCraft#1371]
## Quick description
The current behaviour of the Journal and the Analyzer is a bit odd in my opinion. The animations when you are trying to access them are pretty laggy or at least there is some flickering. They also take an unnecessary amount of time.

## Mods and versions used
* Minecraft: 1.16.5
* Forge: 36.1.32
* AgriCraft: 3.0.3
* InfinityLib: 2.0.5
* JEI, TheOneProbe, Mystical Agriculture

## Steps to replicate the issue
Access the Seed Analyzer or the Journal.

## Expectations and explanations
I think it would be a cool thing to have client config options to disable those animations.
Right now, it's not really necessary to have an animated Journal because there are only 2 pages anyways.
I kinda get the idea for it when speaking about the Seed Analyzer but it makes me pretty uncomfortable to see that flickering.
Maybe it could be done like the Vanilla bed, when the config option for the animation is disabled. Directly teleport the view into the Seed Analyzer instead of an animation.

## Your environment
* How are you playing?
  * Operating System: Windows 10 Pro
  * Launcher: GDLauncher
  * Modpack: own small collection of mods
* What kind of server:
  * [X] Singleplayer
  * [X] Multiplayer (LAN)
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
no log messages after joining the world

## Screenshots (or videos)
[apparently GitHub doesn't like embedding GIFs](https://i.imgur.com/VNMZoyf.gif)

**Comment by InfinityRaider** [comment]
Is that flickering happening both in SP and MP?

**Comment by DAmNRelentless** [comment]
Yes, looks like the camera movement is colliding with the player model and it flickers when it's passing through the texture.
But the last flickering happens when the movement is close before the Analyzer. It seems to quickly rotate 90 degrees and then instantly switch back.

**Comment by GeorgeOrwell1** [comment]
Definitely second this.
