### ISSUE TITLE
Game freazes when agricraft 1.16.5 presend and game dont run

### ISSUE THREAD

**Issue by Liso7150** [AgriCraft/AgriCraft#1373]
## Related issues and searches

* https://github.com/AgriCraft/AgriCraft/issues?q=is%3Aissue%20EXAMPLE

## Mods and versions used

* Minecraft:
* AgriCraft:
* InfinityLib:
* [List the other required mods here]

## Steps to replicate the issue

1. Loaded up `...`
2. Placed a `...`
3. Right-clicked with `...` on `...`
4.

## Your environment

* How are you playing?
  * Operating System:
  * Launcher:
  * Modpack:
* What kind of server:
  * [ ] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [ ] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc

* https://gist.github.com/
* https://paste.ee/
* https://duckduckgo.com/?q=pastebin+alternatives
* Upload them somewhere, and then replace these links.

**Comment by InfinityRaider** [comment]
This report is as useful as an inflatable darts board.
The template exists to be actually used, not just thrown into the issue.
Get a log, crash report, whatever and then open a new issue according to the template.
Thanks.

**Comment by Liso7150** [comment]
> 
> 
> This report is as useful as an inflatable darts board.
> The template exists to be actually used, not just thrown into the issue.
> Get a log, crash report, whatever and then open a new issue according to the template.
> Thanks.

i Eddited it still
