### ISSUE TITLE
Game freezes when starts with Agricraft 3.0.3

### ISSUE THREAD

**Issue by Liso7150** [AgriCraft/AgriCraft#1374]
## Quick description
I turned on my modpack with agricraft and it dont run.
https://i.imgur.com/0VaX3RS.png

## Related issues and searches
* https://gnomebot.dev/api/guild/file/166630061217153024/254806806516203520/861883095748444170/message.txt?lines=1 - 
threaddump from VisualVM

## Mods and versions used

* Minecraft: 1.16.5
* AgriCraft: 3.0.3
* InfinityLib: 2.0.5
* agricraft-optifine-compat: 0.0.1
* Optifine: 1.16.6_HD_U_G8_MOD

## Steps to replicate the issue

1. Instaled mods Pack: https://mega.nz/file/ZL4kEKzB#MAC-FuaCVwWqENG02LnUwpg59c5rG1AsKGiPacQU7rs
2. Turn on MC normal mc start up launcher curseforge.
3. Game Freezes SS: https://i.imgur.com/0VaX3RS.png
4. Turn on VisualVS 
threaddump: https://gnomebot.dev/api/guild/file/166630061217153024/254806806516203520/861883095748444170/message.txt
WithLines: https://gnomebot.dev/api/guild/file/166630061217153024/254806806516203520/861883095748444170/message.txt?lines=1
Errors: https://gnomebot.dev/api/guild/file/166630061217153024/254806806516203520/861883095748444170/message.txt?errors=1

## Expectations and explanations
Agricraft 1.16.5 is somehow dead locking while trying to print a log message to the console

## Your environment

* How are you playing?
  * Operating System: Windows 11 dev bulid: 22000.51 co_release
  * Launcher: Curseforge
  * Modpack: https://mega.nz/file/ZL4kEKzB#MAC-FuaCVwWqENG02LnUwpg59c5rG1AsKGiPacQU7rs
{* What kind of server:
  * [ ] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [ ] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save} - any game dont run by dead locking console

## Links to crash logs, stack traces, etc
#VisualVM threaddump
* https://gnomebot.dev/api/guild/file/166630061217153024/254806806516203520/861883095748444170/message.txt
* Version With Lines https://gnomebot.dev/api/guild/file/166630061217153024/254806806516203520/861883095748444170/message.txt?lines=1
* Only Errors https://gnomebot.dev/api/guild/file/166630061217153024/254806806516203520/861883095748444170/message.txt?errors=1
#Log
* https://gnomebot.dev/api/guild/file/166630061217153024/254806806516203520/861871401458466856/latest.log
* Version With Lines https://gnomebot.dev/api/guild/file/166630061217153024/254806806516203520/861871401458466856/latest.log?lines=1
* Only Errors https://gnomebot.dev/api/guild/file/166630061217153024/254806806516203520/861871401458466856/latest.log?errors=1
## Screenshots (or videos)
https://i.imgur.com/0VaX3RS.png

**Comment by InfinityRaider** [comment]
Does this also happen without Optifine and without the compat mod?

**Comment by InfinityRaider** [comment]
Second question, are you using better weather, if so does it run without BW?

**Comment by Liso7150** [comment]
> 
> 
> Does this also happen without Optifine and without the compat mod?

yes it happen

**Comment by Liso7150** [comment]
> 
> 
> Second question, are you using better weather, if so does it run without BW?

i not using it but it steal freazes

**Comment by Liso7150** [comment]
Whole pack u have in link so u can see mods intall: cursforge import zip

**Comment by InfinityRaider** [comment]
I'm not going to install a modpack to debug an issue.

**Comment by InfinityRaider** [comment]
> 
> 
> > Does this also happen without Optifine and without the compat mod?
> 
> yes it happen

Give me a log without Optifine, without the Optifine fix mod, and without Serene Seasons

**Comment by InfinityRaider** [comment]
Additionally, I would like you to test if this happens on a clean install with just agricraft and InfinityLib as well.

**Comment by InfinityRaider** [comment]
My best guess is some other mod is using org.reflections as well, but with a different logger.
I have tried to disable any logging from org.reflections, but it is not certain it will work (race conditions you know).
It is impossible for me to figure out which mod is doing that to try to work with them, that part will be up to you.
I suggest doing a binary search until you find which mod in combination with agricraft causes this.

**Comment by InfinityRaider** [comment]
Can you try with 3.0.4 to see if this has been resolved?
https://www.curseforge.com/minecraft/mc-mods/agricraft/files/3379947

**Comment by InfinityRaider** [comment]
Closing due to lack of response
