### ISSUE TITLE
Trouble loading some textures with Chlorine 

### ISSUE THREAD

**Issue by Mopaseo** [AgriCraft/AgriCraft#1376]
## Quick description

The textures of 8 items from vanilla Minecraft (melon seeds, pumpkin seeds, wheat seeds, carrots, nether warts, potato, beets and wheat) won't load using the Chlorine mod version 0.0.1.3 . Problem is that without the Agricraft mod, Chlorine doesn't face any problem to load these textures.

## Related issues and searches

I couldn't find any related problems with Chlorine and Agricraft.

## Mods and versions used

* Minecraft: 1.16.5 for Forge 36.1.10
* AgriCraft: 3.0.2
* InfinityLib: 2.0.4
* Chlorine: 0.0.1.3

## Steps to replicate the issue

1. Simply launch Minecraft with the mods listed here, no special steps to follow.

## Expectations and explanations

Obviously these are some pretty common and important items that we can use a lot, so being able to see them would be better even though it's only a small inconvenience.

## Informations that could be useful
I'm pretty sure it's client sided since this bug appears in singleplayer and multiplayer and with or without mods. I also tried enabling the debug setting in the configs but it didn't give me anything. Chlorine is also a pretty great mod because it's a Forge version of the Sodium mod on Fabric and since Optifine doesn't support a lot of mods, Chlorine is a really good alternative.

## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: Minecraft Launcher
  * Modpack: No specific modpacks 
* What kind of server:
  * [X] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [X] Only an existing save

## Links to crash logs, stack traces, etc

No crashes, just a small in game inconvenience.

## Screenshots (or videos)

![2021-07-07_22 33 58](https://user-images.githubusercontent.com/86983903/124834876-ba56f100-df80-11eb-9eec-295aea1851bd.png)
(I use JEI on the screenshot, but after trying without it, the bug didn't go away even after creating a new world)

**Comment by InfinityRaider** [comment]
Does it load them for the vanilla variants?
Does it load the block textures (try planting them)?

**Comment by Mopaseo** [comment]
The textures have no problem loading in vanilla with forge, with Agricraft only and Chlorine only, but the problem happens when the two mods are together. But I did more texting and i just realised that the vanilla variant of the items load too using the mods, but the items also have an agricraft variant that doesn't load.
![2021-07-08_13 04 33](https://user-images.githubusercontent.com/86983903/124911514-1e170380-dfed-11eb-9aca-5971e2b0d376.png)
![2021-07-08_13 04 36](https://user-images.githubusercontent.com/86983903/124911523-20795d80-dfed-11eb-9593-bce2f652c4ae.png)
The carrot and the potato in the inventory are the vanilla variants that can load in.

I also used JEI to have the agricraft variants, and when hovering over the bugged items, they have the "Agricraft" Tag and not the "Minecraft" one. So the bug comes with the Agricraft variant of the items and it's these variants that spawn in the world, because when i break grass in survival, i only get agricraft wheat seeds that don't load.
![2021-07-08_13 14 07](https://user-images.githubusercontent.com/86983903/124912640-7ef30b80-dfee-11eb-9a61-53ffdc37fabc.png)
![2021-07-08_13 14 32](https://user-images.githubusercontent.com/86983903/124912651-81556580-dfee-11eb-8afc-d214269386d6.png)

Also, the wheat and beet items are the only items that have the "Minecraft" tag and also don't load in, but these 2 items loaded in perfectly without Agricraft earlier, so the mod probably has an impact on the items as well.
![2021-07-08_13 20 25](https://user-images.githubusercontent.com/86983903/124913322-47d12a00-dfef-11eb-900c-d390eb8df16d.png)

Ok and finally, I planted a carrot seed from agricarft, 2 wheat seeds one from vanilla minecraft and the other from Agricraft and finally a carrot from vanilla minecraft, and every single one of them was bugged.
![2021-07-08_13 24 00](https://user-images.githubusercontent.com/86983903/124914703-f32eae80-dff0-11eb-9316-2b90cc8a19f7.png)

After that I reloaded that same world but without Chlorine and the bug was still here, I then created a new world without the Chlorine Mod and even without it the bug was still here somehow??? So I thought the bug actually came from JEI since i was using it, so got rid of it leaving me with only agricraft and infintylib. I started breaking grass and the wheat seeds i found where loading perfectly until i planted them. When i planted them, the textured bugged once again this time without any other mod.
![2021-07-08_13 56 51](https://user-images.githubusercontent.com/86983903/124917659-5f5ee180-dff4-11eb-9343-cca5a7bf836c.png)

So now i believe that there is a bug with Agricraft, that seems to get worse with the Chlorine mod i suppose, i'm really confused.

I'm so sorry it's pretty long but i'm just trying to give as much info as possible.

**Comment by InfinityRaider** [comment]
That's ok, more information is better.
Are you using any resource packs?

**Comment by InfinityRaider** [comment]
Ok, so on a fresh profile, with just Minecraft, agricraft, InfinityLib and perhaps JEI (this shouldn't matter), does it occur as well?
Or does it only occur on profiles where Jade has been installed?

**Comment by Mopaseo** [comment]
tried it twice and it also occurred with agricraft and infinitylib only.

**Comment by InfinityRaider** [comment]
Ok I'm going to need a log, it should complain able missing models / textures somewhere

**Comment by Mopaseo** [comment]
Of course but where can I find it, I'm not that good with mod files and stuff like that, so let me know what I can do and i'll send it to you

**Comment by InfinityRaider** [comment]
CLosing due to lack of replies
