### ISSUE TITLE
The Game Crashes When AgriCraft Installed

### ISSUE THREAD

**Issue by Charlobo** [AgriCraft/AgriCraft#1381]
## Quick description
When Agricraft in modpack, game just freeze and cant normaly exit. 
When join in my server, the game just crashes.

## Related issues and searches
I think this bug it similar to this issue
https://github.com/AgriCraft/AgriCraft/issues/1374
The game freezes when agricraft in it
* https://github.com/AgriCraft/AgriCraft/issues?q=is%3Aissue%20EXAMPLE

## Mods and versions used

I think this only happens when agricraft in, I checked my other mods.
* Minecraft:1.16.5
* AgriCraft:3.0.3
* InfinityLib:2.0.5
* abnormals_core-1.16.5-3.2.0.jar
abnormals_delight-1.16.5-1.1.1.jar
agricraft-3.0.3.jar
AutoRegLib-1.6-49.jar
BetterAnimationsCollection-v1.2b3-1.16.5.jar
BetterCaves-Forge-1.16.4-1.1.2.jar
BetterHurtTimer-1.16.3-4.5.2.2.jar
BetterMineshafts-Forge-1.16.4-2.0.4.jar
BetterThirdPerson-Forge-1.16.4-1.5.1.jar
callablehorses-1.16.3-1.2.1.4.jar
carryon-1.16.5-1.15.5.15.jar
charm-forge-1.16.5-2.3.2.jar
charmonium-forge-1.16.5-2.3.2.jar
cloth-config-4.11.26-forge.jar
create-mc1.16.5_v0.3.1c.jar
DripSounds-0.2.1-1.16.jar
DynamicSurroundings-1.16.4-4.0.4.2.jar
EasyMagic-v1.0.2-1.16.5.jar
ElenaiDodge-1.16.2-1.7.2.jar
Fallingleaves-1.16.3-1.1.1.jar
FarmersDelight-1.16.5-0.4.5.jar
farmersreplant-1.16.5-1.0.jar
farsight-1.5.jar
FastFurnace-1.16.4-4.4.0.jar
FirstPersonMod-2.0.1.jar
Fruitful-1.16.5-2.1.0.jar
HardcoreRevival_1.16.5-5.2.1.jar
horsecombatcontrols-1.16.5-1.0.3.jar
Infinitylib-2.0.5.jar
jei-1.16.5-7.7.0.107.jar
JustEnoughCharacters-1.16.4-4.3.0.jar
Kiwi-1.16.5-3.5.2.jar
LIST.TXT
locks-1.16.5-3.0.3.jar
notenoughanimations-1.2.4.jar
parrying-1.10.0.jar
personality-1.16.5-1.0.2.jar
Placebo-1.16.4-4.5.0.jar
PuzzlesLib-v1.0.7-1.16.5.jar
Quark-r2.4-314.jar
RealisticExplosionPhysics-1.16.5-1.0.0.jar
shieldmechanics-1.9-1.16.5.jar
smoothboot-forge-1.16.4-1.2.2.jar
SnowRealMagic-1.16.4-2.5.7.jar
SoundFilters-0.14_for_1.16.2.jar
SpartanShields-1.16.5-2.1.2.jar
SpartanWeaponry-1.16.4-2.1.0-beta-4.jar
Spheric+1.0.3+1.16.5.jar
spiders-2.0-1.16.4-1.0.4.jar
subwild-1.2.1.jar
sworddisplay-1.16.5-1.2.0.jar
TRansliterationLib-1.0.4.jar
twoplayersonehorse-1.16.4-2.0.2.jar
upstream-1.0.jar
veldmg-1.16.5-1.0.0.jar
WeaponThrow-1.16.4-4.2.jar
xercapaint-1.16.5-1.0.jar
YungsApi-1.16.4-Forge-6.jar

## Steps to replicate the issue
The game just freezes, I couldn't do anyting. And the game wont properly exits. When gettin to a server, the game just crashes.

## Expectations and explanations
This bug only happens on client side, according to the crash report, I think it's something relate to wrong recipe and class load?

## Your environment
 PC
* How are you playing?
  * Operating System:Windows 10
  * Launcher:
  * Modpack:
* What kind of server:
  * [√ ] Singleplayer
  * [√] Multiplayer
* Game Modes:
  * [√] Survival
  * [√] Creative
* Save File:
  * [√] Brand new save
  * [√] Only an existing save

## Links to crash logs, stack traces, etc

https://gist.github.com/Charlobo/ffefda49e22175066182674f128e6d65

**Comment by nbrichau** [comment]
As once InfinityRaider said : 
This report is as useful as an inflatable darts board.
The template exists to be actually used, not just thrown into the issue.

Please give at least a crash report and agricraft version.

**Comment by Charlobo** [comment]
> As InfinityRaider once said :
> This report is as useful as an inflatable darts board.
> The template exists to be actually used, not just thrown into the issue.
> 
> Please give at least a crash report and agricraft version.

Sry, I accidentally sent the text of the draft box. I didn't mean to just send these messages. I'll make it right.

**Comment by nbrichau** [comment]
Does this also happen without Optifine ?

**Comment by Charlobo** [comment]
> 没有 Optifine 也会发生这种情况吗？

I haven't tried that, but I will test it tomorrow.  Thank you for the reply.

**Comment by Charlobo** [comment]
> 没有 Optifine 也会发生这种情况吗？

It still happens without Optifine, but it works perfect with AgriCraft OptiFine Compat. Thank you for the reply, the problem seems solved. Sorry for any inconvenience caused to you, hope u have a nice day.
