### ISSUE TITLE
the one probe - interface bug

### ISSUE THREAD

**Issue by NiceClown** [AgriCraft/AgriCraft#1383]
my english is too bad, I'll attach a video yet.
last version forge and AgriCraft. 
If we change the magnifying glass on the quick access panel to any other slot, then we will be able to see everything as if we were still looking through a magnifying glass (by the way, it would be a cool idea to add special glasses so that the seeds are constantly in the analysis)
https://youtu.be/z1vXYpmLFvc

**Comment by InfinityRaider** [comment]
Thanks for the bug report.

I might add an anvil recipe to add magnifying glass to helmets to have that effect instead, good idea.
