### ISSUE TITLE
16.5 loading issue with Botany Pots

### ISSUE THREAD

**Issue by OceanSnipe17** [AgriCraft/AgriCraft#1385]
When loading it fails with the error of "java.lang.ClassNotFoundException: net.darkhax.botanypots.api.events.PotGrowCropEvent$Pre"

Tested with fresh mod pack consisting of just Agricraft and Botany pots.

Using MC 1.16.5
Forge 36.2.0
Agricraft 3.0.4
Botany Pots 7.0.17

**Comment by InfinityRaider** [comment]
Needs at least 7.1.20
