### ISSUE TITLE
Botany Pots compat 1.16.5

### ISSUE THREAD

**Issue by someguyfromdownthestreet** [AgriCraft/AgriCraft#1386]
loading the two mods together i ran into issues havent tested with just these two mods yet will comment on this post after testing it 

"Agricraft (agricraft) encountered an error during the common_setup event phase
java.lang.NoClassDefFoundError: net/darkhax/botanypots/api/events/CropPlaceEvent$Post"

[crash-2021-07-26_14.35.27-fml.txt](https://github.com/AgriCraft/AgriCraft/files/6875664/crash-2021-07-26_14.35.27-fml.txt)

crossposted to other mods github:
https://github.com/Darkhax-Minecraft/BotanyPots/issues/177

**Comment by someguyfromdownthestreet** [comment]
tested with exclusively these two mods
[crash-2021-07-26_14.58.58-fml.txt](https://github.com/AgriCraft/AgriCraft/files/6875694/crash-2021-07-26_14.58.58-fml.txt)

**Comment by InfinityRaider** [comment]
Have you seen #1385 ?
