### ISSUE TITLE
Agricraft / Infinitylib "disabling" third person animations from other mods

### ISSUE THREAD

**Issue by GeorgeOrwell1** [AgriCraft/AgriCraft#1390]
## Quick description

When Agricraft is present, mods that add various third-person animations ([for example eating animations](https://www.curseforge.com/minecraft/mc-mods/player-eating-animation)) are not functioning at all, while when Agricraft isn't present, they work as intended (see attached videos). Do note that this isn't only one mod, but all mods that add a kind of hand/head animation when performing various tasks (like [this one](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)).

## Mods and versions used

* Minecraft: 1.16.5
* AgriCraft: 3.0.4
* InfinityLib: 2.0.5
* Playereatinganimation-1.2 _**/**_ Notenoughanimations-1.2.4

## Steps to replicate the issue

1. Download Agricraft and Infinitylib as well as a mod that adds third person animations.
2. Load up a save (with the aforementioned mods).
3. Eat a food item.
4. Observe the animation.
5. Remove Agricraft and Infinitylib.
6. Load up the save again with the same food item.
7. Observe the difference.

## Expectations and explanations

I would have expected it to be so that the animation-adding mod shows the animation when Agricraft and Infinitylib are loaded.

## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: Vanilla
  * Modpack: Private
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [ ] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc

[latest.log](https://github.com/AgriCraft/AgriCraft/files/6949578/latest.log)

## Screenshots (or videos)

https://user-images.githubusercontent.com/72312697/128610502-14284aa5-c00c-4699-9f38-fd6e7f3108c3.mp4

_With Agricraft + InfinityLib_

https://user-images.githubusercontent.com/72312697/128610545-9fc9b084-4bcf-4618-83ec-db08e3d23a37.mp4

_Without Agricraft + InfinityLib_

**Comment by InfinityRaider** [comment]
Incompatibility between IL and another mod due to Forge not having the proper hooks for player animations, not much I can do there without breaking my own animations....

**Comment by GeorgeOrwell1** [comment]
So I should report this issue to Forge then? If so, what's exactly the problem?

**Comment by InfinityRaider** [comment]
No, they would need a PR
