### ISSUE TITLE
Incompatibility with Blur mod

### ISSUE THREAD

**Issue by GeorgeOrwell1** [AgriCraft/AgriCraft#1391]
## Quick description

As stated in the title, while Agricraft is present it removes the blurry background on all GUI menus which the [Blur](https://www.curseforge.com/minecraft/mc-mods/blur) mod adds.

## Mods and versions used

* Minecraft: 1.16.5
* AgriCraft: 3.0.4
* InfinityLib: 2.0.5
* Blur: 1.1.0-1

## Steps to replicate the issue

1. Open a GUI screen (for example the inventory) with and without Agricraft.
2. Notice the difference.

## Expectations and explanations

My expectations were that the Blur mod would work as intended, even when Agricraft was installed.

## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: Default
  * Modpack: Private
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [ ] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [X] Only an existing save

## Links to crash logs, stack traces, etc

[latest.log](https://github.com/AgriCraft/AgriCraft/files/6953216/latest.log)

## Screenshots (or videos)

![2021-08-09_11 05 16](https://user-images.githubusercontent.com/72312697/128683896-af68f183-db6d-48d5-9fd5-389aad9222cb.png)
![2021-08-09_11 08 12](https://user-images.githubusercontent.com/72312697/128683904-24b86c5d-886d-4baf-87e6-b394cb063479.png)

**Comment by InfinityRaider** [comment]
Not quite sure what AgriCraft does that could interfere with this

**Comment by iridium22** [comment]
error say its is ?

**Comment by InfinityRaider** [comment]
I meant code wise.

**Comment by Ketheroth** [comment]
I can't reproduce it with agricraft 3.0.4 and blur only. Are you sure it's caused by agricraft and not another mod you are using ?
