### ISSUE TITLE
[1.16.5] Rendering Ingredient Crash

### ISSUE THREAD

**Issue by Unhook** [AgriCraft/AgriCraft#1396]
Crash log: https://pastebin.com/jJubL15t

Using MC 1.16.5
Forge 36.2.2
Agricraft 3.0.5

**Comment by InfinityRaider** [comment]
Which seed is this

**Comment by virtualxtetris** [comment]
agricraft:agri_seed:mysticalagriculture:fiery_ingot_plan

**Comment by InfinityRaider** [comment]
Do you have Twilight Forest in your pack?

**Comment by virtualxtetris** [comment]
i have no twilight forest in pack

**Comment by InfinityRaider** [comment]
Ok then disable the fiery ingot seeds in its plant json (config/agricraft/jsons/mystical agriculture/plants) by setting enabled to false.

**Comment by virtualxtetris** [comment]
thanks work

**Comment by Ketheroth** [comment]
I've found the mod making agricraft crash. It's because of ConnectedTextureMod. You can disable this mod if you whant the fiery ingot seed.
I'm going to search if I can fix it in our side. I may have an idea of why it is crashing

**Comment by SGZ-Creations** [comment]
Our case sill has issues and can't be solve by any of the thing here so please reopen the case #1412
