### ISSUE TITLE
1.16.5 Server crash on startup

### ISSUE THREAD

**Issue by Realever** [AgriCraft/AgriCraft#1397]
Hi,
i would use your mod into my private modpack but the server crash on startup.I try it with my complete modpack and only agricrtaft and InfinityLib and the server crash.I play the minecraft version 1.16.5 and the forge version is 36.2.2

## Mods and versions used

* Minecraft: 1.16.5
* AgriCraft: 3.0.5
* InfinityLib: 2.0.6

## Your environment

* How are you playing?
  * Operating System: Linux server
  * Modpack: Private modpack
* What kind of server:
  * [ ] Singleplayer
  * [x] Multiplayer
* Game Modes:
  * [x] Survival
  * [ ] Creative

## Links to crash logs, stack traces, etc
https://paste.ee/p/eBcdi (private modpack)
https://paste.ee/p/QdYbn (without other mods)

**Comment by InfinityRaider** [comment]
Aight I'll try to push za fix ASAP
