### ISSUE TITLE
Agricraft 3.0.5 server crash 

### ISSUE THREAD

**Issue by virtualxtetris** [AgriCraft/AgriCraft#1399]
crash log: https://pastebin.com/KsYzaX5C

using MC:1.16.5
Forge 36.2.2
Agricraft 3.0.5

The new version crasht all time the server with the agricraft version 3.0.4 its work so i think its a problem from the new version

**Comment by InfinityRaider** [comment]
Are you using the hotfix from CurseForge?

**Comment by virtualxtetris** [comment]
ok with the new hotfix its work thanks
