### ISSUE TITLE
JEI 'Fiery Ingot Seeds' crash

### ISSUE THREAD

**Issue by laneyfamily** [AgriCraft/AgriCraft#1400]
Getting crash from JEI rendering seeds for 'Fiery Ingot Seeds'
Happens in single player and on a server new or old world all in survival
Forge 36.2.2
Minecraft 1.16.5
Mod Versions
 agricraft-3.0.5-hotfix.jar
 Infinitylib-2.0.6-hotfix.jar

Log: https://gist.github.com/laneyfamily/165cc5d24bbda29bb48284b88ff589bb

**Comment by InfinityRaider** [comment]
See #1396

**Comment by laneyfamily** [comment]
Quick and efficient, thank you! I'll follow recommendations
