### ISSUE TITLE
minecraft  crach 1.16.5 AgriCraft 3.0.4 and 3.0.5

### ISSUE THREAD

**Issue by iridium22** [AgriCraft/AgriCraft#1402]
## Quick description

crashe when i try start mc it say 

## Related issues and searches

AgriCraft (agricraft) encountered an error during the common_setup event phase
java.lang.NoClassDefFoundError:

(its all its say)

* https://github.com/AgriCraft/AgriCraft/issues?q=is%3Aissue%20EXAMPLE

## Mods and versions used

* Minecraft: 1.16.5
* AgriCraft: 3.0.4 and 3.0.5
* InfinityLib: 2,0,6
* [List the other required mods here]

## Steps to replicate the issue

1. Loaded up `no`
2. Placed a `...`
3. Right-clicked with `...` on `...`
4.

## Expectations and explanations
 start my modpack löl :P

## Your environment

* How are you playing?
  * Operating System: windows 10 64 bit

  * Launcher: curseforge
  * Modpack: my modpack cropblock
* What kind of server:
  * [ ] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [ ] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc

https://pastebin.com/h3Kr7FdK

## Screenshots (or videos)

  
 https://imgur.com/3LR6sLn

**Comment by iridium22** [comment]
https://imgur.com/3LR6sLn

**Comment by InfinityRaider** [comment]
Update botany pots to the latest version.

**Comment by iridium22** [comment]
lol you are king :D

**Comment by iridium22** [comment]
help ? https://pastebin.com/FVUd3KP3 ? :/
