### ISSUE TITLE
sorry my igen :p

### ISSUE THREAD

**Issue by iridium22** [AgriCraft/AgriCraft#1403]
## Quick description
 
i start minecraft but but if is searching ak my mc crach :p

## Related issues and searches

* https://github.com/AgriCraft/AgriCraft/issues?q=is%3Aissue%20EXAMPLE

## Mods and versions used

* Minecraft:1.16.5
* AgriCraft:3.0.4
* InfinityLib:2.0.6
* [List the other required mods here]

## Steps to replicate the issue

1. Loaded up `yes`
2. Placed a `jei searching`
3. Right-clicked with `...` on `...`
4.

## Expectations and explanations
 fine Akashic Tome in jei :( 
 if i typ ak i get a crach  
Display Name: agricraft.plant.mysticalagriculture.fiery_ingot

## Your environment

* How are you playing?
  * Operating System: windows 10 64 bit
  * Launcher: curseforge
  * Modpack: my new
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc

https://pastebin.com/ah2CSF5E

## Screenshots (or videos)

i cant is crach if i typ ak jei sorry :P

**Comment by InfinityRaider** [comment]
See #1396
