### ISSUE TITLE
Valid JSON plant definition doesn't seem to work for mystical agriculture infernium

### ISSUE THREAD

**Issue by tyggna** [AgriCraft/AgriCraft#1405]
## Quick description
JSON looks valid on mystic agriculture inferium plant, but see won't plant in crop sticks.

## Mods and versions used

* Minecraft: 1.16.5
* Forge: 1.16.5-36.2.1
* AgriCraft: 3.0.5-hotfix
* InfinityLib: 2.0.6-hotfix
* MysticalAgriculture: 4.2.2
* Cucumber-1.16.4-4.1.10

## Steps to replicate the issue

1. Create inferium farmland
2. Place agricraft crop sticks on it
3. Right-click with infernium seeds
4. Note how nothing happens

(this works with water seeds, which have an almost identical JSON definition, and JEI reports an agricraft version for water seeds but not inferium, what's more puzzling is that the logs say that the inferium_plant.json loads successfully)

## Expectations and explanations

Inferium seeds should work with agricraft

## Your environment
* How are you playing?
  * Operating System: Windows 10
  * Launcher: Technic
  * Modpack: Learn 2 Spell (I'm the maintainer of this, but I can reproduce the bugged behavior with only the listed mods above)
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc
Startup and console log: https://gist.github.com/tyggna/97f6a13d8cef685cf39a9559a1798906
inferium_plant.json (not working) next to water_plant.json (working), they're nearly identical: https://gist.github.com/tyggna/e6a7a4e5fd37cbf8ca87ac0face7c425

## Screenshots (or videos)
![2021-09-05_18 02 31](https://user-images.githubusercontent.com/36580742/132145031-c0516875-13e4-4640-b644-00a47ac55ca5.png)

**Comment by Ketheroth** [comment]
Yeah there are errors in other plant jsons that override the inferium plant
To fix it before a new version is released please go in your config folder and do this :
- In the file agricraft/json/defaults/mod_mysticalagriculture/plants/fire_plant.json, change the id value (line 11) to be "mysticalagriculture:fire_plant"   <-- will fix inferium seeds
- In the file agricraft/json/defaults/mod_mysticalagriculture/plants/basalt_plant.json, change the id value (line 11) to be "mysticalagriculture:basalt_plant"  <-- will fix aquamarine seeds

**Comment by tyggna** [comment]
> 
> 
> Yeah there are errors in other plant jsons that override the inferium plant
> To fix it before a new version is released please go in your config folder and do this :
> 
>     * In the file agricraft/json/defaults/mod_mysticalagriculture/plants/fire_plant.json, change the id value (line 11) to be "mysticalagriculture:fire_plant"   <-- will fix inferium seeds
> 
>     * In the file agricraft/json/defaults/mod_mysticalagriculture/plants/basalt_plant.json, change the id value (line 11) to be "mysticalagriculture:basalt_plant"  <-- will fix aquamarine seeds

That fixed it.  Thank you so much!  Maybe a warning about duplicate IDs would be a helpful feature in the future.
