### ISSUE TITLE
I/O Crash with hotfix version

### ISSUE THREAD

**Issue by CanBoy67** [AgriCraft/AgriCraft#1406]
## Quick description
The latest version 3.0.5-hotfix seems to have some sort of I/O error regarding the config, I've been able to circumvent this by downgrading to 3.0.4

## Related issues and searches

* https://github.com/AgriCraft/AgriCraft/issues?q=is%3Aissue%20EXAMPLE

## Mods and versions used

* Minecraft: 1.16.5
* AgriCraft: 3.0.5-hotfix
* InfinityLib: 2.0.6-hotfix
* [List the other required mods here]

## Steps to replicate the issue

1. Launch Minecraft
2. Wait a bit
3. Minecraft Crashes

## Expectations and explanations

For Minecraft to load like it's supposed to
## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: GDLauncher
  * Modpack: Custom Modpack
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc

*https://pastebin.com/YegqUqvz

**Comment by InfinityRaider** [comment]
Try updating Forge to see what that gives, it seems to be happening with other mods as well and I have no idea what is causing it:
https://github.com/MinecraftForge/MinecraftForge/issues/7963

**Comment by InfinityRaider** [comment]
Closing due to lack of replies
