### ISSUE TITLE
Camera conflict with Astral Sorcery preventing player attunement

### ISSUE THREAD

**Issue by DreamingLamb** [AgriCraft/AgriCraft#1408]
## Quick description
Incompatibility with Astral Sorcery is preventing players from attuning themselves.

## Related issues and searches
Did a quick search and could not find anything

## Mods and versions used
* Minecraft: 1.16.5
* Forge: 36.1.32
* AgriCraft: 3.0.3 or 3.0.5 Hotfix
* InfinityLib: 2.0.5 or 2.0.6 Hotfix
* Astral Sorcery: 1.16-1.16.5_1.13.12
* Astral dependancies:
* Curious-Forge: 1.16.5_4.0.5.2
* ObserverLib: 1.16.5_1.5.3

## Steps to replicate the issue
No issues loading Minecraft or a world.  Got to the point where I am able to attune myself, setup an attunement table and attempt to attune my player.  The player 'enters' the attunement table and then the camera gets stuck in a loop with it moving and then resetting.  The player is removed from the loop once Minecraft gets to a specific time of day (some time in the morning) as the Astral attunement would stop regardless, due to the time.

This does not happen with attuning an object which does not interact with the player's camera.

Someone has already reported on the Astral GitHub too (https://github.com/HellFirePvP/AstralSorcery/issues/1872), however it's been closed by them.  Removing Agricraft from the pack does fix the issue, so I assume there's a conflict between the two mods and cannot confirm which mod is causing it as there is no crash or logs that I can find.

## Expectations and explanations
Player's camera rotates around the player as they are attuned.

## Your environment
* How are you playing?
  * Operating System: Windows 10 on a Linux server.
  * Launcher: GD Launcher
  * Modpack: Custom, although setup a new instance with just Agri and Astral, with their dependencies and issue persists.
* What kind of server:
  * [X] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save
  * [X] Existing world on a server 

## Links to crash logs, stack traces, etc
Game does not crash so no logs are available.  Checked all logs files that I can, client and server side and there's nothing in them at the time of the event, only thing near it is 'Saved the game'

## Screenshots (or videos)
Video is available in the Astral GitHub, I can confirm this is the same experience I am getting.

**Comment by InfinityRaider** [comment]
Fixed in the previously mentioned InfinityLib commit
