### ISSUE TITLE
game crashes v3.0.5 using JEI

### ISSUE THREAD

**Issue by Shotguun29** [AgriCraft/AgriCraft#1410]
Minecraft V1.16.5
Game crashes when using JEI
java.lang.NullPointerException: Rendering ingredient
steps to repeat crash
Open JEI Type fe
crash
crash report
https://pastebin.com/zdhNVh7D

**Comment by InfinityRaider** [comment]
See #1396

**Comment by Shotguun29** [comment]
> See #1396

thanks
