### ISSUE TITLE
Crash looking though Agricraft JEI recipe menu.

### ISSUE THREAD

**Issue by SGZ-Creations** [AgriCraft/AgriCraft#1412]
## Quick description 
Crash looking though Agricraft JEI recipe menu one specific was when looking at twilight forest ferry metal combined with Mystical agriculture. 

## Mods and versions used

* Minecraft: 1.16.5
* AgriCraft: 3.0.5hotfix
* InfinityLib: 2.0.6hotfix
* [List the other required mods here]

## Steps to replicate the issue

1. Joined mp map.
2. Looked up fiery seed recipe.
3.  Clicked on the Agricraft recipe tab
4. Then Crash

## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: MultiMC
  * Modpack: Customized ATM6 
* What kind of server:
  *  Multiplayer
* Game Modes:
  * Survival
* Save File:
  * Brand new save

## Links to crash logs, stack traces, etc
[crash-2021-10-02_17.21.12-client.txt](https://github.com/AgriCraft/AgriCraft/files/7271757/crash-2021-10-02_17.21.12-client.txt)

**Comment by icha-senpai** [comment]
https://pastebin.com/hhkYqE3y


same issue

**Comment by icha-senpai** [comment]
it also happens when you type ingot in the jei search box

**Comment by InfinityRaider** [comment]
See #1396

**Comment by SGZ-Creations** [comment]
We have Twilight forest so no can't just disable it

**Comment by InfinityRaider** [comment]
It's not about disabling twilight forest, it's about temporarily disabling the fiery ingot seeds.

**Comment by SGZ-Creations** [comment]
Sorry for the agresive answer and Thanks
