### ISSUE TITLE
Automating Crops doesn't seems to be possible with Cyclic and IF

### ISSUE THREAD

**Issue by KalistaUe** [AgriCraft/AgriCraft#1413]
## Quick description
Automating plants doesn't seems to work, likely a compat issue.

## Mods and versions used
* Minecraft: 1.16.5
* Agricraft-3.0.5-hotfix
* Infinitylib-2.0.6-hotfix
* Cyclic-1.16.5-1.4.2
* Industrial-foregoing-1.16.5-3.2.14.6-14
* Patchouli-1.16.4-53.2
* Titanium-1.16.5-3.2.8.4-10

## Steps to replicate the issue
1. Loaded up a world
2. Make a simple crop automation system (only tested with Cyclic and Industrial Foregoing)

## Expectations and explanations
With Cyclic the system should drop the attributed item when the plant has grown but instead drops question mark items and if used with Crop sticks it makes a duplication bug where the growth only generate Crop sticks

With Industrial Foregoing the system should drop the attributed item when the plant has grown but instead doesn't interact at all with the plants (Crop sticks or not, it doesn't work as long as the seed has been changed to their Agricraft version)

## Your environment
  * Operating System:  Windows 10 Version 21H1
  * Launcher: CurseForge v. 0.181.2.16
  * Modpack: Custom Test mod pack
  * [x] Singleplayer
  * [x] Survival
  * [x] Creative
  * [x] Brand new save

## Links to crash logs, stack traces, etc
https://paste.ee/p/OJrE3#s=0

## Screenshots (or videos)
*With Crop Sticks:
https://i.imgur.com/a3P4l4q.png
https://i.imgur.com/e4euM49.png

*Without Crop Sticks:
https://i.imgur.com/WYBiyJ9.png
https://i.imgur.com/dhS4FmA.png

**Comment by InfinityRaider** [comment]
Fixed by #1421
