### ISSUE TITLE
java.lang.NoSuchFieldException: movementBehaviours

### ISSUE THREAD

**Issue by aburone** [AgriCraft/AgriCraft#1414]
Errors on log file
Failed to inject agri harvester behaviour
java.lang.NoSuchFieldException: movementBehaviours

* Minecraft: 1.16.5
* AgriCraft:agricraft-3.0.5-hotfix.jar
* InfinityLib:Infinitylib-2.0.6-hotfix.jar
Don't know it it has any relation but those are referred
* strawgolem-1.16-1.9.jar
* MysticalAgriculture-1.16.5-4.2.3.jar
* industrial-foregoing-1.16.5-3.2.14.6-14.jar
* ImmersiveEngineering-1.16.5-5.0.4-139.jar
* Cyclic-1.16.5-1.4.2.jar
* create-mc1.16.5_v0.3.2d.jar
* BotanyPots-1.16.5-7.1.25.jar
* BloodMagic-1.16.4-3.1.5-25.jar

## Steps to replicate the issue
look at logs while the game loads
(I'm looking for a mod throwing gl errors, so errors like this one jump at me)

## Your environment

* How are you playing?
  * Operating System:win10 LTSC
  * Launcher:tlauncher
  * Modpack:custom
* What kind of server:
  * [x] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [x] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [x] Only an existing save

## Links to crash logs, stack traces, etc
https://pastebin.pl/view/f0273a05

**Comment by InfinityRaider** [comment]
Fixed in #1421
