### ISSUE TITLE
Ticking block entity irrigator automatic crash at login my server

### ISSUE THREAD

**Issue by TheLastLost** [AgriCraft/AgriCraft#1416]
## Quick description
Block entity being ticked on a server, idon't know why but i cant join anymore to my server

## Related issues and searches
Ticking block entity
agricraft:irrigation_tank

## Mods and versions used
* Minecraft:
* AgriCraft:
* InfinityLib:
* forge-1.16.5-36.2.8
* TConstruct-1.16.5-3.1.3.271
* FarmersDelight-1.16.5-0.4.6
* ae2wtlib-0.3.2-1.16.5
* MekanismAdditions-1.16.5-10.0.21.448
* refinedpipes-0.5
* jei-1.16.5-7.7.1.125
* OptiForge-MC1.16.5-0.5.7
* movingelevators-1.2.34-mc1.16.5
* Mekanism-1.16.5-10.0.21.448
* jeiintegration_1.16.5-7.0.1.15
* ae2extras-1.3.1-1.16.5
* Mantle-1.16.5-1.6.127
* gravestone-1.16.5-1.0.7
* CTM-MC1.16.1-1.1.2.6
* appliedenergistics2-8.4.2
* lazierae2-1.16.5-1.1.4
* MekanismTools-1.16.5-10.0.21.448
* mcjtylib-1.16-5.0.23
* rftoolsbase-1.16-2.0.11
* rftoolsutility-1.16-3.1.3
* rftoolsbuilder-1.16-3.1.2
* rftoolsstorage-1.16-2.0.13
* rftoolscontrol-1.16-4.0.11
* rftoolsdim-1.16-7.0.14-beta
* Chisel-MC1.16.5-2.0.1-alpha.4
* RefinedRelocation_1.16.5-8.2.3
* MekanismGenerators-1.16.5-10.0.21.448
* rftoolspower-1.16-3.0.9
* FallingTree-1.16.5-2.11.5
* forge-1.16.5-36.2.8-universal
* Infinitylib-2.0.6-hotfix
* agricraft-3.0.5-hotfix
* agricraft-optifine-compat-0.0.1
* mob_grinding_utils-1.16.5-0.4.28
* chiselsandbits-1.0.12-RELEASE-universal

## Steps to replicate the issue
I don't exactly know i only know that i was walking and my server droped me out.
1. Loaded up `...`
2. Placed a `...`
3. Right-clicked with `...` on `...`

## Expectations and explanations
A server side error of infinitylib. The server has not crashed but sends me errors. I have a issue iopen at infinitylib 

## Your environment
* How are you playing?
  * Operating System: Microsoft Windows 10 Pro  2009  21H2  19044.1266  64bit
  * Launcher:Oficial launcher v1.0.1.0
  * Modpack: specified before
* What kind of server:
  * [ ] Singleplayer
  * [X ] Multiplayer
* Game Modes:
  * [X ] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [ X] Only an existing save

## Links to crash logs, stack traces, etc
* https://pastebin.com/jjTBwLXJ

**Comment by Lgmrszd** [comment]
Can confirm this bug happening, for some reason only one of the players was unable to join after another one placed irrigation tank, in the client log was the same error.

**Comment by InfinityRaider** [comment]
Will be fixed in next version, for now, don't build multiblock tanks across chunk boundaries.
