### ISSUE TITLE
1.12.2 Missing JSON Mystical seeds and correction for them, also correction for the 6 tiers Inferium seeds.

### ISSUE THREAD

**Issue by SirDevil1213** [AgriCraft/AgriCraft#1418]
## Quick description

It seem that some JSON for custom Mystical Agriculture seeds, the seeds exist for Mystical agriculture and the essence, everything, but they don't have JSON for agricraft so impossible to place them in crop stick. JEI can be use to see the seeds are not usable in the crop stick. The list of mods concerned are just under, I use in my personal mudpack a lot more mods juste in case there is the list -> https://pastebin.com/QntPqQLd

## Mods and versions used

* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* AgriCraft: agricraft-2.12.0-1.12.2-b2
* InfinityLib: infinitylib-1.12.1
* Mystical Agradditions: MysticalAgradditions-1.12.2-1.3.2
* Mystical Agriculture: MysticalAgriculture-1.12.2-1.7.5
* AbyssalCraft: AbyssalCraft-1.12.2-1.10.4
* Applied Energistics 2: appliedenergistics2-rv6-stable-7
* Botania: Botania r1.10-364.4
* Embers Rekindled: EmbersRekindled-1.18
* Ender IO: EnderIO-1.12.2-5.3.70
* Immersive Engineering: ImmersiveEngineering-0.12-98
* PneumaticCraft: Repressurized: pneumaticcraft-repressurized-1.12.2-0.11.15-398
* Thaumcraft: Thaumcraft-1.12.2-6.1.BETA26
* The Twilight Forest: twilightforest-1.12.2-3.11.1021-universal
* [ANGRY PIXEL] The Betweenlands: TheBetweenlands-3.7.3-universal
* Just Enough Items (JEI): jei_1.12.2-4.16.1.301 (optional for seeing if the seed are usable in crop stick)

## Steps to replicate the issue

1. Go in a Solo/local world or a Multi/server world
2. Placed a crop stick on some farmlands
3. Right-clicked with the specific seed on the crop stick
4. Nothing happens

## Expectations and explanations

*Expect: Being able to place the seeds in the crop sick.
*Happen: Not able to place the seeds in the crop stick.

## Your environment

* How are you playing?
  * Operating System:
  * Launcher:
  * Modpack: Private Modpack
* What kind of server:
  * [X] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [X] Existing save

## Correction for the Missing Seeds JSON
I made the correction for the missing seeds, I saw that for some topic because they're were in 1.12.2 you said you'll focus on 1.16 instead, so if this is not put in a hotfix at least people will be able to get the files here.

* Mystical Agradditions
 -Dragon Egg https://pastebin.com/0DSAvSzg

* Abyssalcraft
 -Abyssalnite https://pastebin.com/Cya0wwR9
 -Coralium https://pastebin.com/RKX3sn6Y
 -Dreadium https://pastebin.com/MpqsWVaH

* Applied Energestics 2
 -Sky Stone https://pastebin.com/Lx6aYy20

* Botania
 -Elementium https://pastebin.com/8qBKVttn

* Embers Rekindled
 -Dawnstone https://pastebin.com/8eNMpnW5

* EnderIO
 -End Steel https://pastebin.com/YK2nvYN2

* Immersive Engineering
 -HOP Graphite https://pastebin.com/7xhpUWpM

* PneumaticCraft: Repressurized
 -Compressed Iron https://pastebin.com/xsAzv4RX

* Thaumcraft
 -Quicksilver https://pastebin.com/EVX1fKV7
 -Thaumium https://pastebin.com/g81gZzUp
 -Void Metal https://pastebin.com/XHDETsMn

* The Twilight Forest
 -Fiery Ingot https://pastebin.com/PJdHdtwF
 -Ironwood https://pastebin.com/QcKSq1GK
 -Knightmetal https://pastebin.com/Eafst0uP
 -Steeleaf https://pastebin.com/GNvwRBJe 

* [ANGRY PIXEL] The Betweenlands
 -Octine https://pastebin.com/5Sy29PRd
 -Slimy Bone https://pastebin.com/7b0EBTYR
 -Syrmorite https://pastebin.com/Tpcy6ftn
 -Valonite https://pastebin.com/eCcSUCkB

## Correction for the Inferium Seeds
The name of the item receive was not the correct one.
 -Inferium Tier 1 https://pastebin.com/ZBDrU6Sg
 -Inferium Tier 2 https://pastebin.com/m6irbZAT
 -Inferium Tier 3 https://pastebin.com/4kzcMT7F
 -Inferium Tier 4 https://pastebin.com/6qCc5NuK
 -Inferium Tier 5 https://pastebin.com/edQiCbzp
 -Inferium Tier 6 https://pastebin.com/PegeHB4H

**Comment by InfinityRaider** [comment]
Im not doing any 1.12 stuff anymore sorry

**Comment by SirDevil1213** [comment]
No problem, the only reason I change the name was just if people having the same problem to fall here and directly get the correction, but I forget to close the issue. Otherwise I can't wait to play it on the newest version of the game.
