### ISSUE TITLE
no sprinkler recipe agricraft1.12.2

### ISSUE THREAD

**Issue by ChrisCatta** [AgriCraft/AgriCraft#1422]
hi there,
Ican't find the recipe for sprinkler in agricraft 1.12.2

## Related issues and searches

* https://github.com/AgriCraft/AgriCraft/issues?q=is%3Aissue%20EXAMPLE

## Mods and versions used

* Minecraft:1.12.2
* agricraft-2.12.0-1.12.2-b2
* AgriCraft:
* InfinityLib:infinitylib-1.12.1 
* [List the other required mods here]

## Steps to replicate the issue

1. Loaded up `...`
2. Placed a `...`
3. Right-clicked with `...` on `...`
4.

## Your environment

* How are you playing?
  * Operating System:windows 10 64bit
  * Launcher:Technic launcher 0.99.0
  * Modpack:tehhit3 modifié
* What kind of server:
  * [x] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [x] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc

* https://gist.github.com/
* https://paste.ee/
* https://duckduckgo.com/?q=pastebin+alternatives
* Upload them somewhere, and then replace these links.

**Comment by InfinityRaider** [comment]
Sorry, no more 1.12
