### ISSUE TITLE
Seed Analyzer error

### ISSUE THREAD

**Issue by KsmKayk** [AgriCraft/AgriCraft#1423]
## Quick description
Seed analyzer doesnt showing gui

## Mods and versions used

* Minecraft: 1.16.5 Forge
* AgriCraft: Latest (28/11/2021)
* InfinityLib: Latest (28/11/2021)
* [List the other required mods here]

*  sophisticatedbackpacks-1.16.5-3.11.1.390.jar
*  StorageDrawers-1.16.3-8.3.0.jar
*  supermartijn642corelib-1.0.14a-mc1.16.5.jar
*  theoneprobe-1.16-3.1.4.jar
*  thermal_cultivation-1.16.5-1.3.0.jar
*  thermal_expansion-1.16.5-1.3.0.jar
*  thermal_foundation-1.16.5-1.3.2.jar
*  titanium-1.16.5-3.2.8.4-10.jar
*  toms_storage-1.2.19.jar
*  topaddons-1.16.5-2.1.5-beta.jar
*  toughnessbar-6.1.jar
*  Translocators-1.16.5-2.6.0.82-universal.jar
*  trashcans-1.0.10-mc1.16.5.jar
*  twilightforest-1.16.5-4.0.546-universal.jar
*  u_team_core-1.16.5-3.2.1.196.jar
*  valhelsia_core-16.0.13a.jar
*  voicechat-forge-1.16.5-1.8.0.jar
*  WaterStrainer-1.16.3-10.0.0.jar
*  Waystones_1.16.5-7.6.4.jar
*  xnet-1.16-3.0.14.jar
*  XNetGases-1.16.5-2.3.8.jar
*  agricraft-3.0.6.jar
*  agricraft-optifine-compat-0.0.1.jar
*  AI-Improvements-1.16.5-0.4.0.jar
*  angelring-1.16.5-1.3.4.1.jar
*  Apotheosis-1.16.5-4.8.3.jar
*  appleskin-forge-mc1.16.x-2.2.0.jar
*  architectury-1.25.36-forge.jar
*  AttributeFix-1.16.5-10.1.2.jar
*  BiomesOPlenty-1.16.5-13.1.0.477-universal.jar
*  Bookshelf-Forge-1.16.5-10.3.29.jar
*  Botania-1.16.5-420.jar
*  BotanyPots-1.16.5-7.1.30.jar
*  botanypotstiers-1.16.5-1.13.jar
*  BotanyTrees-1.16.5-3.0.5.jar
*  BrandonsCore-1.16.5-3.0.11.238-universal.jar
*  CBMultipart-1.16.5-3.0.3.122-universal.jar
*  cfm-7.0.0pre22-1.16.3.jar
*  Chisel-MC1.16.5-2.0.1-alpha.4.jar
*  ClientTweaks_1.16.3-5.3.0.jar
*  Clumps-6.0.0.27.jar
*  CodeChickenLib-1.16.5-4.0.4.435-universal.jar
*  cofh_core-1.16.5-1.3.1.jar
*  CommonCapabilities-1.16.5-2.8.0.jar
*  compactmachines-4.0.0-beta.2.jar
*  constructionwand-1.16.5-2.4.jar
*  Controlling-7.0.0.28.jar
*  CookingForBlockheads_1.16.5-9.3.4.jar
*  CosmeticArmorReworked-1.16.5-v4.jar
*  CraftingTweaks_1.16.5-12.2.1.jar
*  CTM-MC1.16.1-1.1.2.6.jar
*  Cucumber-1.16.5-4.1.12.jar
*  curios-forge-1.16.5-4.0.5.3.jar
*  Cyclic-1.16.5-1.5.11.jar
*  CyclopsCore-1.16.5-1.12.1.jar
*  DarkUtilities-1.16.5-8.0.10.jar
*  Draconic-Evolution-1.16.5-3.0.17.420-universal.jar
*  Draconic-Machinery_1.0.0-Beta_1.16.5.jar
*  eidolon-0.2.7.jar
*  elevatorid-1.16.5-1.7.13.jar
*  EnderStorage-1.16.5-2.8.0.168-universal.jar
*  ExCompressum_1.16.5-4.0.4.jar
*  exnihilomekanism-1.16-1.0.0.1.jar
*  exnihilosequentia-1.16-20211128-042122.jar
*  exnihilothermal-1.16-1.0.0.0.jar
*  extradisks-1.16.4-1.5.1.jar
*  ExtraStorage-1.16.5-1.5.1.jar
*  extreme_cobble_generator-1.16.5-1.1.1.13.jar
*  extremeSoundMuffler-3.17_1.16.5.jar
*  FastLeafDecay-v25.jar
*  ferritecore-2.1.0-forge.jar
*  FluxNetworks-1.16.5-6.1.7.12.jar
*  forbidden_arcanus-16.2.1.jar
*  FpsReducer-forge-1.24-mc1.16.5.jar
*  ftb-chunks-forge-1605.3.2-build.83.jar
*  ftb-essentials-1605.1.5-build.32.jar
*  ftb-library-forge-1605.3.4-build.87.jar
*  ftb-power-pots-forge-1605.1.2-build.16.jar
*  ftb-teams-forge-1605.2.3-build.40.jar
*  ftb-ultimine-forge-1605.3.1-build.45.jar
*  Industrial Agriculture[Botania]-1.16.5-1.7.2.jar
*  Industrial_AgricultureCore-1.16.5-1.8.13.jar
*  industrial-foregoing-1.16.5-3.2.14.6-14.jar
*  Infinitylib-2.0.7.jar
*  invtweaks-1.16.4-1.0.1.jar
*  ironchest-1.16.5-11.2.13.jar
*  ironfurnaces-1.16.5-2.7.7.jar
*  JAOPCA-1.16.5-3.4.2.16.jar
*  jei-1.16.5-7.7.1.137.jar
*  jeiintegration_1.16.5-7.0.1.15.jar
*  journeymap-1.16.5-5.7.3.jar
*  JustEnoughResources-1.16.5-0.12.1.128.jar
*  LibX-1.16.3-1.0.76.jar
*  Lollipop-1.16.5-3.2.9.jar
*  managear-1.16.3-2.2.3.jar
*  mcjtylib-1.16-5.1.0.jar
*  Mekanism-1.16.5-10.0.24.453.jar
*  MekanismGenerators-1.16.5-10.0.24.453.jar
*  MmmMmmMmmMmm-1.16.5-1.3.1.jar
*  mob_grinding_utils-1.16.5-0.4.30.jar
*  MoreChickens-1.16.5-1.1.2.0.jar
*  MoreMekanismProcessing-1.16.5-1.1.jar
*  Morpheus-1.16.5-4.2.70.jar
*  MouseTweaks-2.14-mc1.16.2.jar
*  mowziesmobs-1.5.19.jar
*  MysticalAgradditions-1.16.5-4.2.3.jar
*  MysticalAgriculture-1.16.5-4.2.5.jar
*  OptiFine_1.16.5_HD_U_G8.jar
*  overloadedarmorbar-5.1.0.jar
*  Patchouli-1.16.4-53.2.jar
*  performant-1.16.2-5-3.76m.jar
*  Placebo-1.16.5-4.6.1.jar
*  polymorph-forge-1.16.5-0.33.jar
*  Powah-1.16.5-2.3.16.jar
*  refinedstorage-1.9.16.jar
*  refinedstorageaddons-0.7.4.jar
*  reliquary-1.16.5-1.3.5.1100.jar
*  rftoolsbase-1.16-2.1.0.jar
*  rftoolsbuilder-1.16-3.1.3.jar
*  rftoolsdim-1.16-7.0.16-beta.jar
*  RSInfinityBooster-1.16.5-1.1+3.jar
*  Runelic-1.16.5-7.0.2.jar
*  Scorge-3.1.3.jar
*  shutupexperimentalsettings-1.0.3.jar
*  silent-gear-1.16.5-2.6.30.jar
*  SilentGems-1.16.3-3.7.16.jar
*  silent-lib-1.16.3-4.9.6.jar
*  SimpleStorageNetwork-1.16.5-1.5.0.jar
*  skin_changer-0.2.2.jar
*  SkyblockBuilder-1.16.4-1.6.12.jar

## Steps to replicate the issue

1. Start Server
2. Enter world without shaders ( crashes if you open seed analyzer with shaders )
3. Place seed analyzer 
4. Open seed analyzer

## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: Curse Forge
  * Modpack: Private
* What kind of server:
  * [ ] Singleplayer
  * [x] Multiplayer
* Game Modes:
  * [x] Survival
  * [x] Creative
* Save File:
  * [x] Brand new save
  * [ ] Only an existing save

[Modpack Exported From Curseforge Launcher](https://drive.google.com/file/d/1tiKtRFUmJNMughDvKqb6SFrXIVjRKToy/view?usp=sharing)
[![image.png](https://i.postimg.cc/B67TnBP3/image.png)](https://postimg.cc/MMRMsRY3)

**Comment by InfinityRaider** [comment]
Working as intended
