### ISSUE TITLE
Crash while right clicking a soil in jei

### ISSUE THREAD

**Issue by Casmin7** [AgriCraft/AgriCraft#1424]
## Quick description
I right clicked snad in jei and crashed my game 

## Mods and versions used

* Minecraft:
* AgriCraft:
* InfinityLib:
* Snad
* Mystical Agriculture

## Steps to replicate the issue

1. Loaded up the game
3. Right-clicked snad in jei
4. BOOM

## Your environment

* How are you playing?
  * Operating System:  Windows 11
  * Launcher: The older one not the newest one
  * Modpack: Survive the light version that hasn't been relsesed yet
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [ ] Survival
  * [X] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc

[crash-2021-11-30_21.07.56-client.txt](https://github.com/AgriCraft/AgriCraft/files/7628214/crash-2021-11-30_21.07.56-client.txt)

**Comment by InfinityRaider** [comment]
I'll have a look at it

**Comment by InfinityRaider** [comment]
Fixed in https://github.com/AgriCraft/AgriCraft/commit/09b833643b2d896389f8212dc40084239404f896
