### ISSUE TITLE
Issue - SimpleFarming Corn won't revert to immature plant when harvested

### ISSUE THREAD

**Issue by nirakoji** [AgriCraft/AgriCraft#1425]
I have an issue to report:
Minecraft 1.16.5
Forge 36.2.9
AgriCraft 3.0.6
InfinityLib 2.0.7
SimpleFarming 1.3.8

Growing SimpleFarming corn with wooden crop supports, my corn matures - but when I harvest it, it stays mature; weeds can't be cleared from it either (weeds are config'd to not kill plants). I harvested 40 ears of corn from one plant before I stopped to make this report.

The crops are growing in a greenhouse, with the glass ~y3 above ground.

This also happens without crop supports.

* How are you playing?
  * Operating System: Windows 10
  * Launcher: Curseforge
  * Modpack: Phoenix Dawn 1.5.2
* What kind of server:
  * [ ] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative

![image](https://user-images.githubusercontent.com/69447149/144613287-8ee15692-bbf7-4f0f-9207-119b55cdc78e.png)

**Comment by InfinityRaider** [comment]
Does this only happen for corn, or are other crops affected as well?
In the plant json file, what is the harvestStage set to?

**Comment by InfinityRaider** [comment]
I still need more feedback, have you modified the harvest stage in the jsons?
Does it only happen with Thermal Cultivation crops or is it any crop?
Does it also happen when agricraft is alone with Thermal Cultivation (no other mods)?

**Comment by nirakoji** [comment]
I didn't modify the .json files, just used them straight from stock.

This was an issue with SimpleFarming Corn and I didn't notice it with anything else, but I didn't test it extensively beyond that. My hunch is that it was a double-high crop issue - but atm I won't have time for a few days to test that.

To that end, I didn't try isolating the issue - and I believe it was resolved via Right Click Get Crops (TeamCoFH), which I understand doesn't help bug fix here. Sorry dude. 🙏

**Comment by InfinityRaider** [comment]
Good find, I'll try this in dev to see if I can replicate it.
