### ISSUE TITLE
Latest update of Thermal Cultivation breaks with AgriCraft

### ISSUE THREAD

**Issue by nirakoji** [AgriCraft/AgriCraft#1428]
Latest update of Thermal Cultivation breaks with AgriCraft
![image](https://user-images.githubusercontent.com/69447149/145445328-7028f7bf-bab9-4f08-b789-61e11292185d.png)
Thermal Cultivation 1.4.1.3
AgriCraft 3.0.6

**Comment by nirakoji** [comment]
Pictured above is Simple Farming corn and Thermal Cultivation Corn (mature and seedling)

I installed "Right Click, Get Crops" from TeamCoFH which seems to resolve my other issue #1425.

**Comment by nirakoji** [comment]
Is there a way to exempt Thermal Cultivation crops from AgriCraft until a fix happens? I'd love to have both coexist in my modpack.

**Comment by InfinityRaider** [comment]
Yes, you can go to the jsons and there is a field there "enabled" set that to false to disable that crop.

**Comment by InfinityRaider** [comment]
Update your jsons to fix this, you can find them here: https://github.com/AgriCraft/AgriPlants/tree/master/mod_thermal_cultivation/plants
