### ISSUE TITLE
Seeds being deleted when breaking the soil

### ISSUE THREAD

**Issue by ItsJamie20** [AgriCraft/AgriCraft#1430]
When breaking any soil with a seed planted on it the seed deleted and does not drop. The same happens when farmland is trampled with a seed planted on it. 

Minecraft: 1.16.5
AgriCraft: 3.0.6
InfinityLib: 2.0.7

Operating System: Windows 10
  Launcher: Curseforge
  Modpack: None
What kind of server:
  [X] Singleplayer
  [ ] Multiplayer
Game Modes:
  [X] Survival
  [X] Creative
Save File:
  [X] Brand new save
  [ ] Only an existing save

Video Showing Issue:
https://user-images.githubusercontent.com/78187683/147301418-487d96da-b66c-4b0b-8c31-461b32779793.mp4

**Comment by remplerus** [comment]
can confirm that it also happens when seeds are placed on crop sticks

**Comment by InfinityRaider** [comment]
Thanks for reporting, has been fixed.
