### ISSUE TITLE
AgriCraft - Seed placing issue [CRASH - 1.16.5]

### ISSUE THREAD

**Issue by Nexusatko** [AgriCraft/AgriCraft#1431]
## Quick description
> Hello, when I place down any seeds it crashes my game and the last thing I see with WAILA is "Air" from AgriCraft. But when I load up again to the game, the seed is here and I can harvest it. If I try to place another or the same seed again, the game crashes again but the seed is also in place after loading up. 

## Mods and versions used
* Minecraft: 1.16.5
* AgriCraft: 3.0.6
* InfinityLib: 2.0.7
* [List the other required mods here]

## Steps to replicate the issue
1. Loaded up 'into multiplayer game server'
2. Placed an 'any seed from AgriCraft'
3. Got crashed the game.
4. After loading up again, the seed was here.

## Your environment
* How are you playing?
  * Operating System: Windows 10 Pro 
  * Launcher: Technic Launcher ( https://technicpack.net/download )
  * Modpack: Future In Botania ( Private server )
* What kind of server:
  * [ ] Singleplayer
  * [x] Multiplayer
* Game Modes:
  * [x] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [x] Only an existing save

## Links to crash logs, stack traces, etc
https://gist.github.com/Nexusatko/486866703c38bb58582db106e7097f82

**Comment by InfinityRaider** [comment]
Can you load up an instance within astral sorcery and without twilight forest to check if it happens then as well?

**Comment by Nexusatko** [comment]
It works without Twilight Forest, is there any way to solve this, so I don't have to remove Twilight Forest? 
Thanks.

**Comment by Nexusatko** [comment]
Edit: It's not Twilight Forest..:'D Forgot to water it.

**Comment by Nexusatko** [comment]
If there are crop sticks, it'll not crash. If there are not, it'll crash.

**Comment by InfinityRaider** [comment]
What do you mean, water it?

**Comment by InfinityRaider** [comment]
If you can pin down with what mod it happens, I can try to fix it.

**Comment by Nexusatko** [comment]
Well, if you first pour it with water and then place seed, it'll crash. And also it'll crash outside of crop sticks. 
Still don't know what mod is causing it.

**Comment by InfinityRaider** [comment]
You mean it happens with waterlogged crops?

**Comment by Nexusatko** [comment]
Yeah.

**Comment by InfinityRaider** [comment]
I am failing to reproduce this, you will have to do a binary search to find out what mod is causing the conflict.

**Comment by AsrielX** [comment]
InfinityRaider, I found the issue here. It's between HWYLA and JER, I removed them both because I had the exact same issue and the bug was fixed.
