### ISSUE TITLE
When i click on the seed analyzer the game crushes and i am not sure why

### ISSUE THREAD

**Issue by lordudi** [AgriCraft/AgriCraft#1432]
## Quick description
when i try to open the seed analyzer gui the modpack i modified crushes

## Mods and versions used
* Minecraft: 1.16.5 modified create above and beyond
* AgriCraft: agricraft-3.0.6.jar
* InfinityLib:Infinitylib-2.0.7.jar
[mods.txt](https://github.com/AgriCraft/AgriCraft/files/7799729/mods.txt)

## Steps to replicate the issue

1. Loaded up `world with the mods`
2. Placed a `seed analyzer`
3. Right-clicked on `seed analyzer`
4. boom crush

Singleplayer
Survival
Brand new save

## Links to crash logs, stack traces
[crash-2022-01-02_22.00.08-client.txt](https://github.com/AgriCraft/AgriCraft/files/7799737/crash-2022-01-02_22.00.08-client.txt)

i am sorry for bothering you but i tried a lot of times to find a reason but i just don't know enough about this mod to actually be able to find this problem

**Comment by InfinityRaider** [comment]
Seems to be an interaction with immersive portals.

**Comment by InfinityRaider** [comment]
Yeah, you'll have to report this to them as I can't do anything about it.
