### ISSUE TITLE
Wetting dry farmland with watering can breaks crop sticks and deletes seed.

### ISSUE THREAD

**Issue by chemicalvamp** [AgriCraft/AgriCraft#1435]
MC 1.16.5
forge 36.2.20
agricraft-3.0.6

Just starting on the mod again, My seeds are being lost if the farmland is still dry when using the watering can to grow the crop.
The farmland ticks from dry to wet and off pops the crop sticks, and the seed is lost.

Single crop sticks, on tilled dirt(farmland), still dry, wheat seed planted, water source a block away, iron watering can.

**Comment by InfinityRaider** [comment]
Update to the latest version first please.
