### ISSUE TITLE
Config file resetting to default.

### ISSUE THREAD

**Issue by chemicalvamp** [AgriCraft/AgriCraft#1436]
MC 1.16.5
forge 36.2.20
agricraft-3.0.6

#Set to true to convert seeds only in the analyzer. Has no effect if "Override vanilla farming" is set to false.
	"Convert seeds only in analyzer" = false

Setting this to true causes the entire config file to reset to it's default state.

Also, can't craft with agricraft seeds, Can't get vanilla wheat seeds to drop.

**Comment by InfinityRaider** [comment]
One issue at a time please.

The config is working as intended, granted the description of "override vanilla farming is poor" (legacy reasons, i can update that description if desired), and is more for auto conversion of seeds . The second one only works when the first is set to true, working as a more precise specification.

I can't replicate the resetting of the entire config, not sure what is happening there.

Update to the latest version, there are now recipes using the agricraft seeds .

There is a config option to disable clearing of vanilla seeds dropping from grass.

**Comment by InfinityRaider** [comment]
Closing due to lack of replies
