### ISSUE TITLE
Seed Analyzer not showing GUI 1.16.5

### ISSUE THREAD

**Issue by Premiumox** [AgriCraft/AgriCraft#1438]
## Mods and versions used
* Minecraft:
* AgriCraft: Latest for 1.16.5
* InfinityLib: Latest for 1.16.5
* MODPACK Monumental Experience 1.1.6.5

## Steps to replicate the issue
1.  place seed analyzer
2. opening seed analyzer
3. In analyzer, but not showing gui

## Expectations and explanations
 Trying it with other versions of infinityLib and  Agricraft on 1.16.5

## Screenshots (or videos)
![2022-02-02_00 44 15](https://user-images.githubusercontent.com/98854820/152070131-adbfc4a6-9898-471d-834c-f7baaeb190d2.png)

**Comment by InfinityRaider** [comment]
This is intended.
You shift right click to insert / extract seeds or the journal.
You right click to analyze the seed. Use the mouse wheel to cycle through the genes.
