### ISSUE TITLE
Duplicating seed via seed analyzer and hoppers

### ISSUE THREAD

**Issue by Premiumox** [AgriCraft/AgriCraft#1439]
## Quick description
You can duplicate seed using seed analyzer and hoopers like on picture. I use this layout cuz seed analyzer not showing gui 
## Mods and versions used

* Minecraft: 1.16.5
* AgriCraft: latest for 1.16.5
* InfinityLib: latets for 1.16.5
* [List the other required mods here] MODPACK  monumental experience 1.16.5

## Steps to replicate the issue

1. Create this pattern like on picture
2. Put agricraft seed in chest on top
3.  It goes to analyzer then
4. Magic.. Seed just duplicating to chest via hoppers (one seed every second)

## Expectations and explanations
Check it, its seems like hoppers duplicate it

## Screenshots (or videos)
![2022-02-01_23 44 33](https://user-images.githubusercontent.com/98854820/152070547-296c3482-f842-46e3-8e26-cebe0bee48e7.png)
![2022-02-02_01 02 48](https://user-images.githubusercontent.com/98854820/152071852-73265c1d-5315-4a54-913e-cf01d675baee.png)

**Comment by InfinityRaider** [comment]
Please specify which versions "latest" is useless for me, as I literally fixed this bug in the actual latest version.

**Comment by Premiumox** [comment]
Versions:
InfinityLib 2.0.7
Agricraft 3.0.7

**Comment by InfinityRaider** [comment]
Thank you.
Is this server or singleplayer?

**Comment by Premiumox** [comment]
Singleplayer, tested other versions with same result
