### ISSUE TITLE
CropGrowth event not taking effect as intended

### ISSUE THREAD

**Issue by someaddons** [AgriCraft/AgriCraft#1441]
## Quick description

You're checking if the event is cancelled here https://github.com/AgriCraft/AgriCraft/blob/cde754627e30284c120a3ea2060ca88071882f54/src/main/java/com/infinityraider/agricraft/content/core/TileEntityCropBase.java#L344
but that event cannot be canceled and instead uses the event result `event.setResult(Event.Result.DENY);` so you need to check the event result after posting it on the bus, similar to how forge does it:

![image](https://user-images.githubusercontent.com/38401808/154953560-1851e6ba-16f2-4b52-8fd4-9b08c9c86a39.png)

## Related issues and searches

* https://github.com/AgriCraft/AgriCraft/issues?q=is%3Aissue%20EXAMPLE

## Mods and versions used

* Minecraft:1.16.5
* AgriCraft:agricraft-3.0.7
* InfinityLib:Infinitylib-2.0.7
* [List the other required mods here]

## Steps to replicate the issue

1. Loaded up `...`
2. Placed a `...`
3. Right-clicked with `...` on `...`
4.

## Your environment

* How are you playing?
  * Operating System:
  * Launcher:
  * Modpack:
* What kind of server:
  * [ ] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [ ] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc

* https://gist.github.com/
* https://paste.ee/
* https://duckduckgo.com/?q=pastebin+alternatives
* Upload them somewhere, and then replace these links.

**Comment by InfinityRaider** [comment]
But the event is cancellable: https://github.com/AgriCraft/AgriCraft/blob/cde754627e30284c120a3ea2060ca88071882f54/src/main/java/com/infinityraider/agricraft/api/v1/event/AgriCropEvent.java#L141

**Comment by InfinityRaider** [comment]
My bad, good find!
