### ISSUE TITLE
3.0.6 - No Industrial Hemp seed drops with Immersive Engineering

### ISSUE THREAD

**Issue by BGazotti** [AgriCraft/AgriCraft#1442]
Cheers! Love the mod, but after a few days of breaking down tall grass I noticed I couldn't get Industrial Hemp seeds to drop. Now, there are several confounding factors here - one of them being that the 3.0.6 version I'm currently using is not the latest one and this might have been fixed already. Another one may be that this is an intentional mechanic added to encourage crop breeding. In any case, I "fixed" the issue by manually editing the 'data/agricraft/loot_modifiers/tall_grass_drops.json' file, including "plant": "immersiveengineering:hemp_plant" as a possible drop and repacking the AgriCraft jar. Just thought y'all might want to know about this.

## Related issues and searches
https://github.com/AgriCraft/AgriCraft/issues/1297 - Main mod compatibility issue

## Mods and versions used
* Minecraft: 1.16.5
* AgriCraft: 3.0.6 
* InfinityLib: 2.0.7
* Immersive Engineering: 5.0.7-143
* A metric f*ckbucket of other miscellaneous mods that may or may not be relevant to this issue in particular:
  [✔️] absentbydesign-1.16.5-1.5.1
  [✔️] advancedperipherals-1.16.5-0.7.7.1r
  [✔️] AgriCraft-GazPatcho
  [✔️] ars_nouveau-1.16.5-1.24.14
  [✔️] AttributeFix-1.16.5-10.1.3
  [✔️] BiomesOPlenty-1.16.5-13.1.0.485-universal
  [✔️] cc-tweaked-1.16.5-1.100.2
  [✔️] Chisel-MC1.16.5-2.0.1-alpha.4
  [✔️] CraftTweaker-1.16.5-7.1.2.489
  [✔️] CTM-MC1.16.1-1.1.2.6
  [✔️] curios-forge-1.16.5-4.0.8.0
  [✔️] dynamiclightsreforged-mc1.16.5_v1.0.1
  [✔️] FastLeafDecay-v25.2
  [✔️] ferritecore-2.1.0-forge
  [✔️] forestry-1.16.5-6.0.11
  [✔️] FpsReducer-forge-1.24-mc1.16.5
  [✔️] geckolib-forge-1.16.5-3.0.61
  [✔️] gravestone-1.16.5-1.0.7
  [✔️] ImmersiveEngineering-1.16.5-5.0.7-143
  [✔️] industrial-foregoing-1.16.5-3.2.14.7-16
  [✔️] Infinitylib-2.0.7
  [✔️] invtweaks-1.16.4-1.0.1
  [✔️] jei-1.16.5-7.7.1.145
  [✔️] journeymap-1.16.5-5.8.0beta10
  [✔️] JustEnoughCalculation-1.16.5-3.8.6
  [✔️] JustEnoughResources-1.16.5-0.12.1.133
  [✔️] magnesium_extras-mc1.16.5_v1.3.1
  [✔️] magnesium-1.5
  [✔️] Mantle-1.16.5-1.6.157
  [✔️] mcjtylib-1.16-5.1.3
  [✔️] Mekanism-1.16.5-10.1.1.456
  [✔️] MekanismGenerators-1.16.5-10.1.1.456
  [✔️] MekanismTools-1.16.5-10.1.1.456
  [✔️] Patchouli-1.16.4-53.2
  [✔️] polymorph-forge-1.16.5-0.39
  [✔️] refinedstorage-1.9.16
  [✔️] rftoolsbase-1.16-2.1.2
  [✔️] rftoolsbuilder-1.16-3.1.5
  [✔️] rftoolsdim-1.16-7.0.20-beta
  [✔️] rftoolspower-1.16-3.0.13
  [✔️] rftoolsutility-1.16-3.1.9
  [✔️] RoadRunner-mc1.16.5-1.4.0
  [✔️] sulfuric-1.1
  [✔️] swingthroughgrass-1.16.4-1.5.3
  [✔️] TConstruct-1.16.5-3.3.3.332
  [✔️] theoneprobe-1.16-3.1.4
  [✔️] titanium-1.16.5-3.2.8.7-22
  [✔️] TrampleStopper-2.6.1-build.22+mc1.16.5
  [✔️] TrashSlot_1.16.3-12.2.1

## Steps to replicate the issue
1. Load up a world
2. Break tall grass like an absolute madman
3. Open inventory; only carrots, potatoes and wheat seeds

## Expectations and explanations
IE hemp seeds are not really that common, but after a few days of playing you'd expect to have at least one of those

## Your environment
* How are you playing?
  * Operating System: Gentoo Linux, unstable branch; Java 1.8.0_322
  * Launcher: MultiMC 0.6.14
  * Modpack: None, self-assembled; Forge 36.2.26
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

**Comment by BGazotti** [comment]
## Amended mod list
The issue persists in a brand-new instance of Minecraft with only the following mods:
* AgriCraft 3.0.7
* InfinityLib 2.0.7
* Immersive Engineering 5.0.7-143
* Forge 36.2.26

**Comment by InfinityRaider** [comment]
This is intended behaviour.
By default agricraft clears grass drops to make agricraft versions of seeds drop.
You can disable this clearing of grass drops in the config or add more seed variants to the drops using a datapack.
