### ISSUE TITLE
 AgriCraft failed to load correctly

### ISSUE THREAD

**Issue by oguzsever** [AgriCraft/AgriCraft#1444]
when i try to start minecraft it always says that the mod (AgriCraft) doesnt load correctly. i tryed to update forge and used the newest version, didnt work. tryed with the recommended one too, didnt work. what should i do?  (i am using both official minecraft + the newest version of AgriCraft)
[crash-2022-02-26_11.39.43-fml.txt](https://github.com/AgriCraft/AgriCraft/files/8146372/crash-2022-02-26_11.39.43-fml.txt)

**Comment by InfinityRaider** [comment]
Very odd, have you tried without Optifine?

**Comment by Kotawolf** [comment]
I just got this and it was an error actually with Botany pots.   A no Class Def error.   I can't find what is the problem.  So testing without.

**Comment by InfinityRaider** [comment]
What version of botany pots?

**Comment by GMarty93** [comment]
im getting the same crash and erorr message im using 7.0.17 of botany pots 1.16.5 MC

**Comment by Kotawolf** [comment]
Same version - the latest Release version.   I didn't check any of the alpha versions.  I was using it with the BotanyTrees.

**Comment by Kotawolf** [comment]
Thanks for asking version, just grabbed the newest ALPHA and didn't get the start up crash.  7.1.31
