### ISSUE TITLE
reloading resource packs

### ISSUE THREAD

**Issue by Warbringer12** [AgriCraft/AgriCraft#1446]
## Quick description
reloading textures with f3+t breaks the textures for all the seeds

## Mods and versions used

* Minecraft: 1.16.5
* AgriCraft:  3.0.7
* InfinityLib: 2.0.7
* [List the other required mods here]

## Steps to replicate the issue

1. Loaded up 
2. reloaded textures with f3+t

expect textures to stay

What kind of server:
Singleplayer
Game Modes:
Creative

Save File:
Brand new save

## Screenshots (or videos)
![before](https://user-images.githubusercontent.com/44590540/158991235-adc4f40d-4d4e-41a3-ae8d-6d5486a65a5b.png)
![after](https://user-images.githubusercontent.com/44590540/158991201-c1371346-dc68-4e2c-983b-752285625732.png)

**Comment by InfinityRaider** [comment]
You have this happening with just Agricraft + InfinityLib?
I can not seem to reproduce this...

**Comment by CoolDCB** [comment]
I will reopen this instead of opening a new issue as I am also experiencing this issue.
