### ISSUE TITLE
Agricraft conflicting with Botany

### ISSUE THREAD

**Issue by Arthurbp19** [AgriCraft/AgriCraft#1448]
Hello I'm new here but I was playing my modpack today and I put agricraft but when I started it crashed I looked at the crash reports and saw this erro

[crash-2022-05-07_18.57.04-fml.txt](https://github.com/AgriCraft/AgriCraft/files/8647778/crash-2022-05-07_18.57.04-fml.txt)
r

How can I solve?

**Comment by InfinityRaider** [comment]
Update botania? What version are you running?

**Comment by Arthurbp19** [comment]
Obrigado. Atualizei e foi me salvou

**Comment by Arthurbp19** [comment]
Thanks. I updated and it worked, it saved me
