### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by agentwolf88** [AgriCraft/AgriCraft#1454]
Crash at startup. With and without optifine. No crashlog.

MC 1.18.2
Forge 40.1.25
AC 3.1.0

[debug.log](https://github.com/AgriCraft/AgriCraft/files/8796523/debug.log)
[latest.log](https://github.com/AgriCraft/AgriCraft/files/8796525/latest.log)

**Comment by agentwolf88** [comment]
Only Agricraft and Infinity Lib.

[debug.log](https://github.com/AgriCraft/AgriCraft/files/8796636/debug.log)
[latest.log](https://github.com/AgriCraft/AgriCraft/files/8796637/latest.log)

**Comment by InfinityRaider** [comment]
Server or client?

**Comment by agentwolf88** [comment]
Client

**Comment by InfinityRaider** [comment]
SLF4J got shaded in the jar on accident.
I have corrected this now, either download the mod again from CF or Modrinth, or manually delete org/slf4j from the jar:
![image](https://user-images.githubusercontent.com/8151219/171012831-7a1c2d21-5368-4556-8f18-7a698ee29d33.png)
