### ISSUE TITLE
[1.18.2] Where is the common or server config?

### ISSUE THREAD

**Issue by itsdinkd** [AgriCraft/AgriCraft#1455]
Why is there only a client config? This would mean when on a server, the client would be able to override what the server has set in its own client config. 

Please advise. Using this mod in a modpack which would also be used on servers and controlled by a client config is not a good idea as a player could edit the client config themselves and basically re-enable / reset anything overriding the server.

**Comment by InfinityRaider** [comment]
If a SP instance modifies things in their config, that will apply when they play in SP.
The server decides what happens.
