### ISSUE TITLE
Server Crash 1.18.2

### ISSUE THREAD

**Issue by RickieGamer** [AgriCraft/AgriCraft#1456]
## Quick description
Latest versions of agricraft crashing on server

## Related issues and searches
https://bin.bloom.host/rukonoloru

## Mods and versions used
* Minecraft: 1.18.2
* AgriCraft: 1.18.2-3.1.0
* InfinityLib: 2.1.0
* [List the other required mods here]

## Steps to replicate the issue
Crashed on server launch

**Comment by Lahnee** [comment]
confirmed issue with only agricraft installed on the server
https://bin.bloom.host/otisuxugon
Works fine from the client.

updating java to 17.0.3.1 did not help

**Comment by aNinjin** [comment]
It seems to crash when it tries to load the world file. This is what the console shows if that helps you.
https://bin.bloom.host/ojarusicon.properties
I also want to note that I tried Forge 40.1.30 and 40.1.31.

**Comment by Xplodin** [comment]
[crash-2022-06-05_02.39.51-server.txt](https://github.com/AgriCraft/AgriCraft/files/8839223/crash-2022-06-05_02.39.51-server.txt)

cannot start server with agricraft in :(

**Comment by InfinityRaider** [comment]
Fixed for next release
