### ISSUE TITLE
Game Client might crash upon rendering a amathyllis plant

### ISSUE THREAD

**Issue by lordgkram** [AgriCraft/AgriCraft#1460]
## Quick description

Game Client might crash upon rendering a amathyllis plant but only on certain growth stages.

## Mods and versions used

* Minecraft: 1.18.2
* AgriCraft: 3.1.1
* InfinityLib: 2.1.1
* Java: 18.0.1.1 (not testet with java 17)

## Steps to replicate the issue

1. Loaded up a world with agricraft
2. Placed a amathyllis plant
3. let it grow

## Expectations and explanations

The amathyllis plant(game also crashed with other plants, but i didn't look further into it) should be rendered and the game shouldn't crash.

## Your environment

* How are you playing?
  * Operating System: Arch Linux, kernel 5.17.7-arch1-1, x86_64
  * Launcher: MultiMC 5
  * Modpack: None
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

## Links to crash logs, stack traces, etc

[crash-2022-06-07_14.07.41-client.txt](https://github.com/AgriCraft/AgriCraft/files/8853039/crash-2022-06-07_14.07.41-client.txt)

**Comment by lordgkram** [comment]
Just testet this problem in development envirement and it still crashes with the same stacktrace
```SH
git clone --recursive https://github.com/AgriCraft/AgriCraft.git
cd AgriCraft
./gradlew runClient
```
witch runs on java17(stated by the crashreport)
[crash-2022-06-07_23.45.59-client.txt](https://github.com/AgriCraft/AgriCraft/files/8856814/crash-2022-06-07_23.45.59-client.txt)

**Comment by InfinityRaider** [comment]
Thanks for reporting, try removing one of the growth stages for the amathyllis crop as a workaround until I fix this
