### ISSUE TITLE
[1.18.2] AgriCraft crashes client when using Cyclic's Sprinkler & Soil.

### ISSUE THREAD

**Issue by Gbergz** [AgriCraft/AgriCraft#1461]
## Quick description
Player on our server were trying to speed up growth using sprinklers from cyclic & upgraded seeds from agricraft.

## Mods and versions used
* Minecraft: 1.18.2
* AgriCraft: 3.1.2
* InfinityLib: 2.1.2
* Cyclic: 1.7.2

## Steps to replicate the issue
1. Install AgriCraft
2. Install Cyclic
3. Use a sprinkler from cyclic on AgriCraft seeds.
4. Crash.

## Expectations and explanations
Explain: Player on our server were trying to speed up growth using sprinklers from cyclic & upgraded seeds from agricraft.
Expect: It not to crash clients.

## Your environment
* How are you playing?
  * Operating System: Win
  * Launcher: CurseForge
  * Modpack: TNP Limitless 5
* What kind of server:
  * [ ] Singleplayer
  * [x] Multiplayer
* Game Modes:
  * [X] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [X] Existing save

## Links to crash logs, stack traces, etc:
https://gist.github.com/Gbergz/5831a9a51dea205ac33ffce534cf20ab

## Crash 2 on cyclic soil:
https://gist.github.com/Gbergz/7e1a55c62a9e9559a3a12ec724dca748

## Screenshots (or videos)
No screenshot.

**Comment by InfinityRaider** [comment]
The issue is that Cyclic seems to be forcing growth ticks on the client side, which does not make sense to me.
I will add some code that prevents it from crashing, but imo, Cyclic should adapt its code so that it does not force growth ticks client side as well.
