### ISSUE TITLE
Netherwart Causes Crash when bonemealed

### ISSUE THREAD

**Issue by Spontaneo** [AgriCraft/AgriCraft#1462]
## Quick description

Anything that applies a bonemeal effect to the netherwart crop will cause it to crash.

## Mods and versions used

* Minecraft: 1.18.2
* AgriCraft: 1.18.2-3.1.2
* InfinityLib:
* [List the other required mods here]

## Steps to replicate the issue

Plant netherwart.
Apply bonemeal effect.
Tested bonemeal, cyclic sprinklers, watering cans, bees, Ars Rituals, Lilly pad of fertility
I have not tested this will all the crops so this might apply to more than just netherwart.

## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: Multi MC
  * Modpack: TNP 5
* What kind of server:
  * [ ] Singleplayer
  * [x ] Multiplayer
* Game Modes:
  * [x ] Survival
  * [ ] Creative
* Save File:
  * [x ] Brand new save
  * [ x] Only an existing save

[crash-2022-06-14_19.06.08-client.txt](https://github.com/AgriCraft/AgriCraft/files/8909574/crash-2022-06-14_19.06.08-client.txt)

**Comment by InfinityRaider** [comment]
This is fixed with https://github.com/AgriCraft/AgriCraft/commit/fec5f5bba123717eeee391af69569ba70b2473aa
