### ISSUE TITLE
Greenhouses spawning seeds of higer tier than set in config

### ISSUE THREAD

**Issue by 57331Fury** [AgriCraft/AgriCraft#1465]
I am making my own modpack, and would like to restrict the tier of seed that can spawn in an agricraft greenhouse. Edited the config file so that "I:"Greenhouse plant tier limit"=1", but when I restart the game, and start a new world, seeds of upto tier 5 still spawn. The only way I can get around this problem is to turn off world gen all together, and i`d rather not have to do that.

* MC version - 1.12.2
* AC version - agricraft-2.12.0-1.12.2-b2
* Sever type - Singleplayer, offline
* Launcher - Curseforge
* Is the issue consistant - Yes. Every greenhouse I have found in every world has seeds above the maximum tier set in the config.
* What you expect to happen - For seeds no higer than tier 1 to spawn.
* Potentially conflicting mods - Actually Additions,  MysticalAgriculture,  MysticalAgradditions.

If I load ONLY Agricraft, and have the config set to only allow tier 1 seeds, then diamond, emerald, lapis, redstone seeds spawn, and if I have Mystical Agriculture loaded, then I end up with ALL modded seeds spawning in the greenhouses, despite the config setting.

**Comment by InfinityRaider** [comment]
Might be a bug there, even so, I am not actively supporting 1.12 anymore.
