### ISSUE TITLE
Crash on Startup 1.18.2 client

### ISSUE THREAD

**Issue by Ammatarasu** [AgriCraft/AgriCraft#1470]
So just tried adding AgriCraft to my modpack but ended up getting this error in my crash log. I dont know if its just an incompatibilty with one of the other mods or if its a specific issue. I've attached the crash log below

[crash-2022-07-15_20.57.37-fml.txt](https://github.com/AgriCraft/AgriCraft/files/9123369/crash-2022-07-15_20.57.37-fml.txt)

[latest.log](https://github.com/AgriCraft/AgriCraft/files/9123384/latest.log)

**Comment by SimonMeskens** [comment]
I get the same error, I assume it's a compatibility problem with the latest Create mod

**Comment by InfinityRaider** [comment]
See #1468
