### ISSUE TITLE
AgriCraft Crash On Ender_IO(1.12.2)

### ISSUE THREAD

**Issue by Mrorik1** [AgriCraft/AgriCraft#1471]
the Crop_Sticks with block_farm_station will crash.
(Sorry,my English is not good.I can't express myself in English.Maybe you can translate the following Chinese with a translator)
种植站收割作物架上的作物时会导致服务器崩溃.(The server will crash when the planting station harvests the crops on the crop rack)
[crash-2022-07-20_08.45.12-server.txt](https://github.com/AgriCraft/AgriCraft/files/9146126/crash-2022-07-20_08.45.12-server.txt)

**Comment by InfinityRaider** [comment]
I'm not supporting 1.12 anymore
