### ISSUE TITLE
[BUG] Crash on load with Create 0.5.0d

### ISSUE THREAD

**Issue by serialtasted** [AgriCraft/AgriCraft#1475]
## Quick description
Agricraft crashes with latest version of Create 0.5.0d
java.lang.NoSuchFieldError: MECHANICAL_HARVESTER

## Mods and versions used

* Minecraft: 1.18.2
* AgriCraft: 3.1.4
* InfinityLib: 2.1.4
* Create: 0.5.0d
* Flywheel: 0.6.5

## Steps to replicate the issue

1. Install Agricraft and Create
2. Launch...
3. Crash

## Links to crash logs, stack traces, etc
* https://pastebin.com/ZVsQTjuH

**Comment by Ataion** [comment]
Hello serialtasted,
i had the same problem like you
in the config from Agricraft there is a subpoint named compat and 
there is the compatibility with the create mod listed wen you change it from true to false it shoud work
i hope it works

**Comment by serialtasted** [comment]
That's a solution that is not really a solution.. The compatibility that it adds is not a big deal, sure. I can live with it disabled for now, but it really needs to be fixed.
Thanks for the tip anyway!

**Comment by desbarmitar** [comment]
I have the same problem. Waiting for a fix.

**Comment by CrownJoker** [comment]
Same problem as well, Minecraft 1.18.2, Forge version 40.1.74, Create version 0.5.0.d, and Agricraft 3.1.4

**Comment by MokahTGS** [comment]
Yup same...waiting for a fix!

**Comment by drewhoener** [comment]
Linking issue #1478
