### ISSUE TITLE
Seed Analyzer causes game to crash when right clicked

### ISSUE THREAD

**Issue by little1wiki** [AgriCraft/AgriCraft#1476]
## Quick description
When right-clicking on the seed analyzer in a single-player survival world, my game crashes.  It is fine when shift-right clicking to put something in, but still crashes even with something in it.  Also tried it in a brand new creative world and it still crashed

## Related issues and searches
https://github.com/AgriCraft/AgriCraft/issues/1463

## Mods and versions used
* Minecraft: 1.18.2
* AgriCraft: 3.1.3
* InfinityLib: 2.1.4
* (all mods listed in crash report)

## Steps to replicate the issue
1. All mods installed
2. Placed down the seed analyzer
3. Right-clicked the seed analyzer
4. Crashed

## Expectations and explanations
I see that in previous issues it has to do with the pehkui mod, however, I do not use the pehkui

## Your environment
* How are you playing?
  * Operating System: Windows 11
  * Launcher: Forge
* What kind of server:
  * [x] Singleplayer
* Game Modes:
  * [x] Survival
  * [x] Creative
* Save File:
  * [x] Brand new save
  * [x] Only an existing save

## Links to crash logs, stack traces, etc
https://paste.ee/p/CNbSR

**Comment by InfinityRaider** [comment]
Optifine
