### ISSUE TITLE
[Forge - 1.18.2] Missing Texture Farmer´s Delight Plants

### ISSUE THREAD

**Issue by MortenDeloke** [AgriCraft/AgriCraft#1482]
## Quick description
When you plant Rice from Farmer´s Delight with the Agricraft Sticks the have a Texture Error, when they reach their "2 Block" phase.
When you plant Tomato from Farmer´s Delight with the Agricraft Sticks the have a Texture Error, when they reach their "Mature" phase.
When you open the Agricultur Journal These two will have there an Error Texture too

## Mods and versions used
* Minecraft: 1.18.2
* AgriCraft: 1.18.2 - 3.1.4
* InfinityLib: 1.18.2 - 2.1.4
* Farmer´s Delight: 1.18.2 - 1.2.0

## Steps to replicate the issue
1. Plant the Farmer´s Delight Rice underwater with the Agricraft Crop sticks Agricraft Crop sticks
2. Bonemeal them until they reach out of the water
3. See the Texture Error

1. Plant the Farmer´s Delight Tomato with the Agricraft Crop sticks Agricraft Crop sticks
2. Bonemeal them until they are ready to harvest
3. See the Texture Error 

## Expectations and explanations
 See the correct Texture

## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: Curseforge
  * Modpack: Custom
* What kind of server:
  * [X] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save
  * [X] Both

## Screenshots (or videos)
* Rice Plant
 https://i.imgur.com/iJO3xqH.png
* Rice Plant Journal
  https://i.imgur.com/REEut19.png
* Tomato Plant
https://i.imgur.com/2bb2KRd.png
* Tomato Plant Journal
https://i.imgur.com/laumujZ.png

**Comment by Ketheroth** [comment]
fixed with 82aa36e
