### ISSUE TITLE
1.12.2 bad sprinkler particle performance

### ISSUE THREAD

**Issue by therealKoolant** [AgriCraft/AgriCraft#1523]
Sprinklers give frame drops even with particles turned down. I'm pretty sure it's because you use the entire water texture for the particles, not just a solid color. I also would like to keep my particles up so I can see other ones. You probably aren't maintaining the 1.12.2 version much, but I'd like it if you could make the sprinklers spawn a bit fewer particles and use a solid color instead of a texture.

**Comment by Ketheroth** [comment]
No more work will be done on 1.12

**Comment by InfinityRaider** [comment]
For future reference, it is not the particles.
Sprinklers, or whichever method to speed up growth ticks, used at large scales will cause 'lag'.
Plants growing induces render updates, therefore, many plants growing every tick will require many growth ticks.
