### ISSUE TITLE
Game crashing with Agricraft after placing sugarcanes on 1.20.4

### ISSUE THREAD

**Issue by ExpertMedal7** [AgriCraft/AgriCraft#1524]
[New Paste 1.txt](https://github.com/user-attachments/files/15847854/New.Paste.1.txt)

## Quick description

Placing a sugar cane down seems to crash the game and you cannot rejoin the world(crashes on world loading) until the agricraft mod has been removed.(Can be compatibility issue so hopefully it helps you figure out the incompatibility or the issue)
## Related issues and searches

* https://github.com/AgriCraft/AgriCraft/issues?q=is%3Aissue%20EXAMPLE

## Mods and versions used

* Minecraft: 1.20.4
* AgriCraft: AgriCraft-fabric-1.20.4-4.0.0-beta.jar
* InfinityLib: None
* [List the other required mods here]

  [✔️] 2032-world-height-1.17+.jar
  [✔️] adastra-fabric-1.20.4-1.16.5.jar
  [✔️] Ad-Astra-Giselle-Addon-fabric-1.20.4-7.2.jar
  [✔️] additionallanterns-1.1.1b-fabric-mc1.20.4.jar
  [✔️] AgriCraft-fabric-1.20.4-4.0.0-beta.jar
  [✔️] Amplified_Nether_1.20.x_v1.2.5.jar
  [✔️] architectury-11.1.17-fabric.jar
  [✔️] bclib-3.30.1.jar
  [✔️] beautify-1.2.1+1.20.4.jar
  [✔️] betterarcheology-1.1.9-1.20.4.jar
  [✔️] better-end-4.30.1.jar
  [✔️] better-nether-9.30.0.jar
  [✔️] BiomeParticleWeather-5.2.0.jar
  [✔️] BiomesOPlenty-fabric-1.20.4-19.0.0.89.jar
  [✔️] Boids-1.1.1.jar
  [✔️] BOMD-1.8.2-1.20.4.jar
  [✔️] botarium-fabric-1.20.4-3.2.2.jar
  [✔️] cardinal-components-api-5.4.0.jar
  [✔️] Chimes-v2.0.2-1.20.4-Fabric.jar
  [✔️] chunkloaders-1.2.8a-fabric-mc1.20.4.jar
  [✔️] cicada-lib-0.7.2+1.20.2-1.20.4.jar
  [✔️] cloth-config-13.0.121-fabric.jar
  [✔️] comforts-fabric-7.2.2+1.20.4.jar
  [✔️] Continents_1.20.x_v1.1.5.jar
  [✔️] continuity-3.0.0-beta.5+1.20.2.jar
  [✔️] Controlify-2.0.0-beta.10+1.20.4.jar
  [✔️] CreativeCore_FABRIC_v2.11.26_mc1.20.4.jar
  [✔️] cristellib-1.2.4-fabric.jar
  [✔️] Croptopia-FABRIC-3.0.1-1.20.4.jar
  [✔️] deeperdarker-fabric-1.20.4-1.2.6.jar
  [✔️] desertupdate-1.2.1-1.20.4.jar
  [✔️] DistantHorizons-7e45051ffdf8ed56514d1cbcf223a24aa58b83e6.jar
  [✔️] do_a_barrel_roll-fabric-3.6.0+1.20.4.jar
  [✔️] duckling-fabric-1.20.4-4.0.0.jar
  [✔️] DungeonsArise-1.20.x-2.1.58-fabric-release.jar
  [✔️] eating-animation-1.20+1.9.61.jar
  [✔️] emi-1.1.6+1.20.4+fabric.jar
  [✔️] EnhancedVisuals_FABRIC_v1.7.1_mc1.20.4.jar
  [✔️] entity_model_features_fabric_1.20.4-2.0.2.jar
  [✔️] entity_texture_features_fabric_1.20.4-6.0.1.jar
  [✔️] entityculling-fabric-1.6.4-mc1.20.4.jar
  [✔️] EpheroLib-FABRIC-1.2.0-1.20.4.jar
  [✔️] Essential.jar
  [✔️] Essential Dependencies.jar
  [✔️] fabric-api-0.96.11+1.20.4.jar
  [✔️] fabric-end-remastered-5.2.4.jar
  [✔️] fabric-language-kotlin-1.10.18+kotlin.1.9.22.jar
  [✔️] fallingleaves-1.15.6+1.20.1.jar
  [✔️] ferritecore-6.0.3-fabric.jar
  [✔️] ForgeConfigAPIPort-v20.4.3-1.20.4-Fabric.jar
  [❌] FpsReducer2-fabric-1.20.4-2.7.jar.disabled (disabled)
  [✔️] geckolib-fabric-1.20.4-4.4.4.jar
  [✔️] Geophilic v2.4.0 f15-48.jar
  [✔️] GlitchCore-fabric-1.20.4-1.0.0.59.jar
  [✔️] grapplemod-1.8+1.20.4.jar
  [✔️] handcrafted-fabric-1.20.4-3.2.1.jar
  [✔️] ImmediatelyFast-Fabric-1.2.14+1.20.4.jar
  [❌] immersive-portals-5.1.8-mc1.20.4-fabric.jar.disabled (disabled)
  [✔️] indium-1.0.30+mc1.20.4.jar
  [✔️] iris-1.7.0+mc1.20.4.jar
  [✔️] lazydfu-0.1.3.jar
  [✔️] lithium-fabric-mc1.20.4-0.12.1.jar
  [✔️] mcw-bridges-3.0.0-mc1.20.4fabric.jar
  [✔️] memoryleakfix-fabric-1.17+-1.1.5.jar
  [✔️] modmenu-9.0.0.jar
  [✔️] modmenu-9.2.0-beta.2.jar
  [✔️] monolib-fabric-1.20.4-1.1.0.jar
  [✔️] moonlight-1.20.4-2.10.3-fabric.jar
  [✔️] more_beautiful_torches-merged-1.20.4-3.0.0.jar
  [✔️] morebowsandarrows-merged-1.20.4-3.0.1.jar
  [✔️] moremobvariants-fabric+1.20.4-1.3.0.1.jar
  [✔️] mru-0.4.0+1.20.4.jar
  [✔️] MutantMonsters-v20.4.1-1.20.4-Fabric.jar
  [✔️] niftycarts-3.3.1+1.20.4.jar
  [❌] noisium-fabric-2.0.3+mc1.20.2-1.20.4.jar.disabled (disabled)
  [✔️] notenoughanimations-fabric-1.7.3-mc1.20.4.jar
  [✔️] notenoughcrashes-4.4.7+1.20.4-fabric.jar
  [✔️] nvidium-0.2.6-beta.jar
  [✔️] Patchouli-1.20.4-85-FABRIC.jar
  [✔️] Patchouli-1.20.4-85-FABRIC (1).jar
  [✔️] physics-mod-pro-v169-fabric-1.20.4.jar
  [✔️] plushies-1.4.0-fabric.jar
  [✔️] PresenceFootsteps-1.9.4+1.20.4.jar
  [✔️] PuzzlesLib-v20.4.44-1.20.4-Fabric.jar
  [✔️] reeses_sodium_options-1.7.2+mc1.20.4-build.102.jar
  [✔️] resourcefulconfig-fabric-1.20.4-2.4.7.jar
  [✔️] resourcefullib-fabric-1.20.4-2.4.10.jar
  [✔️] Resourcify (1.20.2-1.20.4-fabric)-1.3.6.jar
  [❌] RoughlyEnoughItems-14.1.727-fabric.jar.disabled (disabled)
  [✔️] SereneSeasons-fabric-1.20.4-9.3.0.25.jar
  [✔️] skinlayers3d-fabric-1.6.6-mc1.20.4.jar
  [✔️] sleep_tight-1.20.4-1.1.21-fabric.jar
  [✔️] SnowUnderTrees-2.3.0+1.20.4.jar
  [✔️] sodium-extra-0.5.4+mc1.20.4-build.116.jar
  [✔️] sodium-fabric-0.5.8+mc1.20.4.jar
  [✔️] sound-physics-remastered-fabric-1.20.4-1.3.1.jar
  [✔️] spark-1.10.58-fabric.jar
  [✔️] sparsestructures-2.1.2.jar
  [✔️] spawnanimations-v1.9.4-mc1.17x-1.20x-mod.jar
  [✔️] stutterfix-mc1.20.3-0.2.0.jar
  [✔️] supermartijn642configlib-1.1.8a-fabric-mc1.20.2.jar
  [✔️] supermartijn642corelib-1.1.17a-fabric-mc1.20.4.jar
  [✔️] t_and_t-1.12.1.1.jar
  [✔️] TechReborn-5.10.4.jar
  [✔️] tectonic-fabric-1.20-2.3.4.jar
  [✔️] TerraBlender-fabric-1.20.4-3.3.0.12.jar
  [✔️] TheOffcialOvergrownMod9.6.2-neoforge-1.20.4.jar
  [✔️] timecontrol-1.20.4-1.6.0.jar
  [✔️] ToughAsNails-fabric-1.20.4-9.2.0.168.jar
  [✔️] trinkets-3.8.1.jar
  [✔️] VisualWorkbench-v20.4.2-1.20.4-Fabric.jar
  [✔️] Waddles-fabric-1.20.4-0.10.1.jar
  [✔️] waveycapes-fabric-1.4.7-mc1.20.4.jar
  [✔️] weaponmaster_ydm-forge-1.20.4-4.2.3.jar
  [✔️] YetAnotherConfigLib-3.5.0+1.20.4-fabric.jar
  [✔️] YungsApi-1.20.4-Fabric-4.4.3.jar
  [✔️] YungsBridges-1.20.4-Fabric-4.4.2.jar
  [✔️] zipfstmp12527012342083810116.tmp

## Steps to replicate the issue

1. Loaded up `Find a sugarcane and break it`
2. Placed a `Sugarcane on sand`
3. Game crash and world no longer starts with the mod
4.

## Expectations and explanations
Trying to grow sugar canes
Because Game crashes

## Your environment

* How are you playing?
  * Operating System: Windows 11
  * Launcher: MULTIMC
  * Modpack: Custom
* What kind of server:
  * [ X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X ] Survival
  * [ ] Creative
* Save File:
  * [ X] Brand new save
  * [ X] Only an existing save

## Links to crash logs, stack traces, etc

.    https://paste.ee/p/VyBOB

**Comment by Ketheroth** [comment]
3953aa9685169a7bdc36dd82d317e1fcc230a3e1 should fix this issue
