### ISSUE TITLE
Crashing Game. 

### ISSUE THREAD

**Issue by juggalostll7** [AgriCraft/AgriCraft#1527]
We have added this mod to All the mods 9, When we are try to place anything on farmland or right click farmland with a hoe it crashes the game.  The forge version we are running is 47.2.20. We did disable weeds.  The game also crashes when planting seeds on farmland. Also when in creative and accessing the inventory the game would crash. 

When Crashing the error says 

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.m_206579_()" because the return value of "net.minecraftforge.server.ServerLifecycleHooks.getCurrentServer()" is null

Hear is the crash report.  From what I see it has to do with the AgriCraft mod. 

[crash-2024-06-16_15.32.58-client.txt](https://github.com/user-attachments/files/15859654/crash-2024-06-16_15.32.58-client.txt)

Game version is 1.20.1
I am running a server on my PC that we connect to. The server would stay running but the client would crash.

**Comment by AlexandreMouyen** [comment]
I have the same issue on Direwolf20 1.20.1 too. Will we have a patch?

Thanks

**Comment by Ketheroth** [comment]
The issue should be resolved with the version 4.0.2
