### ISSUE TITLE
Agricraft Not Displaying Pam's Harvestcraft Seed Textures

### ISSUE THREAD

**Issue by beebere** [AgriCraft/AgriCraft#1538]
Quick description
I have both pam's harvestcraft-crops and agricraft installed in the same modpack, and the pam's seeds, when converting to agricraft seeds, do not show any textures. The seeds still grow like normal and can be grown with or withou crop sticks but there are no textures.
Searching for both pam's harvestcraft and missing textures provides no results.

Mods and versions used

* Minecraft: 1.20.1
* AgriCraft: 1.20.1-4.0.1-beta
* InfinityLib: -> Resourcefullib 1.20.1-2.1.25 and Resourcefulconfig 1.20.1-2.1.2
* Pam's harvestcraft: 1.20-1.0.3

Steps to replicate the issue
1. open creative world file
2. look in menu for pam's harvestcraft seeds in the agricraft tab
3. seeds are missing textures

Expectations and explanations
Seeds are only missing textures but work otherwise, as in they grow and produce crops except do not have textures

Your environment
* How are you playing?
  * Launcher: Prism Launcher
* What kind of server:
  * [X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [ ] Only an existing save

Screenshots

![image](https://github.com/user-attachments/assets/f9106efd-6f15-4176-a9da-ea74315625d9)
![image](https://github.com/user-attachments/assets/715fcb23-fa98-4c77-bbfd-cb1fff7f5d55)

**Comment by Ketheroth** [comment]
enable the pam's haverstcraft resource pack. It is not enabled by default

**Comment by beebere** [comment]
This fixed my problem. Thank you
