### ISSUE TITLE
Pam's and Farmer's Delight Compat not working correctly/at all

### ISSUE THREAD

**Issue by Cloudy-Q** [AgriCraft/AgriCraft#1540]
## Quick description
Mod not returning Pam's HC2 textures; no support for Farmer's Delight?

1.) Pam's HC2 textures are coming back with the "null" texture. code and callbacks all point to it working, but doesn't

2.) Farmer's Delight support isn't working or not present. No callbacks or added seeds/genetics for any Farmer's Delight plants and its respective add-ons (I don't expect the support for the add-ons but since the base mod was stated in the CurseForge page, I would assume it would be there)

## Related issues and searches
No other similar reports or issues present

Searched through the mod files and everything seems to call back correctly, but I also do not know how to create or edit mods.

## Mods and versions used
Currently in Pack Development but issue can be recreated with just these base mods:

Minecraft - v1.20.1
Agricraft - v4.0.2
Farmer's Delight - v1.2.4
Pam's HarvestCraft 2 - Crops - v1.0.3
Pam's HarvestCraft 2 - Food Core - v1.0.5
Pam's HarvestCraft 2 -Food Extended - v1.0.1
Pam's HarvestCraft 2 - Trees - v1.0.2
Resourceful Config - v2.1.2
Resourceful Lib - v2.1.25

Running on - Forge - v47.3.0

## Steps to replicate the issue
Start-up
Load World

## Expectations and explanations
All Pam's textures would be implemented correctly

Support for Farmer's Delight would be included

## Your environment
* How are you playing?
  * Operating System: Windows 11
  * Launcher: CurseForge
  * Modpack: My Own (currently in Development)
* What kind of server:
  * [x] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [x] Survival
  * [x] Creative
* Save File:
  * [x] Brand new save
  * [x] Only an existing
 save

## Screenshots (or videos)
![agricraft](https://github.com/user-attachments/assets/05be7db1-3c7b-42cf-8c25-f0b95e4540cc)

**Comment by Ketheroth** [comment]
1)  enable the Pam's HC2 compat resourcepack (it's not enabled by default, because of forge's limitation)
2) farmer's delight is not yet supported on 1.20 (but was on earlier minecraft version, hence the note on the curseforge page)

**Comment by Cloudy-Q** [comment]
> 1. enable the Pam's HC2 compat resourcepack (it's not enabled by default, because of forge's limitation)
> 2. farmer's delight is not yet supported on 1.20 (but was on earlier minecraft version, hence the note on the curseforge page)

Thank you! Checking the Resource Pack folder didn't even cross my mind! It's always the simplest solutions that fly over me

I appreciate the reply, having options to add crops helps out here, I have a few crop mods that I'll need to add json files for either way :P

**Comment by Cloudy-Q** [comment]
Simple Solutions to Simple Problems
