### ISSUE TITLE
[BUG] Resourceful Config is not a dependency for the mod on Curseforge

### ISSUE THREAD

**Issue by ACCBDD** [AgriCraft/AgriCraft#1559]
Decided not to use the issue template, as this is relatively minor - on Curseforge, there is no relation for Resourceful Config for the 1.20.1 version of Agricraft. This means that launchers that download the mod don't realize they need to download Resourceful Config as well; it's configured in the mod's mods.toml, leading to a crash on startup that tells the user to download it, but having it in the actual dependencies section would be nice :)

**Comment by Ketheroth** [comment]
fixed it, I forgot to do it
