### ISSUE TITLE
Seed Storage

### ISSUE THREAD

**Issue by InfinityRaider** [AgriCraft/AgriCraft#43]
Elegant way to store seeds of different kinds/stats

**Comment by LordTy** [comment]
Might a chest that only shows the best/worst( toggle-able) of a certain seed type be a good solution?

So when I insert a 1-1-1 a 1-1-2 and a 3-1-1 seed into the chest, i see a single seed stack, with the first seed having the data 3-1-1.

**Comment by InfinityRaider** [comment]
It's almost done, just needs the final finish, some polishing, and a nice render.
Its basicly a warehouse: you have a block per seed that holds infinite seeds, to access them you have to construct some kind of barn and then interact with the interface, you can sort per seed (that is in the warehouse) and then you can sort and filter seeds on stats.

**Comment by LordTy** [comment]
Sounds awesome, I am looking forward to it.

**Comment by medsal15** [comment]
Well, while we're waiting for this storage block, I recommend using the filling cabinet from Extra Utilities. For reasons, it takes ALL seeds. Unlike this storage block, it can't be filled with an infinite number of seeds.

**Comment by darthvader45** [comment]
Honestly, I'd have it be a silo structure rather than a barn.  Silos seem more suited to storing seeds/grains/etc.
