### ISSUE TITLE
Maven Repo

### ISSUE THREAD

**Issue by Keridos** [AgriCraft/AgriCraft#560]
Hi there, is there a maven repo where we can add AgriCraft as a dependency for building our mods in the build.gradle?

**Comment by InfinityRaider** [comment]
No sorry, for 1.7 you can use Gradle's CurseForge plugin to grab the api jar from CurseForge, for 1.8 you'll have to do it manually, apologies.

**Comment by Keridos** [comment]
No problem, thanks for the fast answer. Though I would find it nice, if AgriCraft was on some maven :)

**Comment by RlonRyan** [comment]
Yeah CurseForge really needs to implement some type of ForgeGradle repository...

**Comment by InfinityRaider** [comment]
I'm really not familiar how any of that works or is set up, if it can be done for free, I don't see anything against putting one up, it has been requested multiple times.

**Comment by RlonRyan** [comment]
Oh there is really nothing we can do... It's just with the popularity of both ForgeGradle and CurseForge, you would think that they would work better together...

I'd recommend closing this issue, as there is nothing really to do...

**Comment by Keridos** [comment]
@InfinityRaider you could ask tterrag, i think he has a rather large repo.

**Comment by InfinityRaider** [comment]
Can do, but I'm not going to bother Tterrag with that.

**Comment by TehNut** [comment]
Most mod authors that run a Maven would be more than happy to provide you access.

**Comment by InfinityRaider** [comment]
Well I'm not comfortable to ask someone who I rarely speak with for a service like that.

**Comment by InfinityRaider** [comment]
@RlonRyan you were going to set up a maven?

**Comment by RlonRyan** [comment]
Yup... I have a basic setup going but i'm not sure how much I like it... I think it is too intense for a raspberry pi to run, so I need to find a more lightweight one...

**Comment by TehNut** [comment]
I'm willing to allow you to push to my maven if you want

**Comment by RlonRyan** [comment]
That would be nice!

**Comment by TehNut** [comment]
Alright. Ping me on discord or IRC and we can talk when I get home

**Comment by RlonRyan** [comment]
@TehNut What's your discord?

**Comment by TehNut** [comment]
TehNut#1590. I'm on the /r/feedthebeast, MMD, and Modders Corner discords.

**Comment by RlonRyan** [comment]
For now, you can use [JitPack](https://jitpack.io).

**Comment by TehNut** [comment]
The reason this was delayed was because I couldn't figure out how to do remote pushes for Maven. If wanted, I have created an Agricraft project on my Jenkins [here](https://github.com/InfinityRaider/AgriCraft). If you create a user, I can add you to it and you can push builds whenever you want.

**Comment by RlonRyan** [comment]
@TehNut Broken link...

**Comment by TehNut** [comment]
Hah. I forgot I had copied another link... http://tehnut.info/jenkins/job/Agricraft/

**Comment by RlonRyan** [comment]
AgriCraft will be available on JitPack and TehNut's maven for development purposes.
