### ISSUE TITLE
Recipes for all water channels blocks do not work on servers

### ISSUE THREAD

**Issue by Xiaminou** [AgriCraft/AgriCraft#724]
Cannot craft any of the water channels on servers.

https://youtu.be/GjPc86zkb4A

[fml-client-latest.txt](https://github.com/InfinityRaider/AgriCraft/files/644542/fml-client-latest.txt)
[fml-server-latest.txt](https://github.com/InfinityRaider/AgriCraft/files/644541/fml-server-latest.txt)

Confirmed with agricraft only, does not happen on singleplayer.

Environment: Server
Minecraft: 1.10.2
Forge: 2185
Mods: [list.txt](https://github.com/InfinityRaider/AgriCraft/files/644504/list.txt)

**Comment by Rebelyrocks** [comment]
I am having the same issue, but only with modded planks. If I use vanilla planks the recipes work.

**Comment by Rebelyrocks** [comment]
[crash-2016-12-16_15.05.28-client.txt](https://github.com/InfinityRaider/AgriCraft/files/658136/crash-2016-12-16_15.05.28-client.txt)

**Comment by RlonRyan** [comment]
Fixed as of a5.

**Comment by RlonRyan** [comment]
Does this issue still apply to a5?

**Comment by Renadarain** [comment]
Still applies in a6 - modded server :)
