### ISSUE TITLE
Add JSON Debugging GUI

### ISSUE THREAD

**Issue by RlonRyan** [AgriCraft/AgriCraft#740]
Given that the JSON files are markedly complex, they can be confusing to the end-users at times. This should be addressed by adding some form of ingame notification that notes exactly what is wrong with the JSON files in a clear manner. Such is to allow for the users to easily debug their own JSON files without help from AgriCraft developers.

**Comment by heatherhaks** [comment]
could one simply add chat messages (similar to update notifications) listing off found json files that were not loaded due to error? Simply as a simple placeholder so that it's more obvious where to look until a more sophisticated GUI option is implemented?

**Comment by InfinityRaider** [comment]
I'd rather have a separate java tool, preferrably client side (most likely a Forge Mod, which pack devs can add to their instance).
