### ISSUE TITLE
Rework & Unify GUI System

### ISSUE THREAD

**Issue by RlonRyan** [AgriCraft/AgriCraft#742]
Currently the mod has two separate GUI systems. The first, or the original one is used for all guis with the exception of the Seed Journal, which uses a newer component-based system. Given that maintaining two systems would be a nightmare, it is optimal to migrate to using only one of them. Given that the component GUI system is newer and has shown to work markedly well for the Seed journal, all GUI systems should be migrated to it, and solely it.

This would entail abstracting and unifying container guis with non-contained guis, so that there is an easy, clean base to work with. This may take some work, so it should probably be delayed to a release following 2.0.0.

**Comment by RlonRyan** [comment]
This is partially complete as of 2.0.0a11.

**Comment by InfinityRaider** [comment]
I'd like a streamlined GUI system in InfinityLib to be honest, will probably get to it when we start implementing the GUIs on the 1.16 branch.

Given that as a result, this will be more an InfinityLib related issue, I am closing this here.
