### ISSUE TITLE
New block request: composting bin

### ISSUE THREAD

**Issue by heatherhaks** [AgriCraft/AgriCraft#747]
Currently one ends up with a lot of extra seeds as you work your way to better plants. You also end up with a lot of weed seeds. Currently there is no use for these extra seeds. I request a new block, a composting bin that accepts items such as seeds (configurable in JSON, perhaps with variables such as how much 'value' a given compostable has) and eventually spits out fertilizer which acts like bone meal.

An example of how this would work, with placeholder values, is as follows: Compostable items have a compost value. Let's say wheat seeds have 10 compost value each. The compost bin has a threshold in order to convert items into fertilizer. Let's say the threshold is 100. So in this example, adding ten wheat seeds will get you one fertilizer. This should take some time, say 30 seconds per conversion. If one would like this process to be more complex and likely more interesting, one could allow the compost bin to be faster if it's near water, and maybe allow it to accept 'boosters' like mushroom spores that speed up the conversion rate.

**Comment by InfinityRaider** [comment]
I was thinking of implementing such a thing in 1.16 as well.

**Comment by InfinityRaider** [comment]
Since 1.16 adds a vanilla composter, I have made the seeds compostable in that.
