### ISSUE TITLE
JSON Fertilizer Descriptions

### ISSUE THREAD

**Issue by RlonRyan** [AgriCraft/AgriCraft#750]
Fertilizers should be described by JSON files so that users have complete control over their potency and other effects.

**Comment by InfinityRaider** [comment]
But agricraft does not add fertilizers o.O

**Comment by mrlamb** [comment]
I was wondering if this is why things that act as bonemeal but aren't themselves bonemeal (for example actually additions fertilizer) don't seem to interact with crops even if they interact with bonemeal.

**Comment by InfinityRaider** [comment]
Do the fertilizer adapterizers not cover this?
