### ISSUE TITLE
JSON Plants Missing Seed Drop Option

### ISSUE THREAD

**Issue by RlonRyan** [AgriCraft/AgriCraft#754]
Currently all plants regardless of type, drop their respective seeds when broken. As a result, weed seeds are taking over the empire. Consequently, JSON plants need an option as to whether or not they should drop seeds when broken.

**Comment by InfinityRaider** [comment]
Make it a probability rather than a boolean.
Or even an array of 10 probabilities for different levels of strength.

**Comment by RlonRyan** [comment]
I wonder how complicated the file will be when we actually do the release.

On a side note, do you want to keep the only mature crops drop seeds option?

**Comment by InfinityRaider** [comment]
hmm its not rly completely redundant...

**Comment by RlonRyan** [comment]
Soo...

**Comment by InfinityRaider** [comment]
Keep it, itll overrule the plant specific drop settings, and the plant specific drop settings are still applied when the mature plant drops the seed.
