### ISSUE TITLE
Missing Rendering Modes

### ISSUE THREAD

**Issue by RlonRyan** [AgriCraft/AgriCraft#793]
There are rendering modes that have yet to be implemented in the mod. They are:

- [ ] Gourd Rendering
- [ ] Star Rendering
- [ ] Fast Cross Rendering

**Comment by InfinityRaider** [comment]
star rendering?

**Comment by InfinityRaider** [comment]
Relevant for 1.16 I guess.

**Comment by InfinityRaider** [comment]
I have added additional rendering modes, if more are desired to be added, see [this commit.](https://github.com/AgriCraft/AgriCraft/commit/899bd1fcb29cf1e8247c32c1cce311eb447a7213)
