### ISSUE TITLE
JSON Mod Sensitivity

### ISSUE THREAD

**Issue by RlonRyan** [AgriCraft/AgriCraft#794]
Currently, if you were to bundle a set of plant files that depended on a certain mod, and the mod wasn't present then the log gets spammed with 'invalid plants'. As such, the JSONs should be able to indicate required mods.

**Comment by RlonRyan** [comment]
Partially addressed in 2.0.0a8

**Comment by RlonRyan** [comment]
This should instead be implemented by a required_mods field in the JSON files.

**Comment by InfinityRaider** [comment]
Is this still an issue, or has this been fixed in the meantime?
