### ISSUE TITLE
Broken Irrigation Channel Hitbox

### ISSUE THREAD

**Issue by fflortix** [AgriCraft/AgriCraft#813]
![2017-01-26_22 39 27](https://cloud.githubusercontent.com/assets/25375924/22376727/6be6a8f6-e4af-11e6-9abf-6564cfbc82c0.png)

**Comment by RlonRyan** [comment]
I think you mean hitbox?

**Comment by fflortix** [comment]
Yes ^^' the hidbox does not exist

**Comment by RlonRyan** [comment]
This has been fixed for the upcoming a17 release.
