### ISSUE TITLE
Way to get seeds

### ISSUE THREAD

**Issue by Waisse** [AgriCraft/AgriCraft#825]
Some Agricraft seeds can't be obtained naturally : 

- Sugarcane seed
- Cactus seed
- Both mushroom spores
- Potato seeds

Others can obtained with mob drop, loot chest, village, or via mutation. To fix that, I suggest a way to add seeds to grass drop.

**Comment by InjuredWolf** [comment]
If you need to, edit the seed items in the JSONs for each of those plants to include the base items. Might help.

**Comment by Waisse** [comment]
Of course I need to, default config make too many seeds unavailable. My bandaid fix was to minetweak grass drop : http://pastebin.com/BEMdRk9f

**Comment by RlonRyan** [comment]
I'll have to make a mark-and-sweep reach-ability check for seeds...

**Comment by Morpheus1101** [comment]
The script works fine, however, mushroom spores dont seem to be able to be planted in any crop sticks on Mycelium, grass, dirt, sand, farmland ....Are they as yet not implemented to actually be planted ?

**Comment by RlonRyan** [comment]
I think this is largely fixed as of 2.0.0a16... The default JSON files have been updated as to make all the originally unobtainable seeds obtainable, therefore I am closing this issue.
