### ISSUE TITLE
Disable Vanilla Farming broken

### ISSUE THREAD

**Issue by Thyriel** [AgriCraft/AgriCraft#831]
Version: agricraft-2.0.0-0.6.0-a10.jar

B:"Disable Vanilla Farming"=true
in the config file doesn't seem to work. Planting, growing and harvesting still works on farmland without crops.

**Comment by Thyriel** [comment]
Any news on this ?

**Comment by RlonRyan** [comment]
Yeah this will take a bit to get the event intercept properly implemented.

**Comment by bookerthegeek** [comment]
## Heyo!
Current mods that still are plantable (So you have a list maybe?) (Trying to be helpful 😉)
- Vanilla
- Pam's HarvestCraft
- Immersive Engineering
- Natura
- Roots 2
- Druidry
- Better With mods

**Comment by RlonRyan** [comment]
Fixed for all seeds that are registered with AgriCraft.

**Comment by winnetrie83** [comment]
you also need to fix this for the crops, as they can still be planted while vanilla planting is disabled
