### ISSUE TITLE
JSON Crops not loading in/More Debug Logs Required

### ISSUE THREAD

**Issue by Haerar** [AgriCraft/AgriCraft#832]
As far as I can tell (duplicating the JSON for the vanilla wheat crop and tweaking it) latest build for 1.10.2 is not loading in custom plants correctly... however there's no feedback from the mod to confirm this!

I've gotten the folder to load in based on an installed mod (primordial crops) and logs show it loading (see relevant paste: http://pastebin.com/nN5JRG8p - line 3) however with the following JSON entry (http://pastebin.com/jX1YX5bq) the seeds in question do not become "agri-craft-ised" so to speak. What would be very helpful is some feedback from the mod if it tries to read the JSON file and encounters any particular error causing it to fail to load that plant; as I can't see what (if anything) is different about the JSON I've written versus the HarvestCraft or Vanilla JSON files present in the mod by default.

**Comment by Haerar** [comment]
Version in question is agricraft-2.0.0-0.6.0-a10.jar

**Comment by Haerar** [comment]
Looking through source code I've identified the issue with my particular plant; no "_plant" in the file name. It would be worth therefore logging to console any JSON files in the JSON directories that do not have this identification, "_soil" or "_mutation"; to help modders/modpack creators identify this mistake.

**Comment by RlonRyan** [comment]
Agreed. That requirement should be better documented than it is.

**Comment by RlonRyan** [comment]
I've added notes to the wiki, and a warning in the log files for json files that are misnamed. Hopefully, this will be enough to mitigate the issue.
