### ISSUE TITLE
Pam's seeds on crops turning into cotton

### ISSUE THREAD

**Issue by EPSIL0N** [AgriCraft/AgriCraft#839]
agricraft-0.6.0-a10
infinitylib-0.6.1
pams harvestcraft 1.9.4-1.10.2H

playing on a server and I planted 15 different seeds and I believe about 13 either immediately or after logging out and back in turned into cotton and give cotton.

**Comment by RlonRyan** [comment]
I have no idea what would be doing this. Need to investigate further.

**Comment by RlonRyan** [comment]
This may have been fixed in a11. Please confirm.

**Comment by BarsikTheCaT** [comment]
Well, I'm not the one who opened this issue, but I did not  encounter this issue yesterday playing latest version FTB Beyond.

**Comment by RlonRyan** [comment]
Assumed to be fixed in a11 due to lack of reply in almost a month.
