### ISSUE TITLE
Crop Rendering Bug

### ISSUE THREAD

**Issue by murat0706** [AgriCraft/AgriCraft#843]
![screenshot_1](https://cloud.githubusercontent.com/assets/21083203/23091902/e1891a56-f5c8-11e6-80fc-0ce126e9bdaa.png)

I don't know maybe this bug

**Comment by Ravin890** [comment]
i forget exact thing, but do you maybe have something like multi-core rendering to stabilize fps on?

**Comment by RlonRyan** [comment]
Yeah it has something to do with the rendering code. Not my specialty though...

**Comment by RlonRyan** [comment]
I think this has been fixed in 2.0.0a12... will need confirmation.

**Comment by RlonRyan** [comment]
I believe this issue to be fixed, if not before a14 then certainly by a14. If not please notify to reopen issue.
