### ISSUE TITLE
[Request] Hardcore Options

### ISSUE THREAD

**Issue by bookerthegeek** [AgriCraft/AgriCraft#852]
Hello! How are you today?

I would love some of the following options to be able to be enabled in the configs;
* Percentage chance for parent crops to a) die or b) turn into weeds when cross breeding.
* Percentage chance (per tier of crop) for crops to die when harvested by machines.
* Percentage chance for crops to drop in stats if harvested to often.
  * Configurable. For example will drop `1-10` stat levels in `1-3` stats if harvested more than once every `n` seconds.
* Biome Specific requirements for crop mutations
  * Cactus should only mutate in deserts, sugarcane in swamps
* Biome requirement for crops. (Stats cut in half if grown in incorrect Biome, so 10/10/10 crops produce as 5/5/5 crops)
* Ability to set the block beneath the crop to be two blocks below instead of one below the soil.
  * Plant / Soil / Random Block / Required Block
  * This is for forestry farm compatibility with resource or custom crops
  * Could also have a block that registers itself to Forestry as an allowable block for Multi-Farms, but would allow the essence of the block below it to pass through to the soil above.
* Config setting to ignore an increase in grow ticks. i.e bone meal, watering can, ritual of the green grove.

Thank you for the wonderful mod and taking the time to consider my request.

**Comment by TokkenGmr** [comment]
I really like the idea of this

Really like this
*Biome Specific requirements for crop mutations
*Biome requirement for crops. (Stats cut in half if grown in incorrect Biome, so 10/10/10 crops produce as   5/5/5 crops)

This one has me thinking. Did you want to require 2 blocks?
*Ability to set the block beneath the crop to be two blocks below instead of one below the soil.

**Comment by bookerthegeek** [comment]
@TokkenGmr It would look like Plant / Soil / Random Block / Required Block

The reason for this is that I love forestry, and would love to set a plant, say a custom crop for salt, in a forestry farm but also require it to have a salt block to grow. With the current implementation, this is not possible.

**Comment by RlonRyan** [comment]
Good idea. Probably a long way off since focused on getting as stable core version of 2.0.0 out first.

**Comment by InfinityRaider** [comment]
There are some interesting ideas in here.
Most will probably not be implemented though, however with the 1.16 events this could easily be made into an addon.
