### ISSUE TITLE
Ghost Plants

### ISSUE THREAD

**Issue by RlonRyan** [AgriCraft/AgriCraft#863]
There appears to be a plant ghosting issue in AgriCraft where 'ghost' plants appear on the client as a result of a desynchronization with the server.

This issue encompasses issues #802 and #849.

**Comment by RlonRyan** [comment]
May be fixed in 2.0.0a12

**Comment by micbusin** [comment]
Remove the "ghost plant" with Gardening Trowel (rightclick). The new plant will be able to grow.
