### ISSUE TITLE
Implement The One Probe Integration

### ISSUE THREAD

**Issue by Senophoe** [AgriCraft/AgriCraft#868]
I've been playing FTB Beyond for the last days and on this modpack WAILA has been substituted by The One Probe (TOP). The problem is I can't seem to find the information about crops on the TOP information window. And that trully makes AgriCraft hard to use, since you have to break crops to know what they are and their stats.

Could you implement integration with TOP to work just like it used to with WAILA?
Here's a screenshot of the informations WAILA used to give us: https://i.imgur.com/FiT1TmQ.png

**Comment by mcdodge34** [comment]
Want this too please... There's a guy that did a TOP addons that could perhaps do it also, its in FTB Beyond also...

**Comment by JaSpr** [comment]
I was looking for this, as well.

**Comment by Ravin890** [comment]
So the magnifying glass doesn't work? (Yes its slower but would help for now either way)

**Comment by mallrat208** [comment]
TOP Addon's has support for AgriCraft as of version 1.10.2 - 0.10.0

**Comment by RlonRyan** [comment]
Implemented in upcoming alpha a17.
