### ISSUE TITLE
Enhancement: Water Pads in 1.10.2

### ISSUE THREAD

**Issue by Guinaro** [AgriCraft/AgriCraft#873]
Will waterpads for things like rice, seaweed, cranberries, .... make a reappearance in the 1.10.2 version?

Makes it more realistic to actual farming.

Sinceerly,
Guinaro

**Comment by RlonRyan** [comment]
Interestingly enough, cranberries aren't actually grown in flooded fields. The flooding of the cranberry fields is for harvesting, in that the berries can be knocked off the plant and allowed to float to the surface of the water for easy collection.

Similarly, rice does not require a flooded plain as to grow, rather rice strains have the capacity to grow well in flooded areas, unlike many weeds. Thus the flooding is used for weed control purposes.

Still, I do hope as to have waterpads come back in future release.

**Comment by Lethann** [comment]
Are waterpads not in? I see them in JEI but whenever I use the shovel on farmland it just digs it up rather than make the pad.

**Comment by RlonRyan** [comment]
Waterpads have now been reimplemented in the 1.10.2 branch, and will be available in the next release!
