### ISSUE TITLE
Could not create Vfs.Dir from url

### ISSUE THREAD

**Issue by KasperFranz** [AgriCraft/AgriCraft#876]
This is the startup log message: https://gist.github.com/KasperFranz/d7aee68b43390729b589f07a255923dc

Running the latest beyond modpack (version 1.1.0) on Java 1.8.0_121

**Comment by RlonRyan** [comment]
I've never seen this before, and if it's not a crash I doubt that I'd do anything about it.

**Comment by RlonRyan** [comment]
You know what... this might be a compat issue with one of the mods in ftb beyond...

**Comment by Eufranio** [comment]
My modpack (which is not Beyond): https://www.technicpack.net/modpack/magibeta-pack.940049

**Comment by bookerthegeek** [comment]
Could it be [this][update] here not being a valid url?

[update]:https://github.com/AgriCraft/AgriCraft/blob/master/mod.properties#L30

**Comment by RlonRyan** [comment]
No. The issue is with reflection, totally unrelated to that link.

**Comment by KasperFranz** [comment]
Why did it get closed?
