### ISSUE TITLE
Bonemealing plants

### ISSUE THREAD

**Issue by DrDarkfire** [AgriCraft/AgriCraft#877]
Plants in crop sticks are not affected by bonemealing effects like bone meal, fertilizer(forestry), and watering cans from Extra Utils.

Wondering if this is intentional ore a bug

MC Version: 1.10.2
Mod version: 2.0.0-0.7.0-a12

**Comment by VT-14** [comment]
It's worth pointing out that the Extra Utils Watering Can forces extra growth ticks.  It does not apply a bonemeal effect.  This allows it to work on things like Sugarcane, Grass Spreading, etc.

**Comment by Lethann** [comment]
The watering can from Extra Utils seems to work, however growth in sticks is INSANELY slow so it doesn't feel like it.  I've spent the last three days doing nothing but crops so I can tell.

It would also be nice if it would accept the fertilizer from Actually Additions and have their crops be accepted into sticks.

**Comment by SWfan85** [comment]
I have gotten the watering can to work at expected rates, but i had to target the 2 "pixel" wide strip of block just outside of the crop sticks, and had to be standing within 1 block of the block I was targeting. Hope that helps.

**Comment by Tsukiumy** [comment]
> It would also be nice if it would accept the fertilizer from Actually Additions and have their crops be >accepted into sticks.
you just need to make your own JSON file, i made a excel file to create my jsons with just some info, and if you are not on a server you can change the bonemeal config for the crops editing json of that crop

**Comment by Lethann** [comment]
I don't know how to do JSON files and am playing on a server so.. yea.. not really an option for me. Probably works for others though. If it doesn't support it then that's fine. Was just a suggestion since I knew that Pam's stuff was already included and the AA mod is quickly rising in popularity.

**Comment by RlonRyan** [comment]
I think this should be fixed by a14, given that the growth rates were fixed and the fertilizer items described work by forcing growth ticks.
