### ISSUE TITLE
Textures missing [FTB Beyond 1.10]

### ISSUE THREAD

**Issue by swefreedict** [AgriCraft/AgriCraft#878]
I enabled the resource plants in the config and they grow just fine but the textures are missing. 

All I see is the purple/black boxes.

**Comment by swefreedict** [comment]
I tried with a texture pack (Sphax) which solved the plants not showing but that made the seed  analyser invisible among other glitches with textures.

**Comment by swefreedict** [comment]
Not sure how or why it worked but I solved it by unpacking the agricraft-2.0.0-0.6.0-a11.jar, taking the textures out and making a resourcepack with them. The seed analyzer is still wonky (still visible) but at least I see the plants and seeds now.

**Comment by zunix** [comment]
running into the same issue with FTB Beyond. But even with the resourcepack it wont work as a hot fix. @swefreedict you mind sharing the resourcepack?

**Comment by swefreedict** [comment]
Sure, if InfinityRaider doesn't want it to be shared I'll delete it though.

https://www.dropbox.com/s/4v9mzswdtt4sf55/Free-agricraft.zip?dl=0

**Comment by InfinityRaider** [comment]
I dont mind it at all.

**Comment by zunix** [comment]
thanks for the resourcepack :)

**Comment by Tsyklop** [comment]
Same bug. FTB Beyond 1.10. agricraft-2.0.0-0.8.0-a14
Resourcepack - F32 1.10.2

![2017-03-28_19 10 19](https://cloud.githubusercontent.com/assets/6783568/24415634/c9622946-13ea-11e7-8601-d9787aeaa7d6.png)

**Comment by swefreedict** [comment]
Try with the texturepack I linked above. Does that help? You can use is in combination with F32.

**Comment by Tsyklop** [comment]
@swefreedict Thanks. working.

**Comment by swefreedict** [comment]
Hmm.. I just updated my server to Beyond 1.2.1 and all the textures disappeared again even with the texturepack. *sigh*

**Comment by Lgk2** [comment]
@swefreedict 
"I enabled the resource plants in the config"

I'm curious, how did you enable the plants in the config?

**Comment by swefreedict** [comment]
Just change the 
"enabled": false,
to
"enabled:" true,

You have to do this on every indiviual plant though.
![plant](https://cloud.githubusercontent.com/assets/26554702/24600540/6ce3c35e-1855-11e7-8f4b-6d7c1ef174cd.jpg)

**Comment by RlonRyan** [comment]
This might have been fixed in the upcoming a17 release, will need confirmation however.

**Comment by CodesCubesAndCrashes** [comment]
I haven't seen these textures missing like this in a while. Plus there were those major rewrites that touched the rendering logic. So I'm going to go ahead and close this.
