### ISSUE TITLE
[Suggestion] Change base.json

### ISSUE THREAD

**Issue by Mrbysco** [AgriCraft/AgriCraft#892]
Currently it parents "builtin/generated"
which makes items huge in world:
![2017-03-29_20 45 09](https://cloud.githubusercontent.com/assets/9308260/24470872/aa36d414-14c0-11e7-8d98-8fb8ee3045be.png)

Changing it to "item/generated" will fix this:
![2017-03-29_20 45 21](https://cloud.githubusercontent.com/assets/9308260/24470911/c6f230e4-14c0-11e7-83da-ee7e6c063d66.png)
The above was me changing it in a resource pack to test it.

The change from builtin/generated to item/generated was in 1.9 I believe.

-Mrbysco

**Comment by RlonRyan** [comment]
Thanks for the fix

**Comment by Mrbysco** [comment]
No problem :)
I had my gf tell me the items appeared huge when dropped so I went looking and I immediately guessed right :)
