### ISSUE TITLE
Nearby blocks requirement example

### ISSUE THREAD

**Issue by Smartaros** [AgriCraft/AgriCraft#894]
When adding blocks to the requirements section "nearby" the whole script stops working.
`"requirement": 
  {
    "min_light": 10,
    "max_light": 16,
    "soils": 
	[
      "gravel_soil"
    ],
    "bases": 
	[
      "thermalfoundation:storage_alloy"
    ],
    "nearby": 
	{
	  "minecraft:iron_ore",
	  "minecraft:coal_ore"
	}`
Is there any example that describes how to correctly add blocks to this "nearby" section?

**Comment by RlonRyan** [comment]
Nearby should take the format of the following:

````
"nearby": {
    "minecraft:iron_ore": <radius>,
    "minecraft:coal_ore": 10
}
````
