### ISSUE TITLE
Information request

### ISSUE THREAD

**Issue by bookerthegeek** [AgriCraft/AgriCraft#895]
# Hello!
I am trying to add more soils (Stage one in making life harder for my players). Now, I opened up the soils and used them as a base default for some new soil configs. Except some work and other do not.

## My json files
This one works
```
{
  "path": "vanilla/soils/enchanted_soil.json",
  "enabled": true,
  "id": "enchanted_soil",
  "name": "Enchanted Soil",
  "varients": [
    {
      "item": "botania:enchantedSoil",
      "meta": 0,
      "tags": "",
      "ignoreMeta": true,
      "ignoreTags": [
        "*"
      ],
      "useOreDict": true
    }
  ]
}
```
But this one does not
```
{
  "path": "vanilla/soils/nether_wart_block.json",
  "enabled": true,
  "id": "nether_wart_block",
  "name": "Nether Wart Block",
  "varients": [
    {
      "item": "minecraft:nether_wart_block",
      "meta": 0,
      "tags": "",
      "ignoreMeta": true,
      "ignoreTags": [
        "*"
      ],
      "useOreDict": true
    }
  ]
}
```
#
Any help would be... helpful.

**Comment by RlonRyan** [comment]
Your provided file looks like it should work fine... What does the log have to say about the soil?

**Comment by bookerthegeek** [comment]
As I recall nothing. Let me go run it again and double check.

**Comment by bookerthegeek** [comment]
With just that one extra JSON I get in the log:
```
[AgriCraft]: Attempting to read AgriCraft JSONs!
[AgriCore]: [AGRI-DEBUG]: Loading: "json:mod_Botania" for mod: "Botania"!
[AgriCore]: [AGRI-DEBUG]: Loading: "json:mod_harvestcraft" for mod: "harvestcraft"!
[AgriCore]: [AGRI-DEBUG]: Loading: "json:resource"!
[AgriCore]: [AGRI-DEBUG]: Loading: "json:vanilla"!
[AgriCraft]: Finished trying to read AgriCraft JSONs!
[AgriCraft]: Registering Soils!
[AgriCraft]: Registered Soils (8/8):
[AgriCraft]:  - Stone
[AgriCraft]:  - Mycelium
[AgriCraft]:  - Gravel
[AgriCraft]:  - Sand
[AgriCraft]:  - Farmland
[AgriCraft]:  - Grass
[AgriCraft]:  - podzol
[AgriCraft]:  - Soul Sand
[AgriCraft]: Registering Plants!
```
I removed the rest of the log as it is massive but if needed I can post it for you. This happens with just the

**Comment by bookerthegeek** [comment]
[Entire Log][1] with default everything except the added Nether Wart Block. The section I think you want is [here][2]? After turning on Debug mode in your config I got the log [here][3] and Agricraft starts in the log about [here][4].

The file is named ``` nether_wart_block.json ```, the path is in the vanilla soils folder. 

Hope this helps. 

[1]:https://gist.github.com/bookerthegeek/13cdd66640e217f6ef537631a7c09e23
[2]:https://gist.github.com/bookerthegeek/13cdd66640e217f6ef537631a7c09e23#file-log-L620
[3]:https://gist.github.com/bookerthegeek/e4873f7344c74c08bd49100ca895c627
[4]:https://gist.github.com/bookerthegeek/e4873f7344c74c08bd49100ca895c627#file-log-L620

**Comment by RlonRyan** [comment]
This is really odd... Oh wait... The file has to end in _soil.json... Otherwise AgriCraft completely ignores it.

**Comment by RlonRyan** [comment]
I probably should make a log message warning that some json files were skipped...

**Comment by bookerthegeek** [comment]
Damnit... That was stupid I should have caught that. Thanks for the help. Looking forward to what comes next.
