### ISSUE TITLE
Disabling Plants

### ISSUE THREAD

**Issue by Lgk2** [AgriCraft/AgriCraft#897]
In 1.7.10 there used to be a config setting to disable crops. Nowadays I'm not quite sure how to disable them, when i delete the resource directory it simply reappears on next launch and i can't find the disable setting in the config. I tried deleting the files within the resource folder but I ended up with the same result. 

Am I missing something or is this just a feature that will be added in the future but you haven't been able to get to it yet.

**Comment by Lgk2** [comment]
Oh I found what I was missing. If you want to disable aurigold or any other crop. 

Then go to config/agricraft/config.cfg and set "Enable JSON Writeback" to false.
After that you simply delete the aurigold_mutations.json in config/agricraft/json/defaults/resource/mutations and 
aurigold_plant.json in config/agricraft/json/defaults/resource/plants.

**Comment by RlonRyan** [comment]
Go into the JSON files and set enabled to false.

**Comment by Lgk2** [comment]
What is it called? I can't find it in the config on 1.10.2 server and client even when i delete it and let it recreate a new clean config.

**Comment by RlonRyan** [comment]
Go to the JSON files at config/agricraft/json/default

**Comment by Lgk2** [comment]
I tried to do that but the config reappears even when i change "B:"Enable JSON Writeback"=false" to false but I might have misinterpreted what that change does.

**Comment by Lgk2** [comment]
Ah thank you!
