### ISSUE TITLE
Crash on disabling mutations

### ISSUE THREAD

**Issue by TimPietsch** [AgriCraft/AgriCraft#898]
Just to make sure the error was reproducible I did the following:

I installed Agricraft (agricraft-2.0.0-0.8.0-a14) on a fresh 1.10.2 profile (forge-12.18.3.2254) using the curse launcher. I changed a single line in the agricraft config.cfg:
S:"Mutation Chance"=0.0

On hitting play the game crashes. Is there a different way to prevent crossovers from happening? Also, let me know if you need an actual crash report. Thanks in advance!

EDIT: I found a way to customize mutations and disable the plants I didn't want but still, I think the crash needs further inspection.

**Comment by RlonRyan** [comment]
Agreed, the crash is worth investigating. Thanks for reporting!

**Comment by RlonRyan** [comment]
Fascinating. I cannot duplicate the issue on my end. A crash log would be greatly appreciated (pastebin, hastebin, or gist please).

Thank you for providing such a detailed error report.

**Comment by RlonRyan** [comment]
I see what is happening. It is an issue with an error that I threw but never caught.

**Comment by TimPietsch** [comment]
Sorry I couldn't get to you earlier with a crash report. I guess it's not needed anymore then?

Anyway, glad I could contribute and thanks for the hard work!
