### ISSUE TITLE
Plants dropping multiple crops

### ISSUE THREAD

**Issue by kagenekosama** [AgriCraft/AgriCraft#899]
Hello so vive been playing  with the 1.10 versions and when i destroy a plant (pineapple for example) I get the pinneaple and multiple crops and drops, i have my config file with all the seed drops set to false, any clue why this happens?

**Comment by RlonRyan** [comment]
I assume that you mean that multiple crop sticks drop from a crop when destroyed. I will investigate this.

**Comment by RlonRyan** [comment]
I can not reproduce this issue. I am not sure as to what you mean by multiple drops.

Will reopen if you can elaborate.
