### ISSUE TITLE
Recopies missing

### ISSUE THREAD

**Issue by CamaroKing59** [AgriCraft/AgriCraft#900]
there are no seed recopies in JEI 

Agricraft Version :2.0.0-0.8.0-a14

**Comment by RlonRyan** [comment]
Do you mean recipes?

**Comment by CamaroKing59** [comment]
yes

**Comment by RlonRyan** [comment]
Interesting... Does this mean that there are no AgriCraft seeds?

**Comment by RlonRyan** [comment]
Well I just updated the JEI compat, so this likely won't be an issue in future releases.
