### ISSUE TITLE
Invalid Below Block

### ISSUE THREAD

**Issue by Bax12** [AgriCraft/AgriCraft#902]
All Plants cant be planted on their soil no matter of the block below e.g. Burning Seeds without Glowstone.
They also grow and can be harvested no effect of the block below.

**Comment by RlonRyan** [comment]
Is the base block showing up in JEI?

**Comment by TokkenGmr** [comment]
This is pretty much the same issue as #887. Yes the base does show in JEI, and no errors in log

**Comment by RlonRyan** [comment]
How odd... I guess I have to take a closer look at the requirements section...

**Comment by RlonRyan** [comment]
The issue is that for some reason the code controlling the base block check was commented out...
