### ISSUE TITLE
Can't place seeds

### ISSUE THREAD

**Issue by Gkoliver** [AgriCraft/AgriCraft#904]
The only seeds I can place are weeds. Clicking it just doesn't work. Version is agricraft-2.0.0-0.8.0-a14.

EDIT: Added a14 to the version

EDIT2: Shift + Clicking on the crop sticks with AgriCraft seeds completely voids the seeds.

**Comment by Vaygrim** [comment]
Are you planting seeds on Cropsticks? I ask because planting Agricraft seeds on cropsticks is working fine for my pack.

**Comment by RlonRyan** [comment]
You are six versions out-of-date. Updating will almost certainly fix the issue.

**Comment by starg09** [comment]
Just as a note, report author added the version. He seems to be on the latest build right now :)

**Comment by Protheus** [comment]
Where can you find the newer versions then as CF only has agricraft-2.0.0-0.8.0-a14 ?

http://tehnut.info/jenkins/job/Agricraft/job/1.10.2/ doesn't contain the files.

**Comment by RlonRyan** [comment]
The original issue was for version 2.0.0a8.

**Comment by RlonRyan** [comment]
I still haven't run across this issue on my own yet... perhaps it is related to #929?
