### ISSUE TITLE
[1.10.2] Crash on startup

### ISSUE THREAD

**Issue by UnPure** [AgriCraft/AgriCraft#905]
Crashlog: https://pastebin.com/8n7fhjsf

If you need any other informations, let me know.

**Comment by UnPure** [comment]
Ok, after digging around, it seems like this problem could be related to https://github.com/AgriCraft/AgriCraft/issues/898

Changing 
```
S:"Mutation Chance"=0.2
```

to

```
S:"Mutation Chance"=1.0
```

its producing the crash thats the problem.
I havent tested any other values but if the value is on 0.2 everything is working fine.

**Comment by RlonRyan** [comment]
This was due to an edge case on the value 1.0, which the config allows, but the mutation engine would not accept. This has been fixed now for the latest alpha.
