### ISSUE TITLE
Water Tanks do not support Weather, Storms & Tornadoes Mod systems.

### ISSUE THREAD

**Issue by Axiom1999** [AgriCraft/AgriCraft#907]
For now, I've had to set the mod to "Global Overcast" and to use the vanilla weather system (in turn abiding by the `toggledownfall` rule).

Would be nice if you could support this mod.

**Comment by RlonRyan** [comment]
AgriCraft uses the vanilla checks to test if it is raining, so it should pick up any mod that sets the downfall to true. Also, the irrigation system in 1.10.2 is still WIP, so there might be other changes to the system that affect this issue.
