### ISSUE TITLE
Harvestcraft Coffee plants drop wrong item.

### ISSUE THREAD

**Issue by Dahson** [AgriCraft/AgriCraft#908]
When using growing the coffee plant using crop sticks the coffee plants are dropping "_Cup of Coffee_" (item id: harvestcraft:coffeeItem) instead of "_Coffee Beans_" (item id: harvestcraft:coffee**bean**Item)

I am using the FoolCraft v1.2.2 modpack for Minecraft 1.10.2 which has these versions of the mods
agricraft-2.0.0-0.7.0-a12
Pam's HarvestCraft 1.9.4-1.10.2h
It looks like the problem is in coffee.plant.json file where under products the item is listed as harvestcraft:coffeeItem. I have looked at the json of the current version (agricraft-2.0.0-0.8.0-a14) and it looks to have the same issue, however I have not tested it.

**Comment by darthvader45** [comment]
I think you can simply edit the json file to make it drop the correct item.  Unless it somehow overwrites it every time you start MC.

**Comment by Dahson** [comment]
I realize that you could probably do this but if you play on a server it's rather annoying to have everyone edit the file as most people wouldn't know how to do this.

**Comment by RlonRyan** [comment]
If the server updates the JSON files, the changes will be pushed to all the players with no work on their part needed.

The default JSON for harvestcraft coffee plants will be patched in the next alpha.

**Comment by RlonRyan** [comment]
Fixed for release in next alpha.
