### ISSUE TITLE
Missing Textures on blocks

### ISSUE THREAD

**Issue by darthvader45** [AgriCraft/AgriCraft#909]
I've had a problem where it seems the channels/sprinklers/tanks/etc. have no textures at all.  They appear like they have the texture.png image all over them(i.e. the white field with all the vanilla items/etc. on it).  Please fix whenever you have the time.  Thank you.

**Comment by liketechnik** [comment]
Do you use OptiFine too? I had this issue when I used optifine in combination with agricraft. removing optifine solved this problem for me.

**Comment by darthvader45** [comment]
Hmm, may be an incompatibility with Optifine.

**Comment by RlonRyan** [comment]
Unfortunately we have no plans to support Optifine, given that it messes too much with the rendering system for us to learn and support essentially two rendering systems.

**Comment by darthvader45** [comment]
It happens even without Optifine sometimes.

**Comment by darthvader45** [comment]
Also, you supported Optifine before.  It is still being worked on, and is not a new rendering system in and of itself.
