### ISSUE TITLE
Breaking Blocks

### ISSUE THREAD

**Issue by PandaPaw** [AgriCraft/AgriCraft#910]
The game crashes some times when i break blocks from your mod. I am playing your mod in FTB Beyond.

[Crash Report](https://hastebin.com/kideronuha.rb)

**Comment by RlonRyan** [comment]
Please use Gist, pastebin, or hastebin when posting logs next time.

There was a slight change to the code related to this in a15, and as such we need verification that this issue still occurs in the latest alpha.

Thanks for the bug report.

**Comment by RlonRyan** [comment]
This should be fixed, given that in the current code it is logically impossible.
