### ISSUE TITLE
Water tanks not connecting to Mekanism pipes

### ISSUE THREAD

**Issue by Swadian** [AgriCraft/AgriCraft#911]
![image](https://cloud.githubusercontent.com/assets/15859509/25071761/31fb51a8-22c8-11e7-86c9-e40163729ab2.png)

Using  
Minecraft 1.10.2
Forge 12.18.3.2272
Mekanism 9.2.2.301 
Agricraft 2.0.0-0.8.0-a14

**Comment by RlonRyan** [comment]
The AgriCraft irrigation system is still WIP. Also, allowing connections to other piping systems would bring about questions about balance...

If piping system compat was implemented it would be a long way off from now.

**Comment by VT-14** [comment]
I'm curious what potential "questions about balance" you see coming up.

**Comment by RedGuy54** [comment]
That is crazy, you should at least make it a config option.

**Comment by orblazer** [comment]
Hello, you have news for that integration ?
