### ISSUE TITLE
Water tank can not recieve water from Immersive Engineering fluid pipes

### ISSUE THREAD

**Issue by FlyveHest** [AgriCraft/AgriCraft#914]
I tried building my first watertank this evening, and found out that Fluid Pipes from Immersive Engineering can not pump water into a tank.

I setup a portable tank from Thermal Expansion, and then an ender pipe from that to the tank, and that works, but is not very pretty.

I am not sure if the problem is in Immersive Engineering or Agricraft, it might very well not be Agri, and then this issue can just be closed.

**Comment by RlonRyan** [comment]
This is a complicated issue. For now I am filing it under the same as #911.
