### ISSUE TITLE
Creeper Explosion leads to server crash (on getFruits)

### ISSUE THREAD

**Issue by charkko** [AgriCraft/AgriCraft#915]
Just had a creeper blow up on my farm, followed by the server crashing.  Anytime I log in, the server immediately crashes again.

Log points at a NPE that leads down to agricraft on getFruitsOnHarvest()

Log: https://pastebin.com/ie8wk7ff

Edit: Not a minecraft modder, so not familiar with its modding codebase, but maybe because the consumer is a mob and not a player?

**Comment by RlonRyan** [comment]
This has been addressed in the latest alpha by preventive checking. The involved method shouldn't have been getting such values in the first place, so the check will create a log message in the event of such.

**Comment by charkko** [comment]
Great! I'll look forward to this in the next alpha release! Thanks
