### ISSUE TITLE
(BUG ?) Server console spam on user login

### ISSUE THREAD

**Issue by Vaygrim** [AgriCraft/AgriCraft#918]
Every time a user logs into my server (running AgriCraft 2.0.0-0.8.0-a15) a wall of text spams the server console, usually about 5 full screens in length. These messages always detail the syncing of EVERY... SINGLE.. JSON... to the user who is logging in. All files are listed in excruciating detail, with some entries taking up 4 to 6 lines per plant type.

Can we PLEASE get this streamlined down to one or two 'summary lines' instead of 5 full screens worth of detail? Even if this is behind a config file option, I desperately need it as any server console watching I am doing relating to troubleshooting OTHER issues.. gets obliterated by 1 user logging in. Forces me to back to go to the log files via FTP just to catch up.

Also yes, I've got all your 'debug channel' entries in the config disabled.

**Comment by RlonRyan** [comment]
I've checked the config option again, and it seems to be working. I've modified some of the code pertaining to the issue that should ensure it doesn't show up if it isn't wanted.

Verbose logs are better than terse logs.

**Comment by Vaygrim** [comment]
I appreciate you at least looking into it. I do understand that verbose logs are better, but you are generating an absurd level of verbosity in data every time a user logs in.. at the expense of being able to troubleshoot issues from other mods easily.
