### ISSUE TITLE
[1.7.10] can't run minecraft client in development environment

### ISSUE THREAD

**Issue by liketechnik** [AgriCraft/AgriCraft#919]
I am unable to run the gradle task `runClient` in the 1.7.10 branch. The task runs and minecraft starts its initialization progess but then a window opens which title states: 

> Select an mcp conf dir for the deobfuscator

It is by default in the eclipse directory of the branch. When I select this directory I get an error and the same window opens again. After the third time of selecting the eclipse directory the task terminates. Here's the log of the task.
[task_output.txt](https://github.com/AgriCraft/AgriCraft/files/955035/task_output.txt)

Before running this task I successfully created the development environment by running `setupDecompWorkspace`.

So how can I get this to work?

**Comment by liketechnik** [comment]
Fixed it by pointing it to a directory named `$USER_HOME/.gradle/caches/minecraft/net/minecraftforge/forge/1.7.10-10.13.4.1566-1.7.10/unpacked/conf/` where the needed files are present.

**Comment by RlonRyan** [comment]
This is actually an issue with ForgeGradle, and not our fault. So since you managed to resolve it, I'm closing the issue.

**Comment by TehNut** [comment]
Actually that's CodeChickenCore looking for mappings for it's runtime deobfuscation.

**Comment by RlonRyan** [comment]
Well all I know is it ain't my problem.
