### ISSUE TITLE
[1.10.2] Crops above tier 2 not able to be bonemealed

### ISSUE THREAD

**Issue by Thedrummonger** [AgriCraft/AgriCraft#921]
Any crop above tier 2 can not be bonemealed even when the bonemeal option is set to true. I feel like this is unintended behavior as It would make the bonemeal option pointless in some cases.

Example of a custom crop that can not be bonemealed
https://pastebin.com/1YK9Rq75

Example of a custom crop that can be bonemealed
https://pastebin.com/bcGJxs9F

Agricraft Version 2.0.0-0.8.0-a15

**Comment by RlonRyan** [comment]
There is a certain trade-off to be considered here, but I suppose options in the JSON files should probably be the master ones...

**Comment by RlonRyan** [comment]
This condition has been removed in the upcoming alpha.
