### ISSUE TITLE
[1.10.2] [Bug] game freeze with seed analyzer

### ISSUE THREAD

**Issue by Veggetossj** [AgriCraft/AgriCraft#922]
I did this twice with 2 types of seeds (Sugarcane and Cacti):

Opened the Seed Analyzer and Shift+RMB the unindentified seeds into the Analyzer and then while its still scanning the seeds, Shift+RMB them out again. Result: my game froze.

**Comment by liketechnik** [comment]
Could you please add the exact version you use and a log of the game where the game froze?

**Comment by Veggetossj** [comment]
Version 2.0.0-0.8.0-a15 and it didnt create a log for me when it froze.

**Comment by RlonRyan** [comment]
Lol...
````
[11:13:23] [Client thread/INFO] [agri-gui]: [AGRI-DEBUG]: Width: 44 Height: 8 Progress: 2,147,483,647 Adj. Width: 944,892,804
````
There's your error!

**Comment by RlonRyan** [comment]
Apparently rendering a box with width just under a trillion units takes a very, very long time...

**Comment by RlonRyan** [comment]
Fixed in upcoming alpha.
