### ISSUE TITLE
[1.10.2] [Bug] Game crash when water destroys weed

### ISSUE THREAD

**Issue by JMW1906** [AgriCraft/AgriCraft#923]
The game crashes when a fully grown weed plant is destroyed using flowing water.
We tested this in a singleplayer and in a multiplayer world and on both worlds we got the same crash report (Only with different Coordinates).
Destroying the fully grown weed Plant by Hand did not crash the game.
Destroying a not fully grown weed Plant with water did also not crash the game.
I have added 2 Crash Reports below (one from the Server and one when we crashed the game in a singleplayer world).

**SinglePlayer:** (in multiplayer it is the same)
`-- Block being ticked --
Details:
	Block: minecraft:flowing_water[level=0]
	Block location: World: (-140,68,228)`
(-140,68,228) is the location where the water source block is placed.

**Other Information that might be relevant:**
Minecraft Version: 1.10.2
Modpack: FTB Beyond 1.5.3
Map: Singleplayer: A new world
Agricraft Version: "2.0.0-0.8.0-a14"

**Steps to Reproduce the Error:**
1) Start FTB Beyond 1.5.3.
2) Create a new world.
3) Create farmland, place a crop stick on it and plant a weed seed.
4) Fully grow the weed plant using bonemeal (or wait).
5) Place a waterbucket near the plant so that it is getting destroyed by the flowing water.

[Crash Report Multiplayer.txt](https://github.com/AgriCraft/AgriCraft/files/962910/Crash.Report.Multiplayer.txt)

[Crash Report SinglePlayer.txt](https://github.com/AgriCraft/AgriCraft/files/962909/Crash.Report.SinglePlayer.txt)

**Comment by RlonRyan** [comment]
This may have already been addressed in-dev. I will have to check.

**Comment by RlonRyan** [comment]
This has been fixed already in an upcoming alpha release.
