### ISSUE TITLE
Request: Re-adding flower seeds

### ISSUE THREAD

**Issue by Gkoliver** [AgriCraft/AgriCraft#924]

**Comment by TokkenGmr** [comment]
I assume you are asking about vanilla flowers. I submited json to the [AgriPlants Repo](https://github.com/AgriCraft/AgriPlants/issues/9)

**Comment by Gkoliver** [comment]
Okay.  Thanks!

**Comment by RlonRyan** [comment]
The flowers have been added to the default AgriCraft JSON files thanks to @TokkenGmr.
