### ISSUE TITLE
Ticking World crash

### ISSUE THREAD

**Issue by KappaKiddie** [AgriCraft/AgriCraft#925]
https://pastebin.com/aq36AXLv

**Comment by RlonRyan** [comment]
This should already be fixed in the upcoming alpha.

**Comment by KappaKiddie** [comment]
But what is causing this? My server is crashing every 5 minutes

**Comment by RlonRyan** [comment]
Well, it shouldn't be happening, so I have no idea what is causing it. All I know is that the upcoming alpha has additional checks as to prevent such.

**Comment by KappaKiddie** [comment]
Would it be today or tomorrow?

**Comment by RlonRyan** [comment]
I'm not sure when the next alpha will be released, as it contains multiple changes that I want more time to test out fully.
