### ISSUE TITLE
[1.10.2] Use other mod´s plants for mutation (parents)

### ISSUE THREAD

**Issue by Cakestory** [AgriCraft/AgriCraft#927]
Hi,
I am adding some custom flowers to my modpack and have some problems regarding mutations.
Trying to create a plant from "Pam´s harvestcraft´s" onion_plant" and "garlic_plant", it seems that mutations using parents from other mods do not work. It is working fine for vanilla parent crops though.
Is there a way to use other mod´s plants as parents?

[white_tulip_mutation.txt](https://github.com/AgriCraft/AgriCraft/files/971135/white_tulip_mutation.txt)
[white_tulip_plant.txt](https://github.com/AgriCraft/AgriCraft/files/971136/white_tulip_plant.txt)

(I´ve renamed the files to .txt just for uploading them to github.)

**Comment by RlonRyan** [comment]
Are you certain that the Pam's Harvestcraft JSON files are enabled?

AgriCraft does not differentiate between the JSON files, to the point that the mod that is the source for the plant being emulated has no bearing on the workings of the JSON.

**Comment by Cakestory** [comment]
Yes, I am certain, that all Harvestcraft files are enabled and working (the mutations are shown in JEI).
I have tested several plant configurations as parents and only vanilla parents seem to be working.

**Comment by RlonRyan** [comment]
That's because all the harvestcraft plant id's are substandard. The actual id for the cucumber_plant is `cucumber_crop`. This will be fixed in the next release.
