### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by Tydesson** [AgriCraft/AgriCraft#928]
Crash log : https://pastebin.com/xiS0g1df

agricraft{2.0.0-0.8.0-a14} [AgriCraft] (agricraft-2.0.0-0.8.0-a14.jar)

Have seen a similar crash log already posted few days ago, but just in case.

**Comment by RlonRyan** [comment]
First time I've seen that. I'll have to take a look at it.

**Comment by Tydesson** [comment]
I'm asking on the server who did what, if i get more informations i'll tell you.

**Comment by Tydesson** [comment]
I managed to fix this by deleting the config/agricraft folder on the server. Server is up and running again.

**Comment by RlonRyan** [comment]
I've added a fix for this error, to be released in the next alpha.

Thanks for the report!
