### ISSUE TITLE
Seed can not grow wrong

### ISSUE THREAD

**Issue by Eufranio** [AgriCraft/AgriCraft#929]
I have a seed that is reporting that cannot grow, but is growing: 

![img](http://image.prntscr.com/image/a1004b2cd0f649adb8c78be350fba1b8.png)

There is a torch directly next to it. Using the Magnifying Glass will show that:

![img](http://image.prntscr.com/image/5abb6a7f26cf4d7087e06e604ed49fb1.png)

Looks like it's showing an incorrect light value...

**Comment by RlonRyan** [comment]
I have not run into this issue personally, and will need to investigate.

The important question is though, does the plant still grow?

**Comment by Eufranio** [comment]
Yes, it still growing.

**Comment by RlonRyan** [comment]
Interesting that it is still growing. Luckily, this gives me a comparison point that should make debugging the issue a whole lot easier.

**Comment by tyler489** [comment]
Is this on a mp server?

**Comment by Eufranio** [comment]
Yes

**Comment by tyler489** [comment]
Probably a sponge forge issue then. Little of little thinks like that are caused by spongeforge

**Comment by Eufranio** [comment]
This was tested in a pure forge server.
