### ISSUE TITLE
Crash Rendering Ingredient

### ISSUE THREAD

**Issue by Eufranio** [AgriCraft/AgriCraft#930]
A player got this crash viewing a recipe in JEI: https://hastebin.com/gogebavezi

**Comment by VT-14** [comment]
Rendering crashes should almost always be recreated without Optifine before reporting.  I'm not sure what Agricraft's policy is on it, but the vast majority of mods refuse to deal with Optifine.

**Comment by Eufranio** [comment]
I can't run the game without optifine and I just reported it because AgriCraft had a few rendering crashes a while back, I can get someone to test without Optifine if needed tho.

**Comment by Bazingu** [comment]
Change to NEI instead of JEI? Someone else had this problem and solved it by switching to NEI.

**Comment by Eufranio** [comment]
NEI is a JEI addon.

**Comment by RlonRyan** [comment]
I'm pretty sure that this was already fixed by the a16 release. I will need confirmation though.

**Comment by RlonRyan** [comment]
Well seeing that it's been a month since this issue has been updated I'm going to assume that a16 fixed it.
