### ISSUE TITLE
Random seeds in crop stick and console error

### ISSUE THREAD

**Issue by KappaKiddie** [AgriCraft/AgriCraft#931]
https://pastebin.com/0BSLLU6P 

Random seeds are spawning in this coord, idk why

**Comment by KappaKiddie** [comment]
All types of MysticalAgriculture seeds are randomly spawning in crop sticks, lul

**Comment by RlonRyan** [comment]
Oh... @tokengmr... you set the mystical agriculture spawn rates at 0 right?

**Comment by dshadowwolf** [comment]
...fffff
hrm... left them at what it was for the Botania plant I used to generate the template. I can easily fix that - at the same time I'll double-check stuff and see about getting you the script, template and the input file I used for the files.

**Comment by dshadowwolf** [comment]
Recent PR on AgriPlants fixes the issue and includes the template, input file and script - I've been trying to get to work on making it more flexible, but my work on BaseMetals has been keeping me away from this

**Comment by MokahTGS** [comment]
Is there a way to fix this on our end before it gets patched.  It's a little nuts.

**Comment by dshadowwolf** [comment]
I've put a pull request in on [AgriPlants](AgriCraft/AgriPlants#15) but the solution is to go through the files in config/agricraft/json/default/mod_mysticalagriculture/plants and change the spawn and spread rates to 0. I'll probably have a better fix available in the future - but that is being held up by a lot of work to fix the mod I'm co-author of these days and get it ready for its next release.

**Comment by RlonRyan** [comment]
That is technically not a console error but rather a warning that something hinky is going on with the item dropping code, in that something is calling the InfinityLib itemspawning code attempting to spawn a null ItemStack, and InfinityLib is catching it before it causes the game to crash.

The random spawning was, we'll say, an accidental april fool's joke on @dshadowwolf's part.

**Comment by MokahTGS** [comment]
Would changing the spread to 0 affect mutation breeding for getting 10.10.10 crops?

**Comment by RlonRyan** [comment]
The spread?
