### ISSUE TITLE
[Question] [JSON] "Conditions" option in plant JSONs

### ISSUE THREAD

**Issue by InjuredWolf** [AgriCraft/AgriCraft#932]
Was wanting to know what options I have with the "conditions" option within the plant json files. Can I set 'bases' for the plants still? I noticed the resource plants no longer require their respective ore (though, in previous versions, this was broken anyway).
What are the options, and how do I format it? The wiki is currently outdated.

**Comment by RlonRyan** [comment]
An AgriCondition, at this point in time is basically a combination of the nearby and below blocks that were present in the JSON files before. It allows you to specify a specific block and a specific relative range in which a given amount of the specified block is required to be present. For example, to replicate the old base block functionality:

````
"conditions": [
      {
        "amount": 1, # The amount required in the given range.
        "min_x": 0, # The bounding box, relative to the crop at 0, 0, 0 in which the block(s) are to be placed.
        "min_y": -2, # In this case we specify the box {(0, -2, 0), (0, -2, 0)}, which is the single block directly
        "min_z": 0, # below the soil block. Notice that the upper bound is inclusive, so that to specify a
        "max_x": 0, # single block we use the same point twice, not the upper left and lower right points.
        "max_y": -2,
        "max_z": 0, 
        "item": "minecraft:gold_ore", # This part specifies information about the block required.
        "meta": 0, # This is a *direct* extension of an AgriStack meaning that it has all the same fields as
        "tags": "", # would be found on say the seed_items field.
        "ignoreMeta": true,
        "ignoreTags": [],
        "useOreDict": true
      }
    ]
````

Notice that this is still rather limited, and the hope is that the functionality will be further extended by the time we transition out of alpha. Keep in mind that while we remain in alpha, AgriCraft, and especially the AgriJSONs are continually evolving.

**Comment by RlonRyan** [comment]
Ok. I updated the wiki with the information I provided here. Let me know if you need any additional information.

**Comment by InjuredWolf** [comment]
Cheers. Sounds good. Thankyou.
