### ISSUE TITLE
Server crash when using seed analyzer

### ISSUE THREAD

**Issue by Den1482** [AgriCraft/AgriCraft#934]
We have an issue on our server where interacting with seed analyzer and putting in a seed will crash the server, anyone else experiencing this issue? or is there a fix for it?

Cheers

**Comment by RlonRyan** [comment]
Could you please post the associated crash report?

I hate to say it, but an issue about a crash without a crash report is about as useful as cropsticks without plants.

**Comment by MeisterGeekz** [comment]
Here's the crash report from the server and a little more info - Someone crashed while trying to analyze Obsidian Seeds from Mystical Agriculture and they crashed. I tried a little later with some of the same seed types and there was no crash. Then another crash from a different user when trying to analyze Diamond seeds. These were all server crashes. The report below is from the Diamond Seed crash:
https://pastebin.com/QU2vhAXT

And just in case you need this here is the diamond_plant.json
https://pastebin.com/t04Y6CLd

**Comment by RlonRyan** [comment]
Thanks for the log!
