### ISSUE TITLE
Bug with Agricraft and Mystical agriculture

### ISSUE THREAD

**Issue by Vincicator** [AgriCraft/AgriCraft#937]
Hello, 

I just try tu grow my coal seed in 10/10/10 and the only thing I had is random seed spawning on all empty crops, I had emerald, rabbit, ghast etc... 

Do you know what should be the issue ?

**Comment by SniperSquirrel0** [comment]
I'm having the same issue. When you place down a crop stick very soon it will be occupied by a random mystical agriculture seed.  I do no have a clue as to why it's happening but it's quite annoying.

**Comment by MeisterGeekz** [comment]
I also had this issue. But I found a solution. Check inside your /config/agricraft/json/defaults/mod_mysticalagriculture/plants folder and go through some of the seeds. You'll noticed that some of them have a spawn_chance. After I changed the numbers to 0 I no longer have the issue

**Comment by RlonRyan** [comment]
You'll have to edit the JSON files. This was due to a bug in the templates that will be fixed in the next release.
