### ISSUE TITLE
Crops wont plant

### ISSUE THREAD

**Issue by CamaroKing59** [AgriCraft/AgriCraft#938]
Turned off Vanilla planting and it wont plant on the crop sticks either

agricraft Version: 2.0.0-0.9.0

**Comment by RlonRyan** [comment]
You are several versions out of date, please update from 2.0.0a9 to the latest version.

**Comment by CamaroKing59** [comment]
the version i have in is 2.0.0-0.9.0-a16

**Comment by RlonRyan** [comment]
I see.

**Comment by RlonRyan** [comment]
Fixed! Thanks for the report!

**Comment by CamaroKing59** [comment]
when will the update be out?

**Comment by RlonRyan** [comment]
Not sure, sorry.
