### ISSUE TITLE
Farmland and Water Pads Issues

### ISSUE THREAD

**Issue by Cerdaemon** [AgriCraft/AgriCraft#940]
I looked around and it seems there is nothing about this. I only found a post that says that water pads are supposed to be in the game again. 

Mincraft Version 1.10, FTB Beyond. I came via the Issue tracker in the launcher.

**Issues:** 
**First**, there are two blocks called water pad and one just has a slightly longer description.
**Second**, I cannot create water pads. I tried right clicking farmland with various shovels. I tried left clicking which just broke the dirt. I tried it with hoes and with the tinkers mattock. It was not possible to create a water pad.
**Third**, when right clicking the water pad with the short description in NEI minecraft crashes.

If water pads are not supposed to work please disregard, but I would remove them then.

On all other fronts, great work and thank you for maintaining this mod.

Cerdaemon

**Comment by RlonRyan** [comment]
Which version exactly?

**Comment by Cerdaemon** [comment]
I assume you mean Agricraft? 
Version: 2.0.0-0.8.0-a14

**Comment by RlonRyan** [comment]
Try updating to a16
