### ISSUE TITLE
1.10.2 - Issue with empty cropsticks spawning MysticalAgriculture plants

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [AgriCraft/AgriCraft#942]
As the title states.

When you leave a crop stick un attended with no crop, MysticalAgriculture plants grow out of no where.

**Comment by InfinityRaider** [comment]
This is a funny bug, but it actually gives me an idea...

**Comment by TokkenGmr** [comment]
I think this is due to #937 and should already be fixed for the next release. Or you can change it in the JSON files

**Comment by RlonRyan** [comment]
That would be correct @TokkenGmr. It can be fixed by changing the JSON files, or by regenerating the JSON files when the next release comes out.
