### ISSUE TITLE
Wooden Water Tank Multiblock not stacking/crash

### ISSUE THREAD

**Issue by phallicies** [AgriCraft/AgriCraft#943]
Well I seemed to have made a multiblock that crashes upon trying(just attempting it) to break anything. This is in FTB Beyond.

**Problem:** 1) Wooden water tank multiblock not rendering and functioning correctly.
                 2) CTD when attempting to break said multiblock

**How I screwed up?:** I first made a 4x4x1 water tank which rendered and acted fine, then remembering i could build it higher i tried. So it went to 4x4x2. The multiblock at the time didn't connect to the lower blocks so visually it looked like i stacked i 4x4 on top of another. So i thought maybe it was a size issue and reduced to a 3x3 where it was the same problem. When trying to fill water from the top on these tanks, it doesnt fill it up at all and seems to just be infinitely sucking water away. 

**Edit:** Tested in singleplayer after, seems it does still fill up properly for that singleplayer tank. You just cant see it since the multiblock didn't form correctly with that one and is only visible after it reaches a certain water height. Still have problem with the crashing while trying to disasemmble the multiplayer tank though.

First picture is an attempt at disabling the texture pack to see if maybe it was just a graphical glitch. Re-enabled so you can see issues.

**Pictures:**
![2017-05-12_06 47 21](https://cloud.githubusercontent.com/assets/21095052/26000793/27b6d4da-36df-11e7-8b56-129d6729aebe.png)

![2017-05-12_06 58 52](https://cloud.githubusercontent.com/assets/21095052/26001214/8587db26-36e0-11e7-85aa-ae0a893059f4.png)

![2017-05-12_06 58 58](https://cloud.githubusercontent.com/assets/21095052/26001216/8785cf3c-36e0-11e7-9bf1-657de759ca03.png)

**Log:**
[2017-05-12-3.txt](https://github.com/AgriCraft/AgriCraft/files/996926/2017-05-12-3.txt)

**Comment by RlonRyan** [comment]
This should already be fixed in 2.0.0a16. Please update your version of AgriCraft.
