### ISSUE TITLE
Weeding producing extra crop-sticks

### ISSUE THREAD

**Issue by dshadowwolf** [AgriCraft/AgriCraft#944]
Recently spotted that using a hand-rake to weed seems to be giving me crop-sticks in addition to weed seeds. I'm pretty certain that giving me crop-sticks and leaving the set in the world is not an intended effect.

**Comment by CodesCubesAndCrashes** [comment]
I was just looking at the related code, so I can at least link to the probable cause of this. 

* In the TileEntityCrops::getDrops method, crop sticks are included with the drops. [L138](https://github.com/AgriCraft/AgriCraft/blob/master/src/main/java/com/infinityraider/agricraft/tiles/TileEntityCrop.java#L138) 
* And that method (different from the Block or Event variations) is called in at least four different places: 
  * When you punch a crop, destroying it and getting back the sticks/seeds/fruit. [L127](https://github.com/AgriCraft/AgriCraft/blob/master/src/main/java/com/infinityraider/agricraft/tiles/TileEntityCrop.java#L127)
  * When a crop is raked, causing the plant and seed to be removed, but the crop left in place. [L393](https://github.com/AgriCraft/AgriCraft/blob/master/src/main/java/com/infinityraider/agricraft/tiles/TileEntityCrop.java#L393) 
  * And finally inside BlockCrop::getDrops [L212](https://github.com/AgriCraft/AgriCraft/blob/477c4bb5b4434df171ac5984a6df013ffa158da0/src/main/java/com/infinityraider/agricraft/blocks/BlockCrop.java#L212) and BlockCrop::dropBlockAsItemWithChance [L117](https://github.com/AgriCraft/AgriCraft/blob/477c4bb5b4434df171ac5984a6df013ffa158da0/src/main/java/com/infinityraider/agricraft/blocks/BlockCrop.java#L117). 

**Speculation:** Given that three out of the four are when the crop is being destroyed, the simplest solution I can think of is to change the lambda inside TileEntityCrop::onRaked to filter out crop sticks. I don't have an IDE in front of me right now, but perhaps something like: 

`stack -> if (stack.getItem() != AgriItems.getInstance().CROPS) WorldHelper.spawnItemInWorld(this.worldObj, this.pos, stack)` 

Hope any of this is helpful!

**Comment by RlonRyan** [comment]
This has been fixed for the next alpha. Thanks for the report!

Also, thanks @CodesCubesAndCrashes for the in-depth analysis!

**Comment by CodesCubesAndCrashes** [comment]
You're welcome! 

[Also the fix, for later reference: [line 395](https://github.com/AgriCraft/AgriCraft/commit/89c3ef2ea6d471abe606fc345e1f7b214a86181b#diff-e92d41d0d84f12f89141e0d86116150bR395) in commit 89c3ef2.]
