### ISSUE TITLE
Not supported with Agricultural Expansion

### ISSUE THREAD

**Issue by Dpatau** [AgriCraft/AgriCraft#949]
Hello can we get this mod to support Agricultural Expansion
https://minecraft.curseforge.com/projects/agricultural-expansion

**Comment by CodesCubesAndCrashes** [comment]
Probably going to get a similar response as #912, but maybe it can be added to the list in #572. Cheers!

**Comment by RlonRyan** [comment]
@CodesCubesAndCrases This is more a matter of getting someone to provide the applicable JSONs to the AgriPlants repo. We are more than happy to support any mod that we are provided JSON files for.

**Comment by RlonRyan** [comment]
Although, in the meantime MysticalAgriculture might provide an alternative.

**Comment by RlonRyan** [comment]
Fixed, or at least for the 1.12 branch.
