### ISSUE TITLE
Random crops planting themselves

### ISSUE THREAD

**Issue by FnordMan** [AgriCraft/AgriCraft#950]
Running Agricraft a18 here.

Recently regenerated my configs (delete folder, let agricraft re-create everything) which thankfully fixed my unable to plant seeds issue. (old configs?)

Changes i've made to the configs:
Up mutation chance to 0.4
Single spread stat increase to true (what can I say, I like easy mode)
Disabled weeds (defaults/vanilla/plants/seeds/weed_plant.json, changed "enabled" to false)

The problem? Now i'm getting all kinds of random plants growing where weeds would previously grow. (spider/pig/emerald/etc, basically anything possible? only seen mystical agriculture due to the number of seeds it has?)

Did I disable weeds wrong or is this a bug?

**Comment by FnordMan** [comment]
Update: Re-enabled weeds, still seeing the same behavior, mystical agriculture seeds are planing themselves spontaneously, normal crop or cross crop. So far i've still only seen mystical agriculture seeds.

**Comment by RlonRyan** [comment]
This is an error with the default jsons that has been fixed for the next release.

You need to set the `"spawn_chance"` field in all the mystical agriculture plants to `0.0`.
