### ISSUE TITLE
Disabling vanilla planting disables right clicking with crop items in other mods

### ISSUE THREAD

**Issue by WolfieWaffle** [AgriCraft/AgriCraft#951]
I tried to right click a potato onto a block in my mod, and got the "Vanilla planting is disabled" message. I assume this is because you are not checking that the block that is being right clicked is farmland.

**Comment by RlonRyan** [comment]
Good catch, that would be an issue.

I believe that the solution would be to check if the seed is being clicked on a valid soil?

However that would not catch planting on soils not registered to AgriCraft.

What I need is some kind of forge hook perhaps...

**Comment by TehNut** [comment]
`state.getBlock().canSustainPlant(state, world, pos, EnumFacing.UP, seedItem)`

**Comment by RlonRyan** [comment]
Thanks @TehNut!
