### ISSUE TITLE
I can't find the option to enable ressource crops

### ISSUE THREAD

**Issue by Samkonai** [AgriCraft/AgriCraft#953]
That's all in the tilte

**Comment by RlonRyan** [comment]
You need to go to `config/agricraft/json/defaults/resource/**/*.json` and set the `enabled` field to true as to enable the resource crops.

**Comment by Samkonai** [comment]
I don't have any json in ressource :/

**Comment by RlonRyan** [comment]
you have to go into the subfolders, and find all files ending in `.json`
