### ISSUE TITLE
crop sticks spawning random mystical agriculture plants.

### ISSUE THREAD

**Issue by donaldshoemaker** [AgriCraft/AgriCraft#955]
im playing a custom pack and sorta piecing it together and for some reason if I let a crop stick empty for id say no more than 10 seconds a random mystical agriculture crop will pop into the crop sticks. using the most current version of agricraft and mystical agriculture

**Comment by RlonRyan** [comment]
This is a known issue with the default JSON files. Go to `config/agricraft/json/defaults/mod_mysticalagriculture/**/*_plant.json` and set all the `"spawn_chance"` fields to `0.0`, instead of the default `0.1`.
