### ISSUE TITLE
NPE on game load

### ISSUE THREAD

**Issue by Eufranio** [AgriCraft/AgriCraft#956]
I'm running a modpack and my client suddenly started crashing at the end of loading. It will start if I remove AgriCraft. 

Crash-report: https://hastebin.com/bimutocini
Mod versions are in the crash report. If you need any other info that I can provide, let me know.

**Comment by RlonRyan** [comment]
This has already been fixed for the upcoming alpha release.

**Comment by Eufranio** [comment]
Great, can I know what was the cause of the issue?

**Comment by RlonRyan** [comment]
I don't know off the top of my head, but I know it's been fixed.

**Comment by Eufranio** [comment]
GG
