### ISSUE TITLE
Disable Vanilla Farming also prevents planting seeds inside crop sticks

### ISSUE THREAD

**Issue by TheAtomicOption** [AgriCraft/AgriCraft#957]
Tested on a superflat world with agricraft-2.0.0-0.9.0-a16 and infinitylib-0.9.0 as the only mods. 

Setting Disable Vanilla Farming=true in the config file results in being unable to plant seeds (whether identified or not) inside crops as well as on vanilla farm land.

**Comment by CodesCubesAndCrashes** [comment]
Good news! I believe this is fixed for the next release (a17), by [this commit](https://github.com/AgriCraft/AgriCraft/commit/49e32c2eff4ce53318efa8ac4d6acbe702f1180b) in response to report #938.

**Comment by TheAtomicOption** [comment]
Closing due to this being duplicate issue. Can't wait for the next release!
