### ISSUE TITLE
No Texture if Server Enable some plant and not the client

### ISSUE THREAD

**Issue by Misteralex007** [AgriCraft/AgriCraft#959]
Hi !

I notice a issue. I play with some friend on my server and I enable ressources plant to get iron, gold, etc.
on the config of the server but by default it isn't enable in the client and player haven't the texture loaded. 

I don't know if it's on purpose but if the client cloud load the texture even if the plants are disabled it could be great.

Thanks.

**Comment by TehNut** [comment]
That would be a lot of wasted space on the texture atlas once Agricraft starts shipping more plants by default.

**Comment by Misteralex007** [comment]
Ok, fair enough. I just want to make sure that isn't a bug.

**Comment by RlonRyan** [comment]
Yeah it's problematic... Somehow we need to hack into the texturemap at server connect and add/remove AgriCraft textures as needed. Still that might not be possible, so...

**Comment by RlonRyan** [comment]
Anyways, this is essentially the same as #743, so I'm going to close this issue as a duplicate.

**Comment by InfinityRaider** [comment]
I fiddled around in the past with syncing config options from the server to the client in the past, but decided it was too much of a hassle, and the odds of having to restart the client were to big anyway.

If you do decide to to through with this, I wouldn't hack into the texturemap, and instead just fire a resource manager reload (which can take a looooooong time if there is a lot of mods present).


For now my opinion is this: it's up to the end user / pack maker / server admin that everyone's client config settings are identical to the server. And this is the general approach in modded MC anyway...
