### ISSUE TITLE
Mutation JSONs not working

### ISSUE THREAD

**Issue by sipes42** [AgriCraft/AgriCraft#961]
I have been working on making custom plant and mutations JSONs to bring back compatibility with Ars Magica 2. I have successfully created the seeds and plants for the Wakebloom and Aum flowers (luckily the textures were still hanging around). The issue is that despite creating a Mutations JSON, the seeds are not able to be mutated and the mutation recipe does not appear in the NEI.

Plant JSON for Wakebloom:

> {
  "path": "ArsMagica2_mod/plants/wakebloom_plant.json",
  "enabled": true,
  "id": "wakebloom_crop",
  "plant_name": "Wakebloom",
  "seed_name": "Wakebloom Seeds",
  "seed_items": [
    {
      "item": "agrictraft:wakebloom_seeds",
      "meta": 0,
      "tags": "",
      "ignoreMeta": false,
      "ignoreTags": [
        "*"
      ],
      "useOreDict": false
    }
  ],
  "description": {
    "translations": {},
    "default": "Wakebloom Seeds."
  },
  "growth_chance": 0.5,
  "growth_bonus": 0.025,
  "bonemeal": true,
  "tier": 1,
  "weedable": false,
  "aggressive": false,
  "spread_chance": 0.1,
  "spawn_chance": 0.0,
  "grass_drop_chance": 0.0,
  "seed_drop_chance": 1.0,
  "seed_drop_bonus": 0.0,
  "products": {
    "products": [
      {
        "min": 1,
        "max": 5,
        "chance": 0.9,
        "required": true,
        "item": "arsmagica2:wakebloom",
        "meta": 0,
        "tags": "",
        "ignoreMeta": false,
        "ignoreTags": [],
        "useOreDict": false
      }
    ]
  },
  "requirement": {
    "min_light": 10,
    "max_light": 16,
    "soils": [
      "farmland_soil"
    ],
    "conditions": []
  },
  "texture": {
    "render_type": "hash",
    "seed_texture": "agricraft:items/seedWakebloom",
    "plant_textures": [
      "agricraft:blocks/cropWakebloom1",
      "agricraft:blocks/cropWakebloom1",
      "agricraft:blocks/cropWakebloom1",
      "agricraft:blocks/cropWakebloom2",
      "agricraft:blocks/cropWakebloom2",
      "agricraft:blocks/cropWakebloom3",
      "agricraft:blocks/cropWakebloom3",
      "agricraft:blocks/cropWakebloom4"
    ]
  }
}

Mutation JSON for Wakebloom:

> {
  "path": "ArsMagica2_mod/mutations/wakebloom_mutation.json",
  "enabled": true,
  "chance": 0.9,
  "child": "wakebloom_plant",
  "parent1": "melon_plant",
  "parent2": "artichoke_plant"
}

**Comment by RlonRyan** [comment]
It's probably a bad reference to a harvestcraft Id. They weren't standard originally, so you should double-check that you have the right id.

**Comment by sipes42** [comment]
I have changed the mutation to 

"Parent1":"melon_plant",
"Parent2":"carrot_plant"

I checked beforehand to make sure that there were no other recipes requiring a melon-carrot cross. The mutation still does not function.

**Comment by RlonRyan** [comment]
Can you post a copy of the logs please?

**Comment by sipes42** [comment]
which logs, specifically?

**Comment by RlonRyan** [comment]
The main log should have a section covering AgriCraft JSON file loading and validation. It will tell what type of error we have going on here.

**Comment by sipes42** [comment]
There was no crash, so it won't be a crash-log... when you say "main" log, I can't tell what you mean. Are you referring to FML-client-latest.txt? 

[fml-client-latest.txt](https://github.com/AgriCraft/AgriCraft/files/1033739/fml-client-latest.txt)

**Comment by RlonRyan** [comment]
````
[22:28:47] [Client thread/INFO] [AgriCore/agricraft]: Invalid Mutation: Invalid Child: "wakebloom_plant"!

Mutation:
	- Parents:
		- Parent 1: wheat_plant
		- Parent 2: wheat_plant
	- Child: wakebloom_plant
	- Chance: 0.5

[22:28:47] [Client thread/INFO] [AgriCore/agricraft]: Invalid Mutation: Invalid Child: "wakebloom_plant"!

Mutation:
	- Parents:
		- Parent 1: melon_plant
		- Parent 2: carrot_plant
	- Child: wakebloom_plant
	- Chance: 0.9
````

**Comment by RlonRyan** [comment]
I should probably make a separate log for the JSON information stuff so that one doesn't have to go through a log file that is a couple of megabytes to find the information...

**Comment by sipes42** [comment]
Ok. I guess I'm a little confused. All the references to Wakebloom refer to it as wakebloom_plant, and the seeds work fine when planted... How should I be referring to it in wakebloom_mutation.json?

**Comment by RlonRyan** [comment]
Well you need to check the if for wakebloom.

**Comment by sipes42** [comment]
Okay, changing the name from wakebloom_plant to wakebloom_crop fixed the issue... thanks.
