### ISSUE TITLE
Mutation stats at 1/1/1, divisor at 1, parents at 10/10/10

### ISSUE THREAD

**Issue by mrlamb** [AgriCraft/AgriCraft#962]
Three screenshots real fast: 

https://www.dropbox.com/s/wzs4eoksp72y8p2/Screenshot%202017-05-25%2019.11.33.png?dl=0
https://www.dropbox.com/s/ckeyex1az2cr9ok/Screenshot%202017-05-25%2019.11.28.png?dl=0
https://www.dropbox.com/s/8nvhg4ncf7xfkkf/Screenshot%202017-05-25%2019.11.20.png?dl=0

On the agricraft version downloaded via twitch client today. Same for the new infinitylib (which incidently seems to have broken boatlantern, if you're reading this InfinityRaider).

As you can see, parent plants are both trip 10's but baby came out at 1's.

What other info can I give you?

**Comment by RlonRyan** [comment]
This might have already been fixed in another branch...
