### ISSUE TITLE
Natura seeds not working/incorrect texture config

### ISSUE THREAD

**Issue by FisfulOfDice** [AgriCraft/AgriCraft#964]
The barley and cotton seeds from Natura aren't usable with any Agricraft functionality. They can't be put on crop sticks, used in the analyzer, or show mutation information in JEI. In the json config files, the texture listed as from ActuallyAdditions instead of Natura. Installing AA doesn't seem to affect anything.

**Comment by TokkenGmr** [comment]
Are you using the most current version of agricraft? I am pretty sure I fixed this already, and it looks correct in the agriplants repo.

**Comment by FisfulOfDice** [comment]
It looks like I am, based off Curse: agricraft-2.0.0-0.10.0-a17. I tried deleting the mod and the config folder to see if that changed anything, but I'm still running into the issue.

**Comment by RlonRyan** [comment]
Odd... If it was fixed, then regenerating the config folder should have applied the fix.

**Comment by TokkenGmr** [comment]
@RlonRyan So the agriplants repo is correct I just double checked again. However I created a new Instance with just Agricraft and it looks like the json  from before the last commit is what is in the most recent version of agricraft

**Comment by RlonRyan** [comment]
Yup you're right. I guess that will have to be part of the next release then...

I suppose this issue can be considered fixed then too.

**Comment by FisfulOfDice** [comment]
Just confirmed that the seeds work with the correct json.
