### ISSUE TITLE
Game crashes when I tried to destroy crops.

### ISSUE THREAD

**Issue by IDKZAL** [AgriCraft/AgriCraft#965]
Game crashes when I tried to destroy crops.
Crash Report: https://pastebin.com/raw/Z82S2dUw

Also, Agri has also some issues with Dynamic Surroundings Mod
Crash Report: https://pastebin.com/raw/snPmv4q8

Looks like a sound problem.

**Comment by sipes42** [comment]
I had a similar problem. There is an option in the config file that needs to be changed. It disables sound from agricraft, but sounds from breaking blocks cannot be cancelled.

    B:"Disable sounds"=false

Should be around line 8 or so of the config.

**Comment by IDKZAL** [comment]
Thanks for the info, cant try it anymore because i just removed AgriCraft from my modpack. I guess I just wait until its out of "Alpha" :P

**Comment by RlonRyan** [comment]
Thanks for the investigation @sipes42! It is very helpful and time-saving. I actually submitted a PR to MinecraftForge because that error message was so dang vague (yeah, I know we tried to cancel a un-cancelable event! But which one!?).
