### ISSUE TITLE
Compatibility with Sponge

### ISSUE THREAD

**Issue by RedTech64** [AgriCraft/AgriCraft#966]
Using the latest version of Agricraft and sponge, there appears to be problems with crop sticks where you cannot place them on tilled soil that is wet, and when you try to plant something the crop sticks just break. This appears to be a compatibility issue with SpongeForge.

Here is a video showing the problem: https://www.youtube.com/watch?v=asd2tm3VQ54&feature=youtu.be

**Comment by RlonRyan** [comment]
I'm afraid I'm not entirely sure what to say about this, AgriCraft is hardly stable enough to focus on compat issues ATM, but I acknowledge and respect people wanting to use Sponge (from my days working on ForgeEssentials).

**Comment by LemADEC** [comment]
Latest is a version number.
As of AgriCraft-2.12.0-1.12.0-a6 + spongeforge-1.12.2-2825-7.1.6-RC3713, you can plant into crop sticks without them breaking.
=> close
