### ISSUE TITLE
Question: Seed Storage (1.10.2)

### ISSUE THREAD

**Issue by sipes42** [AgriCraft/AgriCraft#970]
I remember the seed storage system from 1.7.10, and it was very useful. Options for disabling it are still in the config, but I have noticed that even when enabled, the seed storage system does not seem to show up in-game. Has it been phased out? If so, will there be some kind of replacement system?

**Comment by Kaijiro** [comment]
SeedStorage have been disabled for the moment. RlyonRyan, who's developping the mod now has other focuses than fixing the seed storage from the port.

But don't worry, it will be done

**Comment by RlonRyan** [comment]
You are correct @Kaijiro, the seed storage is a rather complicated side-addition that will be added when the core of AgriCraft has been stabilized.

@sipes42 For now I would recommend using a ME or Refined Storage system for storing your seeds. However, I believe that Extra Util might have a filing cabinet that might work, but I'm not entirely sure.

**Comment by sipes42** [comment]
Thanks very much. I will look into the filing cabinets for now.
