### ISSUE TITLE
Seeds not able to be planted at night? Some seeds never?

### ISSUE THREAD

**Issue by sipes42** [AgriCraft/AgriCraft#971]
I have encountered a particularly odd bug (feature?) where trying to plant seeds at night doesn't do anything at all, but upon entering the command /time set day, the seeds are able to be planted. When /time set night is used, the seeds cannot be planted again. The seeds were regular wheat seeds. A custom seed I made was not able to be planted at all, even though I have successfully planted it and mutated it in the recent past.

**Comment by Kaijiro** [comment]
Can it be a problem with light level ?

**Comment by RlonRyan** [comment]
Might be an issue with the new light calculation code. If you could use the debugger on the plant and gist the results here that would be a great help.

**Comment by sipes42** [comment]
this is all it give me...


> Clicked block at (2, 86, -2)
CROP:
-This crop has a plant
-Plant: Wheat
-Id: wheat-plant
-Stage: 0
-Stages: 8
-Meta: 0
-Growth: 1
-Gain: 1
-Strength: 1
-Fertile: true
-Mature: false
AgriSoil: farmland_soil

**Comment by RlonRyan** [comment]
So that specific wheat plant is fertile. Perhaps try using the magnifying glass to check light info on the locations that you can't plant at?

**Comment by sipes42** [comment]
brightness is 15/16. I also cannot plant it in the same spot that the wheat plant was.

**Comment by RlonRyan** [comment]
Interesting. Could you please post a gist of one of the plant JSONs that is not working?

**Comment by sipes42** [comment]
https://gist.github.com/sipes42/31462ec7cf65f9f1ab96a7a3e4d678ad.js

I may have figured it out... "water_pad" isn't registered... but I'm pretty sure it was ignoring that previously because it wasn't a valid soil.

**Comment by RlonRyan** [comment]
There seems to be something wrong with that gist link... Could you please try it again?

**Comment by TehNut** [comment]
https://gist.github.com/sipes42/31462ec7cf65f9f1ab96a7a3e4d678ad

**Comment by FisfulOfDice** [comment]
I just tested with the latest build, and it does seem that seeds can't be planted on crop sticks in the dark. I didn't experiment with exact light levels, but I was able to plant seeds on crop sticks during the day, and when I switched to night with no light source, I was unable to use the crop sticks.

**Comment by CodesCubesAndCrashes** [comment]
The upcoming a21 branch allows seeds to be planted in the dark, even if they won't be able to grow until there's more light. The water_pad is still AWOL, and it's a separate issue. Just making notes here while reviewing the backlog of issues.
