### ISSUE TITLE
Mutation Spread Bug/Mystical Agriculture Bug

### ISSUE THREAD

**Issue by StanTheMann** [AgriCraft/AgriCraft#977]
Hey I am having a couple issues with agricraft right now. I currently have the latest version installed 2.0.0-0.10.0-a17.
 
Current Bugs
- Wheat crops do not mutate to make better wheat crops when using cropsticks, this could be with other crops as well but I haven't tried any yet.
- ~Mystical Agriculture crops keep spawning inside of my cropsticks at random times~ [known issue]
 
I would really like some help to get this mod working as I enjoy it a lot :) if you could get back to me as soon as possible it would be appreciated

**Comment by TokkenGmr** [comment]
The first issue is the same as #968 and the second issue is the same is #969. You can fix the later by going in to the JSON files

**Comment by StanTheMann** [comment]
So i moved my crops and tried to cross over the wheat crops again but still no result. Nothing spawns in the middle empty crossover cropsticks.



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by TokkenGmr** [comment]
I do apologize #968 was incorrect. It was supposed to be #962. It is really just a matter of waiting for the release of 18a

**Comment by RlonRyan** [comment]
This issue might be addressed in the upcoming a18 update, wherein the API was rewritten.

**Comment by Undrhil** [comment]
In regards to the second issue here: all of the MysticalAgriculture plant JSON files have the spawn chance set to 0.1 by default.  Can we have the default for those files set to 0.0 instead?

**Comment by TehNut** [comment]
I believe that was fixed in https://github.com/AgriCraft/AgriPlants/commit/a070892caccec8d3d669faaf941787da1e4e90c7

**Comment by Semajor** [comment]
The mutation problem is a result of one of the options in the config catching all plants as invalid parents. With the option below set to true on a19, my crops never mutated beyond 1/1/1, regardless of single or double parent mutations. This is probably also causing #1028 and #962 to see a loss of stats on plants when mutating. Make sure you have the config option below set to false and you should see your mutations working normally.

# True means any crop that is not considered a valid parent will affect stat gain negatively. [default: true]
B:"Non parent crops affect stats negatively"=false

**Comment by CodesCubesAndCrashes** [comment]
The stat bug is fixed in a20 onwards, there's some good discussion also over in #1069. And the Mystical Agriculture fixed default JSONs were included in a18 onward.
