### ISSUE TITLE
Console spam AGRI-DEBUG messages when debug is set to false.

### ISSUE THREAD

**Issue by JaSpr** [AgriCraft/AgriCraft#979]
We keep getting lots of AGRI-DEBUG messaging when the debug setting is set to false.

   AGRICRAFT 2.0.0-0.9.6-a16
    FTB Beyond 1.7.0 and 1.8.1
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a26c654
    SpongeForge: 1.10.2-2281-5.2.0-BETA-2353
    Minecraft Forge: 12.18.3.2297

**Comment by RlonRyan** [comment]
Huh, I'll have to look into this...

**Comment by JaSpr** [comment]
Especially happens when anybody logs in to the server

**Comment by RlonRyan** [comment]
Which channel is this happening on exactly? Is it the agri-net channel, or the agricraft channel?

**Comment by JaSpr** [comment]
[agricraft-net]

**Comment by RlonRyan** [comment]
Gah... that dang channel doesn't seem to want to follow the debug settings ever...

**Comment by JaSpr** [comment]
Here's a specimen from the logs: 

https://gist.github.com/JaSpr/152be5513ad4356a8635b40a437ae359

**Comment by RlonRyan** [comment]
Thanks
