### ISSUE TITLE
Crashing on All The Mods V 2.55e 

### ISSUE THREAD

**Issue by Shekinah33** [AgriCraft/AgriCraft#981]
Hey I initially thought this was an issue with JEI but Mezz said I should head over here. I play on a server with about 12 people and only me and one friend have an issue where we crash every time we search certain letters in JEI. Both of us have tried reinstalling and everything, even copied over config files from players who had no problem with it, also tried all over google.
I uploaded a crash report below :)
[crash-2017-06-03_18.25.31-client.txt](https://github.com/AgriCraft/AgriCraft/files/1049907/crash-2017-06-03_18.25.31-client.txt)

**Comment by RlonRyan** [comment]
Gah... This issue again... I think I'm just going to have to rewrite the tesselator code altogether.

**Comment by RlonRyan** [comment]
Same as #974
