### ISSUE TITLE
Weed disabling on v2.0.0-0.10.0-a17

### ISSUE THREAD

**Issue by Undrhil** [AgriCraft/AgriCraft#983]
When I set "enabled" to false in the weed.json file, I still get "weeds" but they are randomly chosen from the other plants that are available.  I tested this with just Agricraft and Mystical Agriculture installed and I get tons of random mystical agriculture crops in place of where weeds would grow.

Is there not a way to just disable weeds completely, as there was in the 1.7.10 version of Agricraft?

**Comment by RlonRyan** [comment]
You have to set the spawn chance in all JSON plant files to zero or disable the files all together.
