### ISSUE TITLE
Crash when trying to craft bowl

### ISSUE THREAD

**Issue by Dilnu** [AgriCraft/AgriCraft#984]
Hi, I'm running 1.10.2 Forge 12.8.3.2297 with Agricraft 2.0.0-0.10.0-a17

I tried to disable irrigation in the config and I get this crash log when trying to craft the vanilla bowl recipe with three planks.
https://jpst.it/-6yj

**Comment by RlonRyan** [comment]
That, uh, that might not actually be our fault...

That is a really non-specific crash report.

@tehnut, uh, could you take a look at that log please?

**Comment by TehNut** [comment]
Useless logs! My favorite kind of log.

Not too sure what could be causing that. There's really nothing in that method that could NPE since all if it gets checked.

**Comment by TehNut** [comment]
From the log it looks like it's a minimal environment which makes this even harder to debug.

```
UCHIJAAAA mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
UCHIJAAAA FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2297.jar) 
UCHIJAAAA Forge{12.18.3.2297} [Minecraft Forge] (forge-1.10.2-12.18.3.2297.jar) 
UCHIJAAAA infinitylib{1.10.2-0.10.0} [InfinityLib] (infinitylib-0.10.0.jar) 
UCHIJAAAA agricraft{2.0.0-0.10.0-a17} [AgriCraft] (agricraft-2.0.0-0.10.0-a17.jar) 
```

**Comment by RlonRyan** [comment]
Oh, I missed that, sorry...

But with that environment, I'm not even sure this error makes any sense...

I almost wonder if we've stumbled across some form of Forge error...

I can't tell what function that is to look at the bytecode, and I can't de-compile minecraft to look at the code that way... so...

**Comment by TehNut** [comment]
`a => func_180453_a => renderItemOverlayIntoGUI`

**Comment by RlonRyan** [comment]
How'd you figure that out?

**Comment by TehNut** [comment]
MCPBot on IRC. 

![thing](http://tehnut.info/share/KdBV0aR8ts.png)

There is also a bot with an MCP querying function on the [Modded Minecraft](http://discord.gg/moddedmc) (/r/feedthebeast) discord.

**Comment by RlonRyan** [comment]
Huh...

**Comment by RlonRyan** [comment]
Neat!

**Comment by RlonRyan** [comment]
Based on that def though this definitely feels like something forge should be picking up on, or at least providing a better error message. Then again there are a lot of minecraft functions to hook into so...

**Comment by Dilnu** [comment]
Oh, sorry I can explain more precisely what I think is happening. I think there's an error that occurs because the recipe for the irrigation channel isn't fully unregistered. So it tries to craft the irrigation channel but fails because the item doesn't exist. The bug only occurs when irrigation is disabled in config.

**Comment by RlonRyan** [comment]
@Dilnu that makes sense, thank you very much!

Although, forge should probably add a better check for this...
