### ISSUE TITLE
Crash on server startup with version a18

### ISSUE THREAD

**Issue by DeadSix27** [AgriCraft/AgriCraft#985]
Stacktrace: https://gist.github.com/DeadSix27/953d5baaed09426761c3dceb1372d97e
Say if you need more than that.

**Comment by Tsyklop** [comment]
confirm. same error;

**Comment by RlonRyan** [comment]
Great. Guess that release was premature... I suppose AgriCraft is still in alpha so, it's to be expected. I don't know if I should pull the release since I don't know if I have time to prep a new release soon... Oh well...

**Comment by DeadSix27** [comment]
@RlonRyan it's alright I know what to expect when downloading alpha builds and the only way I can think of how you could prevent these problems is a test-group/test phase where you spread the file outside of curseforge, but then again, why not just spread it on curseforge and receive issues like this...

**Comment by RlonRyan** [comment]
Well, uh, this is problematic...
````
Caught exception from AgriCraft (agricraft)
java.lang.NullPointerException
at com.infinityraider.agricraft.core.JsonPlant.convertProductJSON(JsonPlant.java:215) ~[JsonPlant.class:?]
````
This error shouldn't be occurring... meaning this is a deeply rooted issue...

**Comment by RlonRyan** [comment]
I see... the converter can fail and return a null value even after the validation step... Time to rewrite AgriCore!

**Comment by DeadSix27** [comment]
@RlonRyan DId I open pandoras box? Also, you validate json but the json converter still fails on valid json? Strange, All That you could do is Catch the exception tho, no?

**Comment by RlonRyan** [comment]
Nah, it's not that bad of a fix, it just looks deeply integrated.
