### ISSUE TITLE
[1.10.2] Carrots still plantable vanilla style (a18)

### ISSUE THREAD

**Issue by LordDan1989** [AgriCraft/AgriCraft#986]
The carrots are still plantable vanilla style with vanilla planting disabled. I tested all other crops and they are disabled correctly; it's just the (vanilla) carrots.

Tested on a fresh install for 1.10.2
AgriCraft: a18 (Latest)
InfinityLib: 0.10.0 (Latest)
Forge: 2185 (Recommended)

**Comment by RlonRyan** [comment]
Ah, that would be due to the fact that carrots are not registered as an AgriCraft seed... I guess I need to replace carrot seeds with carrots proper then... That or add a new field in the JSON files for blocking...

**Comment by RlonRyan** [comment]
This is actually the same as #980 upon further inspection.

Thus I am closing this issue and merging it with #980.
