### ISSUE TITLE
Unable to plant HarvestCraft seeds on Crop Sticks

### ISSUE THREAD

**Issue by Redhandjane** [AgriCraft/AgriCraft#988]
I'm currently playing on 1.10.2 with version 2.0.0-0.0.10.0-a18.jar and HarvestCraft version 1.10.2j

Mutations for HarvestCraft are not showing in the recipes and I am unable to plant HarvestCraft seeds on crop sticks. I had the same problem with a17 as well, but I had hoped updating would work, but it is still not working. 

I did try to search within the issues, but I only found older ones as well as the one about night and day, but that's not quite the same issue.

**Comment by RlonRyan** [comment]
Oh... Try regenerating your JSON files. The a18 update has updated Harvestcraft JSON files that might help.

**Comment by Redhandjane** [comment]
I created a new modpack with just AgriCraft, HarvestCraft, Spice of Life, AppleCore, and AppleSkin and it's still not working :(

**Comment by Redhandjane** [comment]
So, I spent most of yesterday removing mods and adding them back in one at a time, to no avail. But I just realized HarvestCraft updated a few days ago. I downgraded and now it's working

**Comment by RlonRyan** [comment]
Huh... so harvestcraft must have changed some ids...

**Comment by digitronics** [comment]
harvestcraft went lowercase ids in latest update, quick workaround is to just search & replace `Item` to `item` in `agricraft/json/defaults/mod_harvestcraft/plants`

**Comment by newborn-k** [comment]
i have a similar issue happening with mystical agriculture.  it wont let me put the MA seeds in the seed analyzer and the crop sticks, any help would be appreciated,

**Comment by Redhandjane** [comment]
Okay thanks! I'll update those now

**Comment by renadi** [comment]
Oh, my, doesn't that sounds fun, time to open a LOT of files in Notepad ++.

Appreciate the information, I just wasted about an hour trying to figure out what had changed on my end as I'd just updated a bunch of mods and started a new world and all.  Appreciate the info!

**Comment by koalabaer1991** [comment]
I replaced all Item to item in agricraft/json/mod_harvestcraft/plants. Just download and replace. 
(sorry upload via github didnt work for me) http://s000.tinyupload.com/index.php?file_id=09825895503917244157

**Comment by Chinthor** [comment]
For those who need a more custom fix for their install or who don't want to download foreign files, NotePad++ can replace all instances in a pack of files. Open NotePad++, do Ctrl+F, click the "Find in Files" tab, hit the [...] after directory, chose the file folder that nerdism pointed out, check "Match Case" but not "Match whole word only" , replace "Item" with "item" and click the "Replace in Files" button. Done.
