### ISSUE TITLE
Crash Exception Ticking World

### ISSUE THREAD

**Issue by Darianna77** [AgriCraft/AgriCraft#993]
Game crashes every time after a few seconds 
Its the Foolcraft Pack...with Extra randomThings and updatet Agricraft Version, as well as Pams ans MystialAgriculture

Log: [https://pastebin.com/BGdnC4n3](url)

**Comment by LordDan1989** [comment]
I have this problem on an un-modded test world. I found that the issue was related to forgetting to Analyze the seeds, meaning the required NBT data of the seed was missing; can you confirm all of your seeds were Analyzed?

Your Pastebin link doesn't work so I was unable to compare your crash report to my own.

**Comment by Darianna77** [comment]
Mhh, today the link is broke...they must have delete the log :/
And yes the seeds was analyzed...but i must try and error so often with disable....ure-enable....update agricraft....pams....and so on..

i can try it again when i re-enable agricraft and plant  a new seed
another bug that i have had...the seeds wont go out of my inventory after planting...
so i can plant 1 seed over and over ...
must delete every single seed per hand.
by the expensive mystical seeds its a gamebreaker when i can plant 100 draconium plants out of 1 seed ;)

**Comment by CodesCubesAndCrashes** [comment]
The link is working at the moment: [https://pastebin.com/BGdnC4n3](https://pastebin.com/BGdnC4n3) 
So I've duplicated it into a gist: [c1e6268fcebee2d11bef4bd562b38eec](https://gist.github.com/CodesCubesAndCrashes/c1e6268fcebee2d11bef4bd562b38eec)
So thanks you! It does look like the same sort of stack trace as LordDan1989 posted in 997. The upside there is that that pack included the minimal number of mods, narrowing down the factors. Cheers.

**Comment by RlonRyan** [comment]
Seems related to #989

**Comment by RlonRyan** [comment]
Yeah, definitely the same as #989. Closing this one as a duplicate issue then. (Just to keep everything indexed nicely).
