### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by vrork** [AgriCraft/AgriCraft#996]
Agricraft 2.0.0-0.10.0-a18, Minecraft 1.10.2

https://gist.github.com/vrork/cbac30cc5897bb34f2e857336fe75276

**Comment by WhiskersWatson** [comment]
Can confirm, just got the same error after trying to agricraft to my pack https://pastebin.com/d66Qyvua

**Comment by Jacky1356400** [comment]
Same here. Updated AgriCraft to a18 and it started to crash on startup. [Crash Report](https://pastebin.com/XstizsnX)

**Comment by RlonRyan** [comment]
Duplicate of #987
